### ISSUE TITLE
Reland IGNORED PATH lint

### ISSUE THREAD

**Issue by csnardi** [w3c/web-platform-tests#10012]
See e.g. https://travis-ci.org/w3c/web-platform-tests/jobs/352986017:

    testharness_runner.html: testharness_runner.html matches an ignore filter in .gitignore - please add a .gitignore exception (IGNORED PATH)

I think this might be because https://github.com/w3c/web-platform-tests/blob/master/tools/lint/lint.py#L151 checks if `path` is excluded but the exclusion rule is `!/testharness_runner.html` so it wouldn't match because of the leading slash. I haven't tested it, however.

**Comment by gsnedders** [comment]
bisect points at b3b4332e7aaf7b027c11be8a0750b9136bb90a70

**Comment by gsnedders** [comment]
I have no idea how your PR failed but others didn't. But hey… :/

Will reassign to @jdm so he can try and reland after reverting.

**Comment by csnardi** [comment]
@gsnedders I'm assuming it's another example of only linting what is changed; since I changed the lint whitelist I assume that linted everything.

**Comment by gsnedders** [comment]
@csnardi Oh, I missed that the whitelist was changed in your commit. Yes, that'd do it. Still, #9902 should've had the lint run against everything (because of lint tool changes) so it's a bit weird.
