### ISSUE TITLE
ci_resources_unittest hangs when running locally

### ISSUE THREAD

**Issue by Hexcles** [w3c/web-platform-tests#10114]
The tox setup doesn't seem to work at all. The test passes in most builds simply because the test is usually deemed unnecessary to run.

I've spotted a few issues and will try to send a fix PR.

cc @lukebjerring who informed me of the breakage. A failing example from his PR: https://travis-ci.org/w3c/web-platform-tests/jobs/353342172

**Comment by lukebjerring** [comment]
The example you link is a successful execution of the tests (and fails because I changed functionality).

To clarify, the tox execution doesn't work at all locally (reproducibly broken on your machine too).

**Comment by Hexcles** [comment]
Thanks for the correction, Luke. Sorry I didn't read the logs carefully enough. So it seems like it does work on Travis, but it's not working locally (even after I fixed another bug I found, see below). The Python process spawns up Geckodriver & Firefox successfully, but then hangs with 100% CPU usage.

@lukebjerring the error we saw earlier when running the test locally was indeed a bug. The test script didn't correctly pass the Firefox path to tox (and pytest), so the system Firefox was used and geckodriver complained. This should be fixed by #10116 I sent out just now.

**Comment by jgraham** [comment]
```
james@ginny:~/develop/web-platform-tests/tools/wpt$ tox
[…]
===================================================================================== 11 passed, 1 skipped in 314.37 seconds ======================================================================================
```

So apparently it's not totally broken locally. Can you attach gdb to the process when it hangs and use `py-bt` to figure out what it's doing (you may need some setup  to get the python extensions working). Alterntaively can you run it under strace to get some idea of what happened  just before it hung?

**Comment by lukebjerring** [comment]
> james@ginny:~/develop/web-platform-tests/tools/wpt$ tox

tox issue described is in `resources/test`

**Comment by Hexcles** [comment]
Turns out the issue is really in `resources/test/wptserver.py`, namely the SSL context.

Explicitly specifying ssl.PROTOCOL_TLSv1 isn't really a good idea, as it actually involves system OpenSSL. In fact, I don't think we even need to check the HTTPS port of wptserve at all. As long as the HTTP port is up and running, wptserve should be ready.
