### ISSUE TITLE
idlharness.js throws string, testharness asserts only objects are thrown

### ISSUE THREAD

**Issue by lukebjerring** [w3c/web-platform-tests#10162]
Fix is simple: Define an IDLHarnessError type and throw those (with `toString` being the message).

So, without this turning into a rant about the gorgeous framework that is _testharness.js_ :
From https://github.com/w3c/web-platform-tests/blob/master/resources/idlharness.js#L586 :

    throw "Partial interface " + parsed_idl.name + " with no original interface";

From https://github.com/w3c/web-platform-tests/blob/master/resources/testharness.js#L1261 :

    assert(typeof e === "object",

That is to say, the same test suite throws a string and asserts that only objects are thrown.

**Comment by lukebjerring** [comment]
Looks like this issue/confusion is WAI, and is more to do with an ambiguous choice of method name. `assert_throws` is more `assert_throws_dom_exception`, asserting that the DOMException's code matches that which is provided. 

To generalize to expecting `idlharness.js` to error for a given input, we'll need to special-case an `IdlHarnessError` type.

**Comment by foolip** [comment]
`assert_throws` can also be used as `assert_throws(new TypeError, () => { .... })`, so the behavior depends on the type of the first argument.

**Comment by lukebjerring** [comment]
Sure, but the `idlharness.js` code is throwing a string, not a type error (or any other error) which means testing expected errors from `idlharness.js` itself is cumbersome.

**Comment by foolip** [comment]
Uh, you're right, that is weird, I was just reacting to "assert_throws is more assert_throws_dom_exception".
