### ISSUE TITLE
Overhaul web-platform-tests documentation

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#10177]
Given we don't have an issue for this and it appears in the Chrome team's Ecosystem Infra team's [Q1 OKRs](https://docs.google.com/document/d/1ojlLDiRruI4e95Z7JQ10JQPRMiQHd_40rBkYCL6IJqw/edit#heading=h.eklwjw99hd2u):

> From TPAC, seems like browser vendors think the web-platform-tests documentation is way too verbose, while others have no idea where to start.

See also: https://github.com/w3c/csswg-drafts/issues/2438 and all the [label:docs](https://github.com/w3c/web-platform-tests/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) issues.

@boazsender can you assign this to whomever is working on it at Bocoup?

**Comment by foolip** [comment]
@gsnedders, right now we're not really planning anything concrete on this, and I think that maybe a first good step would be to go through all of the open docs issues and figure out what's most important. I don't think an umbrella issue will necessarily help since we already have the label.
