### ISSUE TITLE
Evaluate which Payment Request tests can use testdriver

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-platform-tests#10187]
Given:
http://web-platform-tests.org/writing-tests/testdriver.html

We need to go through all the manual tests and see which could use testdriver.js to get a "trusted" click event. Downside will be that running the tests from the web make these kinda useless... though we could reengineer them to work on both the web (as manual tests) and in an automated fashion with testdriver.html. 

We would basically need a way of detecting what environment we are running in.  

cc @rsolomakhin

**Comment by rsolomakhin** [comment]
> We would basically need a way of detecting what environment we are running in.

```javascript
if (window.test_driver) {
   test_driver.click(element);
} else {
   document.getElementById('msg').innerHTML = 'Please click the button';
}
```

**Comment by rsolomakhin** [comment]
Is that how it works?

**Comment by marcoscaceres** [comment]
Could very much be. If so, then we could collect all the buttons and click one at a time, with hopefully not needing to touch the existing tests.

**Comment by marcoscaceres** [comment]
So, didn't work exactly like that... there is no way to detect it... so we have to write them one way or the other. The good news is, the test_driver works (mostly) across all browsers.
