### ISSUE TITLE
idlharness.js doesn't check existence of B when A : B

### ISSUE THREAD

**Issue by lukebjerring** [w3c/web-platform-tests#10214]
For `A implements B`, idlharness errors when B is not defined.

However, for `A : B`, it does not error, and eventually manifests as a null reference, i.e.

    TypeError: Cannot read property 'has_extended_attribute' of undefined

**Comment by inexorabletash** [comment]
Hrm... tests that pull in `dom.idl` started failing in Chrome's CI with:
```
FAIL Test driver promise_test: Unhandled rejection with value: object "CustomEventInit inherits EventInit, but CustomEventInit is not an interface."
```
... where `dom.idl` defines EventInit and then `dictionary CustomEventInit : EventInit ....` - related to this change? (I haven't bisected yet)

**Comment by lukebjerring** [comment]
Will roll back. WebIDL specs A : B as an interface behaviour, doesn't mention it for dictionaries. Will roll back and have a second stab at it.

**Comment by foolip** [comment]
Spec is https://heycam.github.io/webidl/#dfn-inherited-dictionaries

**Comment by lukebjerring** [comment]
Fixed by https://github.com/w3c/web-platform-tests/pull/10334
