### ISSUE TITLE
[runner] Improve styling of pathnames displayed under progress bar

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#1022]
See #1019. Would be nice to prettify the styling of area where the pathnames are displayed. Maybe @darobin has some idea.

**Comment by jugglinmike** [comment]
@sideshowbarker I can take a look at this, but it's difficult to know the status
of the feature from the discussion history alone. Currently, the UI looks like
this:

![screenshot from 2017-02-06 13-36-21](https://cloud.githubusercontent.com/assets/677252/22661035/c821f5de-ec71-11e6-93e3-82eb90557230.png)

I'm thinking of the following improvements:

- Explicitly labeling the value, "Current test:"
- Wrapping in a hyperlink (useful when test execution is paused or a test is
  actively timing out)
- Highlight the "matched" part of the URI

Together, these would look something like this:

![screenshot from 2017-02-06 14-05-59](https://cloud.githubusercontent.com/assets/677252/22662036/97455876-ec75-11e6-8034-28d85b79b6b6.png)


What do you think?

**Comment by bobholt** [comment]
Ping @sideshowbarker to take a look at @jugglinmike's suggestions above.

**Comment by sideshowbarker** [comment]
Sorry for taking so long to follow up on this. The suggested changes in the mock-up look like very good improvements to me (including covering the specific part about which I had originally raised this)
