### ISSUE TITLE
Stability check should also fail when messages aren't stable

### ISSUE THREAD

**Issue by Hexcles** [w3c/web-platform-tests#10246]
Sometimes the result statuses of a test are stable (e.g. all failures), but the messages are flaky (e.g. including a random string in the message), in which case stability checks should also fail.

Unstable messages make it hard for downstreams to create baselines for failed tests.

#10218 is an example https://pulls.web-platform-tests.org/job/26572.5

**Comment by gsnedders** [comment]
Pretty sure we don't guarantee messages are stable, and baselining should be done based on subtest name only.

**Comment by jgraham** [comment]
Yeah, the message shouldn't necessarily be stable, since it has to be informative about the error, which can vary (e.g. the number of pixels difference in a reftests, or the actual values when asserting some relation). The intent is that (test_id, subtest_name) is the stable identifier.
