### ISSUE TITLE
Replace check-stability script with wpt run --stability and document how to run locally

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#10269]
I'm not even sure it's intended to use locally, but it seems to assume quite heavily that it's running on TravisCI. For local use, a way to run it with a list of tests rather than revisions might be nice?

CC @foolip

**Comment by jgraham** [comment]
`wpt run --stability` does something mostly equivalent. Ideally the travis job would change to use that, but there are quite a few details to get right around reporting stuff correctly.

**Comment by mrego** [comment]
JFYI, both `run --stability` and `check-stability` run fine for me locally.

**Comment by foolip** [comment]
Is there anything that needs to be done here? Just documentation?

**Comment by gsnedders** [comment]
Documentation and making CI use `wpt run --stability`.

**Comment by ahmadmiz** [comment]
T

**Comment by gsnedders** [comment]
Per https://github.com/w3c/web-platform-tests/issues/10921 `--stability` is just a subset of behaviour of `--verify` and should really cease being separate, so let's close this in favour of https://github.com/w3c/web-platform-tests/issues/9874.

**Comment by gsnedders** [comment]
Also starting to look into this, we already use `--stability`.
