### ISSUE TITLE
Local imports fail in python file handlers

### ISSUE THREAD

**Issue by jakearchibald** [w3c/web-platform-tests#10378]
```py
from utils import create_wav_header
```

The above fails with `ImportError: No module named utils`, despite `utils.py` existing in the same directory.

**Comment by jakearchibald** [comment]
To workaround, use this before importing:

```py
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

# Now this works:
from utils import create_wav_header
```

**Comment by jakearchibald** [comment]
```py
from .utils import create_wav_header
```

Didn't work in this case either.

**Comment by foolip** [comment]
@jakearchibald, where did you write `from utils import create_wav_header`? I can't find the string "create_wav_header" anywhere in the repo.

**Comment by jakearchibald** [comment]
https://github.com/jakearchibald/web-platform-tests/commit/889cc1d092efef1a26f98a66cfbdd415dde2051f here's a reduction.

However, due to some python lifecycle stuff I don't understand (module caching?) if you visit `works.py`,  then `fails.py` will also work. Restart the WPT server, then `fails.py` will fail.

**Comment by gsnedders** [comment]
@jakearchibald the directory is added to `sys.path`, so after loading `works.py` that directory is in the path.

**Comment by jakearchibald** [comment]
@gsnedders that was my first thought, but `sys.path.pop(0)` doesn't seem to undo it.

**Comment by jgraham** [comment]
Yeah, the module is added to `sys.modules` and loaded directly from there. I have a solution in mind, which I can try quickly.
