### ISSUE TITLE
./resources/test/tox fails after 10231

### ISSUE THREAD

**Issue by lukebjerring** [w3c/web-platform-tests#10388]
Issue started after https://github.com/w3c/web-platform-tests/pull/10231

Message is 

    Could not start wptserve

Running `wptserve` works fine - but not with the config used in the test suite, which produces

    KeyError: u"unknown config override 'external_host'"

**Comment by lukebjerring** [comment]
I took a stab at fixing this, but it's got a large number of issues on top of each other.

I got stuck on `TypeError: 'NoneType' object is not callable`, which is caused by the `path` function not being set, which occurs during `__enter__`. Presumably, the droped `with` statement here is the issue:
https://github.com/w3c/web-platform-tests/pull/10231/files#diff-54595105eb1b125bb44120e81a893f4eL822

**Comment by gsnedders** [comment]
So `resources/test` has its own config for some reason, which is in an outdated format (even though we're meant to be backwards compatible there…). The only diff from the config.default.json at the time it was created is a non-standard HTTPS port? @jugglinmike do you recall why `config.test.json` does that?

**Comment by gsnedders** [comment]
It passes CI without that, so suggest we just land that PR.

**Comment by jugglinmike** [comment]
I suspect I was trying to avoid collisions for folks who were running the development server locally. If a server is already running (e.g. vie `./wpt serve`), the test setup will silently fail to create a dedicated server and instead use the previously-existing instance. This would be pretty confusing for folks who were trying to run the tests.

@gsnedders Do you agree? Would you accept a patch to re-introduce the configuration (with an explanatory code comment this time)?

**Comment by lukebjerring** [comment]
@jugglinmike - FWIW I did the equivalent in `wptserver.py` by trying to load the URL _before_ spawing the `wpt serve` subprocess - if the server's already up, it's ready to go for the `resources/test` tests.

Rolled it back because locally I was seeing a bunch of errors at the time.

**Comment by jugglinmike** [comment]
I don't believe any of these tests rely on the stateful features of wptserve (e.g. "stash"), so maybe the concern isn't worth worrying about. It feels like something that could surprise someone one day, though.

**Comment by gsnedders** [comment]
@jugglinmike if that's the goal we should just set all the ports to "auto" and not explicitly set any?

**Comment by gsnedders** [comment]
@jugglinmike also the file is treated as an override, so we'd only need `ports` defined, and not the rest.
