### ISSUE TITLE
WPT CLI: Extend Firefox logic to branch on the browser's release channel

### ISSUE THREAD

**Issue by jugglinmike** [w3c/web-platform-tests#10436]
Currently, when the WPT CLI is used to run Firefox, it assumes that the browser
being tested is from the "Nightly" release channel. This causes it to download
a "preferences" file which is inappropriate for the stable release channel. The
logic should be extended to inspect the version of Firefox under test and
retrieve a configuration file based on the version found.

@jgraham described the problem and solution to me in IRC today, though I'm
missing some information about how the alternate "preferences" file should be
located. Could you elaborate on that part, James?

**Comment by jgraham** [comment]
I started this on the train last night, so I finished it today. #10443 should fix the problem.

**Comment by jugglinmike** [comment]
Resolved via gh-10443
