### ISSUE TITLE
support test_driver in Safari/Webkit 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-platform-tests#10529]
What needs to happen to get test_driver in WebKit? 

cc @aestes 

Allows us to land https://github.com/w3c/web-platform-tests/pull/10500

**Comment by gsnedders** [comment]
What doesn't work? It should all work?

**Comment by marcoscaceres** [comment]
Sorry, maybe it does. The docs said Chrome and Firefox only.

**Comment by gsnedders** [comment]
It appears to work in Safari TP but not Safari, presumably because of changes in safaridriver.

**Comment by marcoscaceres** [comment]
@gsnedders, thanks for checking. Leaving this open as we need to update the documentation, at least.

**Comment by gsnedders** [comment]
I'm pretty sure I saw it working in Safari before, so I'm a bit confused. I wonder if it's some setup thing not working properly…

**Comment by marcoscaceres** [comment]
Sounds like "it just works"... or, "will just work" based on Safari Tech Preview. Sorry for the noise, @gsnedders.  

@aestes, I'll keep landing ones like #10500. Please take a look that and let me know if it's Apple Pay compatible.

**Comment by marcoscaceres** [comment]
Actually, leaving this open to update the docs.

**Comment by marcoscaceres** [comment]
Must be getting old... I could have sworn [the documentation](https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/testdriver.md) talked about only being supported in Chrome and Firefox. Re-reading it, seems it's all fine.
