### ISSUE TITLE
euckr-encode-form-errors-hangul.html does not run

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#10635]
And https://github.com/w3c/web-platform-tests/blob/master/encoding/legacy-mb-korean/euc-kr/euckr-encode-form-errors-hangul.html even admits it in a comment at the top.

@domenic @r12a should this be removed or can it be fixed somehow? I tried to figure out what was going on, even diffing it against similar files, but no luck thus far.

**Comment by r12a** [comment]
This is another file that was not intended to be a test, and was copied over in error. It should be deleted.

I combed through the other files in the kr directory and i believe it's just this and its headers file that need to be removed.

I'll also comb through the other directories.
