### ISSUE TITLE
Taskcluster master runs fail very often

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#10653]
https://github.com/w3c/web-platform-tests/pull/9226 landed yesterday so we have some finished runs now. The most recent from https://github.com/w3c/web-platform-tests/commits/master:
* https://github.com/w3c/web-platform-tests/commit/16c3c0730390a2e1b6bc2919dfeedc159e2b6a01 &rarr; https://tools.taskcluster.net/task-group-inspector/#/W6qbW3yQQ-udvC3EfCbIWA
* 3e538e72b8f12de065612862486c3fc24beb9c53 &rarr; https://tools.taskcluster.net/task-group-inspector/#/Y2LPzz49RiqEy_TpHP7_fg
* 62c85b4892519965b4e15f4291a4f7acc6e13ab5 &rarr; https://tools.taskcluster.net/task-group-inspector/#/E6sRtJcWRvSeXqYxh3vnAA

In the last, https://tools.taskcluster.net/groups/E6sRtJcWRvSeXqYxh3vnAA/tasks/Dbj4toXRQyq2Yfr2TRk1lA/runs/0/logs/public%2Flogs%2Flive.log has this log:
```
Using certutil /usr/bin/certutil
Installing test prefs from https://hg.mozilla.org/mozilla-central/raw-file/tip/testing/profiles/prefs_general.js
Updating test manifest /home/test/web-platform-tests/MANIFEST.json
STDOUT: WARNING:manifest:No generated manifest found
STDOUT: INFO:manifest:Updating manifest
STDOUT: DEBUG:manifest:Opening manifest at /home/test/web-platform-tests/MANIFEST.json
Using 1 client processes
Starting http server on 127.0.0.1:8000
Starting http server on 127.0.0.1:8001
Starting http server on 127.0.0.1:8443
Closing logging queue
queue closed
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/test/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 453, in run
    rv = run_single(venv, **kwargs) > 0
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 460, in run_single
    wptrunner.start(**kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 309, in start
    return not run_tests(**kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 188, in run_tests
    test_environment.ensure_started()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/environment.py", line 231, in ensure_started
    ", ".join("%s:%s" % item for item in failed))
EnvironmentError: Servers failed to start: 127.0.0.1:8888
[taskcluster 2018-04-26 10:52:26.000Z] === Task Finished ===
[taskcluster 2018-04-26 10:52:26.869Z] Unsuccessful task run with exit code: 1 completed in 335.752 seconds
```

Looks like a job for @jgraham :)

**Comment by foolip** [comment]
@jgraham, in addition to fixing this, what monitoring do you think we should put in place? If this is on track to become critical infrastructure, then I'd like something in https://foolip.github.io/ecosystem-infra-rotation/ to go red when Taskcluster is consistently failing. What API should I look at?

**Comment by foolip** [comment]
Actually, failure rate is not 100%, yay! 5 have succeeded since runs began:
https://tools.taskcluster.net/groups/BJzrvu9gRN6vjLhFrvWk8g
https://tools.taskcluster.net/groups/dejBi8nIReeNeb_g86-fUQ
https://tools.taskcluster.net/groups/KmOaDWNPQ1eNkLf4mnCWaw
https://tools.taskcluster.net/groups/Xe2wHC-IQT2WP2KIUpIgOw
https://tools.taskcluster.net/groups/Bv2TZUgeSyGhXblM8UU0aA

**Comment by foolip** [comment]
@Hexcles @lukebjerring , even for the failing ones there will be *some* results. I guess we will have to decide whether we require all tasks to have succeeded, or if we collect and submit partial results to wpt.fyi and treat it as a processing or frontend problem what runs to show. WDYT?

**Comment by jgraham** [comment]
Re: the API you want the GitHub (combined) status API.

**Comment by foolip** [comment]
@jgraham you mean just to know that Taskcluster has finished?

**Comment by jgraham** [comment]
Yes. If you want to know specifics about the task statuses, you use e.g. https://queue.taskcluster.net/v1/task-group/Jvlwi0jnR-68F5eUlfcfgg/list where the random string is the taskgroup id that you can get from the URL in the status messge.

**Comment by Cactusmachete** [comment]
I've intermittently come across this issue myself when messing around with `./wpt run`. Not sure where it stems from, but it doesn't seem to be Taskcluster specific.

**Comment by jgraham** [comment]
I think the biggest issues here are now fixed. I see occasonal timeouts still, which warrant investigation because I'm not sure it should take so long to run tests, and there seems to be a race condition when merging PRs that we sometimes get "Reference is not a tree".

**Comment by foolip** [comment]
@jgraham it looks like all recent runs are still failing?

**Comment by foolip** [comment]
After https://github.com/w3c/web-platform-tests/pull/10762, based on visual inspection of https://github.com/w3c/web-platform-tests/commits/master Taskcluster has succeeded more often, maybe 80% of the time, but it's not rock solid. @jgraham, do you think this tracking issue is still useful, or does https://github.com/w3c/web-platform-tests/issues/10842 account for all of the remaining issues?

**Comment by jgraham** [comment]
#10842 accounts for everything that I have specifically noticed. I'll file more issues as I figure out more things.
