### ISSUE TITLE
Dubious cross-origin document.origin test

### ISSUE THREAD

**Issue by nox** [w3c/web-platform-tests#10695]
```
/html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_setter.html
```

https://freenode.logbot.info/whatwg/20180427#c1520584

Cc @annevk

**Comment by foolip** [comment]
Also shows up in https://master-dot-wptdashboard.appspot.com/interop/html/browsers/origin/relaxing-the-same-origin-restriction and https://wpt.fyi/html/browsers/origin/relaxing-the-same-origin-restriction

@zcorpan has this showed up in any of your error reports? Seems like there should be cases like sprinkled across wpt and some fraction of them might reveal some interesting interop problem if fixed.

**Comment by zcorpan** [comment]
The only html/browsers/origin/ test I see in https://bocoup.github.io/wpt-disabled-tests-report/ is this one:

/html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_setter_null.tentative.html | webkit | [ Pass Failure ] | webkit.org/b/177440
-- | -- | -- | --


In https://bocoup.github.io/wpt-error-report/ this test shows (I'll defer to @rwaldron on how to interpret the below)

```
document_domain_setter.html (source)
chrome-63.0-linux @ 6ed1ba18d0
1 of 3 were not executed.
edge-15-windows-10-sauce @ 5d55258739
2 of 3 were not executed.
firefox-57.0-linux @ 1dfa574650
2 of 3 were not executed.
safari-11.0-macos-10.12-sauce @ fc2e57a502
2 of 3 were not executed.
```
