### ISSUE TITLE
Python checks for hosts file are not working anymore

### ISSUE THREAD

**Issue by thejohnjansen** [w3c/web-platform-tests#10741]
After @gsnedders recent changes to run.py, tests no longer work on Windows. During the check for the hosts file, it throws an error suggesting you should create the hosts entries. However, doing so does not help.

When the entries are created, there is an additional space character injected between each char

eg:  1 2 7 . 0 . 0 . 1 	 w e b - p l a t f o r m . t e s t

So then later, the checks fail. If I remove the spaces, then all is good.

I was just going to submit a new PR for that, but I cannot find the spot where those spaces are added. I'm still checking, though.

**Comment by gsnedders** [comment]
@thejohnjansen did you not have this happen some point previously?

**Comment by gsnedders** [comment]
So:

`python wpt make-hosts-file | Format-Hex -Encoding Ascii` shows what I'd expect (ASCII output).

`python wpt make-hosts-file > foo` and then `Format-Hex foo` shows the same thing, but encoded as UTF-16?! Um.

**Comment by gsnedders** [comment]
Oh, duh, that's because PowerShell's default output is UTF-16.

**Comment by gsnedders** [comment]
So yeah, you want:

```
python wpt make-hosts-file | Out-File %SystemRoot%\System32\drivers\etc\hosts -Encoding ascii -Append
```
