### ISSUE TITLE
nonexistent-origin is confusing

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#10754]
Presumably this is a domain, so `nonexistent-domain` or `nonexistent-host` would be more accurate. Could we rename this?

Can one use the subdomains here too?

(` docs/_writing-tests/server-features.md`)

**Comment by jugglinmike** [comment]
You might be interested in gh-10560, too. If @gsnedders supports your idea of renaming, then I would be happy to resolve both issues by renaming the domain, updating the hostfile generation logic, and changing existing references in the docs/tests.

**Comment by gsnedders** [comment]
If we can get away with renaming it, I guess we may as well?

**Comment by jugglinmike** [comment]
I couldn't ask for a more enthusiastic endorsement :P gh-10878
