### ISSUE TITLE
Sort out what "Reset if relatedTarget pointed to a shadow tree pre-dispatch" test in dom/events/relatedTarget.window.js actually should test

### ISSUE THREAD

**Issue by smaug----** [w3c/web-platform-tests#10854]
I'm changing the test to actually get the listener called in https://bugzilla.mozilla.org/show_bug.cgi?id=1449560 but it isn't clear to me how to change the test to test what it apparently tries to test.

**Comment by smaug----** [comment]
@annevk

**Comment by smaug----** [comment]
ah, right.
Or, should retargeting not do anything if B is not a node or not a node in same (shadow including) tree

**Comment by annevk** [comment]
@smaug---- B could be `Window` in which case we do want to do something I think. Covering that case also makes the same-tree check more complicated, which is why @hayatoito ended up with the current model I think.

**Comment by annevk** [comment]
I think it's probably easiest if we leave the specification unchanged for this. I'll work on a PR for the affected tests.

**Comment by annevk** [comment]
@smaug---- #10863 has my suggested fix for the test. Firefox Nightly fails it (and also the acvication one, as I think you already knew).
