### ISSUE TITLE
stability checker tries to run all testharness.js tests when testharness.js is modified

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#10928]
this invariably times out, @jgraham has apparently almost fixed this now

**Comment by foolip** [comment]
I'd say this is a dupe of https://github.com/w3c/web-platform-tests/issues/7660. The right fix, IMHO, would be to have a CI which is able to run all testharness.js tests if testharness.js is modified, even if it doesn't do it by default.
