### ISSUE TITLE
Declare timeout in test and extract it into manifest

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#11029]
https://bugs.chromium.org/p/chromium/issues/detail?id=843213 is about how the information in `async_test(undefined, { timeout: 10000 })` isn't machine readable, and so the test runner still can't increase the external timeout based on it.

To make that work, I think the information would have to be in `<meta something=somethin>` and we should extract it into the manifest for `./wpt run` to use.

**Comment by foolip** [comment]
@jgraham, how do you deal with slow tests in Gecko?

**Comment by foolip** [comment]
OK, so we already have `<meta name=timeout content=long>`. Is that information extracted into the manifest and used by the runner already?

**Comment by jgraham** [comment]
Yes.

**Comment by foolip** [comment]
Should the per-test timeout be nuked? Nothing about `var timeout = properties.timeout ? properties.timeout : settings.test_timeout` looks deprecated.

**Comment by jgraham** [comment]
The indicaton that it's deprecated is that that it's not in the documentation. I admit it's not a *great* signal, as there are lots of other things that aren't deprecated and aren't in the documentation. Anyway I would welcome a PR to remove the feature and all the instances of per-test timeouts in existing tests.

**Comment by jgraham** [comment]
wptrunner makes a distinction between an internal timeout ("browser still respodng enough to signal a timeout occurred; keep using the same instance for the next test") and an external timeout ("things are so broken we should kill the browser and restart"). It's possible to just have an external timeout everywhere, but the distinction is meaningful. Also it is helpful for people running tests directly in a browser to understand if they are taking too long.

**Comment by foolip** [comment]
OK, I agree that's a meaningful distinction and useful when running manually. I presume the external timeout is always a bit longer, to not make it entirely racy?

**Comment by jgraham** [comment]
Yes. We set the selenium/marionette timeout to the test timeout + 5s and the "give up waiting for the driver to return" timeout to the test timeout + 10s.

**Comment by foolip** [comment]
OK, nothing to be done here.

**Comment by Hexcles** [comment]
This matches my understanding ("timeouts in tests" are discouraged).

Shall we remove that section from https://web-platform-tests.org/writing-tests/testharness-api.html, or at least mark it as deprecated?
