### ISSUE TITLE
URL: IPv4 normalization?

### ISSUE THREAD

**Issue by SimonSapin** [w3c/web-platform-tests#1104]
#771 adds some tests that suggest that (after percent-decoding and Nameprep) the URL parser should convert hexadecimal and octal numbers in IPv4 addresses to decimal, support less than four dot-separated pieces, and check that they’re within range:

```
http://%30%78%63%30%2e%30%32%35%30.01 s:http p:/ h:127.0.0.1
http://\uff10\uff38\uff43\uff10\uff0e\uff10\uff12\uff15\uff10\uff0e\uff10\uff11  s:http p:/ h:192.168.0.1
http://192.168.0.257
```

(By the way, it looks like the first line should have `h:192.168.0.1` instead of `h:127.0.0.1`. The first two inputs decode to `http://0xc0.0250.01`.)

But I find nothing in the spec that supports this. Should it be added to the spec, or should these tests be removed?

For what it’s worth, [RFC 3986](http://tools.ietf.org/html/rfc3986#section-7.4) says:

> For example, many implementations allow dotted forms of three numbers, wherein the last part is interpreted as a 16-bit quantity and placed in the right-most two bytes of the network address (e.g., a Class B network).  Likewise, a dotted form of two numbers means that the last part is interpreted as a 24-bit quantity and placed in the right-most three bytes of the network address (Class A), and a single number (without dots) is interpreted as a 32-bit quantity and stored directly in the network address. Adding further to the confusion, some implementations allow each dotted part to be interpreted as decimal, octal, or hexadecimal, as specified in the C language (i.e., a leading 0x or 0X implies hexadecimal; a leading 0 implies octal; otherwise, the number is interpreted as decimal).
> 
> These additional IP address formats are not allowed in the URI syntax due to differences between platform implementations.  However, they can become a security concern if an application attempts to filter access to resources based on the IP address in string literal format. If this filtering is performed, literals should be converted to numeric form and filtered based on the numeric value, and not on a prefix or suffix of the string form.

Test case:

``` html
<a href="http://127.0.0.1:8000/">Decimal</a><br>
<a href="http://0x7f.0.0.1:8000/">Hex</a><br>
<a href="http://0177.0.0.1:8000/">Octal</a>
```

Firefox and Chrome both connect to localhost for all three links. Firefox considers all links different for the purpose of applying `:visited` styling and displays them as-is in the address bar, while Chrome considers them all the same and displays the decimal version in the address bar.

It may be worth having in the spec a concept of IPv4 address made of four 8-bit pieces (just like IPv6 address is a separate concept) instead of treating them as string domains.

CC @annevk @sideshowbarker

**Comment by annevk** [comment]
We've added several more IPv4 tests since (and the standard has changed quite a bit on that front). Closing this. If we need more a more specific issue would be great!
