### ISSUE TITLE
[css-text] css3-text-line-break-jazh- tests miss the lang attribute on references

### ISSUE THREAD

**Issue by mrego** [w3c/web-platform-tests#11106]
Several `css3-text-line-break-jazh-` tests miss the `lang` attribute on the reference files,
this is causing issues to run the tests on WebKit in the Mac platform, as the rendering is not exactly the same.

For example http://w3c-test.org/css/css-text/i18n/css3-text-line-break-jazh-027.html
vs http://w3c-test.org/css/css-text/i18n/reference/css3-text-line-break-jazh-027-ref.html

On the test we have:
```html
<div class='test' lang='ja'>中中中&#x2013;文</div>

<div class='ref'>中中<br/>中&#x2013;文</div></div>
```

But on the reference we have:
```html
<div class='ref'>中中<br/>中&#x2013;文</div></div>

<div class='ref'>中中<br/>中&#x2013;文</div></div>
```

Note that `lang='ja'` is missing there.

And this is the output of the tes when run on WebKit in Mac:
![Outpu of the test in WebKit](https://user-images.githubusercontent.com/11602/40391157-adb19718-5e17-11e8-8857-0400e81700a2.png)

And this is the output of the reference file:
![Output of the reference in WebKit](https://user-images.githubusercontent.com/11602/40391190-bcdb56b6-5e17-11e8-9378-d9b3ea300711.png)

Adding `lang='ja'` to the reference is fixing the issue.

So I'd like to know if adding `lang='ja'` to the references would be ok,
if so I could provide a patch and get this tests running properly in WebKit too.

I believe we should make the changes so the test is like:
```html
<div class='test' lang='ja'>中中中&#x2013;文</div>

<div class='ref' lang='ja'>中中<br/>中&#x2013;文</div></div>
```

And the reference file like:
```html
<div class='ref' lang='ja'>中中<br/>中&#x2013;文</div></div>

<div class='ref' lang='ja'>中中<br/>中&#x2013;文</div></div>
```

If I understand it correctly the test would still be valid with such changes.

WDYT? @kojiishi, @litherum, @frivoal

**Comment by mrego** [comment]
BTW, note that some of the tests called `css3-text-line-break-jazh-`
have the `lang='ja'` attribute in the four places (2 in the test and 2 in the reference file).
Example:
* https://github.com/w3c/web-platform-tests/blob/master/css/css-text/i18n/css3-text-line-break-jazh-001.html
* https://github.com/w3c/web-platform-tests/blob/master/css/css-text/i18n/reference/css3-text-line-break-jazh-001-ref.html

And those tests pass fine in WebKit on Mac.

My plan to fix this problem in the rest of the tests following the same approach.

**Comment by kojiishi** [comment]
Sounds good to me. Please note that @r12a is working on a new replacements of these tests. The new tests use JavaScript and reduces the number of test files. IIUC we'll remove these tests once the new one is done.

**Comment by frivoal** [comment]
@mrego 
1. As a general rule, what you propose is fine
2. In a few cases, the spec expects some differences in line breaking between Japanese, Chinese, or non marked CJK text ([see here](https://drafts.csswg.org/css-text-3/#line-break-property) or [here](https://drafts.csswg.org/css-text-3/#line-break-transform)). I don't know if any of the tests in question depend on that, but as you update them, be mindful of that.
3. what @kojiishi said.

**Comment by r12a** [comment]
@mrego please see the PR at https://github.com/w3c/web-platform-tests/pull/10860#event-1611279850 which has been waiting for further review for 2 weeks now.  That PR should fix the issues you mention here and more. I just added you as a potential reviewer.

**Comment by mrego** [comment]
@r12a ok that's really nice, I won't be fixing this then and wait for that PR to reimport things in WebKit.
I took a look and did several comments on the new tests, but @kojiishi or @frivoal or someone else
should be the person revieweing the PR as I don't know this stuff well enough.

I believe we can close this as that PR will address it.
