### ISSUE TITLE
Make a better progress indicator for tools/runner when it's waiting for manifest to be created

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#1171]
We should make the UI more clearly indicate to user that it's waiting for the manifest to be created, rather than just hanging. The existing "Updating and loading test manifest" text is easy to miss. [This is a follow-up to issue #1070]

**Comment by bobholt** [comment]
@sideshowbarker: I believe this was resolved by https://github.com/w3c/wpt-tools/pull/161. Can this be closed?

**Comment by sideshowbarker** [comment]
> I believe this was resolved by w3c/wpt-tools#161. Can this be closed?

Yep, closing
