### ISSUE TITLE
Deal with xml:base in URL doc-conformance tests

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#1190]
see https://critic.hoppipolla.co.uk/showcomment?chain=4283

**Comment by domenic** [comment]
I can't load that URL, but I think this can be closed since we successfully killed xml:base from the platform.

**Comment by sideshowbarker** [comment]
Thanks, closing per https://github.com/w3c/web-platform-tests/issues/1190#issuecomment-241131866
