### ISSUE TITLE
document-lastModified uses a locale-specific string

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#1246]
https://github.com/w3c/web-platform-tests/blob/master/html/dom/documents/resource-metadata-management/document-lastModified.html#L12

https://html.spec.whatwg.org/#dom-document-lastmodified specifies a very precise output; using a local-dependent string can cause the month and day to switch positions, for example.

**Comment by jdm** [comment]
@jgraham Why's this closed?

**Comment by jgraham** [comment]
#1600
