### ISSUE TITLE
resource-timing test fails for .xml file

### ISSUE THREAD

**Issue by valenting** [w3c/web-platform-tests#1258]
https://github.com/w3c/web-platform-tests/blob/master/resource-timing/test_resource_timing.html#L196

getEntriesByName will return an empty array, because the provided name is "/resource-timing/resources/resource_timing_test0.xml" instead of "http://web-platform.test:8000/resource-timing/resources/resource_timing_test0.xml"

**Comment by jgraham** [comment]
This was fixed
