### ISSUE TITLE
likely use of non-standard HTMLCollection.item(String)

### ISSUE THREAD

**Issue by hrj** [w3c/web-platform-tests#1264]
Apropos this line of code:
https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Element-children.html#L10

As I understand, Element.children() returns an HTMLCollection and  HTMLCollection.item() only accepts an integer as parameter. Why does the above test call `item("foo")`?

**Comment by jgraham** [comment]
No this test is correct. item("foo") does item(ToUInt32("foo")) === item(0) (ToUInt32 is an ECMAScript internal algorithm).

**Comment by hrj** [comment]
@jgraham I am trying to find the set of rules that mandate the conversion of the string argument to `0`. Is this conversion applicable in all cases, or is it specific to HTMLCollection? Can you please point me to any specs? Thanks!

**Comment by inexorabletash** [comment]
The __item()__ accessor is defined via Web IDL in https://dom.spec.whatwg.org/#interface-htmlcollection as:

 `getter Element? item(unsigned long index);`

Web IDL defines how values are converted  from ECMAScript to IDL types like __unsigned long__. Specifically: http://heycam.github.io/webidl/#es-unsigned-long

Step 1: x = ToNumber(V) -- x will be NaN
Step 2: N/A
Step 3: N/A
Step 4: x = ToUint32(x) -- x will be 0

**Comment by hrj** [comment]
@inexorabletash Thanks a lot!
