### ISSUE TITLE
resource-timing test includes timestamps in error message

### ISSUE THREAD

**Issue by valenting** [w3c/web-platform-tests#1267]
https://github.com/w3c/web-platform-tests/blob/master/resource-timing/test_resource_timing.html#L269

The failure message includes variable timestamps, which makes each test be difficult to identify and eventually ignore in Firefox's test infrastructure. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1002855#c29

**Comment by jgraham** [comment]
AFAICT this got fixed.
