### ISSUE TITLE
/XMLHttpRequest/xmlhttprequest-timeout-worker-overrides.html fails intermittently due to race condition in the test

### ISSUE THREAD

**Issue by mukilan** [w3c/web-platform-tests#1362]
We encounter this failure in [Servo](https://github.com/servo/servo/issues/3887).

Here are the relevant bits.

The 3rd subtest fails intermittently:

```
Unexpected Results
==================

/XMLHttpRequest/xmlhttprequest-timeout-worker-overrides.html
------------------------------------------------------------
FAIL Timeout test: timeout enabled after initially disabled, original timeout at 0, reset at 400 to 1000
15:30.92 LOG: MainThread INFO Closing logging queue
```

The expected behaviour is that the response is delivered at ~0.6s while the timeout is reset at 0.4s from 0 to 1s. However, sometimes both the response and timeout reset happen very close to 1s (possibly due to the OS scheduling). When this happens, because the time since the fetch started is 1s and the request has not yet completed, we endup with a "timeout" event rather than "load". 

One possible solution I could think of was to change the test so that when we reset the timeout value, we reset it to some value >>1000ms, giving plenty of time for the request to complete.

**Comment by Ms2ger** [comment]
w3c-test:mirror

**Comment by nox** [comment]
AFAICT, this can be closed.
