### ISSUE TITLE
Test runner has no progress on updating and loading test manifest

### ISSUE THREAD

**Issue by zqzhang** [w3c/web-platform-tests#1372]
Just tried to update Vibration test results via http://w3c-test.org/tools/runner/index.html on both Chrome/Firefox for Android and desktop, seems it has no progress on updating and loading test manifest.

CC @sideshowbarker @jgraham

**Comment by sideshowbarker** [comment]
See https://github.com/w3c/web-platform-tests/pull/1501 and https://github.com/w3c/web-platform-tests/pull/1501

**Comment by sideshowbarker** [comment]
See https://github.com/w3c/web-platform-tests/pull/1501 and http://w3c-test.org/submissions/1501/tools/runner/index.html

**Comment by zqzhang** [comment]
Cool.
