### ISSUE TITLE
html/semantics/forms/the-input-element/radio.html shouldn't check isTrusted==true

### ISSUE THREAD

**Issue by Manishearth** [w3c/web-platform-tests#1418]
https://github.com/w3c/web-platform-tests/blob/master/html/semantics/forms/the-input-element/radio.html#L86

`.click()`, which generates _synthetic_ clicks, does not generate trusted events.

See https://html.spec.whatwg.org/multipage/interaction.html#run-synthetic-click-activation-steps

**Comment by smaug----** [comment]
The change here was against the spec, or at least is against the current spec.

**Comment by zcorpan** [comment]
@smaug---- 

> Fire a click event at the element. If the run synthetic click activation steps algorithm was invoked because the click() method was invoked, then the isTrusted attribute must be initialised to false.

https://html.spec.whatwg.org/multipage/interaction.html#run-synthetic-click-activation-steps

https://github.com/w3c/web-platform-tests/commit/5d1a5c182cf0cddb4690613f913c8abd427946cf seems to match that; `isTrusted` should be false.

No?

**Comment by smaug----** [comment]
What has https://html.spec.whatwg.org/multipage/interaction.html#run-synthetic-click-activation-steps to do with change and input events?

**Comment by zcorpan** [comment]
Hah oops! Sorry.

> The activation behaviour for R is to fire a simple event that bubbles named input at R and then fire a simple event that bubbles named change at R.

https://html.spec.whatwg.org/multipage/forms.html#radio-button-state-(type=radio)

> Firing a simple event named e means that a trusted event with the name e, [...]

https://html.spec.whatwg.org/multipage/webappapis.html#fire-a-simple-event

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4117 isTrusted is true in Gecko and Chromium (undefined in WebKit).

Yes, we should revert this change (+ checkbox).

**Comment by cvrebert** [comment]
Refs #2920
