### ISSUE TITLE
Web Platform Tests should support HTTPS.

### ISSUE THREAD

**Issue by mikewest** [w3c/web-platform-tests#1483]
WebAppSec has a number of specs in flight that require HTTPS for some or all of their functionality. "Mixed Content", for instance, only makes sense in the context of a secure site.

We have a number of tests in Blink for these features, but porting them over to WPT isn't possible until there's a secure endpoint we can test against. At a minimum, `https://w3c-test.org/` would alias the insecure version (and even more ideally, we'd have some distinct alias (not-w3c-test.org?) for cross-origin tests). It would also be lovely if we could work out a certificate distribution mechanism for the various local aliases.

Following up on our conversation yesterday: Tobie, would you mind helping me find the right set of folks to get this in front of? I'm totally willing to help, but I need some help helping. :)

**Comment by jgraham** [comment]
Yeah, this is just waiting on me figuring out why the associated wptrunner change doesn't work in Firefox on Windows.

**Comment by jgraham** [comment]
This got fixed.
