### ISSUE TITLE
hasAttribute/getAttribute confusion

### ISSUE THREAD

**Issue by darobin** [w3c/web-platform-tests#1484]
I am confused about the test in https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/attributes.html#L273 (and the following one). As far as I know and can tell, the empty string for namespaces should be converted to null, and on an HTML element the name should get lowercased. Based on this the tests should be in large part reversed. We're seeing some discrepancies in implementations, so it probably isn't a spec bug (though it's not clear that any option actually matches reality).

**Comment by Ms2ger** [comment]
> and on an HTML element the name should get lowercased

Where do you get that? This is `setAttributeNS`, not `setAttribute`.
