### ISSUE TITLE
Add tests for liveness of NodeLists/HTMLCollections.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#1505]
(Please add any I missed.)
- [ ] Node#childNodes
- [ ] ParentNode#children
- [ ] {Document,Element}#getElementsByTagName
- [ ] {Document,Element}#getElementsByTagNameNS
- [ ] {Document,Element}#getElementsByClassName
- [ ] Document#images
- [ ] Document#embeds
- [ ] Document#plugins
- [ ] Document#links
- [ ] Document#forms
- [ ] Document#scripts
- [ ] Document#commands
- [ ] Document#getElementsByName
- [ ] Document#getItems

**Comment by tracywalker** [comment]
I'll take this issue.

**Comment by ashughes1** [comment]
Tracy has moved off the DOM team to focus on e10s so I'll be taking this over. What is meant by "liveness"?

**Comment by plehegar** [comment]
This means that the NodeList or HTMLCollection are operating on the actual underlying data and not a snapshot of the data. Happy to give an example if needed.

**Comment by ashughes1** [comment]
> Happy to give an example if needed.

That would be appreciated, thanks.

**Comment by plehegar** [comment]
See http://jsfiddle.net/plhw3org/gLj2mfky/
The NodeList object was updated. That's what is meant by "live". If it wasn't live, children.length would always return 4. A proper test for the NodeList returned by childNodes needs to check that the list is updated if the children of the Node are removed or appended.

**Comment by kaixinjxq** [comment]
Add tests at #8993 except "Document#commands" and "Document#getItems" since they have been removed from latest spec.
