### ISSUE TITLE
Add more extensive tests for crypto.getRandomValues().

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#1527]
https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#dfn-Crypto-method-getRandomValues

In particular:
* [ ] check that `QuotaExceededError` is thrown for all types of arguments, not just `Int8Array`
* [ ] check that the exception is based on the `byteLength`, not the size 
* [ ] check that lengths less than or equal to 65536 are supported
* [ ] check that the returned view is the same object as is passed to the function
* [ ] check that zero-size arrays are handled correctly
* [ ] check that `Uint8ClampedArray` arguments are supported

**Comment by cgdjmr** [comment]
How should zero-size arrays to be handled? I didn't notice it mentioned in the spec you posted.

**Comment by Ms2ger** [comment]
Indeed, so exactly like size-*n* arrays for other *n* <= 65536: generate *n* random values, and return the argument. (I mentioned that case in particular because it takes Gecko on a different code path.)

**Comment by cgdjmr** [comment]
Ah, got it. Your mentioning it made me wonder if some atypical behavior was expected. 

Thanks for your response. I've been working on some of the tests as a way of learning about HTML5 and JavaScript.
