### ISSUE TITLE
Add XMLHttpRequest test with UTF-16-encoded response w/BOM

### ISSUE THREAD

**Issue by hallvors** [w3c/web-platform-tests#1586]
There's no test that sends back an UTF-16 response with a BOM.

**Comment by hallvors** [comment]
So, the question - for @annevk and others - is whether a response which is UTF-16 encoded with a UtF-16 BOM should be content-sniffed and decoded as UTF-16 (Chrome does this) or not (Gecko).

**Comment by annevk** [comment]
Well the BOM is authoritative. It should not be "sniffed".
