### ISSUE TITLE
Add a test for toDataURL("image/jpg")

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#1602]
Note "jpg", not "jpeg".

Preferably in `2dcontext/tools/tests.yaml`; use `2dcontext/tools/gentest.py` to generate the test.

**Comment by Ms2ger** [comment]
(Originally filed as <https://www.w3.org/Bugs/Public/show_bug.cgi?id=14426>.)

**Comment by zqzhang** [comment]
Resolved by #2047.
