### ISSUE TITLE
Rerun 2dcontext/tools/gentest.py

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#1603]
tests.yaml was changed in https://github.com/w3c/web-platform-tests/pull/1599 so we should regen the tests. I don't have the dependencies currently.

Maybe the script should also be moved to /tools/ and updated to put the tests in the right place.

**Comment by zqzhang** [comment]
I don't have the dependencies either. By manually build and install the https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz#md5=f50e08ef0fe55178479d3a618efe21db, I find there are some other files change, with only an empty line added to the .html files and several .png files change.

Not sure if this the right way to do so :)

**Comment by zqzhang** [comment]
By the way, with this rerun, I find that `html/semantics/embedded-content/the-canvas-element/2d.scaled-manual.png` shall be `html/semantics/embedded-content/the-canvas-element/2d.scaled.png`.
