### ISSUE TITLE
Improve XMLHttpRequest test coverage of request error steps with progress events sending 0 and 0

### ISSUE THREAD

**Issue by diorahman** [w3c/web-platform-tests#1628]
The current test, http://w3c-test.org/XMLHttpRequest/send-timeout-events.htm, doesn't check the values sent by the progress events. As specified in [[1]](https://xhr.spec.whatwg.org/#request-error-steps), the values should be 0 and 0 .

[1]  Request error steps: https://xhr.spec.whatwg.org/#request-error-steps.

**Comment by hallvors** [comment]
Thanks @diorahman - I'll make sure this is tested, either by this test or elsewhere

**Comment by jdm** [comment]
This looks like it was fixed by #1676.
