### ISSUE TITLE
Add more Document#currentScript tests.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#1636]
Via @zcorpan:

- [ ] Test nested scripts; verify outer script before, inner script, outer script after.
- [ ] Verify in beforescriptexecute
- [ ] Verify in afterscriptexecute
- [ ] Test failed load, verify in error event listener.
- [ ] Test document.write.
- [ ] Verify in window.onerror for runtime script errors.
- [ ] Verify in window.onerror for compile-time errors.
- [ ] Verify in event handler attribute.
- [ ] Verify in setTimeout(string, 0)
- [ ] Verify in eval()
- [ ] Verify after a sync XHR
- [ ] Test XHTML
- [ ] Test &lt;svg&gt;&lt;script&gt;
- [ ] Test &lt;script async&gt;
- [ ] Test &lt;script defer&gt;
- [ ] Test document.createElement('script').async = false;
- [ ] Test &lt;link rel=stylesheet href=foo&gt;&lt;script&gt;
- [ ] Test &lt;iframe src=javascript:&gt;
- [ ] Test a cross-origin script.

And probably also:

- [ ] Test in other documents (synthetic, in an iframe)

**Comment by Wafflespeanut** [comment]
I guess #2056 closes this?

**Comment by zcorpan** [comment]
Yeah looks like it.
