### ISSUE TITLE
Need secure Web Socket support for w3c-test.org

### ISSUE THREAD

**Issue by AFBarstow** [w3c/web-platform-tests#1690]
The lack of Secure Web Socket support for w3c-test.org is a known bug that could be reported elsewhere but I wasn't able to find it. See the following thread for some additional information <https://lists.w3.org/Archives/Public/www-archive/2015Mar/0008.html>.

**Comment by AFBarstow** [comment]
@plehegar @siusin @ylafon has there been any progress on this?

**Comment by siusin** [comment]
@AFBarstow Yeah, Secure Web Socket is available now. I'll generate a test report soon.
