### ISSUE TITLE
websockets/interfaces.html has bugs

### ISSUE THREAD

**Issue by AFBarstow** [w3c/web-platform-tests#1692]
Olli Pettay reported websockets/interfaces.html has bugs:

[[
https://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0894.html

websockets/interfaces.html  the test itself has bugs (uses old idlharness.js?).
]]

/Cc @smaug @plehegar

**Comment by plehegar** [comment]
Fixed 7816f216e4fccf5633795fc5572b34d6e2b6e097
