### ISSUE TITLE
no-referrer-policy tests fail when using default ports

### ISSUE THREAD

**Issue by hillbrad** [w3c/web-platform-tests#1839]
@kristijanburnik

/referrer-policy/no-referrer-policy/no-referrer-policy.html works on non-standard ports like 8000 but fails when run from the default port because the colon remains in the expected string but is left out of the produced value.

See: 

http://w3c-test.org/referrer-policy/no-referrer-policy/no-referrer-policy.html

assert_equals: Child reported location. expected "http://w3c-test.org:/referrer-policy/no-referrer-policy/no-referrer-policy.subresource.py?id=same-origin" but got "http://w3c-test.org/referrer-policy/no-referrer-policy/no-referrer-policy.subresource.py?id=same-origin"

**Comment by kristijanburnik** [comment]
Hi,

Thanks for the heads up.

The referrer policy test case is getting extend and updated so this issue
should also be resolved.
https://github.com/w3c/web-platform-tests/pull/1814/files

I expect this update will land very soon, maybe even this week.

If it's urgent I can submit a PR today to resolve the current issue.



On Mon, May 18, 2015 at 11:52 PM, Brad Hill <notifications@github.com>
wrote:

> @kristijanburnik <https://github.com/kristijanburnik>
>
> /referrer-policy/no-referrer-policy/no-referrer-policy.html works on
> non-standard ports like 8000 but fails when run from the default port
> because the colon remains in the expected string but is left out of the
> produced value.
>
> See:
>
>
> http://w3c-test.org/referrer-policy/no-referrer-policy/no-referrer-policy.html
>
> assert_equals: Child reported location. expected "
> http://w3c-test.org:/referrer-policy/no-referrer-policy/no-referrer-policy.subresource.py?id=same-origin"
> but got "
> http://w3c-test.org/referrer-policy/no-referrer-policy/no-referrer-policy.subresource.py?id=same-origin
> "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/web-platform-tests/issues/1839>.
>



-- 

*Kristijan Burnik*

Software Engineer Intern

burnik@google.com
+385 91 4846 379

Google Germany GmbH

Dienerstraße 12

80331 München

Geschäftsführer: Graham Law, Christine Elizabeth Flores

Registergericht und -nummer: Hamburg, HRB 86891

Sitz der Gesellschaft: Hamburg

Diese E-Mail ist vertraulich. Wenn Sie nicht der richtige Adressat sind,
leiten Sie diese bitte nicht weiter, informieren Sie den Absender und
löschen Sie die E-Mail und alle Anhänge. Vielen Dank.



This e-mail is confidential. If you are not the right addressee please do
not forward it, please inform the sender, and please erase this e-mail
including any attachments. Thanks.

**Comment by hillbrad** [comment]
Thanks, Kristijan.  Not urgent.   Thanks for contributing tests!

**Comment by kristijanburnik** [comment]
Hi Brad,

the new tests are in. :-) Can you verify that the issue is fixed?

Take note that the old test is removed and the directory structure has
changed.
https://github.com/w3c/web-platform-tests/tree/master/referrer-policy

--

Also, could you fix the lint issue(I believe it's a missing newline):

W3C-TEST.ORG: subresource-integrity/refresh-header.js.headers line 1
There was 1 error (W3C-TEST.ORG: 1)

https://github.com/w3c/web-platform-tests/blame/master/subresource-integrity/refresh-header.js.headers

Every PR looks broken by lint... :-/

Thanks!

**Comment by sideshowbarker** [comment]
@hillbrad ping

> the new tests are in. :-) Can you verify that the issue is fixed?

**Comment by kristijanburnik** [comment]
@hillbrad, @sideshowbarker 

As far as I was running the tests on http://w3c-test.org/ with the default ports, all seemed fine. :-)

**Comment by mikewest** [comment]
Let's say it's done, then!
