### ISSUE TITLE
[url] Make correct tests for “resolve against URL with credentials” requirements

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#1852]
See #1841. Need to investigate what UAs do here, and then we need to either have tests for this that conform to the current spec (if the current spec is what actually makes the most sense), or we may need the spec to change. @annevk @tomalec

**Comment by tomalec** [comment]
Good catch :)
I did a brief check on what my local browsers does:
Chrome (43.0.2357)
   - `new URL("/smth", "http://foo:bar@localhost:8080/");`  - `http://foo:bar@localhost:8080/smth`
   - anchor elements with `<base>` -  `http://foo:bar@localhost:8080/smth`.

Firefox (38.0.1)  as above

IE (11.0.19)
  - URL API - not supported
  - anchor elements with `<base>` - base disregards href which contains credentails, even  `http://foo:bar@localhost:8080/some/where` does not make anchor point `/some/where/smth`

**Comment by tomalec** [comment]
I would say that adding user info into relative URLs makes sense, as then it conceptually copies everything before leading slash.

**Comment by annevk** [comment]
Thanks @tomalec, will get this sorted once I get back from vacation, around June 10.

**Comment by domenic** [comment]
See also https://github.com/whatwg/url/issues/25 /cc @Sebmaster
