### ISSUE TITLE
html/browsers/history/the-location-interface/location_hostname.html requires HTTP on Windows

### ISSUE THREAD

**Issue by tkent-google** [w3c/web-platform-tests#1862]
If we load html/browsers/history/the-location-interface/location_hostname.html as a local file on Windows, it fails.

```
      var pos = url.indexOf("//");
      if (pos != -1) {
        url = url.substr(pos+2, url.length-pos-2);
        pos = url.indexOf(":");
        if (pos != -1) {
```

This code finds ':' after the driver letter, not before a port number.

**Comment by jgraham** [comment]
Loading tests as file:// urls in general isn't a supported configuration (assuming that's what you mean).

**Comment by sideshowbarker** [comment]
> Loading tests as file:// urls in general isn't a supported configuration (assuming that's what you mean).

Closing this issue per that comment. The test suite as a whole already assumes HTTP and, as far as how the tests are run, only has the goal of ensuring that all tests run properly within the context of being delivered over HTTP by a Web server.

@tkent-google feel free to re-open this if you think this specific test should be doing something differently.
