### ISSUE TITLE
referrer-policy img-tag tests try to use non-stdlib python library

### ISSUE THREAD

**Issue by jgraham** [w3c/web-platform-tests#1874]
These tests try to use PIL which is nonstandard and so not present in most environments. They need to pregenerate the PNG files or something instead.

**Comment by kristijanburnik** [comment]
Can we close this? Since those tests are currently omitted...

**Comment by franziskuskiefer** [comment]
I'd keep this open, we run these tests (they are enabled by default). They work with changes to include the appropriate image library

**Comment by kristijanburnik** [comment]
So you've regenerated the test suite locally with img-tag tests? :-)

**Comment by franziskuskiefer** [comment]
Yes, I'm regenerating the test suite including img-tag tests (and others). Works for me with PIL. But your patch for using BMP without PIL looks better :)

**Comment by kristijanburnik** [comment]
I believe pull request #1965 resolved this issue to everyone's satisfaction. :-)
