### ISSUE TITLE
ManifestIterator#to_test is broken for reftests.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#1880]
`manifest_item` for a reftest looks like `{"path":"2dcontext/building-paths/canvas_complexshapes_arcto_001.htm","references":[["/2dcontext/building-paths/canvas_complexshapes_arcto_001-ref.htm","=="]],"url":"/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm"}`, so `manifest_item.hasOwnProperty("ref_url")` is false.

CC @jgraham

**Comment by bobholt** [comment]
This issue is over 2 years old. Is it still relevant?

**Comment by bobholt** [comment]
This appears to have been resolved by https://github.com/w3c/web-platform-tests/commit/bb5c527a6b330096b07b5a8123ff7fd93acece2b
