### ISSUE TITLE
Tests in html/syntax/parsing/template/ refer non-existing testcommon.js

### ISSUE THREAD

**Issue by tkent-google** [w3c/web-platform-tests#1881]
The following tests contains `script src='../../testcommon.js'>` but html/syntax/parsing/ doesn't have testcommon.js.

html/syntax/parsing/template/additions-to-foster-parenting/template-is-a-foster-parent-element.html
html/syntax/parsing/template/additions-to-foster-parenting/template-is-not-a-foster-parent-element.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/generating-of-implied-end-tags.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/ignore-body-token.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/ignore-frameset-token.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/ignore-head-token.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/ignore-html-token.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/start-tag-body.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/start-tag-html.html
html/syntax/parsing/template/additions-to-the-in-body-insertion-mode/template-end-tag-without-start-one.html
html/syntax/parsing/template/additions-to-the-in-frameset-insertion-mode/end-tag-frameset.html
html/syntax/parsing/template/additions-to-the-in-head-insertion-mode/generating-of-implied-end-tags.html
html/syntax/parsing/template/additions-to-the-in-head-insertion-mode/template-end-tag-without-start-one.html
html/syntax/parsing/template/additions-to-the-in-table-insertion-mode/end-tag-table.html
html/syntax/parsing/template/appending-to-a-template/template-child-nodes.html
html/syntax/parsing/template/clearing-the-stack-back-to-a-given-context/clearing-stack-back-to-a-table-body-context.html
html/syntax/parsing/template/clearing-the-stack-back-to-a-given-context/clearing-stack-back-to-a-table-context.html
html/syntax/parsing/template/clearing-the-stack-back-to-a-given-context/clearing-stack-back-to-a-table-row-context.html
html/syntax/parsing/template/creating-an-element-for-the-token/template-owner-document.html

**Comment by zqzhang** [comment]
I guess it shall be `html/semantics/scripting-1/the-template-element/testcommon.js`

BTW, there are 4 testcommon.js in this repo:

- custom-elements/testcommon.js
- html/semantics/scripting-1/the-template-element/testcommon.js
- shadow-dom/testcommon.js
- web-animations/testcommon.js

Better put them to common/ with meaningful names.

**Comment by tkent-google** [comment]
I guess the commit https://github.com/w3c/web-platform-tests/commit/c32cf1cb05554647f9f9dc5e01e35a4d88f92762 by @jgraham caused this issue.

**Comment by sideshowbarker** [comment]
@jgraham ping
