### ISSUE TITLE
referrer-policy tests require document.origin

### ISSUE THREAD

**Issue by franziskuskiefer** [w3c/web-platform-tests#1886]
To make the referrer-policy tests usable in any other browser than Chrome they should not use `document.origin` (see https://developer.mozilla.org/en-US/docs/Web/API/Document/origin for compatibility).

**Comment by sideshowbarker** [comment]
@kristijanburnik ping

**Comment by kristijanburnik** [comment]
@franziskuskiefer, @sideshowbarker 

Thanks for the heads up.

Doesn't my attempt to polyfill it work?
https://github.com/w3c/web-platform-tests/blob/master/referrer-policy/generic/common.js#L200

Did you try in some browsers which fail because of this? Which?

**Comment by franziskuskiefer** [comment]
oh, that's new. that should work. thanks for fixing. I don't think though that document.origin will be implemented (at least in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=931884#c11)

**Comment by kristijanburnik** [comment]
Not really sure if it's new. I believe it was committed even before this issue was opened.

Again, thanks! :)
