### ISSUE TITLE
Invalid timestamps in all mediasource video files leading to invalid test results.

### ISSUE THREAD

**Issue by jyavenard** [w3c/web-platform-tests#1939]
The mp4 video files used for media-source tests are incorrectly suited for the tests.

None of the video files used for the MP4 tests have a start time of 0.
Yet, all tests assume that they start at 0 and that the end time is shifted by that same offset.

Here are the first sample composition time of each MP4 used by the tests:
test-v-128k-320x240-24fps-8kfr.mp4: 0.083333
test-v-128k-320x240-30fps-10kfr.mp4: 0.066667
test-v-128k-640x480-30fps-10kfr.mp4: 0.066667
test-v-256k-320x240-30fps-10kfr.mp4: 0.066667
test-av-384k-44100Hz-1ch-320x240-30fps-10kfr.mp4: 0.066667
test-av-384k-44100Hz-1ch-640x480-30fps-10kfr.mp4: 0.066667
test-av-448k-44100Hz-1ch-640x480-30fps-10kfr.mp4: 0.066667
test-av-640k-44100Hz-1ch-640x480-30fps-10kfr.mp4: 0.066667

All audio files have a first sample with a composition time of 0.

The mediasource tests will typically call appendBuffer and check that the buffered ranges return start at 0.
However, the buffered attribute is the intersection of the audio and video track ranges. As such, if the first video sample doesn't have a composition time of 0, then the buffered attribute can't start at 0.

Chrome shifts all timestamps to make the first timestamp appear to be 0.
This is a unique behaviour and is certainly not linked to any standards.

The video files should be changed so the tests can truly verify the correctness of the mediasource implementation.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I believe those mp4 files came from @acolwell originally (from the Blink/Chrome project), so I’ll follow up with him and/or @wolenetz about it.

**Comment by wolenetz** [comment]
The spec allows for a small amount of delay from presentation start time to the beginning of the first buffered range while not stalling playback / seek to the presentation start time. If the spec is unclear or the current tests are still incorrect (given merged PRs above which might have fixed them), please re-open this issue.
