### ISSUE TITLE
referrer-policy tests fail due to CORS requests

### ISSUE THREAD

**Issue by franziskuskiefer** [w3c/web-platform-tests#1961]
Many referrer policy tests fail (timeout, see #1960) because they try to perform cross origin requests that are blocked. Not sure where to fix this, but the test server has to allow these requests for these tests to run.

**Comment by estark37** [comment]
@franziskuskiefer: are you sure it's cross-origin requests that are the problem? To me it seems to be certificate errors. In Chrome almost all the tests pass if I run with --ignore-certificate-errors.

**Comment by franziskuskiefer** [comment]
@estark37 hm, it's been a while, but if I remember correctly I was able to solve a bunch of timeouts from #1960 by allowing CORS. But looks like that's not the case (anymore?). The cert issue can also be solved as mentioned in #1483, i.e. by importing the certificate. So I think we can close this one
