### ISSUE TITLE
The webstorage/storage_XXXX_setitem_quotaexceedederr.html tests are glacially slow.

### ISSUE THREAD

**Issue by michael-nordman** [w3c/web-platform-tests#1962]
These tests take from several seconds to several minutes to run on a desktop workstation on Chrome, IE, and Mozilla. I didn't test mobile devices, but no doubt considerably longer. As written they're not suitable for automated testing, any reasonable automated harness would fail with a timeout.

The problem is they incrementally consume memory in very very small bytes, it takes hundreds of thousands of iterations to exceed the limits. Upping the byte size per iteration would save time and energy and allow these to be used in automated testing.

**Comment by zqzhang** [comment]
Feel free to improve or rewrite them, :)

**Comment by zqzhang** [comment]
Fixed by #1971
