### ISSUE TITLE
Content-Security-Policy: Blink-Contrib: Unused resources and non-existing paths

### ISSUE THREAD

**Issue by kristijanburnik** [w3c/web-platform-tests#2014]
Not a great issue, but there seem to be unused resources and some which don't make sense in the WPT context (but do in blink tests).

For example, this file references a blink specific path which would not work if the script was used:
[blink-contrib/resources/go-to-echo-report.js](https://github.com/w3c/web-platform-tests/tree/master/content-security-policy/blink-contrib/resources/go-to-echo-report.js)

```javascript
window.location = "/security/contentSecurityPolicy/resources/echo-report.php?test=" + test;
```

Looks like this is not used in the imported tests: [blink-contrib/resources/generate-csp-report.html](https://github.com/w3c/web-platform-tests/blob/master/content-security-policy/blink-contrib/resources/generate-csp-report.html)

All of these reference a blink path (in blink-contrib directory):

```
connect-src-eventsource-redirect-to-blocked.sub.html
frame-src-redirect-blocked.sub.html
connect-src-beacon-blocked.sub.html
connect-src-eventsource-redirect-to-blocked.sub.html.sub.headers
resources/go-to-echo-report.js
connect-src-xmlhttprequest-redirect-to-blocked.sub.html
report-uri-scheme-relative.sub.html.sub.headers
```

Found out by running:

```bash
cd ~/web-platform-tests/content-security-policy/blink-contrib
grep -rlH "/security/contentSecurityPolicy" .
```

I believe these should be reexamined.

--

These files look like they're unused (at least via my brief static analysis of blink-contrib/resources):

```
alert-pass.js
child-src-test.js
dump-as-text.js
frame-ancestors-test.js
mixed-content-with-csp.html
multiple-iframe-plugin-test.js
multiple-iframe-test.js
referrer-test.js
reflected-xss-and-xss-protection.js
script-src.html
securitypolicy-tests-base.js
securitypolicyviolation-test.js
shared-worker-make-xhr.js
style.xsl
transform-to-img.xsl
```

I used this script:

```bash
cd ~/web-platform-tests/content-security-policy/blink-contrib
for file in $(ls resources/); do 
  grep -rlH $file . > /dev/null || echo $file; 
done | grep -ve ".headers"
```

--

Seems like removing the resource files does not affect the tests (I only ran via the integrated test runner, though.) so I suppose they can be deleted.

@hillbrad 

CC: @mikewest

**Comment by mikewest** [comment]
Happy to review a patch that removes them. :)

**Comment by hillbrad** [comment]
Many thanks
