### ISSUE TITLE
User-Agent can now be set, update XMLHttpRequest and fetch() tests as appropriate

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#2042]
See https://github.com/whatwg/fetch/commit/dab09b0c483c46324082df1e54b29ed4c9c02162 and Fetch for details.

**Comment by hallvors** [comment]
My part of this should be done here: https://github.com/w3c/web-platform-tests/pull/2114

(Will more than one value become comma-concatenated as the setrequestheader-header-allowed test assumes?)

**Comment by annevk** [comment]
Yes, more than one value should behave the same way as any other (unknown) header.

**Comment by annevk** [comment]
Testing this in XMLHttpRequest should be good enough.

Filed:

* https://bugs.chromium.org/p/chromium/issues/detail?id=694279
* https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11010069/
* https://bugs.webkit.org/show_bug.cgi?id=168598

Changed in:

* https://github.com/whatwg/fetch/issues/37
