### ISSUE TITLE
Move animation-timing tests to HTML.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2048]
Spec is now at https://html.spec.whatwg.org/multipage/webappapis.html#animation-frames

**Comment by koustuvsinha** [comment]
you mean move it to html/webappapis ?

**Comment by Ms2ger** [comment]
Yep, create a directory `animation-frames` there.

**Comment by xfq** [comment]
It was fixed in #2091: https://github.com/w3c/web-platform-tests/tree/master/html/webappapis/animation-frames

**Comment by annevk** [comment]
Thanks @xfq!
