### ISSUE TITLE
Replace assert_object_equals in track-element/cors/support/common.js

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#2087]
Need to replace the `assert_object_equals` instance in https://github.com/w3c/web-platform-tests/blob/master/html/semantics/embedded-content/media-elements/track/track-element/cors/support/common.js

Part of https://github.com/w3c/web-platform-tests/issues/2033

**Comment by foolip** [comment]
Happy to review, but I don't have time to work on this now.

**Comment by sideshowbarker** [comment]
OK, added a change for this to https://github.com/w3c/web-platform-tests/pull/2092

**Comment by foolip** [comment]
This is closed, should there be a Critic review? Changes LGTM in any case, although I think it'll be sensitive to changes in which order attributes are added to the objects.

**Comment by sideshowbarker** [comment]
> This is closed, should there be a Critic review?

https://github.com/w3c/web-platform-tests/pull/2092 is the open PR for it, and the corresponding critic review is at https://critic.hoppipolla.co.uk/r/5735

There are two other files in that review, but if you could check of just this one, that’d be great.

>  Changes LGTM in any case, although I think it'll be sensitive to changes in which order attributes are added to the objects.

Yeah, but for the purpose of this set of tests, I think just comparing the stringifications is sufficient.
