### ISSUE TITLE
docs/css-naming.md doesn't mention unique filename requirement

### ISSUE THREAD

**Issue by cvrebert** [w3c/web-platform-tests#2095]
In https://lists.w3.org/Archives/Public/public-css-testsuite/2015Aug/0003.html , Gérard says there is a requirement that (at least for CSS tests?) testcase filenames must be unique (e.g. having both `/a/x.html` and `/b/x.html` is prohibited). If confirmed, this requirement should be added to the documentation.

**Comment by cvrebert** [comment]
Confirmed by @plinss in http://krijnhoetmer.nl/irc-logs/testing/20150817#l-158

**Comment by cvrebert** [comment]
See also https://lists.w3.org/Archives/Public/public-css-testsuite/2015Aug/0034.html

**Comment by gsnedders** [comment]
The lint should also check if it doesn't currently.

**Comment by cvrebert** [comment]
It doesn't currently, but Peter said he'd add it to the linter.
