### ISSUE TITLE
Cache should reject urls with embedded credentials

### ISSUE THREAD

**Issue by ecoal95** [w3c/web-platform-tests#2098]
In

* https://github.com/w3c/web-platform-tests/blob/master/service-workers/cache-storage/script-tests/cache-put.js#L182
* https://github.com/w3c/web-platform-tests/blob/master/service-workers/cache-storage/script-tests/cache-match.js#L282

you check that cache.put succeeds when credentials are embedded in the url.

After reading http://www.w3.org/TR/service-workers/#cache-put:
```
If request is a Request object, then:
 1. Set r to request's request.
 2. If r's url's scheme is not one of "http" and "https", or r's method is not `GET`, return a promise rejected with a TypeError.
Else if request is a string, then:
 1. Set r to the associated request of the result of invoking the initial value of Request as constructor with request as its argument. If this throws an exception, return a promise rejected with that exception.
 2. If r's url's scheme is not one of "http" and "https", return a promise rejected with a TypeError.
```

Actually creating a `Request` passing an url with credentials as first argument, given https://fetch.spec.whatwg.org/#dom-request, should throw a `TypeError` (Step 13.3):
> If parsedURL includes credentials, throw a TypeError. 

Shouldn't the expected behaviour be to actually reject the `put`?

**Comment by jdm** [comment]
Note that https://slightlyoff.github.io/ServiceWorker/spec/service_worker/ is the spec to be using, rather than w3.org/TR/service-workers.
