### ISSUE TITLE
parse-a-sizes-attribute has some wrong expectations

### ISSUE THREAD

**Issue by yoavweiss** [w3c/web-platform-tests#2142]
In https://github.com/w3c/web-platform-tests/blob/master/html/semantics/embedded-content/the-img-element/sizes/sizes-iframed.sub.html#L84 the expected result should be that `not (123)` is invalid, and `100vw` is picked as the default length.
Similarly, in https://github.com/w3c/web-platform-tests/blob/master/html/semantics/embedded-content/the-img-element/sizes/sizes-iframed.sub.html#L102 `not (.)` is invalid.

/cc @zcorpan

**Comment by zcorpan** [comment]
Fixed by https://github.com/w3c/web-platform-tests/commit/1ef8dd1713ee9a1608ec6f89842e925d1c1c75a6
