### ISSUE TITLE
html/semantics/forms/constraints/form-validation-validity-tooLong.html has errors

### ISSUE THREAD

**Issue by cvrebert** [w3c/web-platform-tests#2152]
Among the required conditions for `tooLong` to be true, [the HTML spec includes](https://html.spec.whatwg.org/multipage/forms.html#limiting-user-input-length:-the-maxlength-attribute):
> [the form control's] value was last changed by a user edit (as opposed to a change made by a script),

However, the testcase in question merely changes the `.value` via script and calls `setSelectionRange` and `execCommand` via script. There's no user interaction, so these don't qualify as "user edit"s. Thus, the testcase's assertions that `.tooLong` should be true are in error. The correct way to test this aspect of `tooLong` requires interactive tests (similar to #2150).

**Comment by zcorpan** [comment]
Agreed.

**Comment by cvrebert** [comment]
@zcorpan Opened #2180 to fix this.

**Comment by zcorpan** [comment]
Thanks!
