### ISSUE TITLE
Implent a web application for displaying test results

### ISSUE THREAD

**Issue by jgraham** [w3c/web-platform-tests#2162]
web-platform-tests provides us with hundreds of thousands of conformance tests for web browsers, and `wptrunner` provides a tool that allows running these tests in multiple major browsers. However it is currently difficult to use the output from wptrunner to understand where particular browsers are failing tests, and where different browsers are failing to interoperate.

The goal of this project is to create a web app that can parse the output from wptrunner runs (possibly from multiple browsers) so that browser developers can answer questions like "which tests for a given spec am I failing", "what are the differences between the test results between two browsers" and "which tests don't pass in any browser".

**Comment by jmaher** [comment]
this is a great project, can we outline an ideal ORM (django, custom, node.js, python, etc.)?

I would like to make it easier to understand what the wptrunner tests and what the specs are.  Ideally some document that explains what we are testing so someone could understand what to build.

Is there anything that shouldn't be done here?  Maybe the UI should match a similar UI of another tool?

As this is a web based tool, how would the data get imported in?  Is this data publicly available from different vendors via an API?  Should tests be run locally to compare browsers and generate the required data?

Thanks for answering the questions!

**Comment by gsnedders** [comment]
Disclaimer: I've not discussed the below with anyone else, and others might have different opinions.

I'd strongly recommend Python (given the rest of the tooling around wpt is Python), and using some existing web framework (and possibly push gently in the direction of Django, given possible future features, though that's certainly not any strong requirement).

Insofar as categorisation, a file contains one or more tests (whether more than one is possible depends on the "type"; we probably don't need to worry about this, though), and a file is in some directory. Tests for a given spec are all in one directory (or some subdirectory thereof), so really the filtering only needs to be by directory (e.g., show me all failures in `/html`).

UI-wise I don't really know what to suggest. There's the [CSS WG Test Harness](http://test.csswg.org/harness/results/css-flexbox-1_dev/grouped/), though there's plenty of reasons why the UI there is pretty bad, IMO. Opera's old "SPARTAN" system had a far simpler UI (though was also a UX nightmare in many places!), there's a screenshot at the end of [this blog post](https://dev.opera.com/blog/automated-testing-of-the-browser-core/).

Data import: initially we should probably have some simple upload field to upload the output, and possibly (if there's time!) implement a flag on [wptrunner](https://github.com/w3c/wptrunner) to automatically upload the results. We probably longer-term want to some some public instance with some API such that browser vendors can automatically upload results from CI systems.

**Comment by jgraham** [comment]
I have a slightly different take than @gsnedders here.

I think the first use case we want to be able to address is a developer who has run the tests themselves, possibly in multiple browsers, or multiple revisions of the same browser, and wants to be able to make a comparison between those two builds. For a concrete use case consider the problem "I'm implementing the DOM specification in Servo and I want to see which tests Servo fails that Gecko or Blink pass". So using wptrunner I can generate [structured log](http://mozbase.readthedocs.org/en/latest/mozlog.html#data-format) structured log data corresponding to those tests. I then want a webapp that:

* Allows me to load each structured log file and ingests the data
* Gives some overview of the tests that were run
* Allows me to display filtered results (e.g. by selecting statuses per input) so that I can display PASS for gecko or blink and !PASS for servo.

The significant challenge in the UI is to deal with the fact that there might be tens or hundreds of thousands of results, so simply building a big table showing everything isn't a sensible option.

In terms of implementation, I suggest we start with the backend i.e. ingesting the data. A reasonable approach here might be:

* Write a javascript component for reading structured log files (this is GFB material).
* Investigate the options for storing the ingested data (there are several possibilities here e.g. just using in-memory JSON, using IndexedDB, using some wrapper over IndexedDB that provides SQL-like querying).
* Implement the backend data storage of the structured logs
* Investigate the options for the frontend. It seems possible that some kind of framework (e.g. angular, react, whatever else is popular) will be helpful here with the standard kind of HTTP loading of data instead replaced by calls to the storage backend.
* Implement some sort of treeview that can show subsets of the test result data in a way that allows questions like those above to be answered. Or, alternately, make it possible to enter simple queries though a GUI and return a list of tests matching each (this would be less interactive so easier)

**Comment by foolip** [comment]
@jgraham, OK to close this now that https://wpt.fyi/ exists?
