### ISSUE TITLE
Merge /csp into /content-security-policy

### ISSUE THREAD

**Issue by cvrebert** [w3c/web-platform-tests#2165]
Shouldn't https://github.com/w3c/web-platform-tests/tree/master/csp be consolidated into https://github.com/w3c/web-platform-tests/tree/master/content-security-policy ?

**Comment by hillbrad** [comment]
Actually I think it should be deleted.

https://github.com/w3c/web-platform-tests/pull/2166

**Comment by cvrebert** [comment]
Okay, closing for #2166.
