### ISSUE TITLE
Remove links to testharness.css

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#2217]
`testharness.js` does this itself. We should remove links from existing tests.

**Comment by edmilsonefs** [comment]
@gsnedders you are right, I can see ﻿﻿﻿https://github.com/w3c/testharness.js/blob/master/testharness.js#L2082

So I just need to remove 319 lines from multiples files that has the following tag:
```
<link rel="stylesheet" href="/resources/testharness.css" />
```
