### ISSUE TITLE
Write tests for li@type.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2225]
Similar to https://github.com/w3c/web-platform-tests/pull/2224

**Comment by common-nighthawk** [comment]
https://github.com/w3c/web-platform-tests/pull/2380

**Comment by common-nighthawk** [comment]
@Ms2ger the tests for li@type where merged with https://github.com/w3c/web-platform-tests/pull/2380.  i think this issue can be marked as closed.
