### ISSUE TITLE
Write tests for ul@type.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2226]
Similar to https://github.com/w3c/web-platform-tests/pull/2224

**Comment by common-nighthawk** [comment]
The 'type' attribute is no longer valid on 'ul' starting with HTML5--
http://www.w3.org/TR/html-markup/ul.html
http://www.w3schools.com/tags/att_ul_type.asp

Do we still want to test, or is this now all relegated to CSS and will be tested in that suite?--
https://github.com/w3c/csswg-test

**Comment by Ms2ger** [comment]
None of those links are relevant. The HTML specification has requirements on browsers to take the `type` attribute into account: <https://html.spec.whatwg.org/multipage/#lists>.

**Comment by common-nighthawk** [comment]
Thanks for the link.  That makes sense.  I'll complete the tests for ul@type and submit a PR later today.

**Comment by common-nighthawk** [comment]
https://github.com/w3c/web-platform-tests/pull/2370
