### ISSUE TITLE
HTMLOptionsCollection.namedItem(name) returns a single item, but tests expect NodeList

### ISSUE THREAD

**Issue by keith-rollin** [w3c/web-platform-tests#2255]
common-HTMLOptionsCollection-namedItem.html implements six tests. The final three invoke HTMLOptionsCollection.namedItem(name) and treat the result as a NodeList. However, according to the spec, only a single element should ever be returned:

https://html.spec.whatwg.org/multipage/infrastructure.html#htmloptionscollection

> element = collection . namedItem(name)
> element = collection[name]
> Returns the item with ID or name name from the collection.
> If there are multiple matching items, then the first is returned.

**Comment by cdumez** [comment]
Also note that Safari behaves according to the specification and thus fails this test.

**Comment by keith-rollin** [comment]
Chrome and Firefox also follow the spec and fail the test.

**Comment by patrickkettner** [comment]
was this fixed in #2302?

**Comment by keith-rollin** [comment]
Yes, it was. I guess that means this ticket should be marked as closed. Let me click that button and see what happens.
