### ISSUE TITLE
setrequestheader-bogus-value.htm and setrequestheader-bogus-name.htm expect the wrong exception type

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#2256]
Both of these files include tests for ByteString values that contain values >255, but according to http://heycam.github.io/webidl/#es-ByteString these should check for TypeError, not SyntaxError.

**Comment by fylith** [comment]
may I work on this issue?

**Comment by jdm** [comment]
@fylith Please do! Ask questions if anything is unclear :)

**Comment by xfq** [comment]
Did #2804 and #2806 fix this issue?

**Comment by jdm** [comment]
Yep.
