### ISSUE TITLE
Add a test that `document.body.onfoo` and `window.onfoo` mirror each other.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2258]
For all event handlers listed in the tables at <https://html.spec.whatwg.org/multipage/#handler-onblur> and <https://html.spec.whatwg.org/multipage/#handler-window-onafterprint>.

In particular, test

```js
document.body.onfoo = f;
assert_equals(window.onfoo, f);
```

and similar.

**Comment by martiansideofthemoon** [comment]
@Ms2ger could I work on this issue? Where could I start?

**Comment by jdm** [comment]
Since tests are organized according to the spec they're related to and the particular section that describes the behaviour, I would add a new test to https://github.com/w3c/web-platform-tests/tree/master/html/webappapis/scripting/events .

**Comment by cvrebert** [comment]
@Ms2ger This was implemented by #2298, yeah?

**Comment by gsnedders** [comment]
We can probably increase test coverage of this, though whether we should keep this the same issue or not I don't really care. Probably not?

**Comment by Ms2ger** [comment]
Filed #2314.
