### ISSUE TITLE
Trying to run the tests on Windows never outputs the "started server" message

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#2260]
I tried the following on Windows:

```
python ./serve --config ../config.jsdom.json
```

I got only the following output:

```
INFO:web-platform-tests:Using existing host cert
```

However, the test server does seem to be up and running at the configured port.

I need to be able to detect when the server starts. My Linux collaborators are able to wait until the process outputs 

```
INFO:web-platform-tests:Starting http server on web-platform.test:9000
```

Do you have any ideas what might be going wrong here?

**Comment by jgraham** [comment]
I don't have windows to hand to check, but I will next time I do.

In any case presuming that Log messages represent a stable API seems rather dangerous; can't you just poll for the server actually being accessible on the expected port?

**Comment by domenic** [comment]
> can't you just poll for the server actually being accessible on the expected port?

That's probably a better idea, yeah. Thanks, will do.

**Comment by bobholt** [comment]
Closing, given the workaround seems to be acceptable. Please reopen if this is still an issue.
