### ISSUE TITLE
CSSOM-Views is almost entirely untested so far

### ISSUE THREAD

**Issue by rocallahan** [w3c/web-platform-tests#2304]
E.g. `getBoundingClientRect`, `getClientRects`, `inner/outerWidth/Height`, `pageX/YOffset`, `offsetLeft/Top/Parent`, `clientWidth/Height`, and everything in `GeometryUtils`.

Gecko has mochitests for these, most of which could quite easily be converted.

**Comment by jgraham** [comment]
It seems like CSS has a handful of tests here https://github.com/w3c/csswg-test/tree/master/cssom-1 but we can certainly improve that coverage.

**Comment by cvrebert** [comment]
There is a small CSSOM-View test suite: https://github.com/w3c/csswg-test/tree/master/cssom-view-1

**Comment by gsnedders** [comment]
Closing because it's really in scope of csswg-test.

**Comment by jgraham** [comment]
Reopening until there's an equivalent issue in CSS that people can find when they're looking for tests to write.
