### ISSUE TITLE
http://w3c-test.org/tools/runner/index.html does not work

### ISSUE THREAD

**Issue by miherlosev** [w3c/web-platform-tests#2447]
I open the http://w3c-test.org/tools/runner/index.html page in Google Chrome
Click 'Start' button and web application is hunging.
I open the 'Console' tab and found the script error:
`Manifest generation failed`
`Traceback (most recent call last):`
  
         	File \"/u/www.w3c-test.org/web-platform-tests/master/tools/wptserve/wptserve/handlers.py\", line 246, in __call__\n    rv = self.func(request, response)\n  
			File \"/u/www.w3c-test.org/web-platform-tests/master/tools/runner/update_manifest.py\", line 15, in main\n    manifest_file = manifest.manifest.load(root, path)\n  
			File \"/u/www.w3c-test.org/web-platform-tests/master/tools/manifest/manifest.py\", line 370, in load\n    rv = Manifest.from_json(tests_root, json.load(f))\n  
			File \"/usr/lib/python2.7/json/__init__.py\", line 278, in load\n    **kw)\n  
			File \"/usr/lib/python2.7/json/__init__.py\", line 326, in loads\n    return _default_decoder.decode(s)\n  
			File \"/usr/lib/python2.7/json/decoder.py\", line 365, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  
			File \"/usr/lib/python2.7/json/decoder.py\", line 381, in raw_decode\n    obj, end = self.scan_once(s, idx)\n
			ValueError: Unterminated string starting at: line 17370 column 16 (char 724,`

**Comment by jakearchibald** [comment]
For others that might encounter this, deleting the manifest seems to fix it.

```sh
rm MANIFEST.json
./serve
```
