### ISSUE TITLE
Various IndexedDB tests expect the wrong exception

### ISSUE THREAD

**Issue by beidson** [w3c/web-platform-tests#2455]
Various IndexedDB tests expect the wrong exception.

The following tests perform an operation on a deleted IDBObjectStore:
idbobjectstore_add16.htm
idbobjectstore_clear4.htm 
idbobjectstore_count4.htm
idbobjectstore_delete7.htm
idbobjectstore_put16.htm 

The tests try to catch a InvalidStateError exception. However, each of those tests performs the operation while the transaction is inactive.

Firefox fires a TransactionInactiveError exception, whereas Chrome, Edge, and shipping WebKit (Safari 9) match the test.

Who is right? The spec states that the TransactionInactiveError should take precedence over the InvalidStateError.

For example, the spec for IDBObjectStore::count (http://www.w3.org/TR/IndexedDB/#widl-IDBObjectStore-count-IDBRequest-any-key):
"If the transaction this IDBObjectStore belongs to is not active, the implementation must throw a DOMException of type TransactionInactiveError. If the object store has been deleted, the implementation must throw a DOMException of type InvalidStateError." 

Either the test or the spec has to change.

The spec could be updated to give the InvalidStateError precedence, but that would make the spec disagree with Chrome, Edge, and Safari.

Or, if the test means to exercise the InvalidStateError in compliance with the current spec, it should do so during an active transaction.

**Comment by inexorabletash** [comment]
Ignore TRs when there's an ED.

Precedence of exceptions was undefined in the "v1" spec (the TR - http://www.w3.org/TR/IndexedDB/) - you could infer an order but it doesn't actually say to apply the rules in the order they appear - it's not written as an imperative algorithm. Sad story. But apparently we've survived thus far.

The Editor's Draft of "v2" (https://w3c.github.io/IndexedDB/) *does* attempt to define the order, although (because of the above) implementations differ. See https://github.com/w3c/IndexedDB/issues/11 which attempts to get some sanity.

Per "v2", it should be `InvalidStateError` in these cases. So I believe the test is right - sanity check, anyone?

(On behalf of Chrome: if someone comprehensive implements tests that validate the precedence of exception cases when multiple clauses apply, I'll update the implementation to match! Fixing the implementation is easy, writing the tests is hard!)

**Comment by beidson** [comment]
> Ignore TRs when there's an ED.

What's a TR? What's an ED?

> Precedence of exceptions was undefined in the "v1" spec ... you could infer an order but it doesn't actually say to apply the rules in the order they appear

I agree the precedence is undefined. I also agree that you could infer an order, especially since it's apparently the only option.

> But apparently we've survived thus far.

Agreed - because in reality, the specific exception that's thrown in cases like these doesn't matter in practice. A web author who is attentive will fix one exception, then see a different is thrown, then fix that one. The order doesn't matter.

*YET*, the order does matter, because we have a conformance test that relies on the order.

Chrome/Edge/Safari 9 have correct behavior and pass this test.
Firefox has correct behavior, yet fails this test.

It's a bad test in two ways. You can be spec compliant yet fail, and the test doesn't actually test what it means to test.

> The Editor's Draft of "v2" ....

That's all good and well, but the v1 spec is a CR that is out in the real world, and that makes it significantly more important at this stage.

> Per "v2", it should be InvalidStateError in these cases. So I believe the test is right.

This seems... silly. The test predates the existence of V2 of the spec, and therefore was clearly meant for V1 of the spec, which is a CR, and every browser has shipped. 

> if someone comprehensive implements tests that validate the precedence of exception cases when multiple clauses apply ... writing the tests is hard!

I'm not claiming that the test *should* validate the precedence of exception cases, especially as the precedence is undefined in V1 as mentioned. Based on this discussion, I don't think any of the V1 tests should.

Which means that any V1 test that *does* rely on the precedence is flawed.

These tests claim to test one thing (performing operations on deleted object stores), but don't actually do that.

Fixing these tests to actually test what they claim to test fixes the problem where spec compliant engines can fail the test.

**Comment by inexorabletash** [comment]
Sorry, actually looking at the tests - yeah, this one is simple. The tests are just bad. PR pushed.

**Comment by beidson** [comment]
Thanks for the quick discussion and action!
