### ISSUE TITLE
MutationObserver tests fail unexpectedly(maybe?)

### ISSUE THREAD

**Issue by henrikkorsgaard** [w3c/web-platform-tests#2482]
Hi,

I’m running the mutationObserver tests up against a small implementation of MutationObservers in jsdom/javascript. I think I’ve found a bug in the tests pertaining to MutationObservers that will cause a lot of test to fail if they follow the specification and return a full [MutationRecord](https://dom.spec.whatwg.org/#mutationrecord) object.

The [first set of tests ](https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/dom/nodes/MutationObserver-attributes.html) fails, mainly because the test only specify a partial MutationRecord (expectedRecord) object to compare with. This will cause all the tests to fail, as the test itself [sets undefined fields to null (object)](https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/dom/nodes/mutationobservers.js#L21). My impression is that MutationRecords, if undefined, should contain a DOMString null, e.g. attributeNamespace.

In the [very first test case](https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/dom/nodes/MutationObserver-attributes.html#L73-L77) the [expected MutationRecord](https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/dom/nodes/MutationObserver-attributes.html#L75) should contain `oldValue:"n"` to avoid failing. Actually [this line](https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/dom/nodes/mutationobservers.js#L21) will cause all unset values in the expectedRecord to be set to null (object) causing any full mutationRecord to fail the tests. I don’t know how important it is to adhere to specification in case of DOMstring null vs null (object) and I’m not sure if I understand it right, but I get errors for returning null as DOMstring as part of the mutation record (i.e. attributeNamespace).

I wanted to get some input before making a pull request and I’m not sure if I have the time to go through all the test cases and add the expectedRecord values. 

Best,
Henrik

**Comment by domenic** [comment]
These tests almost all pass in Firefox and Chrome: http://w3c-test.org/dom/nodes/MutationObserver-attributes.html

So it seems like there must be either a spec bug or some misreading, hmm...

**Comment by domenic** [comment]
I think it might have been a misreading. Since the first test case does not pass `attributeOldValue: true`, it is expected that `oldValue` be null.

**Comment by henrikkorsgaard** [comment]
Ok, that explains the first case. 

I can't explain the second case and it might be jsdom specific, so I'm closing the issued for now.
