### ISSUE TITLE
Range-mutations erroneously expects Range to be updated on nodes without parents

### ISSUE THREAD

**Issue by rniwa** [w3c/web-platform-tests#2499]
[Range-mutations](https://github.com/w3c/web-platform-tests/blob/master/dom/ranges/Range-mutations.html) contains a bunch of test cases that expect Range boundary points to be updated when a detached text node is split.

However, this contradicts the [DOM spec concept split a `Text` node](https://dom.spec.whatwg.org/#concept-text-split) which only updates range objects when Text node's `parent` is not null.

This incorrect testing results in Gecko erroneously getting a perfect score on the test whereas Blink/WebKit are being penalized for implementing the spec'ed behavior.

**Comment by rniwa** [comment]
@Ms2ger @ayg @annevk

**Comment by annevk** [comment]
@smaug----, opinions? It does seem to me that most DOM operations work well both when a node is part of a document and when it is not part of a document. So maybe this is just a bug in the standard.

**Comment by rniwa** [comment]
Oh wait a minute, there is step 9 which says:

```
9. If parent is null, run these subsets:
    1.For each range whose start node is node and start offset is greater than offset, set its start offset to offset.
    2. For each range whose end node is node and end offset is greater than offset, set its end offset to offset.
```

So maybe the test is right but it's odd that this happens after replacing data only when the parent is null...

**Comment by smaug----** [comment]
Don't know which particular test we're talking about there, but the spec looks clear.
And I think 'if parent is null' happens after replacing data, since replacing data does its own
range offset changes.

**Comment by Ms2ger** [comment]
CC @nox @dzbarsky

**Comment by nox** [comment]
There is definitely a problem in the spec with regard to split Text nodes without a parent.

**Comment by nox** [comment]
Actually no, the case I was thinking about is covered by split's step 9.

**Comment by nox** [comment]
So actually the spec is correct, except that step 9 is redundant because replacing the data in step 8 already fixes the ranges' offsets.

**Comment by nox** [comment]
I think this can be closed, no?

**Comment by annevk** [comment]
Are you sure step 9 is a no-op? Would be good to remove it in that case, no?

**Comment by nox** [comment]
Step 9 says:

> If parent is null, run these substeps:
> * For each range whose start node is node and start offset is greater than offset, set its start offset to offset.
> * For each range whose end node is node and end offset is greater than offset, set its end offset to offset.

AFAIK the first bullet point corresponds to step 8 of replace:

> For each range whose start node is node and start offset is greater than offset but less than or equal to offset plus count, set its start offset to offset.

Second bullet point corresponds to step 9 of replace, I think:

> For each range whose end node is node and end offset is greater than offset but less than or equal to offset plus count, set its end offset to offset.

**Comment by annevk** [comment]
The conditions are a little different though. This would be easier to discover with code coverage tools. Blame is probably also rather tricky as the standard got converted at least once...

**Comment by nox** [comment]
The conditions are different, but at the end the maths give the same result AFAIK.

**Comment by annevk** [comment]
I guess I ended up introducing this in https://github.com/whatwg/dom/commit/ec0a6a02#diff-8d4d847e6257b75f4bf8030496281de4. I'll post a PR to remove it.

**Comment by annevk** [comment]
Note that it was further simplified in https://github.com/whatwg/dom/commit/ac85f2f693c0f6b29af07444acd9dde87ad6c594 but this step was not removed.

**Comment by annevk** [comment]
Closing this in favor of https://github.com/whatwg/dom/pull/419. Review appreciated.
