### ISSUE TITLE
Amend cross-origin tests to use assert_equals where possible

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#2519]
Per the comment in `html/browsers/origin/cross-origin-objects/cross-origin-objects.html`:

> Note: we eschew assert_equals in a lot of these tests, since the harness ends up throwing when it tries to format a message involving a cross-origin object.

This is no longer true, now that https://github.com/w3c/testharness.js/issues/59 has been fixed, so we should update our copy of testharness.js (by updating the resources submodule), and amend the cross-origin tests to use `assert_equals`.

**Comment by marimeireles** [comment]
Hi @gsnedders, I'd like to take this bug.
I saw that testharness.js is no longer a submodule and I assume I can just fix the test, so I'm going to give it a shot.

**Comment by gsnedders** [comment]
@marimeireles yeah, it should just be fixing the test
