### ISSUE TITLE
[XHR] Add test for non-simple request being redirected to a CORS-friendly other-origin destination

### ISSUE THREAD

**Issue by hallvors** [w3c/web-platform-tests#2520]
We should have a test that is basically just like 
/XMLHttpRequest/send-redirect-to-cors.htm
but testing non-simple request (just add a custom header)

**Comment by sideshowbarker** [comment]
https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/send-redirect-to-cors.htm#L54 is already setting a custom header, isn’t it? (At least one that will trigger a preflight…)

```javascript
          if (setExplicitType) {
            client.setRequestHeader("Content-Type", "application/x-pony")
          }
```

**Comment by annevk** [comment]
Yeah, and we also have https://w3c-test.org/cors/redirect-preflight.htm. Closing based on that.

I hope there are not too many other issues without proper labels...
