### ISSUE TITLE
XMLHttpRequest/setrequestheader-allow-whitespace-in-value.htm doesn't test anything

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2612]
From https://github.com/servo/servo/pull/9598#issuecomment-185299295

> The problem is the line
> 
> ``` python
>                 self.dict[headerseen] = line[len(headerseen)+1:].strip()
> ```
> 
> in https://hg.python.org/cpython/file/v2.7.10/Lib/rfc822.py
> 
> I pushed a test change at https://github.com/servo/servo/commit/5f3de4f26b56de44a66273734b06231e30d0e99b; @jgraham, wdyt?

**Comment by annevk** [comment]
I made the change to wptserve you suggested in https://github.com/w3c/wptserve/issues/112 but it still doesn't seem to work.

**Comment by annevk** [comment]
headers-normalize-response.htm should maybe also be updated.
