### ISSUE TITLE
XMLHttpRequest/formdata-set.html calls File ctor improperly

### ISSUE THREAD

**Issue by inexorabletash** [w3c/web-platform-tests#2616]
Test case 'testFormDataSetEmptyBlob' calls:

```js
new File(new Blob(), 'blank.txt')
```

... which throws in both FF and Chrome since Blob doesn't match the File ctor's first __sequence<>__ arg:

```webidl
[Constructor(sequence<(Blob or DOMString or ArrayBufferView or ArrayBuffer)> fileBits, ...)]
```

It should probably be `new File([new Blob()], 'blank.txt')`.

But even with that the test fails (in FF and Cr) on `assert_object_equals: unexpected property "name"`; since `assert_object_equals` is busted (and we want to get rid of it anyway), so the test needs more TLC...

cc: @bzbarsky

**Comment by bzbarsky** [comment]
Yeah, assert_object_equals really doesn't make sense here.  Would it make more sense to iterate both formdatas and assert_array_equals on the things coming out of the iterators?

**Comment by inexorabletash** [comment]
So far as I can tell that case isn't comparing FormDatas. It looks like is is comparing `new File([], 'blank.txt')` with a File minted by doing:

```js
var fd = new FormData();
fd.set('key', new Blob(), 'blank.txt');
var file = fd.get('key');
```

So... I think this would capture the intent?

```js
test(function() {
  var fd = new FormData();
  fd.set('key', new Blob(), 'blank.txt');
  var file = fd.get('key');

  assert_true(file instanceof File);
  assert_equals(file.name, 'blank.txt');
}, 'testFormDataSetEmptyBlob');
```

The other properties (`type`, `lastModified`, `size`, ...) don't seem relevant to the test.

**Comment by jdm** [comment]
cc @KiChjang who wrote the test.

**Comment by KiChjang** [comment]
@inexorabletash Since we can't use assert_object_equals here, I think that's a good workaround. The intent is to check that the value returned is indeed a File object, and has its name set as 'blank.txt', as you've correctly tested.

**Comment by inexorabletash** [comment]
Cool. I'll get a PR up tomorrow, but don't wait for me if someone wants to fix it more quickly.

**Comment by inexorabletash** [comment]
Critic review up at https://critic.hoppipolla.co.uk/r/6216 if anyone feels like doing the honors.
