### ISSUE TITLE
How to test dom/nodes svg files?

### ISSUE THREAD

**Issue by youennf** [w3c/web-platform-tests#2631]
dom/nodes contain several test files that have a html flavor and a svg flavor.
See for instance https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Element-childElementCount-svg.svg and https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Element-childElementCount-xhtml.xhtml

HTML-flavored tests are regular testharness tests.
SVG-flavored  tests include testharness.js/testharnessreport.js but do not seem to create any actual JS test.

How are we supposed to handle these tests?

**Comment by gsnedders** [comment]
They've always worked as normal `testharness.js` tests (there's a JSON log dumped to the DOM, and testharnessreport.js's callbacks get called like normal), they just didn't produce any HTML table, but I changed/fixed that in #8137 while sitting in SVG WG F2F at TPAC. So, uh, this is fixed now. (Well, sort of; it's somewhat limited by `viewBox` size!)
