### ISSUE TITLE
Could not find a way to automatically run tests with prefixes on

### ISSUE THREAD

**Issue by agouaillard** [w3c/web-platform-tests#2638]
trying to run the /mediacapture-streams test in multiple browsers.
since getUserMedia is still prefixed in all browsers, all the test run automatically from the test runner fail, but most succeed when run with prefixes allowed.

How could I use the runner to run those tests with prefixes?
Or would there be another way to run those tests automatically, taking prefixes into account?

**Comment by Ms2ger** [comment]
I have no interest in making any changes on this side that would encourage vendor prefixing. I'd suggest you try to convince browser vendors to implement an unprefixed version, before we're stuck having to implement the prefixed version forever.

**Comment by agouaillard** [comment]
I agree with you, non prefix tests should be the default and the ultimate goal. However, I would also love to have a solution to test with or without prefixes (like a global checkbox) without having to run every single test manually twice (once to make the page appear and to click on the link, a second time to run with prefixes).
