### ISSUE TITLE
Need tests for Fullscreen

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#2656]
See https://fullscreen.spec.whatwg.org/. Presumably in a "fullscreen" directory.

**Comment by foolip** [comment]
I started wring some using testharness.js for Blink with the intention of upstreaming. The trouble is that a user gesture is required, and that requires a private API. I worked around it inserting a button to click manually in the absence of such an API, but to upstream in that state would require marking them a manual tests. That would make them basically useless, and they wouldn't be run in Blink's w-p-t import.

I don't know what to do about this. Last I looked the answer was something involving WebDriver, but at the time I couldn't get any test working.

**Comment by foolip** [comment]
These are the tests:
https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/LayoutTests/fullscreen/api/
https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/LayoutTests/fullscreen/model/
https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/LayoutTests/fullscreen/resources/

**Comment by annevk** [comment]
Not sure, @jgraham?

**Comment by foolip** [comment]
I'll just take this as an umbrella bug for upstreaming Blink tests, the first PR for which was https://github.com/w3c/web-platform-tests/pull/3692

@annevk, do you want to be in fullscreen/OWNERS so you see any test changes?

**Comment by annevk** [comment]
Not really, but folks should feel free to ping me on IRC.

**Comment by foolip** [comment]
There are some tests in https://github.com/w3c/web-platform-tests/tree/master/fullscreen now and I think an umbrella issue isn't going to be useful any longer, so closing this. Issues for specific parts lacking coverage might be useful, but realistically what needs to happen is a concerted effort to convert and upstream engine-specific tests, which would be better tracked in those bug trackers.
