### ISSUE TITLE
Bug in test for cross-origin access to window[@@iterator]

### ISSUE THREAD

**Issue by caitp** [w3c/web-platform-tests#2664]
Commit 29017da60c1e31ef00d80e7db012509942fa4a4f adds a test which is apparently meant to verify that `@@iterator` can't be accessed on a window from a different browsing context (I think this is based on  the changes from https://github.com/whatwg/html/pull/638 ?)

However, the test is actually only checking that the same-origin / same-context `window` does not have `@@iterator` at all.

I believe this is incorrect, but I'd appreciate if someone could point me to where this had changed, if it has indeed changed.

**Comment by caitp** [comment]
bz says this was just removed from window in a recent spec change, so I guess it's a valid test --- the name is very confusing though, isn't this covered by the Window IDL tests?

**Comment by Ms2ger** [comment]
I don't see an issue here.
