### ISSUE TITLE
Test Node#isSameNode()

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2671]
Added back in https://github.com/whatwg/dom/commit/97f0a958bc1dcb98265d116bafdc80ae1b059823.

**Comment by qyearsley** [comment]
It looks like this is fixed by f8d1ffa80e263334d9471281ba69734cdf8bdaa5, is that correct?

@Ms2ger @amarant

**Comment by jdm** [comment]
Yep!
