### ISSUE TITLE
Update TextEncoder tests for utf-16 spec changes

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2706]
Once https://github.com/whatwg/encoding/pull/36 is merged. See also https://github.com/whatwg/encoding/issues/18. Tests are under `encoding/`.

**Comment by xfq** [comment]
https://hg.mozilla.org/integration/mozilla-inbound/rev/fbb40278805ff5a8aac8b1a1dbd8b0a180f82296

@Ms2ger Did this commit fix this issue?

**Comment by annevk** [comment]
Yeah, `encoding/textencoder-constructor-non-utf.html` tests this. Thanks @xfq!
