### ISSUE TITLE
Integrate test262 somehow

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2708]

**Comment by gsnedders** [comment]
This is pretty low priority, given in practice almost everyone who actually cares about it runs it through the JS shells rather than the whole browser.

**Comment by bobholt** [comment]
I bet @jugglinmike has thoughts on this.

**Comment by jugglinmike** [comment]
There is plenty of room for bugs when it comes to browser integration; passing in a JS shell does not guarantee passing in an embedding browser. So there's definitely value in running Test262 in a browser.

That said, automating that test suite is a non-trivial task that [may require the use of internal APIs](https://github.com/tc39/test262/blob/master/INTERPRETING.md#host-defined-functions). I think it's out-of-scope for WPT to offer a solution here, and I suspect that most vendors would prefer to manage that separately, anyway.

For those looking to do so, the [Test262 project's readme file](https://github.com/tc39/test262/blob/master/README.md) offers some suggestions for test runners available today.
