### ISSUE TITLE
Some html files in UTF-8 are not labelled with meta charset

### ISSUE THREAD

**Issue by jungshik** [w3c/web-platform-tests#2747]
Some html files in UTF-8 with non-ASCII characters are not labelled with 'meta charset="utf-8"'. 

For instance, 
https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/idbcursor-direction-index-keyrange.htm

has the following, but is not labelled. (the test is not affected because "Åke" is not used in the test ). 

``` html
<link rel="author" href="mailto:odinho@opera.com" title="Odin Hørthe Omdal">

<script>
    var records = [ 1337, "Alice", "Bob", "Bob", "Greg", "Åke", ["Anne"] ];
....
</script>
```

Others are:

IndexedDB/idbcursor-direction-objectstore-keyrange.htm  :  the same as above 
WebIDL/ecmascript-binding/es-exceptions/exceptions.html : it has non-ASCII quotation marks ("smart quotes")  in the comment. Either we can add charset label or replace 'smart quotes' with 'ASCII quotes'. 

@inexorabletash, @Velmont @ayg

**Comment by inexorabletash** [comment]
I'm fine with updating the IndexedDB tests. The test restricts itself to "AA" ... "ZZ" which skips "Åke" if it's parsed as UTF-8 or windows-1252. But the test would work fine w/o that entry either (it has another sentinel and doesn't need one anyway). So I'd prefer to remove those entries to keep the test focused - if we want a collation order test it should be separate.

**Comment by Ms2ger** [comment]
PR welcome, btw.
