### ISSUE TITLE
TEST webgl# WPT crash

### ISSUE THREAD

**Issue by renchenglei** [w3c/web-platform-tests#2773]
WebGL tests crash caused by same name function in JS. For instance, [drawingbuffer-hd-dpi-test.html](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/conformance/canvas/drawingbuffer-hd-dpi-test.html) has a function named 'test', but [js-test-pre.js](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/resources/js-test-pre.js) also has the function 'test'.
Maybe there are two solutions：
      1.Modify [js-test-pre.js](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/resources/js-test-pre.js) and [testharness.js](https://github.com/w3c/testharness.js/blob/72dd67688097e7d310c64d3e524807d8bc34070c/testharness.js) . 
       Add a new name function in testharness.js(for example 'WebGLTest') and js-test-pre.js calls the new function 'WebGLTest'.
      2.Modify WebGL test files and change 'test' to other names, but there many files need to modify.
I suggest the first one, I add a new function in testharness.js as follows:
**function WebGLTest(func, name, properties)
    {
        test_name = name ? name : test_environment.next_default_test_name();
        properties = properties ? properties : {};
        var test_obj = new Test(test_name, properties);
        test_obj.step(func, test_obj, test_obj);
        if (test_obj.phase === test_obj.phases.STARTED) {
            test_obj.done();
        }
    }
expose(WebGLTest, 'WebGLTest');**
modify js-test-pre.js as follows:
**var WPT_TEST_ID = 0;
function reportTestResultsToHarness(success, msg) {
  if (window.parent.webglTestHarness) {
    window.parent.webglTestHarness.reportResults(window.location.pathname, success, msg);
 // } else if (window.test) { // WPT test harness
    } else if (window.WebGLTest) { // change test to WebGLTest
  //  test(function () {
     WebGLTest(function () {// change test to WebGLTest
      assert_true(success, msg);
    }, "WebGL test #" + (WPT_TEST_ID++) + ": " + msg);
  }
}**
After modification, the WebGL tests can run successfully.

**Comment by renchenglei** [comment]
@zqzhang @emilio @jdm 
Thanks a lot.

**Comment by emilio** [comment]
I'm looking into it, the changes you propose look good so far :)

**Comment by zqzhang** [comment]
Shall have been fixed by #2802.
