### ISSUE TITLE
TEST webgl# lost two files

### ISSUE THREAD

**Issue by renchenglei** [w3c/web-platform-tests#2800]
[context-release-upon-reload.html](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/conformance/context/context-release-upon-reload.html) and  [context-release-with-workers.html](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/conformance/context/context-release-with-workers.html) can't run, because [/webgl/conformance-1.0.3/conformance/context/resources/](https://github.com/w3c/web-platform-tests/tree/master/webgl/conformance-1.0.3/conformance/context/resources) lost [context-release-upon-reload-child.html](https://github.com/KhronosGroup/WebGL/blob/master/conformance-suites/1.0.3/conformance/context/resources/context-release-upon-reload-child.html) and [context-release-child-with-worker.html](https://github.com/KhronosGroup/WebGL/blob/master/conformance-suites/1.0.3/conformance/context/resources/context-release-child-with-worker.html).
Details:
       [context-release-upon-reload.html](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/conformance/context/context-release-upon-reload.html) has one line code:
`host.src = "resources/context-release-upon-reload-child.html";`
[context-release-with-workers.html](https://github.com/w3c/web-platform-tests/blob/master/webgl/conformance-1.0.3/conformance/context/context-release-with-workers.html)  has one line code:
`host.src = "resources/context-release-child-with-worker.html";`

@zqzhang @emilio @jdm 
Thanks a lot.

**Comment by emilio** [comment]
So, we don't include the resources directory, that should be easy to fix! Looking into it too

**Comment by emilio** [comment]
(I mean, html files in the resources directory)
