### ISSUE TITLE
fetch/api/cors/cors-redirect-credentials-worker.html should be piping its worker through "sub"

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-platform-tests#2801]
Otherwise it's trying to `new URL("http://{{host}}:{{ports[http][0]}}/fetch/api/cors/../resources/redirect.py....", stuff)` which of course fails.

Oh, and having those new URL calls throw apparently does NOT make the test fail? That seems pretty broken.  @jgraham, @jdm

**Comment by bzbarsky** [comment]
Looks like this test expects all its `fetch()` calls to throw a `TypeError`, and of course that's what happens if you try to construct a `URL` from a bogus string.  There should be one sanity test in here which is expected to succeed, to catch issues like this.  :(

**Comment by bzbarsky** [comment]
@youennf Did your recent changes to all this stuff fix this test to actually be testing something useful?

**Comment by youennf** [comment]
I did some changes to these tests a few weeks ago so that they work in more constrained test envs. I think they should be fine now, although there is no sanity check. That would be a nice addition

**Comment by annevk** [comment]
I looked into this. If we wanted a proper simple test that doesn't fail, it'd require some refactoring. Should I go ahead and do that or do we think it's fine now?

**Comment by youennf** [comment]
I am all for a simple passing test if that is not too much work

**Comment by annevk** [comment]
This should be fixed now per my PR that just landed.
