### ISSUE TITLE
Test colSpan behavior around zeroes

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#2821]
See https://github.com/whatwg/html/issues/757. Test at https://jsbin.com/codoxe/1/edit?html,console. Per that thread Firefox and Safari nightly will get it right; Chrome and Edge will get it wrong.

**Comment by ayg** [comment]
This isn't already tested by html/dom/reflection-tabular.html?

**Comment by domenic** [comment]
It looks like it is, thanks.
