### ISSUE TITLE
_invokeSubresource in Referrer Policy tests uses content attribute instead of IDL attribute

### ISSUE THREAD

**Issue by franziskuskiefer** [w3c/web-platform-tests#2822]
The change to _invokeSubresource in https://github.com/w3c/web-platform-tests/commit/a0475c8cd9cb3d8ac66ed5a9aaa4cbbbd831e63d uses the content attribute `referrerpolicy`. This should be the IDL attribute `referrerPolicy`. (It is used as IDL attribute in queryNavigable, appendIframeToBody, and loadImage in common.js)

@estark37

**Comment by tungmangtdh3** [comment]
https://github.com/w3c/web-platform-tests/blob/master/referrer-policy/generic/common.js line 28
I think content attribute should not be accessed like that.
I think the proper way to access an attribute in this case should be : 
- IDL attr element[idlAttr] =...
or content Attr element.setAttribute(contentAttr, value).
So, imho, the above commit makes sense. 
@annevk

**Comment by annevk** [comment]
Yeah, you should probably make it clear in common.js that you're using IDL attributes then. E.g., one comment says "referrer_policy" but that's obviously wrong.

**Comment by annevk** [comment]
(And don't worry about tagging me. Happy to help.)

**Comment by jdm** [comment]
This has since been updated to use `referrerPolicy` correctly.
