### ISSUE TITLE
Should 'same URL in source and img' tests in viewport-change.html expect a load event when viewport changed?

### ISSUE THREAD

**Issue by EdgarChen** [w3c/web-platform-tests#2878]
See https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element:update-the-image-data and the discussion in https://www.w3.org/Bugs/Public/show_bug.cgi?id=24712. Looks like we expect a load event if selected source is the same as the last selected source. So the test should expect a load event, @zcorpan am I reading anything wrong here? Thank you.

**Comment by zcorpan** [comment]
When the viewport is changed, you should not run the "update the image data" algorithm. That algorithm is only run on "relevant mutations" (like setting the `srcset` attribute).

When the viewport is changed, the spec runs a separate algorithm:
https://html.spec.whatwg.org/multipage/embedded-content.html#img-environment-changes

which says
> ⌛ If selected source and selected pixel density are the same as the element's last selected source and current pixel density, then abort these steps.

Though the spec still requires a load event if the selected source is the same but the selected pixel density is different (but at least some browsers don't); that is issue https://github.com/whatwg/html/issues/835

**Comment by EdgarChen** [comment]
Thanks for the explanation.
