### ISSUE TITLE
(More) Various IndexedDB tests expect the wrong exception

### ISSUE THREAD

**Issue by beidson** [w3c/web-platform-tests#2888]
(More) Various IndexedDB tests expect the wrong exception

This is basically the exact same thing as https://github.com/w3c/web-platform-tests/issues/2455 except I noticed it in 4 more tests.

In the following tests:
idbindex_get8.htm  
idbindex_getKey8.htm  
idbindex_openCursor3.htm
idbindex_openKeyCursor4.htm

The test expects an InvalidStateError because the IDBIndex is deleted.

But the spec for each of those 4 methods calls out as the very first step:
"If the transaction this IDBIndex belongs to is not active, the implementation must throw a DOMException of type TransactionInactiveError."

WebKit and Chrome both do the TransactionInactiveError, while Firefox happens to pass the test.
I haven't tried Edge/IE

Per the discussion in issue 2455, I'm aware that IDB v1 did not formally specify a precedence for the exceptions. And I'm also aware that IDB v2 does spec a precedence.

But, per the conclusion in 2455, it seems that these tests are currently bogus, as V1 is at CR while V2 is still under development.

I think these tests should be changed to allow either TransactionInactiveError or InvalidStateError, as a V1-comformant implementation could throw either.

**Comment by inexorabletash** [comment]
See also https://github.com/w3c/IndexedDB/issues/11 as well. (also linked from #2455) We can probably get Chrome and Firefox and the spec aligned.

I don't have a strong preference on the test themselves.

**Comment by brettz9** [comment]
As it has been a while and this looks like the only remaining IndexedDB test problem, could priority for fixing this be bumped up?

**Comment by inexorabletash** [comment]
PRs welcome! :)

**Comment by brettz9** [comment]
If it is indeed the case that as per https://github.com/w3c/web-platform-tests/issues/5313#issuecomment-290970635 "if the test doesn't match the latest, which is https://w3c.github.io/IndexedDB/, it should be updated." then I think this issue can be closed.

**Comment by inexorabletash** [comment]
Yeah, the TR is old. We could insert a whole discussion here about how the web is not versioned and specs being versioned is simply process overhead, but I'm on vacation at the moment. :)

Closing unless the ED disagrees with implementations.
