### ISSUE TITLE
XMLHTTPRequest: update tests that disallow withCredentials for sync XHR

### ISSUE THREAD

**Issue by hallvors** [w3c/web-platform-tests#2894]
To follow up https://github.com/whatwg/xhr/issues/66 we need to fix or remove some tests, I believe.
https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/XMLHttpRequest-withCredentials.js#L23

**Comment by Ms2ger** [comment]
Fixed in https://github.com/servo/servo/pull/10850, will get fixed here on the next sync.

**Comment by bzbarsky** [comment]
There's more, like cors/credentials-flag.htm, that don't seem to be fixed in the servo change...

**Comment by bzbarsky** [comment]
I guess I'll fix this in gecko including all the tests and then someone can have the merging fun.  ;)
