### ISSUE TITLE
Dropzone Tests

### ISSUE THREAD

**Issue by stevendwood** [w3c/web-platform-tests#3020]
**Dropzone should not affect the dropEffect seen by dragenter and dragover**

This test asserts the following: 

The user is dragging an element with effectAllowed "all", when they drag it over the dropzone, which wants to make a link, the dataTransfer.dropEffect should not be touched.  Is this right ? An element which accepts a drop can only influence the cursor the browser displays on dragover by setting the dropEffect when the user drags over it.   Furthermore, if the effectAllowed is "move" and the dropzone operation is "link" then the dropzone should not cancel the dragover event since it cannot accept a drop (not supporting any of the allowed effects).   In other words, if the effectAllowed was "copy" then the dropzone with operation "link" should not accept the drop, one way to do this is to set the dropEffect on dragover and the browser should pick up that operation which will take place on drop (dropEffect) is not one of the allowed effects.

Perhaps I did not understand the spec here - but I took it to mean that a dropzone would indicate what effect would take place on the actual drop, by setting the dropEffect on dragover.  Using the [dropzone] attribute lets you specify this in markup.  Implementing dragover/enter and messing with the dropEffect when you have a [dropzone] attribute seems wrong, the dropEffect is something that gets set by the drop target on drag over to give the user feedback about what will happen when a drop takes place, if the dropEffect advertised by the element is not one of the effectAlloweds then the drop should not be allowed.  You set the dropEffect to indicate this. 

Also i believe that the dropEffect is reported back to the source on drop, rather than being read in the drop target, perhaps that is why it is not available ondrop ? [https://html.spec.whatwg.org/multipage/interaction.html#event-drag](https://html.spec.whatwg.org/multipage/interaction.html#event-drag)

**Comment by annevk** [comment]
This is obsolete as we dropped the dropzone attribute in https://github.com/whatwg/html/commit/3044a7e8517a4488cea811789d19974a8d5a56ae. Sorry for wasting your time :/

**Comment by stevendwood** [comment]
No worries thanks for letting me know.
