### ISSUE TITLE
Should the 'calc(1px' be a valid component value in <img>'s sizes attribute?

### ISSUE THREAD

**Issue by EdgarChen** [w3c/web-platform-tests#3066]
Parsing sizes attribute runs
- https://html.spec.whatwg.org/multipage/embedded-content.html#parse-a-sizes-attribute

calc() defines in https://drafts.csswg.org/css-values/#calc-syntax
But parsing a component value runs
- https://www.w3.org/TR/css-syntax-3/#parse-a-component-value
- https://www.w3.org/TR/css-syntax-3/#consume-a-component-value0
- https://www.w3.org/TR/css-syntax-3/#consume-a-function0

A function ending with EOF-token is valid.
So `sizes='calc(1px'` in parse-a-sizes-attribute.html [[1]](https://github.com/w3c/web-platform-tests/blob/5df9b57edb3307a87d5187804b29c8ddd2aa14e1/html/semantics/embedded-content/the-img-element/sizes/sizes-iframed.sub.html#L177)[[2]](https://github.com/w3c/web-platform-tests/blob/5df9b57edb3307a87d5187804b29c8ddd2aa14e1/html/semantics/embedded-content/the-img-element/sizes/sizes-iframed.sub.html#L178) seems a valid value. 

@yoavweiss @zcorpan am I reading anything wrong here? Thank you.

**Comment by zcorpan** [comment]
Yes I think you are right. Can you do a PR to revert https://github.com/w3c/web-platform-tests/pull/1274 ?

**Comment by EdgarChen** [comment]
Sure, I will provide a PR for this. Thank you.
