### ISSUE TITLE
service worker problems

### ISSUE THREAD

**Issue by publicocean0** [w3c/web-platform-tests#3075]
Hi, i m trying to create a websocket proxy with a service worker. Pratically it keeps up the connection even if normally when you change page or you close the page the connection was destroyed. 

It works the browser is using now a single connection but:
1) i have no event "stopping" in service worker for understand when to close the connection
2) if the service worker is stopped  and i trying to send a event from another client (different browser )  the service worker doesnt wake up. 

I thing it could be added to w3c specifications.

**Comment by annevk** [comment]
https://github.com/w3c/ServiceWorker/ is the service worker repository. This is the repository for tests.
