### ISSUE TITLE
Event-dispatch-multiple-stopPropagation.html seems incorrect

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#3084]
(Originally https://github.com/tmpvar/jsdom/issues/1501)

The test in question is http://w3c-test.org/dom/events/Event-dispatch-multiple-stopPropagation.html which passes in Firefox and Edge but fails in Chrome and jsdom. jsdom in particular is doing its best to follow the spec algorithms exactly, although we've been known to make mistakes. The failure is line 43,

```js
    assert_array_equals(actual_result, [parent]);
```

As @Sebmaster says there,

> The stop propagation flag is never cleared in the spec except as a default and in [initialize event](https://dom.spec.whatwg.org/#concept-event-initialize). That, in turn, is only called in initEvent. Seems like we're working according to spec here?

It seems like we have either a spec or test bug here. /cc @annevk.

**Comment by annevk** [comment]
That is https://github.com/whatwg/dom/issues/219 I think.

**Comment by domenic** [comment]
Fixed by https://github.com/w3c/web-platform-tests/pull/3469.
