### ISSUE TITLE
The battery-status/battery-promise.html test is incorrect

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-platform-tests#3107]
The "setting iframe's src makes its Navigator object vary thus getting another battery promise" creates an iframe with no src attribute, waits for onload, then sets src.  It then asserts that this should create a new Navigator and battery promise.

But per spec inserting the iframe will land in https://html.spec.whatwg.org/multipage/browsers.html#creating-a-new-browsing-context and create an about:blank document in the iframe, then go to https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes and thence to https://html.spec.whatwg.org/multipage/embedded-content.html#iframe-load-event-steps to fire the load event.

Now setting the src will navigate, but the navigation is same-origin and therefore the existing Window gets reused.  Hence there is no new Navigator in this case.

**Comment by bzbarsky** [comment]
Specifically, setting src will land in https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes which will go to https://html.spec.whatwg.org/multipage/embedded-content.html#otherwise-steps-for-iframe-or-frame-elements which will perform the navigation.  And note this (easily missed) text after the algorithm steps:

> Similarly, if the child browsing context's session history contained only one Document when the process the iframe attributes algorithm was invoked, and that was the about:blank Document created when the child browsing context was created, then any navigation required of the user agent in that algorithm must be completed with replacement enabled.

So in this case the navigation is performed with replacement enabled.  We go to https://html.spec.whatwg.org/multipage/browsers.html#navigate and eventually land in https://html.spec.whatwg.org/multipage/browsers.html#initialise-the-document-object which says:

> If browsingContext's only entry in its session history is the about:blank Document that was added when browsingContext was created, and navigation is occurring with replacement enabled, and that Document has the same origin as the new Document, then
>
> Let window be the Window object of that Document.

and that is precisely the situation we're in.  So the new document uses the same Window as the old document, and hence also the same Navigator object.

**Comment by zqzhang** [comment]
@bzbarsky good catch. Thanks for this great finding.

I am a little confused here.

> Now setting the src will navigate, but the navigation is same-origin and therefore the existing Window gets reused. Hence there is no new Navigator in this case.

I find even with the iframe src attribute set was created initially, but if setting the src in same-origin, we still get the same situation. See

https://github.com/w3c/web-platform-tests/compare/master...zqzhang:battery-promise?expand=1

Both Chrome and Firefox Nightly get failed for the test 'setting src of an iframe with initial frame makes its Navigator object vary thus getting another battery promise'.

What's wrong here?

**Comment by bzbarsky** [comment]
What's wrong is that you're not waiting for support-iframe.html to actually load before you grab the originalNavigator/originalPromise values and start the load of support-iframe-next.html.
