### ISSUE TITLE
What's the correct way of running ServiceWorkers tests?

### ISSUE THREAD

**Issue by amiq11** [w3c/web-platform-tests#3120]
Hi,
I'm working on the service workers team on chromium and trying to run wpt tests related to the service workers. ([[this issue](http://crbug.com/602693)] is tracking service workers' tests on wpt tests.)

Then, I tried the tests following the [README.md](https://github.com/w3c/web-platform-tests/blob/master/README.md), but there seems to be many bugs coming from the origin problem. Test looks running on 'http://web-platform.test:8000', so registration will fail because of the same-origin policy. 

I'm very new to web-platform-tests, so could you tell me how to run the service workers' tests correctly?
Or, if this is a real bug, I'd like to help you work on that.

**Comment by jdm** [comment]
All of the tests containing .https in the filename should be run automatically under the configured HTTPS origin, as far as I know (which is https://web-platform.test:8443 by default).

**Comment by amiq11** [comment]
Do I have to start with https://web-platform.test:8443/tools/runner/index.html instead of http://...:8000/tools/runner/index.html ? or Should it be fine with HTTP one?

**Comment by jdm** [comment]
I'm not sure; the test harnesses for the browsers I use (Firefox & Servo) hide all that from me.

**Comment by jdm** [comment]
Firefox appears to use http:// to load the wptrunner harness.

**Comment by amiq11** [comment]
Thanks, I don't know about the wptrunner!
But I cannot work with it so created [another issue](https://github.com/w3c/wptrunner/issues/190) on the wptrunner repo... 
Anyway, thanks for your cooperation:)
