### ISSUE TITLE
Have smarter checks for content type equality

### ISSUE THREAD

**Issue by Manishearth** [w3c/web-platform-tests#3121]
According to https://tools.ietf.org/html/rfc7231#section-3.1.1.1, the following content types are equivalent:

```
     text/html;charset=utf-8
     text/html;charset=UTF-8
     Text/HTML;Charset="utf-8"
     text/html; charset="utf-8"
```

We should convert it to lowercase and trim any whitespace after semicolons/commas before testing for equality in tests like /XMLHttpRequest/send-content-type-charset.htm.

I think it's unreasonable to expect user-agents to twiddle with the content type (as in that test, where only certain charsets are changed) and preserve the whitespace/capitalization.

cc @Ms2ger

**Comment by annevk** [comment]
Is that web-compatible? I believe sites have depended on casing of these things. I agree that ideally everything is canonicalized, but can that be observed in any existing implementation?

**Comment by Manishearth** [comment]
Firefox seems to twiddle with the content type directly. Chrome, not so much, it fails half of the tests in send-content-type-charset.htm because it tries to twiddle but doesn't do it correctly (in one case, it doesn't get rid of a space after `charset=`, in another, it erroneously capitalizes an existing utf8. In a third it runs replacement when it shouldn't be doing so.

Both seem to handle spaces after semicolons fine -- these spaces are preserved in the rewritten header. Chrome messes up the casing, so I guess at least for `XHR.send()`'s content type twiddling, we should be okay with case-canonicalizing. I'd prefer if we didn't nitpick over spaces after semicolons either.

**Comment by annevk** [comment]
I think what I'm saying is that eventually content will depend on some or all of these characteristics. I guess for now we can ease the requirements here, but it would be nice if we also figured out what kind of output would be desirable here and try to align on that.

**Comment by jdm** [comment]
This is https://github.com/w3c/web-platform-tests/pull/2667#issuecomment-196728740 and https://github.com/w3c/web-platform-tests/pull/2807 again, right?

**Comment by Manishearth** [comment]
Looks like it.
