### ISSUE TITLE
XHR/send-redirect-to-cors.htm shouldn't have a pony content type

### ISSUE THREAD

**Issue by Manishearth** [w3c/web-platform-tests#3123]
https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/send-redirect-to-cors.htm

https://fetch.spec.whatwg.org/#cors-preflight-fetch-0, step 7.8:

> If one of request's header list' names is not in headerNames, its corresponding header is not a CORS-safelisted request-header, and headerNames does not contain `*`, then return a network error. 

a content-type header of `application/x-pony` isn't a safelisted header, and for this test, the allowed headerNames are x-test and x-foo.

This test [sets that header](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/send-redirect-to-cors.htm#L26), and expects it to exist in the final response. According to this step, if such a header is there it should cause a network error (so there shouldn't be any headers in the response).

The test shouldn't include a non-allowed content-type header.

**Comment by annevk** [comment]
I fixed this in https://github.com/w3c/web-platform-tests/commit/98d584081c252f4e0b4b2439406ea26a8db3c10a.
