### ISSUE TITLE
Need tests for compat mouse events for multiple pointers

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/web-platform-tests#3156]
A recent [fix](https://github.com/w3c/pointerevents/pull/56) in the PointerEvent spec calls for new tests with compatibility mouse events. The spec now clarifies that with multiple active pointers, the compat mouse boundary events behave as if there's a single compat mouse that "follow" each active pointer.

**Comment by RByers** [comment]
@mustaqahmed owns this, but assigning to myself due to GitHub limitation.
