### ISSUE TITLE
web-platform-tests import method question

### ISSUE THREAD

**Issue by Dcampb007** [w3c/web-platform-tests#3163]
Hello, I was wondering how does w3c determine which files in the web-platform-tests repo are actual test files and which aren't. I am working on a project where we are importing some directories from the web-platform-tests repo and I am trying to prevent the test importer from importing files that are not tests to the test runner (which causes an error). Any help is very much appreciated.!!

PS. If there is a designated area for asking questions about the repo, please direct me.!

**Comment by jdm** [comment]
The tests that get run are the ones specified in MANIFEST.json. The tools that automatically generate a MANIFEST.json do so by treating any file that imports `/resources/testharness.js` or contains a `<link rel="matches" href="something.html">` as a test.

**Comment by Dcampb007** [comment]
thanks @jdm ! would you happen to know which file/files that process takes place in? I need to build something similar to it.

**Comment by jdm** [comment]
That's https://github.com/w3c/web-platform-tests/blob/master/manifest, which calls into https://github.com/w3c/wpt-tools/blob/c77a6c6cb5e91196c47adf2aa6dada60d6c380f4/manifest/update.py .
