### ISSUE TITLE
crypto is not a global object

### ISSUE THREAD

**Issue by jimsch** [w3c/web-platform-tests#3164]
The tests need to use self.crypto.subtle not crypto.subtle as the root of the access point for the worker tests.  Note that this also works for the html tests as well.  Look at \WebCryptoAPI\getRandomValue.js for an example of this. 

This is the problem with failures when running on FireFox.

**Comment by jimsch** [comment]
Maybe I am wrong -it is possible that the problem is the fact that Firefox release does not do the worker threads.  But it still might be something to look at.

**Comment by engelke** [comment]
I'll fix it in the morning. Thanks.

**Comment by Ms2ger** [comment]
This should be fine.
