### ISSUE TITLE
shadow-dom/resources/shadow-dom.js fails lintcheck

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#3193]
This change
https://github.com/w3c/web-platform-tests/commit/4bcdc1e50529f10c4581963e706732af11f28641

causes new PRs to fail lintcheck because `shadow-dom/resources/shadow-dom.js` uses `console.log` (twice).

https://travis-ci.org/w3c/web-platform-tests/builds/138874205

**Comment by hayatoito** [comment]
Ops. I did not realize that we have linkcheck for that. I'll fix it tomorrow. Please feel free to revert the change if we can not wait.

**Comment by zcorpan** [comment]
Thanks. I think it's OK to wait.

(If you want to keep the `console.log` you can add an exception in some whitelist file I believe.)
