### ISSUE TITLE
Add a test for click event while a pointer event is captured

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/web-platform-tests#3213]
Even though the PointerEvent spec doesn't override the [click target definition in UI Event](https://www.w3.org/TR/DOM-Level-3-Events/#event-type-click), a captured pointer makes the outcome slightly different. See the discussion in [this spec issue](https://github.com/w3c/pointerevents/issues/75).

We need a test for correct implementation.

**Comment by RByers** [comment]
@NavidZ or @mustaqahmed own this, assigning to myself for tracking
