### ISSUE TITLE
[webvtt] the value of line and position

### ISSUE THREAD

**Issue by alastor0325** [w3c/web-platform-tests#3222]
Hi, @zcorpan ,
Could you help me to verify whether these tests [1] have error?

For **settings-line.vtt**, since the line is a double value, the cue7/8/9 should return its line value instead of "2147483647", right? Also, the cue14 should return "1.5".

For **settings-position.vtt**,  since the position is a double value, cue10 should return "1.5%".

Thanks!

[1] https://github.com/w3c/web-platform-tests/blob/master/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/support/settings-line.vtt
https://github.com/w3c/web-platform-tests/blob/master/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/support/settings-position.vtt

**Comment by zcorpan** [comment]
> For settings-line.vtt, since the line is a double value, the cue7/8/9 should return its line value instead of "2147483647", right?

Hmmm. Yeah, I suppose so. I'm not sure what the 10000000000000000000000000000000000 should return, though.

> Also, the cue14 should return "1.5".

No. That setting fails to parse, so is dropped on the floor.

"If linepos contains any characters other than U+002D HYPHEN-MINUS characters (-) and ASCII digits, then jump to the step labeled next setting."

https://w3c.github.io/webvtt/#parse-the-webvtt-cue-settings

However, it's possible to set the value to 1.5 with the DOM API, and the spec doesn't really address what to do with it. At some point the spec changed from integers to doubles but when snap-to-lines is true it still expects integers. Will file a spec bug about that.

> For settings-position.vtt, since the position is a double value, cue10 should return "1.5%".

Yeah.

**Comment by alastor0325** [comment]
Do we need to make the **parser rule** and **DOM API** consistency? 
Because the rendering steps would round **line** to an integer, so maybe we can accept the floating value of the **line** in the file?

**Comment by zcorpan** [comment]
We could certainly do that. Can you file an issue?

**Comment by silviapfeiffer** [comment]
patches have landed to webvtt repo - should this be closed?

**Comment by zcorpan** [comment]
Yep. Tests are upstreamed as well in https://github.com/w3c/web-platform-tests/issues/3387

Thanks
