### ISSUE TITLE
Different behavior of querySelector depending on the caller

### ISSUE THREAD

**Issue by rianby64** [w3c/web-platform-tests#3301]
Hello!

I've a question about [the querySelector's behavior](https://github.com/rianby64/question-querySelector). I don't know whom to ask about it.

Notice that
```html
<div id="aText"></div>
<script>
  // the querySelector should take in count the Capital Letters
  document.currentScript.ownerDocument.querySelector('#aText');
  // but in my example, it doesn't
</script>
```

Please, help. I was looking for the tests for querySelector and couldn't find [the concrete test for it](https://github.com/w3c/web-platform-tests/search?utf8=%E2%9C%93&q=querySelector).
I know that the behavior for querySelector may vary depending on the interface, as explained [here](https://www.w3.org/TR/selectors-api/#interface-definitions).

Thanks!

**Comment by cvrebert** [comment]
Both of the HTML files in your repo lack a doctype, so they'll use Quirks Mode, which is never good.

**Comment by rianby64** [comment]
But, the failing test (at chrome) is passing at OperaMini ... So, I don't know if this fail test is a bug or not. Can you please advice me what should I use to import htm? Thanks a lot!

**Comment by rianby64** [comment]
@cvrebert Thanks a million! You're right )) I'll keep on reading about standards. It's passing!
