### ISSUE TITLE
open() is a footgun

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#3309]
CC @bzbarsky

**Comment by bzbarsky** [comment]
In that we've had multiple instances of open() being used in various python scripts serving up responses to read image/video/etc files, with the result that the tests fail on Windows but not other OSes.

**Comment by jgraham** [comment]
Yeah, writing a lint for open() without an explicit mode as we speak.

**Comment by jgraham** [comment]
https://github.com/w3c/wpt-tools/pull/87 https://github.com/w3c/web-platform-tests/pull/3311

Not perfect, but perhaps better.

**Comment by brightest-dazes** [comment]
Getting better just need to not be so isolated
