### ISSUE TITLE
browsing_context_name_cross_origin.html assigns the result of setTimeout to an event handler

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#3323]
This is clearly nonsense: https://github.com/w3c/web-platform-tests/blob/master/html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html#L40 . Either it should be `onload = function() { setTimeout(next, 0); }` or not interact with the onload event handler at all.

**Comment by Ms2ger** [comment]
CC @gsnedders
