### ISSUE TITLE
CENC initData in encrypted-media/Google/encrypted-media-utils.js has zero size

### ISSUE THREAD

**Issue by cpearce** [w3c/web-platform-tests#3430]
The CENC initData in [encrypted-media/Google/encrypted-media-utils.js](https://github.com/w3c/web-platform-tests/blob/master/encrypted-media/Google/encrypted-media-utils.js#L35) has 0 size.

This was causing Firefox to fail to parse this initData, though I've fixed that in Firefox Nightly.

A zero size means that the initData isn't valid, it doesn't follow the MP4 CENC spec.

The size of the box should be 52 decimal, or 0x34 hex.

**Comment by ddorwin** [comment]
I agree that the size should be changed.

A size of 0 means this is the last box in the file and its contents extend to the end of the file. That might work for a single PSSH box, but it's definitely not good practice.

**Comment by ddorwin** [comment]
PR #3455
