### ISSUE TITLE
[eme] generate-request-disallowed-input.js assumes InvalidAccessError instead of TypeError on initData that fails sanitization

### ISSUE THREAD

**Issue by cpearce** [w3c/web-platform-tests#3435]
The spec for [MediaKeySession.generateRequest()](https://w3c.github.io/encrypted-media/#dom-mediakeysession-generaterequest) says that initData which is invalid or which fails sanitization should result in the promise returned by MediaKeySession.generateRequest() being rejected with a TypeError, but test [Google/encrypted-media-generate-request-disallowed-input.html](https://w3c-test.org/encrypted-media/Google/encrypted-media-generate-request-disallowed-input.html) is testing that we're throwing an InvalidAccessError.

The test should be checking for TypeError, not InvalidAccessError.

**Comment by ddorwin** [comment]
Agreed. This test has been migrated, so I will modify it manually. Other unmigrated Google tests also use InvalidAccessError. These are being changed as part of fixing Chrome's behavior (https://crbug.com/646902). We'll upload those when they are committed in Blink.
