### ISSUE TITLE
Add strict-origin* referrer policy tests 

### ISSUE THREAD

**Issue by tungmangtdh3** [w3c/web-platform-tests#3436]
New 'strict-origin' and 'strict-origin-when-cross-origin' tests should be added to referrer-policy tests.
Assign to me @tungmangtdh3 :)

**Comment by jdm** [comment]
You will want to coordinate with https://github.com/w3c/webappsec-referrer-policy/issues/57 to make sure no work is duplicated.

**Comment by tungmangtdh3** [comment]
#3437
