### ISSUE TITLE
Invalid checks in dom/nodes/Document-getElementsByTagName.html / dom/nodes/Element-getElementsByTagName.html ?

### ISSUE THREAD

**Issue by cdumez** [w3c/web-platform-tests#3443]
I think there may be a couple of invalid checks in  the following tests:
- dom/nodes/Document-getElementsByTagName.html
- dom/nodes/Element-getElementsByTagName.html

In particular, I do not understand why the following ones would work:
`
  test(function() {
    var t = element.appendChild(document.createElementNS("http://www.w3.org/1999/xhtml", "test:aÇ"))
    this.add_cleanup(function() {element.removeChild(t)})
    assert_array_equals(context.getElementsByTagName("AÇ"), [t], "All uppercase input")
    assert_array_equals(context.getElementsByTagName("aÇ"), [t], "Ascii lowercase input")
    assert_array_equals(context.getElementsByTagName("aç"), [], "All lowercase input")
  }, "Element in HTML namespace, prefix, non-ascii characters in name")

  test(function() {
    var t = element.appendChild(document.createElementNS("test", "test:AÇ"))
    this.add_cleanup(function() {element.removeChild(t)})
    assert_array_equals(context.getElementsByTagName("AÇ"), [t], "All uppercase input")
    assert_array_equals(context.getElementsByTagName("aÇ"), [], "Ascii lowercase input")
    assert_array_equals(context.getElementsByTagName("aç"), [], "All lowercase input")
  }, "Element in non-HTML namespace, prefix, non-ascii characters in name")
`

In each case, the element has a 'test' prefix and yet the getElementsByTagName() calls never provide the prefix. As far as I can tell from the DOM specification, the qualified names would not match we getElementsByTagName() would never return the element in this case.

I am missing something?

**Comment by cdumez** [comment]
@annevk @Ms2ger @ayg ?

**Comment by annevk** [comment]
DOM changed regarding this and I forgot about tests.

**Comment by cdumez** [comment]
@annevk Is the DOM change you're referring to about getElementsByTagName() taking a qualifiedName instead of a localName? When looking at those tests I realized that Safari / Chrome match by localName but the latest DOM spec says qualifiedName.

**Comment by annevk** [comment]
Yeah: https://github.com/whatwg/dom/issues/143. https://github.com/w3c/web-platform-tests/pull/2808 supposedly updated the tests.
