### ISSUE TITLE
[eme] video_512x288_h264-360k_enc_2keys_2sess.mp4 has non-compliant 'pssh' boxes

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3447]
[video_512x288_h264-360k_enc_2keys_2sess.mp4](https://github.com/w3c/web-platform-tests/blob/b267d1f728f1337ac8a6bfa2448f3ee28e826049/encrypted-media/content/video_512x288_h264-360k_enc_2keys_2sess.mp4) has four concatenated 'pssh' boxes in the 'moov' box. They appear to be:
>Widevine
>PlayReady
>Widevine
>PlayReady

I assume the first pair is for one key and the second pair is for another key.

<br/>The ["cenc" Initialization Data Format registry entry](https://w3c.github.io/encrypted-media/format-registry/initdata/cenc.html) defines the format as
>one or more concatenated Protection System Specific Header ('pssh') boxes [CENC], each for a unique SystemID.

and the Processing section says to:
>Examine the series of 'pssh' boxes to find the first 'pssh' box that the CDM instance supports.

This file is inconsistent with the first item and would likely not be processed as expected (CDMs would only use the first supported box if the `initData` from an `"encrypted"` event was passed to `generateRequest()`).

**Comment by mwatson2** [comment]
This is fixed by PR #3629
