### ISSUE TITLE
Test should wait for connected state before calling terminate

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#3522]
@louaybassbouss, @yhe39,

The Presentation API [terminate test](https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationConnection_onterminated-manual.html) calls `terminate` as soon as the `start` promise is resolved.

However, the connection is not entirely established at this stage (see #3521), and the [termination algorithm](http://w3c.github.io/presentation-api/#terminating-a-presentation-in-a-controlling-browsing-context) will thus simply abort at step 1 without firing a `terminate` event.

I think that the test should rather wait for the `connect` event on `connection` before it calls `terminate`.

**Comment by louaybassbouss** [comment]
@yhe39 can you check this?

**Comment by Honry** [comment]
@louaybassbouss, @yhe39 has moved to another domain, I will take care of this.

**Comment by tidoust** [comment]
Closing the issue. Addressed by #3821.
