### ISSUE TITLE
Manual test on reconnection errors can be automated

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#3524]
@louaybassbouss, @taff-franck,

Is there a reason why the Presentation API [reconnection test](https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/reconnectToPresentation_error-manual.html) that passes a wrong presentation identifier to `reconnect` is manual?

In particular, as opposed to calling `start`, calling `reconnect` can be done in the absence of user interaction (that is, even if the algorithm isn't _allowed to show a popup_).

Also, the test should check that the Promise is rejected with a `NotFoundError` (see step 10 of the`[reconnecting to a presentation](http://w3c.github.io/presentation-api/#reconnecting-to-a-presentation) algorithm).

**Comment by louaybassbouss** [comment]
agree with @tidoust, @taff-franck can you fix this issue?

**Comment by louaybassbouss** [comment]
@tidoust this issue should be fixed by PR #4172. Feel free to close this issues after the PR is reviewed and merged.
