### ISSUE TITLE
Test expects AbortError, but should rather get NotAllowedError

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#3527]
@louaybassbouss, @mariuswsl,

Presentation API test that checks display selection abortion expects to receive an `AbortError`:
https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_error-manual.html#L33

That seems wrong to me. Aborting the selection of a display should match step 11 of the [starting a connection](http://w3c.github.io/presentation-api/#starting-a-presentation) algorithm and should thus result in a `NotAllowedError` exception.

Also, note that [exceptions messages](https://heycam.github.io/webidl/#dfn-exception-message) are implementation specific so the test should not assume that `err.message` will equal `Dialog closed.`.

**Comment by louaybassbouss** [comment]
agree with @tidoust, @mariuswsl can you fix this issue?
