### ISSUE TITLE
[eme] Migrate remaining Google tests

### ISSUE THREAD

**Issue by mwatson2** [w3c/web-platform-tests#3534]
The following tests remain to be migrated from the Google directory to new framework:
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-keystatuses-multiple-sessions.html
- encrypted-media-keystatuses-multiple-updates.html
- encrypted-media-onencrypted.html
- encrypted-media-playback-encrypted-and-clear-sources.html
- encrypted-media-playback-multiple-sessions.html
- encrypted-media-requestmediakeysystemaccess.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-setmediakeys-again-after-playback.html
- encrypted-media-setmediakeys-again-after-resetting-src.html
- encrypted-media-setmediakeys-at-same-time.html
- encrypted-media-setmediakeys-multiple-times-with-different-mediakeys.html
- encrypted-media-setmediakeys-multiple-times-with-the-same-mediakeys.html
- encrypted-media-setmediakeys-to-multiple-video-elements.html
- encrypted-media-setmediakeys.html
- encrypted-media-syntax.html
- encrypted-media-unique-origin.html
- encrypted-media-update-disallowed-input.html
- encrypted-media-utils.js
- encrypted-media-waiting-for-a-key.html

The following have already been migrated and should be disabled:
- encrypted-media-check-init-data-type.html
- encrypted-media-events.html
- encrypted-media-generate-request-disallowed-input.html
- encrypted-media-keystatuses.html
- encrypted-media-not-callable-after-createsession.html
- encrypted-media-playback-setmediakeys-after-src.html
- encrypted-media-playback-setmediakeys-before-src.html
- encrypted-media-playback-two-videos.html

The following use Chromium-specific features and should be disabled:
- encrypted-media-async-creation-with-gc.html
- encrypted-media-async-setcert-with-gc.html
- encrypted-media-lifetime-mediakeys-with-session.html
- encrypted-media-lifetime-mediakeys.html
- encrypted-media-lifetime-mediakeysession-reference.html
- encrypted-media-lifetime-mediakeysession-release-noreference.html
- encrypted-media-lifetime-mediakeysession-release.html
- encrypted-media-lifetime-multiple-mediakeys.html
- encrypted-media-lifetime-reload.html

Please reply to this issue to claim some of the work.

**Comment by jdsmith3000** [comment]
It is reasonable to disable tests that are currently migrated.  We can leave others active and turn them off as new tests are migrated over.

I agree with the chrome specific list, and can do the edits to disable them and the migrated tests.

**Comment by jdsmith3000** [comment]
I'm preparing a PR for this change.

**Comment by mwatson2** [comment]
@jdsmith3000 Do you mean the change to disable some of the Google tests, or
something else ?

On Aug 24, 2016, at 4:30 PM, jdsmith3000 <notifications@github.com> wrote:

I'm preparing a PR for this change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w3c/web-platform-tests/issues/3534#issuecomment-242197753>,
or mute the thread

**Comment by jdsmith3000** [comment]
Disabling Google tests.  I intend to create sub folders and move the disabled tests so we know which remain to be migrated.  Okay?

I want to make this change and then re-run the test status report with dupes and Chromium specific tests removed from the reports.

**Comment by mwatson2** [comment]
All sounds good.

On Aug 24, 2016, at 4:52 PM, jdsmith3000 <notifications@github.com> wrote:

Disabling Google tests. I intend to create sub folders and move the
disabled tests so we know which remain to be migrated. Okay?

I want to make this change and then re-run the test status report with
dupes and Chromium specific tests removed from the reports.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w3c/web-platform-tests/issues/3534#issuecomment-242204320>,
or mute the thread

**Comment by ddorwin** [comment]
SGTM

**Comment by mwatson2** [comment]
Actually, I meant this issue to cover the entire job of migrating the remaining tests, but I will open a new issue for that.

**Comment by mwatson2** [comment]
#3583
