### ISSUE TITLE
[eme] Migrate remaining Google tests to main framework

### ISSUE THREAD

**Issue by mwatson2** [w3c/web-platform-tests#3583]
The following are in need of migration. Please reply to this issue to claim some:
- encrypted-media-clear-key-invalid-license.html
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-keystatuses-multiple-sessions.html
- encrypted-media-keystatuses-multiple-updates.html
- encrypted-media-onencrypted.html
- encrypted-media-playback-encrypted-and-clear-sources.html
- encrypted-media-playback-multiple-sessions.html
- encrypted-media-requestmediakeysystemaccess.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-setmediakeys-again-after-playback.html
- encrypted-media-setmediakeys-again-after-resetting-src.html
- encrypted-media-setmediakeys-at-same-time.html
- encrypted-media-setmediakeys-multiple-times-with-different-mediakeys.html
- encrypted-media-setmediakeys-multiple-times-with-the-same-mediakeys.html
- encrypted-media-setmediakeys-to-multiple-video-elements.html
- encrypted-media-setmediakeys.html
- encrypted-media-syntax.html
- encrypted-media-unique-origin.html
- encrypted-media-update-disallowed-input.html
- encrypted-media-waiting-for-a-key.html

**Comment by sukhmal** [comment]
I will start off by migrating setmediakeys tests:

- encrypted-media-setmediakeys-again-after-playback.html
- encrypted-media-setmediakeys-again-after-resetting-src.html
- encrypted-media-setmediakeys-at-same-time.html
- encrypted-media-setmediakeys-multiple-times-with-different-mediakeys.html
- encrypted-media-setmediakeys-multiple-times-with-the-same-mediakeys.html
- encrypted-media-setmediakeys-to-multiple-video-elements.html
- encrypted-media-setmediakeys.html

**Comment by jdsmith3000** [comment]
These then are remaining for someone to migrate:

- encrypted-media-clear-key-invalid-license.html
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-keystatuses-multiple-sessions.html
- encrypted-media-keystatuses-multiple-updates.html
- encrypted-media-onencrypted.html
- encrypted-media-playback-encrypted-and-clear-sources.html
- encrypted-media-playback-multiple-sessions.html
- encrypted-media-requestmediakeysystemaccess.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-syntax.html
- encrypted-media-unique-origin.html
- encrypted-media-update-disallowed-input.html
- encrypted-media-waiting-for-a-key.html

**Comment by mwatson2** [comment]
I will look at:

- encrypted-media-keystatuses-multiple-sessions.html
- encrypted-media-keystatuses-multiple-updates.html

**Comment by mwatson2** [comment]
Actually, encrypted-media-keystatuses-multiple-sessions.html has already been done.

**Comment by mwatson2** [comment]
encrypted-media-keystatuses-multiple-updates.html tests that a single clearkey session can receive two `update()` calls each adding a single key, after only a single `license-request` message has been generated.

I don't believe any of the DRMs support this flow.

So, then I would propose that we do not need to migrate this test (see #3737)

**Comment by mwatson2** [comment]
I will look at:
- encrypted-media-playback-encrypted-and-clear-sources.html
- encrypted-media-playback-multiple-sessions.html

**Comment by ddorwin** [comment]
Regarding https://github.com/w3c/web-platform-tests/issues/3583#issuecomment-247439997, `encrypted-media-keystatuses-multiple-updates.html` is probably testing that the keys in the session can change. The test cheats a little because it is easy to create a Clear Key license. However, DRMs might support this flow in a (non-continuous) key rotation scenario. Writing that test would require support from the test server.

**Comment by mwatson2** [comment]
@ddorwin Do you mean the keys within a single session ? This is only possible to test if either:
(a) the DRM supports unsolicited provision of new keys (and our server supports creation of such messages), or
(b) the DRM fires new `license-request` messages itself, which our server can respond to.

I had imagined that one form of key rotation is supported by the DRM triggering a new `license-request` when the expiration time of its existing keys approaches. Does Widevine support this ? We would need to switch to the JWT authorization approach, since the test dummy approach doesn't give us very short-lived keys.

**Comment by ddorwin** [comment]
Yes. I think (b) but with `"license-renewal"` is the likely scenario. Yes, I believe this is supported.

This isn't a high priority, and I'm fine with deferring this work (to a separate bug and marking the text as done for now). I just wanted to point out that the scenario this test is trying to cover is valid for Key Systems other than Clear Key.

**Comment by mwatson2** [comment]
Ok, I filed #3740

**Comment by mwatson2** [comment]
encrypted-media-playback-encrypted-and-clear-sources.html is addressed by #3739.

I believe encrypted-media-playback-multiple-sessions.html may already be addresed by #3629

**Comment by mwatson2** [comment]
Indeed encrypted-media-playback-multiple-sessions.html is already addressed by #3629 (#3745 to move it).

**Comment by mwatson2** [comment]
I will look at encrypted-media-requestmediakeysystemaccess.html next. The remaining tests to be migrated are:
- encrypted-media-clear-key-invalid-license.html
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-onencrypted.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-syntax.html
- encrypted-media-unique-origin.html
- encrypted-media-update-disallowed-input.html
- encrypted-media-waiting-for-a-key.html

**Comment by mwatson2** [comment]
PR #3747 for encrypted-media-requestmediakeysystemaccess.html

**Comment by mwatson2** [comment]
Stefan Pham is working on:

- encrypted-media-clear-key-invalid-license.html
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-onencrypted.html
- encrypted-media-session-closed-event.html
- encrypted-media-unique-origin.html

**Comment by squapp** [comment]
PR #3790 for 

- encrypted-media-clear-key-invalid-license.html
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-onencrypted.html
- encrypted-media-unique-origin.html

Working on these next:
- encrypted-media-waiting-for-a-key.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-waiting-for-a-key.html

**Comment by sukhmal** [comment]
PR #3795 for

- encrypted-media-setmediakeys-again-after-playback.html
- encrypted-media-setmediakeys-again-after-resetting-src.html
- encrypted-media-setmediakeys-at-same-time.html
- encrypted-media-setmediakeys-multiple-times-with-different-mediakeys.html
- encrypted-media-setmediakeys-multiple-times-with-the-same-mediakeys.html
- encrypted-media-setmediakeys-to-multiple-video-elements.html
- encrypted-media-setmediakeys.html

**Comment by squapp** [comment]
PR #3799 for 

- encrypted-media-waiting-for-a-key.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-update-disallowed-input.html

Next (and last test):
- encrypted-media-syntax.html

**Comment by jdsmith3000** [comment]
Since the last file is in work to be migrated, I'd like to move the remaining Google tests into a disabled subfolder, and comment out the test harness lines so they don't run.  Okay?

These files are currently still in the Google folder:

- encrypted-media-clear-key-invalid-license.html
- encrypted-media-clearkey-update-non-ascii-input.html
- encrypted-media-onencrypted.html
- encrypted-media-reset-src-after-setmediakeys.html
- encrypted-media-session-closed-event.html
- encrypted-media-setmediakeys-again-after-playback.html
- encrypted-media-setmediakeys-again-after-resetting-src.html
- encrypted-media-setmediakeys-at-same-time.html
- encrypted-media-setmediakeys-multiple-times-with-different-mediakeys.html
- encrypted-media-setmediakeys-multiple-times-with-the-same-mediakeys.html
- encrypted-media-setmediakeys-to-multiple-video-elements.html
- encrypted-media-setmediakeys.html
- encrypted-media-syntax.html
- encrypted-media-unique-origin.html
- encrypted-media-update-disallowed-input.html
- encrypted-media-utils.js
- encrypted-media-waiting-for-a-key.html

**Comment by jdsmith3000** [comment]
@mwatson2 @sukhmal Any objections to pulling these now?  I believe they only pass on Chrome, and it would be best to focus on the migrated tests now.

**Comment by mwatson2** [comment]
Fine by me to disable them now.

**Comment by jdsmith3000** [comment]
@squapp I see you are working:

- encrypted-media-syntax.html

https://github.com/w3c/web-platform-tests/pull/3846 moves all of the remaining Google tests into the disabled folder and comments out the test harness links so that they no longer run.  I plan to merge that change in later today.  FYI.

Do have an ETA for this last test?

**Comment by jdsmith3000** [comment]
The Google tests have now all been disabled, but migration work is not yet completed.  Re-opening this issue until that is done.

**Comment by squapp** [comment]
@jdsmith3000 encrypted-media-syntax.html will be completed by tomorrow, Wednesday

**Comment by squapp** [comment]
PR #3874 for the last test: encrypted-media-syntax.html

**Comment by mwatson2** [comment]
The last PR for this has been merged.
