### ISSUE TITLE
[eme] Migrate account on DRMToday servers

### ISSUE THREAD

**Issue by mwatson2** [w3c/web-platform-tests#3624]
We are still using the CableLabs account on the DRMToday servers. We should use the account that they provided for us.

**Comment by ddorwin** [comment]
The current test server is reporting a 403, blocking progress.
>https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/ Failed to load resource: the server responded with a status of 403 (Forbidden)

Migration _may_ address this, but we can't be sure since we don't know the cause.

@mwatson2, who has the account information?

/cc @jdsmith3000 @paulbrucecotton @greg80303 @mavgit

**Comment by ddorwin** [comment]
@mwatson2, what all is involved in this? Is it more than updating the account information in `drm-messagehandler.js`?

**Comment by mwatson2** [comment]
IIUC:

- Ingest our content metadata (including keys) into the DRMToday system. There is admin web page for this and also a command line tool. Need to get right the cases where multiple keys are retrieved independently and the case where a request for any key associated with an asset returns all the keys associated with an asset.
- Either: (a) Set up a new "authentication proxy". CableLabs has a simple node-based implementation for this, but we would need an actual server to run it on, or (b) Implement the "upfront authentication token" approach where the client creates and signs a JWT with the required rights information

The JWT thing actually looks reasonably simple, so that might be better than keeping the additional server dependency.

**Comment by mwatson2** [comment]
A third option (probably the best) is to set the account to use the "Test Dummy" authentication server. This avoid a dependency on another server and does not require creation of a JWT.

To do this we would change a setting on the DRMToday account and include appropriate values in the `userId` and `sessionId` in each request to trigger the right license response as described [here](https://fe.staging.drmtoday.com/frontend/documentation/integration/administration_frontend.html?highlight=test%20dummy#uisetting-Test_dummy).

**Comment by mwatson2** [comment]
I am working on this today.

**Comment by mwatson2** [comment]
PR #3733 

This migrates to the W3C EME Test DRM Today account and removes the dependency on an authentication server.
