### ISSUE TITLE
[eme] Explicitly surface DRM test server errors

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3706]
Problems with the DRM test server caused many tests to fail in a non-obvious way ([example](https://lists.w3.org/Archives/Public/public-html-media/2016Sep/0065.html)).

We should try to make such failures obvious in some way, at least by including it in the test page, but preferably in some unmistakable way in the reporting.

**Comment by mwatson2** [comment]
We could cause tests to stop with NOTRUN when there are server errors if we refrain from testing any asserts before the server round trip is complete successfully, and call test.done() on server errors. There does not appear to be any other way to signal a problem with the test itself that is distinguishable from a test failure.

**Comment by ddorwin** [comment]
While it doesn't help with the report aspect [`assert_unreached`](https://github.com/w3c/testharness.js/blob/master/docs/api.md#assert_unreacheddescription) would be an appropriate way to report server replies other than `200`.

**Comment by mwatson2** [comment]
Presently, we are using `forceTestFailureFromPromise` for various kinds of unexpected failure. This forces a TIMEOUT. We could use the same thing here (In fact, I don't think we have much choice).
