### ISSUE TITLE
[eme] Three persistent-license tests fail due to missing acknowledgement in release message response

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3718]
On Chrome OS 53, three of the five `/encrypted-media/drm-.*persistent-license.*` tests fail due to bad responses from the DRMtoday server. I've included the failure for each below.

**1. [drm-mp4-playback-destroy-persistent-license.html](https://www.w3c-test.org/encrypted-media/drm-mp4-playback-destroy-persistent-license.html)**
```
drm-messagehandler.js:223
POST https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/ 400 (Bad Request)
  (anonymous function) @ drm-messagehandler.js:223
  messagehandler @ drm-messagehandler.js:175
  onMessage @ playback-destroy-persistent-license.js:32eventCallback @ utils.js:93
  Test.step @ testharness.js:1401
  (anonymous function) @ testharness.js:1425
drm-mp4-playback-destroy-persistent-license.html:1
Uncaught (in promise) com.widevine.alpha update, XHR status is "Bad Request" (400), expected to be 200. readyState is undefined. Response is [object Response]
```

**2. [drm-mp4-playback-persistent-license-events.html](https://www.w3c-test.org/encrypted-media/drm-mp4-playback-persistent-license-events.html)** (after manually applying PR #3717)
```
drm-messagehandler.js:223
POST https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/ 406 (Not Acceptable)
  (anonymous function) @ drm-messagehandler.js:223
  messagehandler @ drm-messagehandler.js:175
  onMessage @ playback-persistent-license-events.js:47
  eventCallback @ utils.js:93
  Test.step @ testharness.js:1401
  (anonymous function) @ testharness.js:1425
drm-mp4-playback-persistent-license-events.html:1
Uncaught (in promise) com.widevine.alpha update, XHR status is "Not Acceptable" (406), expected to be 200. readyState is undefined. Response is [object Response]
```

**3. [drm-mp4-playback-retrieve-destroy-persistent-license.html](https://www.w3c-test.org/encrypted-media/drm-mp4-playback-retrieve-destroy-persistent-license.html)**
```
lic.staging.drmtoday.com/:1
POST https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/ 400 (Bad Request)
drm-retrieve-destroy-persistent-license.html:1
Uncaught (in promise) com.widevine.alpha update, XHR status is "Bad Request" (400), expected to be 200. readyState is undefined. Response is [object Response]
```

**Comment by mwatson2** [comment]
These are the same problems I encountered. Apparently DRMToday are aware of the problem and working on a fix.

**Comment by mwatson2** [comment]
Btw, if it is possible for the Widevine _Record of License Destruction Acknowledgement_ to be constructed by the client, then we could work around this problem (we are testing the client, not the server).

**Comment by louaybassbouss** [comment]
I think it makes sense in this case to use `NOTRUN` instead of `FAIL`. But if these are temporary errors, it is important to ensure that at the time of generating the report using the test runner http://w3c-test.org/tools/runner/index.html all involved 3rd party components are running and working correctly.

**Comment by mwatson2** [comment]
I was not able to work out how to make an individual test return NOTRUN. Do you know how to do this ?

**Comment by ddorwin** [comment]
These tests now fail for a different reason:

>InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

The problem is that the Key System wrapper for Widevine in drm-messagehandler.js assumes that the `response` object as a `license` member but this is not the case for the release acknowledgement response. Thus, `undefined` is passed to `atob`.

This logic appears to be specific to the DrmToday server. The JSON of the response does not contain the `license` member. It's not a license we expect, but we do need some blob to pass to `update()`. Maybe the server needs to be updated to provide a `license` member or some other member that the test will need to look for.

**Comment by mwatson2** [comment]
@ddorwin What does the Widevine CDM expect as an acknowledgement message ? Is it something that can only be created by the server ?

**Comment by mwatson2** [comment]
@ddorwin CastLabs tell me that the response we are seeing now is everything they are given by the Widevine server. So, I am wondering if the Widevine CDM expects some kind of "default" acknowledgement, rather than something from the server ?

**Comment by mwatson2** [comment]
This was a server side issue which is now resolved.
