### ISSUE TITLE
Update XHR data-uri.htm to match the resolution of Fetch issue 339.

### ISSUE THREAD

**Issue by wisniewskit** [w3c/web-platform-tests#3738]
Recently Fetch was changed in [issue 339](https://github.com/whatwg/fetch/issues/339) to allow all methods for data URLs. XMLHttpRequest/data-uri.htm should reflect that change. Here is a patch which makes it so:

``` diff
diff --git a/XMLHttpRequest/data-uri.htm b/XMLHttpRequest/data-uri.htm
index 8c29705..de5c14d 100644
--- a/XMLHttpRequest/data-uri.htm
+++ b/XMLHttpRequest/data-uri.htm
@@ -18,16 +18,6 @@
           return;
         }

-        // Note: fetching a data URL with a non-GET method returns a network
-        // error per <http://fetch.spec.whatwg.org/#basic-fetch>.
-        if (method.toUpperCase() !== 'GET') {
-          assert_equals(client.status, 0);
-          assert_equals(client.responseText, '');
-          assert_equals(client.statusText, '');
-          test.done();
-          return;
-        }
-
         assert_equals(client.responseText, "Hello, World!");
         assert_equals(client.status, 200);
         assert_equals(client.getResponseHeader('Content-Type'), charset);
```

**Comment by annevk** [comment]
I posted a PR, review appreciated.

**Comment by wisniewskit** [comment]
Sure, for what it's worth that PR seems fine to me.

**Comment by annevk** [comment]
Good enough for me. Let me know if you want to be an owner of XMLHttpRequest tests.

**Comment by wisniewskit** [comment]
Sure, if it would help then I don't mind. Just let me know if there's any reading material I should go through, and any services I should subscribe to or lurk on.

**Comment by annevk** [comment]
You can PR this repository and add your username to XMLHttpRequest/OWNERS as a first step. http://web-platform-tests.org/ has some documentation on reviewing.
