### ISSUE TITLE
[eme] Add tests for rejecting improper licenses for the session type

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3756]
The [`update()` algorithm](https://w3c.github.io/encrypted-media/#update) says the CDM should "Reject promise with a newly created TypeError" if a persistable license is provided to a session type other than `"persistent-license"` and vice versa.

The drmtoday server appears to request a different license based on a custom header (see `getCustomHeaders()` in `drm-messagehandler.js`), so we should be able to test these negative cases.

Note that failing this test could cause a key to be unexpectedly persisted, which could hide problems in other tests. It might be good to have a license with a key that does not appear in other tests.

**Comment by mwatson2** [comment]
Pull Request #3774 

This fails on Chrome, Firefox and Edge. I believe this is a known bug on Edge and that the license is indeed persistent. On Chrome and Firefox I don't know if the license gets persisted (and what the implications of this are) or whether it is treated just as a temporary license despite being marked as persistent.

Presently this is using a key also used for real content. This should be migrated to a different key if possible.
