### ISSUE TITLE
Onboarding W3C/WPT test suites into Edge mainline testing

### ISSUE THREAD

**Issue by DLehenbauer** [w3c/web-platform-tests#3757]
This tracking issue serves two purposes.  The first purpose to is invite discussion within the W3C/WPT community about the role web-platform-tests plays in automated testing for browser vendors.  The second purpose of this tracking issue is to test the waters regarding EdgeHTML developers contributing fixes for nitpicky issues in existing tests, and explain the motivation for doing so.

Historically, our quality team has run ‘web-platform-tests’ periodically outside of the main development loop, using heuristics to detect when a previously stable test has regressed.  This has been an inexpensive “safety net” for detecting issues that slip through our mainline testing.  However, we would like to more aggressively leverage ‘web-platform-tests’ in driving our compliance and interoperability.

To that end, many EdgeHTML developers bring portions of ‘web-platform-tests’ into our mainline testing as part of onboarding new features.  When they do this, they typically make changes to the tests to meet our requirements for mainline testing.  These requirements include deterministically passing 1000x iterations daily, fully investigating any failures, and complying with coding standards that were established to facilitate use of these tests across the broader organization.

Some of the changes we make to the tests are purely about improving reliability, some are about making failures more actionable (improvements to assert messages and test names), while other changes may be viewed as a bit less necessary, but are considered best practices (‘use strict’ requirement for example).

For us, the ideal situation would be one in which we can contribute these changes back to the community at large so that we can then consume ‘web-platform-test/master’ directly in our mainline testing, instead of maintaining an internal fork as we do today.  However, we’re unsure of how the community will feel about some of these change, which is why we wanted to open the conversation.

**Comment by jdm** [comment]
I (and others at Mozilla) welcome changes to the test suite that improve reliability and user-visible strings. I don't see any particular reason to push back against incorporating best practices, either.

**Comment by foolip** [comment]
@thejohnjansen @patrickkettner, what is the status of this? Are the most important blocking issues for EdgeHTML upstreaming of test changes already tracked as separate issues?

**Comment by foolip** [comment]
Ping @DLehenbauer @thejohnjansen @patrickkettner. Seems like this is an issue for Microsoft and not a concrete thing we can do in upstream WPT, so should we close this issue in favor of specific changes you might require?

**Comment by DLehenbauer** [comment]
There is no work requested here, only a question to the community about policy.

We've likely heard from all that want to provide feedback.

**Comment by jgraham** [comment]
FWIW my pint of view is that improvements in test reliability are very welcome. Changing names of things can be disruptive since data about which tests are expected to fail in implemenatations are generally keyed on name. Other changes may or may not be welcome; it's hard to judge without concrete examples, but if they don't affect the test functionality or ability to run the tests, I don't foresee objections. However anything that would impose additional conditions  on tests written by others (e.g. some requirement for all tests to "use strict" would require additional discussion.

Getting contributions from Microsoft in general is very valuable, and I'd really like to make this happen.
