### ISSUE TITLE
[eme] Add tests for readyState changes

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3760]
We need tests to ensure that the media element's `readyState` value is set as defined in the [Wait for Key](https://w3c.github.io/encrypted-media/#wait-for-key) and [Attempt to Resume Playback If Necessary](https://w3c.github.io/encrypted-media/#resume-playback) algorithms (and otherwise matches the HTML5 spec.

**Comment by mwatson2** [comment]
PR #3868
