### ISSUE TITLE
[eme] isInitDataTypeSupported() calls are not passing keysystem, causing false positives

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3763]
The following calls to `isInitDataTypeSupported()` do not pass the `keysystem` parameter, causing `requestMediaKeySystemAccess()` to fail for an `initDataType` value of `undefined` and thus report false.

In the case of `/generate-request-disallowed-input.js`, **no** tests are actually exercised on any browser.

```
./scripts/check-initdata-type.js:        return isInitDataTypeSupported(initDataType).then(function(result) {
./scripts/generate-request-disallowed-input.js:        return isInitDataTypeSupported(initDataType).then(function(result) {
```

**Comment by mwatson2** [comment]
PR #3779
