### ISSUE TITLE
Minor:  DRM tests with Clear Key in title and message handler comment/src

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/web-platform-tests#3818]
encrypted-media\drm-not-callable-after-createsession.html:
- Line 17:     
- Line 18:     script src=/encrypted-media/util/clearkey-messagehandler.js></script>

encrypted-media\drm-keystatuses-multiple-sessions.html:
- Line 5:     <title>Encrypted Media Extensions: Successful Playback, Temporary session with Clear Key, mp4, multiple keys for audio/video</title>
- Line 21:     

encrypted-media\drm-mp4-playback-temporary-two-videos.html:
- Line 5:     <title>Encrypted Media Extensions: Successful Playback, Temporary session with Clear Key, mp4, two videos</title>
- Line 21:

**Comment by louaybassbouss** [comment]
can this issue be closed?
