### ISSUE TITLE
[eme] Test failure during playback when a license expires

### ISSUE THREAD

**Issue by mwatson2** [w3c/web-platform-tests#3826]
When a license expires during playback, playback should fail. A license with a specific expiry time can be obtained with the code in PR #3798.

This test may be tricky to make reliable, since we only have 10 seconds of content and will need to set the expiration and start playback such that expiration occurs during playback. Likely the expiration will need to be set 10-15s in the future, to give time for the license exchange content loading etc. to complete, then playback could be started, then paused to wait until a few seconds before license expiration, then started again.

**Comment by mwatson2** [comment]
Ok, so I created PR #3936 anyway. This tests a license expiring using the playDuration control (the absolute expiration control on DRMToday is not accurate enough to have the license expire during our short playback).

All three browsers fail on this, because they all continue playback, with timeupdates, past the expiration. Chrome / Firefox at least stop rendering video (continuing with audio only) and issue a keyStatus update with expired status. Edge renders the video all the way through, so perhaps the server is not returning the right kind of license ?

**Comment by mwatson2** [comment]
@jdsmith3000 I wonder if someone at MS could look at the license that is being returned for PlayReady in this test and check that it has the specified play duration limit ?

**Comment by jdsmith3000** [comment]
I will confirm.

**Comment by jdsmith3000** [comment]
This issue hasn't moved for close to a month.  Do we view fixing it as V1.

The existing test has known issues with Edge, but in concept, we believe the requirement behind it is valid.

**Comment by ddorwin** [comment]
It sounds like Chrome and Firefox mostly do what they are supposed to. I wonder if Chrome actually stops audio after three seconds. If so, this would be related to https://crbug.com/658422.

@mwatson2, do you want to rebase, and we can review?

/sub @jrummell-chromium
