### ISSUE TITLE
XHR event-readystatechange-loaded.htm test needs a reality check.

### ISSUE THREAD

**Issue by wisniewskit** [w3c/web-platform-tests#3834]
Chrome is somehow passing the test XMLHttpRequest/event-readystatechange-loaded.htm despite actually firing multiple LOADING events, as is evidenced on sites like https://edupad.ch/ through careful debugging, or just by reading their [source code](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/xmlhttprequest/XMLHttpRequest.cpp#478).

In addition, Firefox [recently found](https://bugzilla.mozilla.org/show_bug.cgi?id=1304067) that active sites like the aforementioned one still rely on this legacy behavior, so a [spec issue](https://github.com/whatwg/xhr/issues/92) was filed. The test in question will need to be changed accordingly, once the spec is revised.

**Comment by hallvors** [comment]
Ugh. Anyone knows how the test could capture what Blink is actually doing here?

**Comment by wisniewskit** [comment]
I don't think the test should have to concern itself with Chrome; flipping the test's expectation around to match the spec (which just updated) should be enough to fix it. Firefox, WebKit, and Edge should all pass it in that case.

However, Chrome *will* fail the test if its expectation is simply flipped. They'll either have to just fix that and match other browsers and the spec, or chime in and explain what heuristics/flukes let them support this legacy behavior while still "passing" the test in its current form.

**Comment by annevk** [comment]
This got fixed in #4126.
