### ISSUE TITLE
Should skip presentation.defaultRequest test if not supported by browser

### ISSUE THREAD

**Issue by schien** [w3c/web-platform-tests#3844]
According to the second note of section 6.2.1 [1], setting presentation.defaultRequest should take no effect if browser doesn't support it. We should run the test steps related to defaultRequest in controlling-ua/idlharness.html only if browser supports it.

[1] https://w3c.github.io/presentation-api/#controlling-user-agent

**Comment by tomoyukilabs** [comment]
@schien Section 6.2.1 says "Controlling user agents must implement the following partial interface" (i.e. `defaultRequest` attribute). Therefore, I think controlling-ua/idlharness.html should check `navigator.presentation.defaultRequest`, whether browser supports it or not.

**Comment by schien** [comment]
However, in the second note it says "setting presentation.defaultRequest" should take no effect. I take this sentence as "assigning value to defaultRequest will be no-op", which means presentation.defaultRequest will still be null after the assignment. That's my interpretation.

**Comment by tomoyukilabs** [comment]
I'm afraid that the spec might look ambiguous. I regard it as "Although the `defaultRequest` property can be set to any instance of `PresentationRequest` or `null`, browsers which do not support `defaultRequest` will never refer to its value unless a script accesses it directly".

**Comment by tidoust** [comment]
@schien Back to your initial point, I don't think that there is any way to mark tests that check optional features of a spec as "optional", and no way to skip them or to have them report a "not supported" status either.

The label of the [test on defaultRequest](https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/defaultRequest_success-manual.html) has been prefixed with "[Optional]" to clarify that failure may mean "not supported".

I see "Better support for tests of "optional" features (philosophically controversial)" was on the [agenda of the WebPlatformTests F2F](https://www.w3.org/wiki/TPAC2016/WebPlatformTests) for TPAC, but it does not seem to have been discussed. It could be worth creating a generic issue here or on wpt-tools but I don't think there's much we can do for the defaultRequest test in the meantime.

**Comment by schien** [comment]
As @mfoltzgoogle mentioned that we didn't override the set attribute algorithm in https://github.com/w3c/presentation-api/issues/359#issuecomment-253887460, I'm happy to follow the description @tomoyukilabs described in previous comment.

So, the automation test can keep as the way it is: try set the attribute and do WebIDL check on it.
