### ISSUE TITLE
High-value interop tests in old-tests/submission/Opera/script_scheduling

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#3850]
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/035.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/040.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/080.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/083.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/084.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/108.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/127.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/128.html
http://w3c-test.org/old-tests/submission/Opera/script_scheduling/130.html

These fail in Chrome but pass in Firefox and Edge. Moving them to the appropriate place (HTML?) would be great so that it's obvious that these should be taken seriously.

See https://crbug.com/651572 for the source of this data, which includes failing subtests.

Note: Results may have changed in the interim.

@zcorpan

**Comment by gsnedders** [comment]
I guess we probably want to give them more useful file names to follow the existing directory structure, that will get quickly time consuming.

**Comment by foolip** [comment]
@jdm reminder me of this again today. @domenic, do you know where under html/ these would belong? http://wpt.fyi/old-tests/submission/Opera/script_scheduling is pretty green!

**Comment by domenic** [comment]
https://github.com/w3c/web-platform-tests/tree/master/html/semantics/scripting-1/the-script-element seems about right.

**Comment by foolip** [comment]
Any preferences for the naming? All in a directory, scheduling-000.html, or something else?

I'm thinking we should at least move all of the tests that pass in some browser, those need action one way or another even if they don't match what the spec says. And then vet the <10 tests that fail everywhere. Seem OK?

**Comment by domenic** [comment]
Ideally they'd have names that reflect what they're testing, but that's presumably too much work.

A subdirectory seems good. Maybe execution-timing.

**Comment by gsnedders** [comment]
I think we should just move them all; keeping them in old-tests seems too likely that they'll just stay there forever.

Once Mozilla's infrastructure changes and we can rename tests more easily we can always rename again later.
