### ISSUE TITLE
[eme] drm-keystatuses-multiple-sessions.html appears broken

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3877]
https://www.w3c-test.org/encrypted-media/drm-keystatuses-multiple-sessions.html times out in Chrome. In the console, I see a 403 followed by an exception:

>https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/ Failed to load resource: the server responded with a status of 403 (Forbidden)
utils.js:129 Uncaught (in promise) TypeError: test.force_timeout is not a function(…)

@mwatson2, any thoughts?

**Comment by mwatson2** [comment]
This is probably a variantId thing. I'll look into it.

Btw, the keystatuses tests are failing on Chrome because of the lack of the keystatuseschange event after close().

**Comment by mwatson2** [comment]
PR #3883
