### ISSUE TITLE
[eme] drm-mp4-playback-temporary-encrypted-clear-sources.html needs a longer timeout

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3878]
https://www.w3c-test.org/encrypted-media/drm-mp4-playback-temporary-encrypted-clear-sources.html is timing out on all three browsers. In Chrome, it plays three or four videos then reports TIMEOUT. When it played three, the fourth played after the TIMEOUT was reported. I'm guessing it needs more time.

The Clear Key version may just barely pass because it does not need to fetch licenses.

Another option would be to break this test up into two tests that play two videos each. It would also be nice if the description explained what the four videos are.

**Comment by ddorwin** [comment]
We should also/instead make the playbacks take less time. The current test is likely too long to be run as part of automated browser tests. This would eliminate the need to extend the timeout, thought it may still make sense to split the test up depending on the purpose of the four playbacks.

**Comment by mwatson2** [comment]
PR #3882 

The purpose of the test is to check that the same media element can be used to play, alternately, separate encrypted and clear sources. We can reduce the playback time needed to 0.5s and reduce the number of playbacks to 3 instead of 4 (So, we will test encrypted, clear, encrypted).
