### ISSUE TITLE
DOM Node.contains testcase has inaccurate assertion description

### ISSUE THREAD

**Issue by cvrebert** [w3c/web-platform-tests#3939]
The assertion descriptions (https://github.com/w3c/web-platform-tests/blob/a514a0e8b352fd91aca059d1e939762294b20fe8/dom/nodes/Node-contains.html#L30 ) say "compareDocumentPosition" instead of "contains".

**Comment by gbrmachado** [comment]
Hello. I've created a PR to fix it.
