### ISSUE TITLE
[eme] *-mp4-setmediakeys-multiple-times-with-different-mediakeys.html have syntax error

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3953]
```
setmediakeys-multiple-times-with-different-mediakeys.js:56 Uncaught SyntaxError: Unexpected token )
```

There appears to be an extra `)` after a `then(` without a `test.step_func(`. I tried fixing it but ran into a couple other problems, so someone familiar with this test should look at it.

Also, is there a reason that not all of the resolve functions use `test.step_func()`?

**Comment by mwatson2** [comment]
`test.step_func()` is only needed if the function body contains assertions.

**Comment by mwatson2** [comment]
PR #3955
