### ISSUE TITLE
[eme] Syntax tests should expect remove() to work for all session types

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3982]
The `remove()` tests in `syntax-mediakeysession.js` expect that "remove() on a temporary session should fail." However, the behavior of [`remove()`](https://w3c.github.io/encrypted-media/#remove) was changed such that it works for all session types.

Chrome will fail the corrected test currently: https://bugs.chromium.org/p/chromium/issues/detail?id=616166

**Comment by ddorwin** [comment]
Note that the current spec algorithm would result in a `TypeError`, which is not what is intended: https://github.com/w3c/encrypted-media/issues/337.

**Comment by ddorwin** [comment]
The spec bug has been fixed, so we can move forward with correcting the test expectations.

**Comment by mwatson2** [comment]
PR #4012
