### ISSUE TITLE
[eme] Why does playback-temporary-multikey-multisession.js wait for pause, waiting, and stalled?

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3993]
`playback-temporary-multikey-multisession.js` currently has the following `playing` event handler:
```
        function onPlaying(event) {
            consoleWrite("playing");
            waitForEventAndRunStep('pause', _video, onStopped, test);
            waitForEventAndRunStep('waiting', _video, onStopped, test);
            waitForEventAndRunStep('stalled', _video, onStopped, test);
        }
```
`onStopped()` generates a new session if necessary.

Is this supposed to handle the case where playback is blocked waiting for a key? If so:
 * Of those three events, it appears that only `waiting` could possibly be fired as a result (see [Event Summary](https://html.spec.whatwg.org/multipage/embedded-content.html#mediaevents)).
 * Shouldn't this be triggered by the `waitingforkey` event?

**Comment by ddorwin** [comment]
Note that the `onWaitingForKey()` event handler only logs to the console.

**Comment by mwatson2** [comment]
A better question is why this file is in the repo at all ;-)

This was a pre-cursor to the multikey-sequential test (which does indeed only way for `waitingforkey`). This script should have been removed when that was introduced. It is not used by any of the actual tests.

**Comment by mwatson2** [comment]
PR #3997
