### ISSUE TITLE
PresentationRequest_error.html is buggy

### ISSUE THREAD

**Issue by smaug----** [w3c/web-platform-tests#4003]
Per Presentation API 'new PresentationRequest(null);' should not throw. null converts to string "null", following the normal WebIDL rules.

https://github.com/w3c/web-platform-tests/pull/3063

**Comment by tidoust** [comment]
Closing issue as this got fixed in https://github.com/w3c/web-platform-tests/commit/17e59f9772e57f3804555146f231ad101774b917
