### ISSUE TITLE
[eme] Expecting wrong error in update-disallowed-input.js

### ISSUE THREAD

**Issue by jrummell-chromium** [w3c/web-platform-tests#4030]
The test https://w3c-test.org/encrypted-media/clearkey-mp4-update-disallowed-input.html is failing on Chrome 56.0.2895.0 (latest canary build) with:
```
assert_equals: expected "InvalidAccessError" but got "TypeError"
```

The code in scripts/update-disallowed-input.js is checking for 'InvalidAccessError' when it fails, but according to the spec it should be 'TypeError' (http://w3c.github.io/encrypted-media/#dom-mediakeysession-update, step 6.2).

**Comment by jrummell-chromium** [comment]
Same issue with https://w3c-test.org/encrypted-media/clearkey-update-non-ascii-input.html.

**Comment by ddorwin** [comment]
@cpearce, I believe Firefox currently passes these tests and needs to be updated to use `TypeError`.
