### ISSUE TITLE
[eme] Requests to DRMToday license servers are being rejected with 403

### ISSUE THREAD

**Issue by SingingTree** [w3c/web-platform-tests#4031]
I am seeing many test failures occurring due to 403 responses from requests to https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/.

Examples for failing tests:
- http://www.w3c-test.org/encrypted-media/drm-mp4-playback-temporary.html
- http://www.w3c-test.org/encrypted-media/drm-mp4-playback-temporary-setMediaKeys-after-src.html

Has anything changed in how the test code or that endpoint that may result in this behaviour? It appears to be a regression.

**Comment by SingingTree** [comment]
I've just tested this on another machine and it does not appear to be happening on that machine, though it is still taking place on the original machine.

**Comment by mwatson2** [comment]
I think it's due to clock skew. We set our auth token creation time to Date.now() and the server rejects tokens it thinks we're created in the future.

I made a fix for this yesterday, but it may still be in a PR. I will check shortly.

**Comment by SingingTree** [comment]
I'll have a look at the timing information on both machines. I've been logging the network traffic for the request, and see nothing is jumping out at me as inconsistent between the working machine and the failing machine in the requests. Both machines were running against the live code, so it doesn't appear to be an all or nothing bug.

On of the things that I failed to mention and have edited into the first post just now is that this is happening irrespective of browser.

**Comment by mwatson2** [comment]
I think PR #4045 will fix it.

**Comment by SingingTree** [comment]
Cool, thanks for the update.

**Comment by mwatson2** [comment]
I'll take your response as an "Approval" for the PR. Unfortunately, something seems broken with the WPT CI tool, so it will not let me merge ...
