### ISSUE TITLE
Test on presentation.defaultRequest may crash without reporting results

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#4039]
A couple of bugs on the [defaultRequest_success-manual.html](https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/defaultRequest_success-manual.html) test:
1. The test assumes that the `PresentationRequest` constructor exists and will crash with no way to report results if it is run on a user agent that does not support the Presentation API at all. Wrap the call to `new PresentationRequest()` in a `try... catch`?
2. The "Not Supported" button should be disabled (the whole "If your browser does not support" text could perhaps be hidden) as soon as the "connectionavailable" event is detected, or as soon as the button is clicked.

**Comment by tomoyukilabs** [comment]
Thanks for the review. I will fix these bugs after #4035 is merged.

**Comment by louaybassbouss** [comment]
@tomoyukilabs PR #4035 is merged
