### ISSUE TITLE
PresentationConnection_onxxx tests are incorrect

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#4040]
The tests on the `close`, `connect` and `terminate` events are incorrect for different reasons:
1. All 3 tests assume that the events will fire. The test will never fail if they don't (harness timeout is disabled because it is a manual test). There needs to be a call to `step_timeout` somewhere to restart the timeout and ensure the test fails if events are not fired.
2. The test on `connect` calls `close()` right away, which will likely close the connection before it reaches the `connected` state. The test should not call `close()`.
3. The test on `terminate` uses `onconnected` instead of `onconnect` (test files would probably benefit from being renamed with right attribute names by the way)

Also, given that the Presentation API uses Promises, these tests should probably be re-written to use `promise_test` instead of `async_test` to avoid having to write a custom `catch` handler for the Promise returned by `start`.

**Comment by louaybassbouss** [comment]
thx @tidoust, @obstschale can you please submit a PR that fixes this issue

**Comment by obstschale** [comment]
I try to send a PR in few days. I will meet @louaybassbouss to discuss further problems :)

**Comment by obstschale** [comment]
@tidoust you mention in 1. that `step_timeout` should be used. But if I rewrite these test to `promise_test` I think ne `step_*` functions are need, aren't they? Cause in [w3c/testharnees.js](https://github.com/w3c/testharness.js/blob/master/docs/api.md#promise-tests) it states:

> Note that in the promise chain constructed in test_function assertions don't need to wrapped in step or step_func calls.

**Comment by obstschale** [comment]
@tidoust I just made a PR #4222. Please give me some feedback. The test passes now but I am unsure if it is correct and whether I missed something :)

I will provide fixes for the other tests if I received feedback

**Comment by tidoust** [comment]
@obstschale `step_timeout` is not a _wrapping_ function for the note you cite, and has nothing to do with the use of `promise_test` either.

By default the test harness times out after a few seconds. This is extremely important for automated tests, as some of them could otherwise just hang forever without reporting any result.

Our test is not automated though. A user action is required to start it. The user is not a machine. We cannot let the test harness time out while the user reads the instructions and performs the action. This is why there is a call to `setup({explicit_timeout: true})` at the beginning of the test which disables the timeout.

Now, once the user has selected a display, the test can be fully automated again. This is good because it means we don't need to ask the user about the test result (if the test is run through the test runner, the test result will be automatically reported).

To make that happen, we need to ensure that the test harness reports a result no matter what, and in particular that the test cannot ever hang. This is what a call to `step_timeout` would give: it would re-enable the test harness timeout once we're done with user interaction.

For a concrete and similar example, see https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_success-manual.html#L58

For what it's worth, the note in the test harness documentation, which can perhaps be clarified, means that you don't need to do:

```js
promise_test(t.step_func(function () {
  return foo.then(t.step_func(function () {
    assert_true(true);
  }));
}));
```

You can simply write:

```js
promise_test(function () {
  return foo.then(function () {
    assert_true(true);
  });
});
```

**Comment by obstschale** [comment]
That makes sense. Thx for explaining. Although the whole topic is still confusing ^^ But I'm learning :)

**Comment by obstschale** [comment]
I guess with #4256 and #4319 this issue is complete, isn't it?

**Comment by obstschale** [comment]
- [x] 1. Add `step_timeout` to tests (#4319)
- [x] 2. remove `close` call in `connect` test (#4256)
- [x] 3. Use `onconnect` instead of `onconnected` in `terminate` class
- [ ] 4. Rename Tests accordingly
- [ ] 5. Use `promise_test` instead of `async_test`

**Comment by obstschale** [comment]
@tidoust In #4256 there was a renaming issue mentioned by @tomoyukilabs 

> These files should be renamed to PresentationConnection_onconnect-manual.html and PresentationConnection_onterminate-manual.html.

Should I rename the files in a new PR?

**Comment by tomoyukilabs** [comment]
or, I can submit a PR to change appropriate file names after your PR.

**Comment by tomoyukilabs** [comment]
@obstschale After your PR #4330 is merged, shall I submit a PR to rename the files?

**Comment by obstschale** [comment]
Thx but I will do it after my PR is merged. But I wait for @tidoust :)

**Comment by tomoyukilabs** [comment]
Thanks, @obstschale!
