### ISSUE TITLE
reconnectToPresentation_success-manual test is incorrect

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#4041]
The [reconnect to a presentation](https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/reconnectToPresentation_success-manual.html) test needs to be updated:
1. It should not use `localStorage`: it may not be supported and there does not seem to be any need for it (unless the goal is to test reconnection after a refresh of the page, which could be the purpose of another test)
2. Most of the code gets run outside any `promise_test` or `async_test` container, which means the test will just silently crash e.g. if the presentation connection cannot be established
3. The two buttons should not appear at the same time.

Also, since reconnection does not require a user gesture, I wonder if the test should not be re-written to attempt the reconnection automatically: it could call `close()`, wait for the `close` event and call `reconnect` at that point. That would slightly improve the automation of the test, as it would avoid requiring two user inputs.

**Comment by louaybassbouss** [comment]
Thx @tidoust, @obstschale  can you please submit a PR that fixes this issue

**Comment by louaybassbouss** [comment]
@tidoust PR #4172 should fix this issue. Feel free to close after the PR is merged.
@obstschale please focus on other tests
