### ISSUE TITLE
reconnectToPresentation_error-manual.html should catch the promise reject

### ISSUE THREAD

**Issue by schien** [w3c/web-platform-tests#4048]
According to the spec reconnect to an unknown presentation Id should get a promise reject (NotFoundError), which we should add in https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/reconnectToPresentation_error-manual.html#L26

**Comment by louaybassbouss** [comment]
Thx @schien feel free to submit a PR that fixes this issue

**Comment by louaybassbouss** [comment]
@schien I just submitted PR #4172 that fixes this issue and another issue at same time. Feel free to close this issues after the PR is reviewed and merged.
