### ISSUE TITLE
[presentation-api] Provide a invalid URL that universally applies to all browsers

### ISSUE THREAD

**Issue by schien** [w3c/web-platform-tests#4051]
In https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationRequest_error.html, ":invalid" can be interpreted as a relative URL. We can use "http://", which prevents browser to interpreted as a relative URL and is invalid to all browsers.

**Comment by schien** [comment]
pull request provided: https://github.com/w3c/web-platform-tests/pull/4052

**Comment by gsnedders** [comment]
Fixed in #4155, AIUI. Reopen if wrong.
