### ISSUE TITLE
[eme] playback-temporary-events.js: Expected order of resolving close-related promises does not match the spec

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#4058]
`playback-temporary-events.js`, which is used in `*-mp4-playback-temporary-events.html`, checks the order of resolution of the `closed` promise attribute and the promise returned by the `close()` call.

It currently expects the latter (logged as `'closed'`) to be resolved before the former (logged as `'closed-promise'`).

I believe the spec says the order should be the opposite. The [close()](https://w3c.github.io/encrypted-media/#close) algorithm queues a task to:
 1. Run the [Session Closed](https://w3c.github.io/encrypted-media/#session-closed) algorithm on the session.
 1. Resolve the returned promise.

That first step synchronously resolves the `closed` attribute promise. Thus, the promises are resolved in series. It would seem that they should be resolved in order.

I don't recall whether such ordering is guaranteed. If not, we should probably allow both orders. It's also possible that the test and harness (e.g. `test.step_func()`) are interfering.

Currently, Chrome and Firefox pass both `*-mp4-playback-temporary-events.html` test, meaning they resolve the returned promise before executing all steps of the [Session Closed](https://w3c.github.io/encrypted-media/#session-closed) algorithm. Implementing the current spec would require user agents to wait for the "cdm to close the session associated with session" then execute the Session Closed algorithm before resolving the returned promise.
@cpearce @jdsmith3000

P.S.
The naming of these events is confusing. We should rename them to `'closed-attributed-resolved'` and `'close-returned-promise-resolved'` or similar.

**Comment by mwatson2** [comment]
I agree the test is currently incorrect. I will make a PR for this.
