### ISSUE TITLE
Expired license test's timeout too restrictive, races

### ISSUE THREAD

**Issue by SingingTree** [w3c/web-platform-tests#4079]
encrypted-media/drm-mp4-playback-temporary-expired.html uses the normal test time limit. However, the test has a number of waits in it, and when you get network latency on top of these waits it's possible to race on if the tests passes or times out.

I see fairly consistent failures when running against the live tests from NZ, and I'm able to reproduce this by serving locally, but introducing lag into the requests. With an extra latency of 1100 milliseconds on the video request locally I can reliably race with both ok and timeout results.

This is remedied if the test instead you the long timeout. I will submit a PR shortly with the change made.

**Comment by ddorwin** [comment]
Fixed by #4080.
