### ISSUE TITLE
[eme] Unique-origin tests failing due to recent change in testharness.js

### ISSUE THREAD

**Issue by jrummell-chromium** [w3c/web-platform-tests#4106]
A recent change to the testharness.js [1] requires that promise_tests actually return a promise. Test /encrypted-media/clearkey-mp4-unique-origin.html (and the drm- version) now fail as the test in scripts/unique-origin.js does not return a promise.

[1] https://github.com/w3c/testharness.js/commit/873f9680aff66553f84d38f21a038c4534cc2789

**Comment by ddorwin** [comment]
Fixed by #4119.
