### ISSUE TITLE
MANIFEST.json contains non-test files

### ISSUE THREAD

**Issue by tkent-google** [w3c/web-platform-tests#4137]
1. Checkout web-platform-tests
2. cd web-platform-tests
3. ./manifest

Expected:
MANIFEST.json doesn't contain the following entries because they are not tests.

      {
        "path": "uievents/keyboard/key-manual.css",
        "url": "/uievents/keyboard/key-manual.css"
      },
      {
        "path": "uievents/keyboard/key-manual.js",
        "url": "/uievents/keyboard/key-manual.js"
      },

Actual:
MANIFEST.json contains them.

Note:
I'm not sure we should rename them, or we should fix 'manifest' command.

**Comment by gsnedders** [comment]
@jgraham?

**Comment by sideshowbarker** [comment]
The manifest should be our accurate and complete record of just the actual test files. Otherwise what other record do we have? So if non-tests are ending up in the manifest, that should be considered a bug that we need to fix.

**Comment by gsnedders** [comment]
Yeah, the question is mostly whether we should be requiring nothing be called `*-manual.*` or changing the manifest generation.

**Comment by foolip** [comment]
For context: https://codereview.chromium.org/2464713002/diff/120001/third_party/WebKit/LayoutTests/TestExpectations

In other words, we have to skip these "tests" in Chromium because of this bug.

**Comment by jgraham** [comment]
Those files should be renamed. That's our system for identifying manual tests.
