### ISSUE TITLE
[presentation-api] Test coverage for start() event order

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/web-platform-tests#4168]
The Presentation API controller tests have coverage for `onconnectionavailable`, `onconnect`, `PresentationConnection.state`, and resolution of the Promise from `start()` in isolation, but I don't see a test case that makes sure these event loops happen in a specific order.  

This issue tracks the work to add a test case to check the order of the following:
1. Promise from `start()` resolves
2. `connectionavailable` fires
3. state is `connecting`
4. `connect` fires
5. state is `connected`

**Comment by tomoyukilabs** [comment]
According to [Establishing a presentation connection](https://w3c.github.io/presentation-api/#establishing-a-presentation-connection), should the steps 4. and 5. be invoked in reverse order?

> If connection completes successfully, queue a task to run the following steps:
1. Set the presentation connection state of presentationConnection to `connected`.
2. Fire a simple event named `connect` at presentationConnection.

Anyway, I will update startNewPresentation_success-manual.html to make it able to check the event order, and then PR after #4035 is merged.

**Comment by tomoyukilabs** [comment]
> According to Establishing a presentation connection, should the steps 4. and 5. be invoked in reverse order?

Sorry, I've understood now. We can check the step "state is `connected`" just after the step "`connect` fires" during the test.

**Comment by louaybassbouss** [comment]
@tomoyukilabs  PR #4035 is merged please feel free to work on this issue

**Comment by tomoyukilabs** [comment]
@louaybassbouss Thanks! I submitted PR for this issue.

**Comment by tidoust** [comment]
@mfoltzgoogle New version of the `start` test prepared by @tomoyukilabs now checks the order of events. Please have a look and re-open this issue if needed:
https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_success-manual.html
