### ISSUE TITLE
wpt-pr-bot text is confusing

### ISSUE THREAD

**Issue by RByers** [w3c/web-platform-tests#4228]
wpt-pr-bot adds text to PRs like: "Reviewers for this pull request are: @Rbyers".  People [tend to assume](https://github.com/w3c/web-platform-tests/pull/2163#issuecomment-260952922) this means the MUST wait for someone from that list to approve the PR, increasing the frustration at the difficulty of getting WPT PRs landed.  I've [tried to clarify this in the README](https://github.com/w3c/web-platform-tests/pull/4227) but people likely won't notice.  Can we update the text generated by wpt-pr-bot to make this more clear?

**Comment by RByers** [comment]
I searched around for the code for wpt-pr-bot but can't seem to find it anywhere.

**Comment by RByers** [comment]
Found [the announcement](https://lists.w3.org/Archives/Public/public-test-infra/2016JanMar/0001.html).  @tobie WDYT?  Arguably even the file name "OWNERS" is misleading (could be "WATCHLIST" or something).

**Comment by tobie** [comment]
File is here: https://github.com/tobie/ganesh/blob/master/lib/reviewers.js

Yeah. Text sure needs fixing. Suggestion/PR welcome. If not I'll look at it once I get back home.

**Comment by tobie** [comment]
Quick PR. LMK what you think or if you have another suggestion.

**Comment by tobie** [comment]
Note I'm happy to change the OWNERS file name to something else if you prefer. That'll need a PR here first, though, and a bit of sync.

**Comment by RByers** [comment]
That helps, thank you!  What about just adding a link to https://github.com/w3c/web-platform-tests/blob/master/README.md#test-review from the bot text - so it's obvious where to look for details / how to add yourself to the list of people to be notified?

IMHO it's probably not worth the hassle at this point to change the file name - maybe wait and see if there continues to be confusion?

**Comment by tobie** [comment]
https://github.com/w3c/web-platform-tests/pull/4235#issuecomment-262081975

**Comment by tobie** [comment]
Closing. LMK if you end-up changing the file names so I can update the bot accordingly.
