### ISSUE TITLE
Add a cleanup step to terminate presentations

### ISSUE THREAD

**Issue by tidoust** [w3c/web-platform-tests#4258]
Given that presentations may persist beyond the controlling browsing context, tests should always terminate presentations that they create (even when the test fails), typically using the [`add_cleanup` method](https://github.com/w3c/testharness.js/blob/master/docs/api.md#cleanup).

Examples of Presentation API tests that need this:
https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_success-manual.html
https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/reconnectToPresentation_success-manual.html

**Comment by obstschale** [comment]
I have a question about `add_cleanup`: Is this function called after a test to reset everything? So e.g. in [`PresenentationConnection_onconnected-manuel`](https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/PresentationConnection_onconnected-manual.html#L23) the button is disabled. Should `add_cleanup` enable it again so a new test can run without reloading the page?

**Comment by tidoust** [comment]
> Is this function called after a test to reset everything

It depends on what you mean by "reset". It is called after a test to free resources that could persist beyond the test itself. I don't think it is meant to reset a manual test so that it can be run again without reloading the page.

> Should add_cleanup enable it again so a new test can run without reloading the page?

Actually, this would be hard to do in our case because our tests are not entirely manual: they still use the test harness and you cannot easily reset the test harness without reloading the page.

**Comment by obstschale** [comment]
Ok, if I understand you correctly, that means a cleanup **will not** reset the test, so I can run the same test again without reloading the page (That includes: enable button, which is disabled; freeing bound resources, which are set during a test) but rather make sure that no resources, which are set during a test, persist and cause problems during a second test after a page reload.

**Comment by tidoust** [comment]
That looks correct.

**Comment by obstschale** [comment]
:+1: I try to find out how to do this.
