### ISSUE TITLE
LICENSE file should contain actual legalese instead of just pointing to a separate webpage

### ISSUE THREAD

**Issue by cvrebert** [w3c/web-platform-tests#4295]
Equivalent csswg-test issue with additional context: https://github.com/w3c/csswg-test/pull/1091

I've been told that the `LICENSE` file should contain actual copyright & license text before I can send additional PRs. Currently, [the file](https://github.com/w3c/web-platform-tests/blob/master/LICENSE) just contains a link to http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html

A license is an agreement between a project maintainer and downstream. It should be spelled out and concrete--not linked to something that can be changed and which is separate from the code.
You wouldn't have a lease agreement on a web page where the terms can be changed without notice.

**Comment by sideshowbarker** [comment]
Resolved by https://github.com/w3c/web-platform-tests/commit/e4860d02963ec4922de464b508eb1cf1c1aef27d

https://github.com/w3c/web-platform-tests/blob/master/LICENSE.md
