### ISSUE TITLE
commandDisabled should be removed/replaced in <dialog> tests

### ISSUE THREAD

**Issue by nt1m** [w3c/web-platform-tests#4315]
https://github.com/w3c/web-platform-tests/blob/56ea52b8668ceee63ec196c59dd11ad7797e4f0d/html/semantics/interactive-elements/the-dialog-element/dialog-showModal.html#L58

The <dialog> spec just says the document should be inert, which means no interaction should be allowed. There's nothing mentioned about commandDisabled ?

**Comment by nt1m** [comment]
Looks like it's part of HTML4 (https://html-differences.whatwg.org/#htmlelement-extensions), but I see it no where in the HTML5 spec.

**Comment by nt1m** [comment]
Looks like `commandDisabled` was removed here from the HTML spec: https://github.com/whatwg/html/pull/244

What should the replacement within the test be ? `disabled` ?

**Comment by domenic** [comment]
I would just remove that line.

**Comment by nt1m** [comment]
@domenic Thanks. Going to submit a PR

**Comment by nt1m** [comment]
@domenic Looks like it might not make sense to remove it here: https://github.com/w3c/web-platform-tests/blob/56ea52b8668ceee63ec196c59dd11ad7797e4f0d/html/semantics/interactive-elements/the-dialog-element/dialog-showModal.html#L100
Otherwise, that test is testing nothing useful.

**Comment by domenic** [comment]
I don't believe there is any such replacement.

**Comment by nt1m** [comment]
@domenic: should I remove the test: "when opening multiple dialogs, only the newest one is non-inert" altogether then ?

**Comment by domenic** [comment]
I guess so. I don't know of any way to test inertness directly. Maybe someone else does though...
