### ISSUE TITLE
Some question about pause-remove-from-document-networkState.html

### ISSUE THREAD

**Issue by ChiahungTai** [w3c/web-platform-tests#4318]
I have one question about pause-remove-from-document-networkState.html.
Per spec:

> When  a media element is removed from a Document, the user agent must run the following steps:
> 
> Asynchronously await a stable state, allowing the task that removed the media element from the Document to continue. The synchronous section consists of all the remaining steps of this algorithm. (Steps in the synchronous section are marked with ⌛.)
> 
> ⌛ If the media element is in a Document, abort these steps.
> 
> ⌛ If the media element's networkState attribute has the value NETWORK_EMPTY, abort these steps.
> 
> ⌛ Pause the media element.

Is that means when the networkState is NETWORK_EMPTY, then the media element should not be paused?

If that is Yes, why this test still wait for the pause event?
`    v.onpause = t.step_func(function() { t.done(); });
`

This test case is fail on Chrome, Firefox and Edge. Is this test case correct?

**Comment by smaug----** [comment]
I don't see " If the media element's networkState attribute has the value NETWORK_EMPTY, abort these steps." in the HTML spec. Are you perhaps looking at W3C HTML5 spec, since that has the NETWORK_EMPTY? At least Gecko isn't trying to implement HTML5 but HTML spec https://html.spec.whatwg.org/

**Comment by ChiahungTai** [comment]
I am using this link. 
https://www.w3.org/TR/html5/embedded-content-0.html#playing-the-media-resource

**Comment by ChiahungTai** [comment]
smaug, you are right. I can close this issue now.
