### ISSUE TITLE
Redundant messages from logger calls in check_stability.py

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#4323]
Every `logger` call in `check_stability.py`—e.g., `logger.debug(…)`, `logger.info(…)`—seems to cause *two* messages to be emitted instead of just one; for example:

```
DEBUG:check_stability:Setting up GitHub logging
DEBUG:check_stability:Setting up GitHub logging
travis_fold:start:browser_setup
INFO:check_stability:# Firefox #
INFO:check_stability:# Firefox #
…
DEBUG:check_stability:pip install -r w3c/wptrunner/requirements_firefox.txt
DEBUG:check_stability:pip install -r w3c/wptrunner/requirements_firefox.txt
…
etc. etc.
```

**Comment by jugglinmike** [comment]
This seems to be a problem with the way the `wpt-tools` project is configured. I've opened https://github.com/w3c/wpt-tools/pull/155 to address the issue.
