### ISSUE TITLE
XMLHttpRequest url encoding question

### ISSUE THREAD

**Issue by mingchou** [w3c/web-platform-tests#4345]
XMLHttpRequest/open-url-encoding.htm specifies the document charset is windows-1252. The first test passes \u00DF as the query string and expect it's encoded as %C3%9F. Wondering why \u00DF isn't encoded with the document's charset 'windows-1252' as %DF?

Tested with Chrome Canary57.0.2950.0 and Edge38.14393.0.0, both of them encode it as %DF

**Comment by annevk** [comment]
The standard doesn't invoke the URL parser with an override and therefore it should use UTF-8: https://xhr.spec.whatwg.org/#dom-xmlhttprequest-open.
