### ISSUE TITLE
2dcontext tests for drawing images don't guarantee that the image is loaded before finishing

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#4508]
drawimage_html_image_1.html creates an image element, sets the src, and adds an onload handler, but the image is not in the document and the test doesn't use reftest-wait. There is no synchronization guaranteeing that the image's onload handler will run before the window load event in this case.

**Comment by EdgarChen** [comment]
It seems #1882 fix this.

**Comment by jdm** [comment]
Nope - the images are still never added to the document, so there is no synchronization between when the img.onload code runs in relation to when the reftest is considered complete.

**Comment by jdm** [comment]
I am modifying the tests in https://github.com/servo/servo/pull/14962/commits/ec05015b389219b487e52879f09a26103088bdf4 to address this.

**Comment by jdm** [comment]
This is incorrect. Detached images block the document load event, so it should be working just fine.
