### ISSUE TITLE
force_timeout doesn't appear to work

### ISSUE THREAD

**Issue by jakearchibald** [w3c/web-platform-tests#4519]
https://github.com/w3c/web-platform-tests/blob/master/notifications/constructor-basic.html doesn't seem to timeout instantly.

**Comment by annevk** [comment]
@jgraham?

**Comment by jugglinmike** [comment]
The reported test is a bit hinky: we don't currently enforce time restrictions on synchronous tests, so I'm not sure it's appropriate for them to artificially time out. But then again, I'm not sold on the idea of any sort of artificial time out. It seems to me that "failure" is always a more accurate/transparent way to communicate the situation.

That said, there is definitely a bug here, so [I've submitted a patch to correct it](https://github.com/w3c/web-platform-tests/issues/6143).

**Comment by foolip** [comment]
Adding the priority:roadmap label since a PR exists and needs review. If there is no traction, please randomly assign someone working on ecosystem infra.

**Comment by leonhsl** [comment]
As @jugglinmike created the fix PR, set as owner of this issue :-)

**Comment by foolip** [comment]
OK, so https://github.com/w3c/web-platform-tests/pull/6143 was superseded by https://github.com/w3c/web-platform-tests/pull/8504 and is merged. And now http://w3c-test.org/notifications/constructor-basic.html does fail immediately with NOT RUN "You must allow notifications for this origin before running this test". Awesome, last I tried there was no way to achieve this, I didn't even know this is the "feature" I was missing.

Thanks @jugglinmike and @jgraham, closing this now.
