### ISSUE TITLE
XMLHttpRequest/send-authentication-cors-basic-setrequestheader.htm is a bogus test

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-platform-tests#4547]
The test does a GET to corsenabled.py and expects `.responseText` to contain something interesting (like the things it put in the x-user and x-pass headers).

But corsenabled.py always returns "Test" as the response body, so there is no way this test can pass.

I have no idea whether the script (shared with other tests, note!) or the test is wrong.

**Comment by jdm** [comment]
I believe you are looking at the wrong corsenabled.py - the test requests auth2/corsenabled.py instead, but then hits #3429.

**Comment by bzbarsky** [comment]
Ah, good catch on the wrong corsenabled.py.  But good to know the test is in fact still broken... I could see nothing wrong on the Firefox end here, certainly.

**Comment by annevk** [comment]
I wrote a fix for both issues, seems the test ends up passing everywhere.
