### ISSUE TITLE
Tests relying on larger viewports

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#4619]
Currently, the docs say we use 800x600 screenshots for reftests, and wptrunner uses 600x600. We also have a `<meta name='viewport-size'>` that's totally undocumented and that only works for Servo per https://github.com/w3c/wptrunner/issues/166.

The following tests give different results at 800x600 v. 600x600 (the expected results are those at the larger size):

FAIL /html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_start_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u002E_LF_u05D0.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_white-space_nowrap.html
FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_white-space_nowrap.html
FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/default_styles/inherit_as_default_value_inherits_values_from_media_element.html

Comparing with 1600x1200 v. 600x600 (same again; 1600x1200 was the size used by Presto's CI system for the curious):

FAIL /html/dom/elements/global-attributes/dir_auto-contained-L.html
FAIL /html/rendering/replaced-elements/embedded-content-rendering-rules/canvas-fallback.html
FAIL /html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/2_tracks.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_end.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_middle.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_middle_position_50.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_middle_position_gt_50.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_middle_position_lt_50.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_middle_position_lt_50_size_gt_maximum_size.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_start.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/align_start_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/basic.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/bidi_ruby.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u002E_LF_u05D0.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u002E_u2028_u05D0.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u002E_u2029_u05D0.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u0041_first.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u05D0_first.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u0628_first.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/bidi/u06E9_no_strong_dir.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/decode_escaped_entities.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/dom_override_cue_align_position_line_size.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/dom_override_cue_align_position_line_size_while_paused.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/dom_override_cue_text.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/dom_override_cue_text_while_paused.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/dom_override_remove_cue_while_paused.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/evil/single_quote.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/evil/size_90.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/evil/size_99.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/background_shorthand_css_relative_url.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/color_hex.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/color_hsla.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/color_rgba.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/cue_selector_single_colon.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_overline.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_overline_underline_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_underline.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_normal_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_nowrap_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_pre-line_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_pre.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_box.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_shorthand_css_relative_url.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_animation_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_color.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_font_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_font_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_namespace.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_timestamp_future.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_timestamp_past.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_transition_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_with_class.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_with_class_object_specific_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_animation_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_color.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_font_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_font_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_namespace.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_timestamp_future.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_timestamp_past.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_transition_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_with_class.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_with_class_object_specific_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/color_hex.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/color_hsla.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/color_rgba.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/cue_func_selector_single_colon.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/id_color.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_animation_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_color.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_font_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_font_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_namespace.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_timestamp_future.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_timestamp_past.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_transition_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_with_class.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_with_class_object_specific_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/not_allowed_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/not_root_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/root_namespace.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/root_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_overline.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_overline_underline_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_underline.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/type_selector_root.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_animation_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_color.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_font_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_font_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_namespace.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_timestamp_future.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_timestamp_past.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_transition_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_with_class.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_with_class_object_specific_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_animation_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_background_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_background_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_color.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_font_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_font_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_namespace.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_outline_properties.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_outline_shorthand.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_text-decoration_line-through.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_text-shadow.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_timestamp_future.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_timestamp_past.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_transition_with_timestamp.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_voice_attribute.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_with_class.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_with_class_object_specific_selector.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_normal_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_nowrap_wrapped.html
PASS expected FAIL /webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_pre-line_wrapped.html

Notably, almost all of the WebVTT tests rely on a 1280x720 video (within the normal body margins), hence will need a viewport larger than that.

**Comment by gsnedders** [comment]
CC @zcorpan given you wrote most of the WebVTT tests.

**Comment by zcorpan** [comment]
See https://github.com/w3c/web-platform-tests/pull/4385

**Comment by gsnedders** [comment]
Also #4383

**Comment by zcorpan** [comment]
Trimming webvtt from OP:

The following tests give different results at 800x600 v. 600x600 (the expected results are those at the larger size):

FAIL /html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html

Comparing with 1600x1200 v. 600x600 (same again; 1600x1200 was the size used by Presto's CI system for the curious):

FAIL /html/dom/elements/global-attributes/dir_auto-contained-L.html
FAIL /html/rendering/replaced-elements/embedded-content-rendering-rules/canvas-fallback.html
FAIL /html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html

**Comment by zcorpan** [comment]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html has different rendering because the instruction wraps. But it wraps in the same way in the test as in the ref if they're both the same viewport size, right? So this is not a problem?

**Comment by zcorpan** [comment]
/html/rendering/replaced-elements/embedded-content-rendering-rules/canvas-fallback.html

This gets a scrollbar in 600x600, but not the ref. That should be fixed.

**Comment by gsnedders** [comment]
Moved to #5403 for better tracking.
