### ISSUE TITLE
Possible problem with `idbcursor-continuePrimaryKey-exceptions.htm` test

### ISSUE THREAD

**Issue by brettz9** [w3c/web-platform-tests#4632]
Related to `IndexedDB/idbcursor-continuePrimaryKey-exceptions.htm`...

There are calls to `assert_class_string`, e.g.:

```js
assert_class_string(cursor, 'IDBCursorWithValue',
                'result should be a cursor');
```

This function's definition in `testharness.js` is as follows:

```js
    function assert_class_string(object, class_string, description) {
        assert_equals({}.toString.call(object), "[object " + class_string + "]",
                      description);
    }
```

While `{}.toString.call(object)` distinguishes between objects and arrays, it does not appear to work with custom objects as it just converts them to `[object Object]` (at least in Chrome--but since it is calling `toString` on a generic object instead of the object's own `toString`, I'd expect this to be the case universally). So, I'd expect this function to never return the expected `'[object IDBCursorWithValue]'` (unless perhaps there is some magic in native objects I'm not aware of which lets this happen).

I don't know if this is why the Chrome tests for this file are failing, but in our own Node implementation of IndexedDB (as is the case if run in the Chrome JS console), the following type of approach (on the prototype) therefore doesn't work (at least without overriding `Object.prototype.toString`):

```js
function IDBCursor () {}
IDBCursor.prototype.toString = function () {return '[object IDBCursor]'};
({}.toString.call(new IDBCursor())) // Gives "[object Object]"
```

I only see one other IndexedDB test using this function, and it is expecting `Array`, which is one case which does work.

**Comment by brettz9** [comment]
And sorry, not sure if you would like me flagging you as a matter of course on IndexedDB issues here, @inexorabletash .

**Comment by inexorabletash** [comment]
> While {}.toString.call(object) distinguishes between objects and arrays, it does not appear to work with custom objects as it just converts them to [object Object] 

`{}.toString.call(x)` is effectively the same as invoking `Object.prototype.toString.call(x)` which returns what has historically been called the "class name" or "branding" of the target. In ES6 this is exposed as a hook via the @@toStringTag symbol:

```js
Object.prototype.toString.call({ [Symbol.toStringTag]: 'Xyz' }); // [object Xyz]
```

If you invoke this on platform objects in any browser you get the appropriate branding:

```js
Object.prototype.toString.call(indexedDB); // [object IDBFactory]
```

> (at least in Chrome--but since it is calling toString on a generic object instead of the object's own toString, I'd expect this to be the case universally).

It's not calling it on a generic object; it's grabbing the `toString` method from a generic object (which is therefore the same as grabbing `Object.prototype.toString`) and invoking `call` on the function, passing in a specific target. This is standard ECMAScript for retrieving the "class string"/"branding".

> So, I'd expect this function to never return the expected '[object IDBCursorWithValue]' (unless perhaps there is some magic in native objects I'm not aware of which lets this happen).

https://heycam.github.io/webidl/#es-platform-objects _"The class string of a platform object that implements one or more interfaces must be the identifier of the primary interface of the platform object."_

https://heycam.github.io/webidl/#dfn-class-string _"Some objects described in this section are defined to have a class string, which is the string to include in the string returned from Object.prototype.toString. If an object has a class string, then the object must, at the time it is created, have a property whose name is the @@toStringTag symbol and whose value is the specified string."_

> ...in our own Node implementation of IndexedDB...

You must not be implementing those clauses of WebIDL.

**Comment by brettz9** [comment]
Sorry, I had meant "calling a general object's `toString`"

Awesome info, thanks! And I see from the [WebIDL section on identifiers](https://heycam.github.io/webidl/#dfn-identifier) that the identifier can be found in `interface XYZ`

Looking to implement now...
