### ISSUE TITLE
stability log sometimes swamped with commit messages

### ISSUE THREAD

**Issue by RByers** [w3c/web-platform-tests#4635]
Why can't I see the details of what tests passed vs. failed in [this log](https://travis-ci.org/w3c/web-platform-tests/jobs/193516170)?
/cc @bobholt

**Comment by bobholt** [comment]
@RByers: Travis only shows the first 10000 lines in the UI. There is a link to the [raw log](https://api.travis-ci.org/jobs/193516170/log) at the bottom of that page. It's worth noting that the comment bot I'm working on parses the full raw log, not the UI presentation

**Comment by RByers** [comment]
Yeah, I saw the raw log option.  But it seemed like there was a lot of log spam that could perhaps be silenced so that the useful log output occurred within the 10,000 limit?  But if your bot is going to replace / solve all this anyway then there's certainly no point worrying about the current behavior :-)

**Comment by bobholt** [comment]
Ah, I see. It looks like it would be an easy change to make in `check_stability.py` - remove the line outputting the commits in the PR to the log. The question is does anybody ever find that list valuable when it's shorter?

**Comment by sideshowbarker** [comment]
> The question is does anybody ever find that list valuable when it's shorter?

Hard to measure whether anybody does or not, but one way to find out is to remove them and see if anybody complains. So I reckon maybe we should just do that. It’s almost certainly at least not going to break anything for anybody.
