### ISSUE TITLE
urltestdata.json port segment uncertainty

### ISSUE THREAD

**Issue by sakjur** [w3c/web-platform-tests#4644]
There's a discrepancy between this repository and WebKit's test suite for the port segment of `http://f:00000000000000000000080/c`.

In [url/urltestdata.json:223](https://github.com/w3c/web-platform-tests/blob/907a506/url/urltestdata.json#L223) the port segment is specified as empty whereas in the [segments.html:23](http://trac.webkit.org/browser/trunk/LayoutTests/fast/url/segments.html?rev=211299#L23) from WebKit's test suite it is specified as being 0.

Is this caused by an err in either test suite or a result of WebKit not complying with the W3C standard for that URL?

**Comment by domenic** [comment]
@annevk ?

**Comment by annevk** [comment]
@sakjur it's a bug in WebKit, see https://url.spec.whatwg.org/#port-state. (There's no W3C standard for URLs.)
