### ISSUE TITLE
Put basic test for DOMTokenList in dom/lists/

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [w3c/web-platform-tests#4703]
When I'm looking tests for `DOMTokenList` then I intuitively look in the `dom/lists/` but it contains only a part of them, so once again I have spend some time to find others. Looks like most of them are placed in `dom/nodes/Element-classlist.html`, but `DOMTokenList` is used not only by the `classList`.

So maybe move this test to `dom/lists/`? Create separate files for all methods (plus additional files testing specific behavior if necessary) or just use one file covers all methods and other cases (but with additional comments and separators between them because now whe have a block of text and it's hard to analyze anything. If moving is not an option then please add some info in `dom/lists/` where we can find other test for `DOMTokenList`.

**Comment by annevk** [comment]
I proposed adding a simple README. Moving seemed a little weird since then folks might wonder where Element.prototype.classList is defined.
