### ISSUE TITLE
Test the FontFaceSetLoadEvent constructor

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#4822]
See https://github.com/w3c/csswg-drafts/issues/810 for discussion and existing tests in Blink.

**Comment by gsnedders** [comment]
https://codereview.chromium.org/2579513005/ is where tests landed in Blink, in `third_party/WebKit/LayoutTests/fast/css/fontfacesetloadevent-constructor.html `.

**Comment by foolip** [comment]
Now that we've merged, where should this test be moved?

**Comment by gsnedders** [comment]
My understanding, from what @astearns had said before, is new test suites should go at the top level.

**Comment by foolip** [comment]
OK, I'll put it under a new css-font-loading/

**Comment by foolip** [comment]
Upstreaming in https://codereview.chromium.org/2841903002
