### ISSUE TITLE
Documentation: web-platform-tests.org lacks HTTPS and HSTS

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#4924]
Our documentation should be hosted reliably.

**Comment by foolip** [comment]
@gsnedders, this is unfixable while using CNAME magic and being hosted by GitHub pages, right?

**Comment by gsnedders** [comment]
Current status: 

>  Enforce HTTPS — Not yet available for your site because the certificate has not finished being issued (web-platform-tests.org)

**Comment by foolip** [comment]
Does that mean that it should now be possible, but isn't working?

**Comment by jgraham** [comment]
I changed the IP addresses in the DNS record, and gsnedders did the other bits; this works now.

**Comment by gsnedders** [comment]
We don't have HSTS, but oh well.

**Comment by annevk** [comment]
Did we update all links?
