### ISSUE TITLE
data: URLs in webvtt tests

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#4940]
Some webvtt tests use data: URLs, like webvtt/api/VTTCue/align.html

```
     t.src = 'data:text/vtt,'+encodeURIComponent('WEBVTT\n\n00:00:00.000 --> 00:00:00.001\ntest\n\n'+
                                                 '00:00:00.000 --> 00:00:00.001 align:start\ntest\n\n'+
                                                 '00:00:00.000 --> 00:00:00.001 align:center\ntest\n\n'+
                                                 '00:00:00.000 --> 00:00:00.001 align:end\ntest');
```

I think this is not supposed to work (anymore), since data: URLs get an opaque origin, and do not have CORS headers, cannot be same-origin with the page. I did not manage to step through the spec's steps right now though... @annevk can you help?

Anyway, what we should do is replace the data: URLs with actual files, and separately test that `data:` URL results in `error` being fired (with and without `crossorigin` attribute on `video`).

cc @BenjaminSchaaf

**Comment by annevk** [comment]
No, this should still work. Step 12 (number likely to change over time) of https://fetch.spec.whatwg.org/#concept-main-fetch makes all data URLs same-origin, but also points out that we override that when the data URL contents end up creating an environment.

**Comment by zcorpan** [comment]
Huh! Good thing I asked 😊 Thanks.

Since the cited test seems to get an `error` event in Chromium, I still think it could be good to change to use files, and test `data:` separately... but then expect to succeed.

**Comment by annevk** [comment]
Or Chrome could just fix its bug...

**Comment by zcorpan** [comment]
https://github.com/w3c/web-platform-tests/pull/6994
https://github.com/w3c/web-platform-tests/pull/7008

https://bugs.chromium.org/p/chromium/issues/detail?id=758906
