### ISSUE TITLE
UnicodeDecodeError in environment mangling

### ISSUE THREAD

**Issue by mnot** [w3c/web-platform-tests#4951]
`/tools/sslutils/openssl.py`line 70 does:

> env[k.encode("utf8")] = v.encode("utf8")

This will cause a `UnicodeDecodeError` when `PS1` or `PS2` has certain escape sequences in them. 

This deals with it:

>            try:
>                env[k.encode("utf8")] = v.encode("utf8")
>            except UnicodeDecodeError:
>                pass

(although you could also just set the value to `v`)

**Comment by lyzadanger** [comment]
See also: https://github.com/w3c/wpt-tools/issues/163

**Comment by mnot** [comment]
Was fixed in wpt-tools.
