### ISSUE TITLE
URL test data: expected query and fragment should have no leading ?/#

### ISSUE THREAD

**Issue by smola** [w3c/web-platform-tests#499]
In `url/urltestdata.txt`, expected query and fragment always have a leading '?' and '#'. Example:

http://user:pass@foo:21/bar;par?b#c  s:http u:user pass:pass h:foo port:21 p:/bar;par q:?b f:#c

The spec says the leading '?' and '#' are not part of query and fragment themselves, but these test could misguide implementors into including them "to pass the tests".

If you give ok to this change, I can provide a quick pull request.

**Comment by annevk** [comment]
@domenic @jasnell what do you think? Making `urltestdata.json` reflect URL records might be somewhat better than having it reflect the JavaScript API.

**Comment by annevk** [comment]
(That might also make it easier to omit fields that have their default value?)

**Comment by domenic** [comment]
Strong -1 from me. Being able to do simple assert_equals against the public API is what makes this a valuable way of testing the public API. If we start reconstructing the expected values from the JSON plus added test-specific logic, that'd be a big step backward to the old days where urltestdata just contained URL strings and the tests had to have their own mini-parser to reconstruct the expected values.

**Comment by annevk** [comment]
Okay, not a hill I'm dying on.
