### ISSUE TITLE
page visibility idlharness test is broken

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-platform-tests#5116]
If you implement onvisibilitychange, it will happily tell you "Unrecognized type EventHandler" and fail the test.

Looks like @plehegar forgot to add a definition of EventHandler in https://github.com/w3c/web-platform-tests/commit/47ebaea27fb722d87198e065e18f4216ff6de72e

**Comment by plehegar** [comment]
@bzbarsky I wasn't able to confirm that the fix removes the failure. If you can check and confirm the fix, that would be nice.

**Comment by bzbarsky** [comment]
Once the obvisibilitychange fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1333912 lands I should be able to do that.
