### ISSUE TITLE
Stability bots did not run

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#5174]
https://github.com/w3c/web-platform-tests/pull/5173

Does a force push break followed by a normal push for a subsequent commit break them somehow?

**Comment by jugglinmike** [comment]
I can see from [the latest commit's build log](https://travis-ci.org/w3c/web-platform-tests/jobs/212689017) that the stability bot definitely ran. This looks like it may be related to [the prbuildbot](https://github.com/w3c/prbuildbot), but I'm not sure how we go about debugging that. @bobholt: is there any place to surface the logs of that bot?

**Comment by bobholt** [comment]
@jugglinmike: It's on the w3c-test.org machine, so @sideshowbarker has access to those logs.

**Comment by sideshowbarker** [comment]
I’ve looked through the logs and I don’t see any failures for #5173 related to the stability checker. I do see a message about a comment failing to get posted because it was too big:

    body is too long (maximum is 65536 characters

```
Mar 20 07:37:11 vela wptserve.sh[17898]: DEBUG:urllib3.connectionpool:"POST /repos/w3c/web-platform-tests/issues/5173/comments HTTP/1.1" 422 248
Mar 20 07:37:11 vela wptserve.sh[17898]: ERROR:root:{"message":"Validation Failed","errors":[{"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}],"documentation_url":"https://developer.github.com/v3/issues/comments/#create-a-comment"}
```

So that makes me think that Travis must have run the stability checker as expected, but from looking at the PR you can’t tell that because the comment the stability checker produced was over the comment-length limit that GitHub has set.

**Comment by jugglinmike** [comment]
Sounds like we need to merge https://github.com/w3c/prbuildbot/pull/2. @bobholt if that's correct, then I can make time for it today. Let me know!

**Comment by bobholt** [comment]
@jugglinmike: Ah yeah, that'd probably do it. I completely forgot about that PR.

**Comment by jugglinmike** [comment]
Ran out of time today. I'll try again tomorrow

**Comment by jugglinmike** [comment]
Resolved via https://github.com/w3c/prbuildbot/pull/12
