### ISSUE TITLE
Stability bots run tests that are not changed in PR

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#5218]
See https://github.com/w3c/web-platform-tests/pull/5150#issuecomment-286857289

cc @jugglinmike @bobholt

**Comment by jugglinmike** [comment]
We've landed a change to limit what the stability bot considers "changed" in a given pull request (or more specifically, in the "branch" build for pull requests): https://github.com/w3c/web-platform-tests/pull/5196 . That should resolve the problem you've identified here, but please let me know if the problem shows up elsewhere.
