### ISSUE TITLE
Update documentation for the new CSS test suites

### ISSUE THREAD

**Issue by xfq** [w3c/web-platform-tests#5264]
For example, remove the "However, for mainly historic reasons, the CSS WG testsuite is in a separate repository, csswg-test." sentence; add info about the CSS WG test domains in the `hosts` file etc.

Thank you for the great work, @gsnedders!

**Comment by gsnedders** [comment]
As far as I'm aware, nothing actually used the domains, so I think #5265 is literally all we need. Thanks!

**Comment by xfq** [comment]
In [docs/introduction.md](https://github.com/w3c/web-platform-tests/blob/3d5db8631c592ba41a7e5f7aac1bc2c1600b497c/docs/introduction.md#test-layout):

> Each top level directory in the repository corresponds to tests for a single specification.

@gsnedders Do you plan to move the CSS tests out of the `css/` directory?

**Comment by foolip** [comment]
Closing this in favor of updating the documentation for https://github.com/w3c/web-platform-tests/issues/7503, since that change is imminent.
