### ISSUE TITLE
Style rules section largely duplicates lint-tools docs

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5296]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/14 by @gsnedders on 17 Jan 2017, 17:15 UTC:

> On General Guidelines.

**Comment by foolip** [comment]
I think this is about these two docs:
http://web-platform-tests.org/writing-tests/general-guidelines.html
http://web-platform-tests.org/writing-tests/lint-tool.html

I actually think the split is quite reasonable, what's the duplication or problem?

**Comment by gsnedders** [comment]
Maybe the duplication isn't such a problem? I was mostly thinking about the fact that they largely cover the same material (the general guidelines saying "do x, not y"; the lint tool docs saying "this lint checks for y, do x instead").

**Comment by foolip** [comment]
I think the overlap is quite small, because most of our guidelines are too vague to be lints, and the lints are mostly about various kinds of mistakes that wouldn't make sense as explicit anti-guidlines.
