### ISSUE TITLE
Rewrite the CSS User Stylesheets page

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5298]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/17 by @gsnedders on 18 Jan 2017, 15:21 UTC:

> My hard copy has a single note scribbled on it saying to rewrite it entirely.

**Comment by foolip** [comment]
@gsnedders, this isn't a very descriptive issue, I'll go ahead and close it, if there's a problem hopefully someone (you?) will complain again.
