### ISSUE TITLE
IndexedDB `IDBDatabase.transaction` exception order issue (mode check should precede store check)

### ISSUE THREAD

**Issue by brettz9** [w3c/web-platform-tests#5313]
Per IndexedDB's `idbdatabase-transaction-exception-order.html`, there is the following test expecting that the "No such store" check (`NotFoundError`) should precede the "invalid mode" check (`InvalidAccessError`):

```js
indexeddb_test(
  (t, db) => {
    db.createObjectStore('s');
  },
  (t, db) => {
    assert_throws('NotFoundError', () => {
      db.transaction('no-such-store', 'versionchange');
    }, '"No such store" check (NotFoundError) should precede ' +
       '"invalid mode" check (InvalidAccessError)');
    t.done();
  },
  'IDBDatabase.transaction exception order: NotFoundError vs. InvalidAccessError'
);
```

However, per the original spec and the draft spec, the very first step is to check for mode (and besides this, it is to throw a `TypeError` per both specs, not an `InvalidAccessError`--this was probably a carry-over error from the prior test which is the only actual case where `InvalidAccessError` should occur in this method).

Would you like a PR to reverse the order expectation here? @inexorabletash

**Comment by brettz9** [comment]
Pinging @inexorabletash in case my subsequent edit to add mention didn't notify you.

**Comment by annevk** [comment]
@brettz9 not sure what you mean with original/draft, but if the test doesn't match the latest, which is https://w3c.github.io/IndexedDB/, it should be updated.

**Comment by brettz9** [comment]
By original I mean the RC, and draft I mean https://w3c.github.io/IndexedDB/

**Comment by brettz9** [comment]
Sorry by the original I mean the released version at https://www.w3.org/TR/IndexedDB/  :)

**Comment by annevk** [comment]
Yeah, so this would need to be fixed, but maybe also check implementations. If they haven't changed I'm not sure it's worth the churn.

**Comment by inexorabletash** [comment]
Huh, blink does check mode after stores. Unfortunate - I like TypeError being first. I'll check the other browsers when I'm at work and fix the test or spec. Thanks for filing the issue!

**Comment by inexorabletash** [comment]
Huh, looks like I noted things correctly in https://github.com/w3c/IndexedDB/issues/11 but didn't align the spec text with it. Chrome and Firefox both have:

*  InvalidStateError (closed/version) > InvalidAccessError (empty) > NotFoundError > TypeError (mode)

So test and spec are wrong:

* Test should check for TypeError there
* Spec should move the check down

**Comment by inexorabletash** [comment]
Spec issue: https://github.com/w3c/IndexedDB/issues/187

**Comment by inexorabletash** [comment]
All fixed - thanks @brettz9 !
