### ISSUE TITLE
Don't duplicate interfaces in the tree

### ISSUE THREAD

**Issue by ayg** [w3c/web-platform-tests#5339]
For idlharness tests, we need interfaces of base classes and members to be defined even if they aren't being tested.  This means that sometimes we have a few copies of the same interface declarations in the tree, and they aren't all updated at the same time.  E.g., interface Node is in both dom/interfaces.html and html/dom/resources/untested-interfaces.idl.  Does it make sense to have each interface (or collection of interfaces) kept in a canonical .idl that's imported by any test file that wants it?  Either we could have a central directory for IDL files, or have all tests import from the directory of the spec that defines the IDL.

**Comment by annevk** [comment]
I think we could maybe centralize the whole setup if someone invested some effort in it and reduce a whole lot of boilerplate and copy-and-pasting.

I haven't looked closely, but it seems the harness basically needs an instance of something and some IDL. That really doesn't need to be spread around the entire directory tree with everyone defining all the HTML around it and such.

If we just have a list of ways to create instances and corresponding interfaces, and all the various interface files, we should be able to make a smarter setup with less duplication and less work for additions.

**Comment by ayg** [comment]
We could centralize it completely, and perhaps even move idlharness.js into wpt, but then the tests for interfaces wouldn't be together with the tests for that spec.  This would be more similar to the HTML reflection tests.  I think I prefer the way it is now, with the tests for each spec's IDLs together with that spec instead of centralized.  It's not really much boilerplate, we just have to not have the actual IDLs duplicated.

**Comment by ayg** [comment]
I was looking at this, and basically all the tests just define stubs, sometimes as minimal as `idl_array.add_untested_idls('interface Navigator {};');`.  That doesn't seem like meaningful duplication.  On the other hand, the XHR tests copy the entire Event interface definition, which is certainly going to change at some point.  Should we convert all tests to pull in the entire interface for every specification they're testing?  I'd be inclined to leave the ones that don't declare anything but the interface name, but if you declare e.g. a subclass, you should have access to the up-to-date version of the base class' IDL to test inheritance properly.

**Comment by annevk** [comment]
Yeah I don't know. If stubs are sufficient I guess the current setup is fine, though it's still more work than having a script that would create the necessary stubs.

I also noticed that in quite a few places we don't test the IDL inside workers. I created a patch for URL at #5661, but there's many other places that need something like this. (And again, a centralized solution would just make this work automatically since it can use the Exposed syntax and such and then have it available for all APIs rather than converting each one.)

**Comment by ayg** [comment]
Are stubs okay if you're defining an interface that inherits from an untested interface?  Or are there tests on the derived interface that need to know more information about the base interface (members, attributes, etc.)?  I don't know offhand.  It definitely matters if the base interface has NoInterfaceObject, and it seems like untested interfaces are still tested on objects passed with add_objects() (although maybe this is a bug?).  It also matters if the base interface has a stringifier.  More things might be added later.

So it seems like tests should all include the full IDLs if they inherit an interface or such, but it would be a lot of work to fix them all.
