### ISSUE TITLE
Should tests be split into separate files?

### ISSUE THREAD

**Issue by g-ortuno** [w3c/web-platform-tests#5393]
This is more of a question than an issue. In Chromium, we sometimes put all of our tests in a single file but I see that most tests here e.g. [worker tests](https://github.com/w3c/web-platform-tests/tree/master/workers), are split into separate files. Is that something we should do before upstreaming our tests?

@reillyeon: fyi

**Comment by annevk** [comment]
Same file is fine, as I said on IRC:

>  if you look at url/ you'll find ample precedent for lots of parser/setter tests together (with a separate JSON as source so they can be reused by non-browser impls)

**Comment by domenic** [comment]
The biggest reason to split things into separate files is if you modify global state in some way. It is often just easier to start a new environment than try to clean up everything.

The only other reason is the usual reason in software projects: maintainability, separation of concerns, etc. But those aren't as important as having tests in the first place.
