### ISSUE TITLE
 Reftests take screenshot too early in Chrome

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5412]
~~Probably https://github.com/w3c/wptrunner/issues/241~~

Almost identical to to #6328.

https://github.com/w3c/csswg-drafts/issues/1088 is the issue that causes the issue here. Notably, wptrunner needs to block screenshots on fonts loading.

cc/ @jgraham @jugglinmike @bobholt

**Comment by gsnedders** [comment]
Actually, it's worse than that, as discussed in the email thread:

We need to take a screenshot after:

  * after the document's load event has been fired
  * the document.fonts.ready promise being fulfilled
  * all @imports from stylesheets have been loaded
  * after all <uri> subresources in all stylesheets have been loaded (so background-image, content, etc.)

And the last two of those can't be detected through JS. :\

**Comment by gsnedders** [comment]
OK, maybe the last two block the load event in Chrome per https://github.com/w3c/web-platform-tests/pull/5525 so maybe we're okay.

**Comment by foolip** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=507054 is the Chromium bug tracking document.fonts.ready being fulfilled. That may not be the only required fix, but I think we should treat this as blocked on that.

**Comment by gsnedders** [comment]
@foolip that bug is only really about the Blink test runner, is it not? whereas, I believe, this is about wptrunner.
