### ISSUE TITLE
[css-regions-1] Style cascading when element is flowed in itself

### ISSUE THREAD

**Issue by csswg-test-issue-mover** [w3c/web-platform-tests#5424]
Originally posted as https://github.com/w3c/csswg-test/issues/78 by @mibalan on 29 Aug 2013, 14:30 UTC:

> The CSS cascade follows the DOM order. This test(s) should make sure that in more complicated cases where an element is flowed in itself (or an indirect child gets flowed in the element) the CSS cascade does not get confused.
> 
> Something similar should cover proper CSS cascading when using nested named flows.

**Comment by gsnedders** [comment]
ignore this
