### ISSUE TITLE
Can't generate manifest file with steps as proposed

### ISSUE THREAD

**Issue by DavidBruant** [w3c/web-platform-tests#544]
STR:
````
git clone git@github.com:w3c/web-platform-tests.git
cd web-platform-tests
git submodule init
git submodule update --recursive
python tools/scripts/manifest.py MANIFEST.json
````
The manifest file isn't generated and the following is printed:

> INFO:Web platform tests:Working directory not clean, adding local changes

`git status` reveals `modified:   tools/pywebsocket (untracked content)` which contains a bunch of untracked src/mod_pywebsocket/*.pyc files.

Reverting changes allows to generate the manifest, but then `python serve.py` doesn't work. That's solve by doing `git submodule update --recursive` again.

Maybe the issue can be solved with adding the guilty files to .gitignore somewhere.

**Comment by jgraham** [comment]
This got rewritten.
