### ISSUE TITLE
Add a real lint tool

### ISSUE THREAD

**Issue by csswg-test-issue-mover** [w3c/web-platform-tests#5468]
Originally posted as https://github.com/w3c/csswg-test/issues/926 by @gsnedders on 27 Oct 2015, 05:27 UTC:

> We want to move in the direction of having no build warnings, and really want to avoid regressing anything we currently have. We probably also want to add further lint checks.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/926#issuecomment-151379069 by @gsnedders on 27 Oct 2015, 05:29 UTC:

> I don't know if we just want to take wpt's lint tool. We probably want something more because we want to make sure the flags we have are what we expect.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/926#issuecomment-151383990 by @cvrebert on 27 Oct 2015, 06:05 UTC:

> > We probably also want to add further lint checks.
> 
> e.g. Check that files referenced by `<link rel="match">` actually exist.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/926#issuecomment-151401589 by @gsnedders on 27 Oct 2015, 07:30 UTC:

> Note the build system currently gives warnings for those.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/926#issuecomment-151402809 by @cvrebert on 27 Oct 2015, 07:38 UTC:

> Ah, I had assumed that the linter was what powered @syncbot, which doesn't currently issue a warning in said case.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/926#issuecomment-151404169 by @plinss on 27 Oct 2015, 07:48 UTC:

> @cvrebert correct @syncbot is powered by the Shepherd tool. Adding reference link tests should be easy.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/926#issuecomment-151408923 by @gsnedders on 27 Oct 2015, 08:09 UTC:

> Can we reduce the multiplicity of tooling we have around?
> 
> We currently have, as far as I'm aware, three different lint systems:
> - wpt's
> - Shepard's
> - CSS build system
> 
> Ideally we should have one. Really what we check for csswg-test should be a superset of the rules of wpt's lint tool, I think.

**Comment by gsnedders** [comment]
I think we can close this now; we might potentially want to add some "dynamic linter" that checks that spec links actually point to spec fragments that exist (and still exist) but that's a project for another time. (It's dynamic insofar as it isn't guarantee a commit that passes the lint at time t will pass at t+1, because specs change, etc.)
