### ISSUE TITLE
drawCustomFocusRing

### ISSUE THREAD

**Issue by plehegar** [w3c/web-platform-tests#547]
web-platform-tests / 2dcontext / drawing-paths-to-the-canvas / canvas_focus_drawCustomFocusRing_001.html

will need to be revisited once we know what can be done with it.

**Comment by Elchi3** [comment]
drawCustomFocusRing and drawSystemFocusRing are gone: https://html5.org/r/8854

**Comment by foolip** [comment]
They are also listed in html/semantics/embedded-content/the-canvas-element/historical.html so the remaining work is to remove the test I think. I'll send a PR.
