### ISSUE TITLE
Import issues in Shepherd into GitHub somehow

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#5485]
Originally posted as https://github.com/w3c/csswg-test/issues/1101 by @gsnedders on 29 Jul 2016, 16:43 UTC:

> - [x] get the repo and PRs from known good users mirrored somewhere (likely css.w3c-test.org) // @sideshowbarker @deniak 
> - [ ] figure out some way of importing all issues in Shepherd into GitHub (do we want to do this here if we're then going to merge this into web-platform-tests? we should check if there's any way to move issues en-mass)
> 
> I'm sure I'm missing something that was mentioned before. @plinss?

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1101#issuecomment-240927292 by @gsnedders on 19 Aug 2016, 04:49 UTC:

> We now have http://csswg-test.org/ with http://csswg-test.org/submissions/ containing PRs

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1101#issuecomment-241860804 by @frivoal on 23 Aug 2016, 20:10 UTC:

> How is "good users" defined? write access to the csswg-test repo?

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1101#issuecomment-241929411 by @gsnedders on 24 Aug 2016, 01:08 UTC:

> @frivoal I believe so.

**Comment by foolip** [comment]
I don't quite understand what this issue is about. Is there a set of issues somewhere outside of wpt that now should be filed as individual issues here? Leaving this without a priority, but we should close this if there's nothing actionable.

**Comment by frivoal** [comment]
In days long gone, the CSS WG did not use a pull-request->review->fix->review->merge workflow, but a commit->review->fix->approve workflow. But people did not always follow up on the reviews. So there are lots of test which have reviews and are known to be problematic, or lots of test marked as "not reviewed yet, someone should look at this" (by the way, I am not convinced the system was smart enough to mark as approved things that have been reviewed and merged via github).

This was a bad workflow, so it is good we moved away from it.

But the question is what to do with all these test with know issues, and all these unreviewed tests.

The system which knows about all this is https://test.csswg.org/shepherd/

One approach is to just leave it where it is, forever readonly, and to just fix bugs opportunistically as we run into them.

Another one would be to convert these open issues into github issues, possibly with some filtering.

I expect the signal to noise ration to be quite poor, so unless someone has a briliant idea to make sense out of this thing without too much work, I'd be OK with just closing this issue as WONTFIX.

**Comment by foolip** [comment]
Do all of these have some kind of metadata in the file, or does only Shepherd know about them? If the former, then that might be valuable when investigating tests that fail everywhere. If the latter, then dumping a list of the affected files (before the names change more) would be useful.

**Comment by gsnedders** [comment]
> One approach is to just leave it where it is, forever readonly, and to just fix bugs opportunistically as we run into them.

AIUI, the plan is to keep it as is, forever readonly.

> Another one would be to convert these open issues into github issues, possibly with some filtering.

The original CSS WG resolution was to convert all of these, but it seemed when I looked into it before like there was pretty terrible signal:noise and then I massively deprioritised it. Loads of the issues there are minor nits.

**Comment by frivoal** [comment]
> when I looked into it before like there was pretty terrible signal:noise

Not surprised. It would seem the best course of action is to do nothing :)

@astearns or @atanassov , can you put this on the csswg's agenda, to attempt to get a firm and consensual WONTFIX?

**Comment by foolip** [comment]
Closing per https://github.com/w3c/web-platform-tests/issues/5485#issuecomment-335870469, thanks all!
