### ISSUE TITLE
Multicol tests linking to themselves as references

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#5501]
Originally posted as https://github.com/w3c/csswg-test/issues/1221 by @gsnedders on 01 Mar 2017, 14:09 UTC:

> Many of them have `<link rel="match" href=""/>`.
> 
> There was a reftest.list: https://github.com/w3c/csswg-test/blob/b07165c7dcb68b5a390c8e4418e33713cbc6a184/contributors/opera/incoming/multicol/reftest.list
> 
> This got removed in 6ca77060aa37877b5d2885fa0bfdaa664fbd8adc after the tests had been partially moved over to meet testsuite guidelines in 717ba0abf18ace96f272d9b13f2192813178548c, which is also where `<link rel="match" href=""/>` comes from.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1221#issuecomment-283351912 by @gsnedders on 01 Mar 2017, 14:19 UTC:

> This might only be `css-multicol-1/multicol-rule-shorthand-2.xht`?

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1221#issuecomment-283356589 by @gsnedders on 01 Mar 2017, 14:36 UTC:

> Which originally was part of: `== rule-shorthand.html rule-shorthand-2.html rule-stacking.html rule-stacking-ref.html`. Unfortunately, the other three files mentioned have all drastically changed and are nowhere near a reference nowadays.

**Comment by gsnedders** [comment]
Interestingly, even in the presto-testo dump that doesn't hold true, but we do have the original ref. Will post PR shortly.
