### ISSUE TITLE
Test that CSSOM insertRule() index argument is optional

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#5524]
See
https://github.com/w3c/csswg-drafts/commit/7949d41a2d86107f8ad4624c055b4b0c9c28ad0d
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27384

**Comment by zcorpan** [comment]
(Also remember to file bugs on browsers that fail the tests.)

**Comment by sendilkumarn** [comment]
I would like to give it a shot
