### ISSUE TITLE
Test CSSOM insertRule cross-origin

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#5526]
> annevk
zcorpan: an interesting thing you might want to test with insertRule is using it on cross-origin stylesheets
annevk
zcorpan: apparently not all browsers throw
annevk
zcorpan: opaque cross-origin, not CORS

**Comment by csnardi** [comment]
I think https://github.com/w3c/web-platform-tests/commit/28cb17e68938f7abe4104c93d9af6bd9a65320dd and https://github.com/w3c/web-platform-tests/commit/9c0a4b5434db0077f37837c6fd94aa72705ddba5 added same/cross-origin testing for insertRule.

**Comment by zcorpan** [comment]
Nice! Closing.
