### ISSUE TITLE
Where do we test support for image formats? (APNG)

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#5531]
In https://codereview.chromium.org/2814453004/ there are some tests that could be part of web-platform-tests, checking basic support for APNG.

What is the appropriate place for this? I suggest a new apng/, other thoughts?

@jgraham @sideshowbarker @gsnedders (please poke more people who might care)

**Comment by annevk** [comment]
Yeah, apng/ seems best.

**Comment by gsnedders** [comment]
This seems fairly obvious given current policy, given they're tests for the APNG spec. So yeah, I think we can close this as resolved?

Semi-relatedly, https://philip.html5.org/tests/apng/tests.html might be worth importing.

**Comment by LeonScroggins** [comment]
> Semi-relatedly, https://philip.html5.org/tests/apng/tests.html might be worth importing.

Those are good tests, although several have animation, which we do not have a good way to test (there is a chromium bug tracking that: https://bugs.chromium.org/p/chromium/issues/detail?id=707356).

**Comment by foolip** [comment]
Great, https://github.com/w3c/web-platform-tests/pull/5543 has a test, filed https://github.com/w3c/web-platform-tests/issues/5546 to import https://philip.html5.org/tests/apng/tests.html

**Comment by gsnedders** [comment]
@LeonScroggins Right, any sort of uncontrollable animation is basically impossible to test in any cross-browser way. :/
