### ISSUE TITLE
Don't use RTCPeerConnection#addStream in tests

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#5533]
https://github.com/w3c/web-platform-tests/pull/4114 added a test that uses `addStream()`, which has been removed from the WebRTC spec in https://github.com/w3c/webrtc-pc/commit/ce5794c3d698cf0906a58ff50a80a9e0e3ddd998.

@fippo, can you take a look?

Reported by @youennf in https://github.com/w3c/webrtc-pc/issues/1086#issuecomment-293303101

**Comment by fippo** [comment]
If we completly remove addStream the simplecall test is going to be broken for some time in Chrome and even longer in Edge (at minimum 6 months; and there are currently [no plans to extend this beyond legacy interop](https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/#BWxhxIOGUhGWgsMI.97) which probably covers the legacy onaddstream).

The pragmatic thing would be to conditionally use addTrack and fall back to addStream and add listeners for addTrack in addition to addStream. See [here](https://github.com/fippo/web-platform-tests/commit/fba8084aef0f080b9fc299a225a4136af9963f57). This means the dirty hack is in the test but implementations can do the right thing.

The setRemoteDescription test also uses onaddstream but that is easier to fix.

+ @jan-ivar @shijuns

**Comment by foolip** [comment]
Tests in web-platform-tests should be derived from the corresponding spec, or that is certainly the norm. http://web-platform-tests.org/reviewing-tests/checklist.html says "The spec backs up the expected behavior in the test." @gsnedders, is there some even stronger language somewhere?

An area where specs and implementation are so ill aligned that it's not possible to write simple tests like this is a serious problem, but I don't think it should be masked in the test suite. Letting Chrome and Edge fail seems quite appropriate, putting the burden on us/them to sort out this situation.

@guidou

**Comment by foolip** [comment]
@henbos too

**Comment by henbos** [comment]
Browsers should implement the spec, the testing should reflect that, if we design the tests to pass on non-compliant implementations that does not do much to encourage browsers towards the correct implementation.

That said it makes sense to test implementations that are implemented on multiple browsers for interoperability purposes. addStream is so frequently occurring that interoperability of it is important, testing makes this today makes sense. But maybe that is an argument for making it a legacy API in the spec, in which case it should be tested because it is covered by the spec?

If it truly is going away I think web platform tests should reflect that. Chrome does not support addTrack yet though. I don't like conditionally using one API or the other - web platform tests should test what should be implemented, it's not an adapter.js.

**Comment by foolip** [comment]
> addStream is so frequently occurring that interoperability of it is important, testing makes this today makes sense. But maybe that is an argument for making it a legacy API in the spec, in which case it should be tested because it is covered by the spec?

Whether re-standardization of addStream is inevitable due to compat constraints I don't know. To get rid of it would require some implementer to do the web compat analysis (httparchive) and if there's stuff in the wild that will break, come up with a timeline and migration plan. I'd be happy to do some httparchive poking if anyone would use the results.

There would be value in testing non-standard APIs that are widely implemented. I think the idea of a defacto/ or non-standard/ directory has been floated in the past, but that everyone really prefers if specs proceed tests. @jgraham or @RByers told me about this.

**Comment by fippo** [comment]
I don't see the WebRTC WG having any kind of migration plan from what is out there to 1.0... PR for killing addStream + onaddstream is up.

**Comment by youennf** [comment]
This is worrying to have such a widely used unspecified API, and probably there for a long time.
If there is one legacy API to be described in WebRTC, that should be this one.

From a web dev point of view, addStream/onaddstream is so much simpler to use in the simple A/V case that it even seems beneficial to have it.

**Comment by nils-ohlmeier** [comment]
> From a web dev point of view, addStream/onaddstream is so much simpler to use in the simple A/V case that it even seems beneficial to have it.

I think that is the prefect use case for some code on top of the API which simplifies their usage, but not an argument to have the native API's implement the simple and the more complex API.
