### ISSUE TITLE
Make cssom-view/MediaQueryList-001.html less brittle

### ISSUE THREAD

**Issue by qyearsley** [w3c/web-platform-tests#5541]
@plinss @zcorpan

https://github.com/w3c/web-platform-tests/blob/master/cssom-view/MediaQueryList-001.html fails if when `window.matchMedia('(device-aspect-ratio: 1280/800)')` has no matches, but this doesn't mean that MediaQueryList or window.matchMedia don't conform to the spec. This test could be improved so that it passes on different platforms and devices regardless of device aspect ratio.

Context: http://crbug.com/710226

**Comment by zcorpan** [comment]
My comment is at https://bugs.chromium.org/p/chromium/issues/detail?id=710226#c5

**Comment by zcorpan** [comment]
Fix at https://codereview.chromium.org/2829913003
