### ISSUE TITLE
Stability checker sometimes duplicates text in github comment

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#5552]
See https://github.com/w3c/web-platform-tests/pull/5390#issuecomment-291969797

The "travis_fold:end:running_tests" (source `travis_fold:end:running_tests`) also looks suspect.

cc @jugglinmike

**Comment by bobholt** [comment]
Just a preliminary peek under the hood. Those lines are being repeated in the build log (and the comment bot just echoes them back in the comment). Whether this is a check_stability.py issue or a Travis hiccup, I'm unsure, but I'm leaning toward hiccup. Logging out the formatted title only happens once, in the main method, and not in a loop or conditional: https://github.com/w3c/web-platform-tests/blob/master/check_stability.py#L768

**Comment by bobholt** [comment]
I believe this was a regression in wpt-tools that was resolved some time ago. Feel free to reopen if you see this again.
