### ISSUE TITLE
Document untestable conditions

### ISSUE THREAD

**Issue by jugglinmike** [w3c/web-platform-tests#5558]
Over time, the project maintainers have recognized a number of conditions that are not testable from the WPT infrastructure. Others may be testable, but not in an automated way. Documenting this information would highlight some of the project's longer-term goals (along with open areas for research), help direct potential contributors, and give us an opportunity to prioritize future work.

I'd like to use this issue to collect a list of all untestable conditions as we know them today. From there, we can discuss the best way to publish/maintain that list going forward.

Here's what I think we need for this data to be useful

- **Description** - summary of the condition we'd like to test
- **Blockers** - reason(s) why we cannot write an automated tests for this today
- **Potential solutions** - changes to the infrastructure that would make testing possible (if any)

**Comment by jugglinmike** [comment]
Okay, I'll start

### Privileged ports

**Description** I've only encountered [one use-case for this](https://github.com/w3c/web-platform-tests/pull/5227#issuecomment-293292568), and it is very much an edge case. I'm happy to add more compelling motivations here, but if none exist, we'll probably just track this as low-priority.

**Blockers** Running a server on these ports requires escalated permissions, and granting them can be problematic for in some environments (e.g. contributors who lack that ability, or [container-based continuous integration environments](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments)).

**Potential solutions** We could annotate the relevant tests with metadata describing this requirement and update the project documentation accordingly. Runners like the web runner and `wptrunner` could then be updated to only run these tests if explicitly configured to do so. This would not solve the problem, exactly, since it does nothing to address the underlying issue. It would allow contributors to author and share tests, though.

### Invalid HTTP traffic

**Description** Although the HTTP specifications may be rigorous in their definition of valid protocol usage, the reality of the web is not always in alignment. The W3C/WhatWG specifications may specify expected behavior for such conditions. This makes it necessary to reproduce the conditions in test environments.

**Blockers** The project's web server, wptserve, exposes request handlers that are derived from [Python's built-in BaseHTTPRequestHandler](https://docs.python.org/2/library/basehttpserver.html). The documentation for that module explicitly prohibits protocol violations:

> BaseHTTPRequestHandler has the following instance variables:
>
> [...]
>
> **`wfile`**
>
> > Contains the output stream for writing a response back to the client.
> > Proper adherence to the HTTP protocol must be used when writing to this
> > stream.

Anecdotally, I've had success in writing invalid responses for local testing purposes. That said, it seems irresponsible to rely on this in light of the above documentation.

**Potential solutions** The `wptserve` project could be extended with a lower-level request handler that exposed the underlying TCP socket connection. This would obviously be onerous for general use, but it would allow us to write the relevant low-level tests. Previously suggested at https://github.com/w3c/wptserve/issues/116

### Externally-controlled state

**Description** The web platform is expanding to include APIs that concern state which is external to the browser. Examples include [Device Orientation](https://w3c.github.io/deviceorientation/spec-source-orientation.html), [Bluetooth](https://webbluetoothcg.github.io/web-bluetooth/), and [Geolocation](https://www.w3.org/TR/geolocation-API/). Thoroughly testing these specifications requires precise control over the external state.

**Blockers** Because they aim to describe the state of the world, these specifications rarely (if ever) define methods for manual override. Simply extending the specifications to facilitate testing on an as-needed basis is not an option because if this level of control were available generally, the trust between developers, users, and the user agent would be severely undermined.

**Potential solutions** Work with specification authors and browser vendors to define and implement "test-only" APIs that could be enabled only under highly controlled circumstances. Not only would this would allow WPT to accept specification conformance tests, it would enable application developers to test the business logic they author using the new platform functionalities. Such "test-only" APIs could be defined in the JavaScript runtime. Alternatively, the testing APIs could be defined in terms of [the WebDriver draft specification](https://w3c.github.io/webdriver/webdriver-spec.html)--a developing standard derived from the mature open source software project [Selenium](http://www.seleniumhq.org/). [This is being actively discussed on the public-test-infra mailing list](https://lists.w3.org/Archives/Public/public-test-infra/2017AprJun/0013.html).

**Comment by annevk** [comment]
FWIW, there's a number of these kind of issues filed: #5630, #2669, #4751, #4880. Did you want to collect all those here?

**Comment by jugglinmike** [comment]
@annevk Thanks! Do you think there's any value in a "tracking issue" like this? Or would it just be extra overhead when an issue "tag" like "needs automation" (as @foolip [requested](https://github.com/w3c/web-platform-tests/issues/4751#issuecomment-278539160)) would do?

In the latter case, I'm happy to create that tag, file issues for the things I reported above (skipping the first since it is already captured by gh-4751), and close this issue.

**Comment by foolip** [comment]
I've been using the "infra" and "type:missing-coverage" labels for things like that recently.

**Comment by annevk** [comment]
Having a dedicated label sounds great. If you want a tracking issue that seems fine in addition.

**Comment by foolip** [comment]
How about "type:untestable"? @jgraham?

**Comment by annevk** [comment]
#2161 is also related.

Do we have a generic issue yet for any kind of permission API, such as the Notifications API? It's currently impossible to write cross-browser automated tests for those.

**Comment by jgraham** [comment]
`type:untestable` is fine.

FWIW I think the discussion of BaseHTTPHandler is rather missing the point; the documentation basically means that it's your responsibility to write valid HTTP. That's precisely the thing that allows us to test invalid HTTP.

**Comment by jugglinmike** [comment]
Okay, we now have a label for currently-untestable conditions, `type:untestable`:

https://github.com/w3c/web-platform-tests/issues?utf8=%E2%9C%93&q=label%3Atype%3Auntestable%20

> Having a dedicated label sounds great. If you want a tracking issue that
> seems fine in addition.

It doesn't sound like a tracking issue would really add anything, so I'm happy to stick to labels until we have a need for that. The two novel features from my earlier comment are now tracked with dedicated issues: gh-5668 and gh-5669

> Do we have a generic issue yet for any kind of permission API, such as the
> Notifications API? It's currently impossible to write cross-browser automated
> tests for those.

I couldn't find anything, so I created gh-5671 to track that.

> FWIW I think the discussion of BaseHTTPHandler is rather missing the point

I'm pretty good at missing the point, but I'd rather have that discussion in a dedicated thread. Let's pick it up in gh-5668.

Thanks for the input, all! This issue has served its purpose; now closing.
