### ISSUE TITLE
getUserMedia() tests cannot be automated due to device selection dialog

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#5563]
In https://github.com/w3c/web-platform-tests/pull/5557 there was a tests that failed on both Chrome and Firefox:
https://github.com/w3c/web-platform-tests/blob/master/webrtc/simplecall.html

Both failed with "WebRTC called error callback for getUserMedia", which means that the failure callback for getUserMedia was invoked.

The cause is very likely related to the device selection dialog. Some WebDriver extension may be needed to either select a device or deny the request, so that all scenarios can be tested automatically.

**Comment by foolip** [comment]
The test itself says this:
```
To run this test, you must have a webcam and a microphone or use
fake devices by specifying
  --use-fake-device-for-media-stream --use-fake-ui-for-media-stream
for Chrome or by setting the
  media.navigator.streams.fake
property to true in Firefox.
```

What's missing, then, is some common way of doing this, and having wptrunner actually do it.

@jgraham, I guess this would be a good fit for a WebDriver extension?

**Comment by fippo** [comment]
see also [adapter.js](https://github.com/webrtc/adapter/blob/master/test/selenium-lib.js#L55) for more test flags (chrome's --mute-audio might be useful too but is not listed there oddly).
Note that we're having quite some trouble with Firefox and getUserMedia on travis since FF52 :-/

**Comment by foolip** [comment]
I filed https://crbug.com/711611 to track the slightly broader issue of WebRTC test automation in Chromium.

**Comment by fippo** [comment]
also note that Firefox on travis [now requires pulseaudio](https://github.com/webrtc/adapter/pull/504) (less changes here since you already require sudo)

**Comment by agouaillard** [comment]
@jgraham, @foolip will ping you offline for the webdriver extension.

**Comment by leonhsl** [comment]
It may be not proper, but anyway we need to make this issue be owned, so, set @jgraham as owner for the relationship with WebDriver extension.

**Comment by foolip** [comment]
I think this issue is a dupe of these two together:
 * [Tests involving "permissions" API/UI](https://github.com/w3c/web-platform-tests/issues/5671)
 * [Need mock MediaStream data for some WebRTC tests](https://github.com/w3c/web-platform-tests/issues/7424)

Both assigned to kereliuk@, but the second is still blocked on having a WebDriver proposal. Will comment there instead.
