### ISSUE TITLE
Test that Web IDL sequence conversion happens correctly

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#5566]
I wrote this up because [Blink is working on handling `sequence<>`  correctly](https://bugs.chromium.org/p/chromium/issues/detail?id=690428) and I wanted to make sure they didn't optimize incorrectly:

http://jsbin.com/nemazayubu/edit?html,console,output

However nobody seems to pass this test right now, including Firefox, which is surprising to me. @bzbarsky 

(I haven't yet tested Safari Tech Preview, so their my last hope.)

We should get it, or some form of it, into WPT. I'm open to suggestions on better sequence-accepting APIs to test.

**Comment by bzbarsky** [comment]
There's a bug in the test.  This line:

      console.log("Using an array but with customized iteration (should be same as iterator): ", array);

should be:

      console.log("Using an array but with customized iteration (should be same as iterator): ", ctx.getLineDash());

If I fix that, then as far as I can tell Firefox passes.

**Comment by domenic** [comment]
Ah, thank you!! Fixed the test at that URL, and indeed Firefox is good to go. I'll work on turning this into a WPT PR soon.

**Comment by domenic** [comment]
Note to self: another thing we could test is that the getter for Symbol.iterator is only involved once, so that if people do want to do fast-path optimizations, they do it while still respecting the spec.

**Comment by bzbarsky** [comment]
For what it's worth, Gecko does in fact do fast-path optimizations here.  One thing that needs to be done carefully there (apart from not optimizing cases which have non-default iterator behavior) is either not optimizing arrays with accessors or handling changes to %ArrayIterator%.prototype.next partway through the iteration, when a getter for an accessor property on the array mutates it.

**Comment by domenic** [comment]
Great test idea. Also just changing %ArrayIterator%.prototype.next even before iteration needs to be tested.

**Comment by bzbarsky** [comment]
Also, arrays with holes and an accessor defined on %ArrayPrototype%.

**Comment by samweinig** [comment]
WebKit does not get the case of an custom iterator on the array instance (it will if it's on the prototype) right. https://bugs.webkit.org/show_bug.cgi?id=171150 is tracking the fix.
