### ISSUE TITLE
"Reviewable" is annoying and prevents seeing if something is successful or not

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#5590]
Although for some time we stopped using that old third-party code-review tool (Opera Critic I believe?), and had a brief period of bliss using just GitHub's interface, recently someone has reintroduced a new tool that edits our pull requests with a pointer out to some third-party service, "Reviewable".

This is not only intrusive and annoying, what with its giant purple badge taking up half of the OP of every pull request: it also hooks into the CI system, and prevents the CI from marking a pull request as "passing CI", because "1/2 checks have finished" (the second check, presumably, being whether someone has gone to that site and done whatever they want me to do). Indeed, if you look at the list of open PRs, there's not a green checkmark to be found anymore: https://github.com/w3c/web-platform-tests/pulls

I'd humbly request that whoever is so excited about using this tool please remove it from the test infrastructure and use it yourself in an opt-in manner, instead of foisting it upon all contributors.

I could be persuaded otherwise if we had evidence that some large percentage (e.g. 80%+) of pull requests received review through this tool. But my suspicion is that it's closer to 0%.

**Comment by jgraham** [comment]
Now that we have merged the infrastructure directly into the repository I want this for the more complex infra reviews. GitHub tools just aren't good enough yet.

**Comment by jgraham** [comment]
I've configured reviewable so that the review status is always shown as complete.

**Comment by annevk** [comment]
That's not a good solution. See e.g. how that makes it seem as if https://github.com/w3c/web-platform-tests/pull/5610 is okay to merge while it's clearly not.

**Comment by annevk** [comment]
Isn't there a way to make it only apply to infra patches or just add a comment "reviewable" to enable it for a certain PR? The majority of PRs shouldn't need this.

**Comment by domenic** [comment]
Yes, this doesn't address my point that if you really want this personally @jgraham, you can use it yourself, and not foist it upon all contributors. Please see my last paragraph especially.

**Comment by jgraham** [comment]
I think the argument that making this not required to pass status checks isn't a good solution because then the PR looks like it's OK to merge is a totally bogus argument; if we disabled it entirely then it would have exactly the same effect: the PR would be marked as OK to merge as soon as the travis checks passed.

I don't see what harm this is causing if it doesn't affect the status check. In particular the argument that it isn't always needed and therefore should be set up to be painful for the cases where it is needed vs being harmless in the case it isn't needed and easily available when it is required seems very weak.

**Comment by domenic** [comment]
This is causing harm in the same way advertising any other service that is irrelevant to contributors causes harm. How would you feel if we edited the Infra to start advertising LastPass on every post, because I find it useful for managing my GitHub passwords?

**Comment by jgraham** [comment]
I'm really trying to make things better here but I'm not motivated to spend time on it when you make such disingenuous comparisons.

**Comment by domenic** [comment]
Yes, and I'm really trying to contribute to web-platform-tests, but I'm not motivated to spend time on it when any PR I make becomes a nascar for your favorite web services.

**Comment by domenic** [comment]
Any way of making it opt-in, so that you can use it on PRs you want to use it on, but it never appears for the rest of us, would be acceptable.

**Comment by tobie** [comment]
Yeah, pushing such tools onto new contributors (that aren't aware they can ignore them) steepens the learning curve of the project. It also makes it unclear for everyone where reviews are happening. We've had this discussion many times in the past already. I'm glad to see others voicing their concerns here.

**Comment by tobie** [comment]
Related issue: https://github.com/Reviewable/Reviewable/issues/471

**Comment by tobie** [comment]
Alright, so @wpt-pr-bot now removes the reviewable badge in all PRs but those that touch the tools directory.

**Comment by domenic** [comment]
That's amazing!! What a great solution.

**Comment by bobholt** [comment]
Based on @domenic's comment above, I'm going to assume this was an acceptable solution to the issue and close. Feel free to reopen if I've misread.
