### ISSUE TITLE
./lint --help does not show help

### ISSUE THREAD

**Issue by smfr** [w3c/web-platform-tests#5597]
I would expect ./lint --help to show some options and quit. Instead, it just runs the tool.

**Comment by gsnedders** [comment]
It should. This was broken temporarily, but then fixed in https://github.com/w3c/web-platform-tests/pull/5542.

**Comment by smfr** [comment]
Confirmed that it works on top of tree. One niggle: "paths" is vague and doesn't differentiate directories (that don't work) and files (that do).
