### ISSUE TITLE
./lint is too slow and can't check only a subdirectory

### ISSUE THREAD

**Issue by smfr** [w3c/web-platform-tests#5598]
./lint seems to trawl the entire repo looking for issues. It could be much smarter and only look at files for which I have local changes, or stashed changes.

I would also like it to be able to only check a subdirectory, like:

> ./lint css

**Comment by gsnedders** [comment]
If you're on an up-to-date (or a sufficiently old!) branch, which #5597 implies you are, you should be able to pass files (but not directories) to lint, so `find css -type f -print0 | xargs -0 ./lint`. There's https://github.com/w3c/wpt-tools/issues/184 for adding some recursive option (or maybe that should just be the default), and there's been occasional discussions about making it faster in various ways but most of that requires a fair amount of refactoring hence nothing has happened.

**Comment by smfr** [comment]
Dup of #184
