### ISSUE TITLE
Also test accessor properties in WindowProxy [[DefineOwnProperty]]

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#5599]
@annevk, it appears per https://bugs.chromium.org/p/chromium/issues/detail?id=695385#c13 at least that Chrome has bugs with accessor properties that don't manifest for data properties. So adding a few lines to https://github.com/w3c/web-platform-tests/commit/8bb5fdc92acf9479599db3827e9cd71dc8f5aa92 that also try accessor properties would be ideal.

**Comment by annevk** [comment]
An accessor is a getter/setter, right? How are those applicable to indexed property tests?

**Comment by domenic** [comment]
You can do `Object.defineProperty(window, 5, { get() { return "123"; } })` which will apparently trigger a very different code path in Blink/V8 than the test's existing ``Object.defineProperty(window, 5, { value: "123" } })`

**Comment by annevk** [comment]
Oh, those wouldn't throw? Okay...

**Comment by domenic** [comment]
They should throw, just like the value: version, but apparently in Blink they got into a state where the value: descriptor threw but the get() descriptor defined the property.

**Comment by annevk** [comment]
Copy-and-pasted a bit more.
