### ISSUE TITLE
Certain IndexedDB tests inevitably fail with newly covered "finished" test behavior

### ISSUE THREAD

**Issue by brettz9** [w3c/web-platform-tests#5612]
@pwnall , @inexorabletash 

If the "finished" checks in https://github.com/w3c/web-platform-tests/commit/9d1ec68f7ecfd319af0029889547a6412fa83bad are the desired behavior, then the following tests inevitably fail for a compliant implementation:

1. `TransactionInactiveError vs. SyntaxError` test in `idbdatabase-createObjectStore-exception-order.htm`
2. `TransactionInactiveError vs. NotFoundError` test in `idbdatabase-deleteObjectStore-exception-order.htm`
3. `synchronously after abort() is called` and `in a promise microtask after abort() is called, before the transaction abort event is fired` tests in `upgrade-transaction-lifecycle-user-aborted.html`

This is because all of these are expecting a `TransactionInactiveError` failure after an `abort` but `InvalidStateError` checks (which is now indicated as failing upon the beginning of an abort) are supposed to always precede `TransactionInactiveError` checks (at least in the cases above).

**Comment by inexorabletash** [comment]
There's a bug in `support.js`. I have a fix locally, will try and get it up for review tomorrow.

**Comment by inexorabletash** [comment]
You can see the fix as part of https://codereview.chromium.org/2820393003/

https://codereview.chromium.org/2820393003/diff/20001/third_party/WebKit/LayoutTests/external/wpt/IndexedDB/support.js

Basically, two things:

* `var options` was shadowing the `options` argument, so it was ignored.  
* The logic for actually using the upgrade_will_abort was inverted

I also needed to move the `add_cleanup()` call to the `upgradeneeded` handler to cover cases where the upgrade aborts.

**Comment by brettz9** [comment]
Ok, I can try again after you have a chance to finish, but as a heads up, it wouldn't appear to me to be the same issue if you are only refactoring `support.js`...

Taking this example:

```js
indexeddb_test(
  (t, db, txn) => {
    const store = db.createObjectStore('s');

    txn.abort();

    assert_throws(
      'TransactionInactiveError',
      () => { db.createObjectStore('s2', {keyPath: '-invalid-'}); },
      '"not active" check (TransactionInactiveError) should precede ' +
      '"valid key path" check (SyntaxError)');
```

After the abort, `InvalidStateError` should throw, not `TransactionInactiveError`, so I'm not sure how magic in `support.js` could resolve this.

But don't let me take you away from fixes to give explanations--just mentioning in case there are multiple issues here.

**Comment by inexorabletash** [comment]
Hrm.... my comments may be missing the point of this issue. I was just dealing with failures with 2 of those tests (`idbdatabase-createObjectStore-exception-order.htm` and `idbdatabase-deleteObjectStore-exception-order.htm`) and was assuming it was the same cause.

I'll take a real look tomorrow.

**Comment by inexorabletash** [comment]
It looks like Chrome, Firefox and the tests match.

The spec's "or it is finished" clause is not correct, and/or the concept of "finished" needs to be refined further. I'll raise it as a spec issue.
