### ISSUE TITLE
log broken on resources directory

### ISSUE THREAD

**Issue by ayg** [w3c/web-platform-tests#5664]
With the submodules merged in, I would expect git log on resources/ files to give the history for the files from the old testharness.js repository, the same way it works on editing/.  But I don't see it.  @jgraham, do you know what happened here?  It seems like blame does work.

Compare outputs of these commands:
```
git log --follow resources/testharness.js
git log --follow editing/include/implementation.js
```

**Comment by jgraham** [comment]
You have to use `git log --full-history`. Unfortunately the default git history simplication mechanism notices that the full history of those directories is equivalent to the history of just the submodule merges and elides it. I'm not sure there's much we can do here.
