### ISSUE TITLE
Invalid HTTP traffic

### ISSUE THREAD

**Issue by jugglinmike** [w3c/web-platform-tests#5668]
**Description** Although the HTTP specifications may be rigorous in their definition of valid protocol usage, the reality of the web is not always in alignment. The W3C/WhatWG specifications may specify expected behavior for such conditions. This makes it necessary to reproduce the conditions in test environments.

**Blockers** The project's web server, wptserve, exposes request handlers that are derived from [Python's built-in BaseHTTPRequestHandler](https://docs.python.org/2/library/basehttpserver.html). The documentation for that module explicitly prohibits protocol violations:

> BaseHTTPRequestHandler has the following instance variables:
>
> [...]
>
> **`wfile`**
>
> > Contains the output stream for writing a response back to the client.
> > Proper adherence to the HTTP protocol must be used when writing to this
> > stream.

Anecdotally, I've had success in writing invalid responses for local testing purposes. That said, it seems irresponsible to rely on this in light of the above documentation.

**Potential solutions** The `wptserve` project could be extended with a lower-level request handler that exposed the underlying TCP socket connection. This would obviously be onerous for general use, but it would allow us to write the relevant low-level tests. Previously suggested at https://github.com/w3c/wptserve/issues/116

**Comment by jugglinmike** [comment]
This was originally raised in the discussion of gh-5558, where @jgraham responded:

> FWIW I think the discussion of BaseHTTPHandler is rather missing the point;
> the documentation basically means that it's your responsibility to write
> valid HTTP. That's precisely the thing that allows us to test invalid HTTP.

That is not how I interpreted the quoted text. By my reading, the term "must" indicates that protocol violations are explicitly not supported by the module or (put differently) there is no guarantee regarding the behavior of the module itself under these conditions.

I understand where you're coming from, though. Both my limited testing (as noted above) and a light reading of the standard library's source tend to support that interpretation. But as long as the word "must" is used in the documentation, I'm inclined to think that any stability we see today is coincidental. If the text instead used the term "should," then I would be more inclined to close this issue as "not necessary." This may be the case of a docs issue; I'll try to learn more.

**Comment by jgraham** [comment]
The documentation is presuming you want valid HTTP. If you do, and you're using this API (which is raw socket access) then you clearly must write valid HTTP. Not wanting valid HTTP is an unusual abberation confined to the fevered imaginations of evil minded testers. I don't think it's surprising that the documentation didn't cover this case :)

**Comment by jugglinmike** [comment]
I'm inclined to agree with you, but I'd still rather move forward with a little more certainty. Let's see if we can get some clarification via https://bugs.python.org/issue30160

**Comment by jugglinmike** [comment]
[The docs now read](https://docs.python.org/3.7/library/http.server.html#http.server.BaseHTTPRequestHandler.wfile):

> **`wfile`**
>
> > Contains the output stream for writing a response back to the client.
> > Proper adherence to the HTTP protocol must be used when writing to this
> > stream in order to achieve successful interoperation with HTTP clients.

Which makes this about the closest I've ever come to resolving an issue through pedantry alone.
