### ISSUE TITLE
idlharness.js cannot parse partial dictionary

### ISSUE THREAD

**Issue by soareschen** [w3c/web-platform-tests#5714]
Example WebIDL:

```
dictionary A {
  boolean a;
};

partial dictionary A {
  boolean b;
};
```

When attempt to parse the above definition using `idl_array.add_idls()`, the code fail with the error `Uncaught Duplicate identifier A`.

**Comment by JKereliuk** [comment]
Is there someone who can own this issue? @gsnedders, @soareschen

**Comment by alijuma** [comment]
This has priority:roadmap but no owner. Who's a good owner for this?
