### ISSUE TITLE
Bring back the edit buttons on the documentation

### ISSUE THREAD

**Issue by tobie** [w3c/web-platform-tests#5752]
When the docs were still on testthewebforward.org, there were an edit button on the each page that brought you directly to the editing that very page within the GitHub interface.

So for example:

http://web-platform-tests.org/writing-tests/testharness-api.html

would have a link to:

https://github.com/w3c/web-platform-tests/edit/master/docs/_writing-tests/testharness-api.md

It would be awesome to bring those back!

**Comment by gsnedders** [comment]
I was thinking that a few days ago, actually! Agreed this should happen.

Clearing myself as assignee as I'm unlikely to have time to do this for a week or two.

**Comment by tobie** [comment]
Yeah sorry, should have @-mentioned you rather than assigned you the bug.

**Comment by gsnedders** [comment]
This was done recently in #10004.
