### ISSUE TITLE
w3c-bots should not post new comments in old closed PRs

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#5783]
This is kinda related to #5611

@w3c-bots sometimes posts comments for old, closed or merged PRs.

e.g. https://github.com/w3c/web-platform-tests/pull/1 has been closed since Aug 12 2013, and today for some reason there were new bot comments, which are useful to nobody. Could the bot first check if the PR is open and if not, do nothing?

**Comment by bobholt** [comment]
I believe this was resolved by https://github.com/w3c/prbuildbot/pull/18. Feel free to reopen if that is not the case.
