### ISSUE TITLE
Notifying reviewers

### ISSUE THREAD

**Issue by tobie** [w3c/web-platform-tests#5784]
Following up on #5611, I removed the comments @wpt-pr-bot was adding to list PR OWNERS in favor of turning those into review requests instead.

Reviewers must have commit rights on the repo, though, so until every owner does, I'm still adding a comment if some of the owners wouldn't get notified otherwise.

Here's what those look like: 

![image](https://cloud.githubusercontent.com/assets/3392/25739661/1e1fac0a-3183-11e7-99cc-460c542b4bd2.png)

Here's how the algo works:

1. If the PR author already asked for someone to review the PR, stop here. They know better.
1. Otherwise
    1. Find all owners across relevant OWNERS file.
    1. Remove PR author from owners.
    1. Ask a review from all owners that are collaborators.
    1. If there are owners that are not collaborators, add a comment @-mentioning them.

It would be good to be able to point owners that are not collaborators to a contact or process for getting them added as collaborators to the project. Is there a link I can reference? Would you rather that comment said something different?

Is the algorithm OK? Are there changes you'd like to see?

**Comment by tobie** [comment]
After a conversation in irc, we decided to additionally tag PRs which didn't have collaborators in the OWNERS and thus which couldn't get the PR merged without external help.

The tag is [status:needs-collaborator](https://github.com/w3c/web-platform-tests/pulls?q=is%3Apr+is%3Aopen+label%3Astatus%3Aneeds-collaborator).

**Comment by jgraham** [comment]
I think we should comment that no OWNERs for this directory are able to merge and ask that they ping someone on irc for help merging or to be added as a collaborator. Someone watching that tag can help to ensure that we don't miss too many cases where this occurs.

**Comment by tobie** [comment]
OK, so added this. Don't really have great means of testing this without spamming everyone, so I deployed it and we'll see how it goes.

LMK if there are issues.

**Comment by tobie** [comment]
Also added a status:needs-owners label for when that's an issue.

**Comment by tobie** [comment]
Here's the script: https://github.com/tobie/ganesh/blob/master/lib/comment.js

**Comment by tobie** [comment]
@zcorpan: fixed the issue where the PR was considered contributor-less if the only contributor was the author. This should no longer be the case.

@foolip: you suggested OWNER files should be fetched recursively up to the repository root and all the contributors notified. This was avoided by design to limit the number of people notified for each pull request. I think that before we change this, we should see if the fix mentioned just above isn't sufficient for your case, then assess the impact of such a change on other owners, and finally see if there aren't other options we can use instead.

**Comment by jgraham** [comment]
If we look up the tree for more owners, I'd like to explicity ignore the root because we have some things that I ought to be notified on unavoidably in the root (e.g. `.travis.yml`), and I don't think that notifying me for every PR in the repo helps anyone :)

**Comment by foolip** [comment]
@jgraham, there is no OWNERS file in the root of the repository, do you mean in top-level directories?

In any case, I realize these are a bit different from Chromium's OWNERS files. We don't automatically ping all OWNERS, but rather the person who sends a review gets to pick whoever they like, and going up the tree if necessary to find someone responsive.

As an alternative to commenting, could we just add "everyone" as read-only collaborators, or is the problem that people have to accept an invitation so it can't be automated?

**Comment by tobie** [comment]
> In any case, I realize these are a bit different from Chromium's OWNERS files. We don't automatically ping all OWNERS, 

So the original design here was to ping whoever was in the first OWNER files that were found moving up to the root for each directory that was touched by the pull request. Proposal to include everyone up to the root is here: https://github.com/tobie/ganesh/pull/8 as that's the design people seem to prefer (I'm a bit concerned it's going to be less flexible and more noisy, but it that's what people prefer…).

> but rather the person who sends a review gets to pick whoever they like, and going up the tree if necessary to find someone responsive.

So the main problem is only collaborators get to pick reviewers.

> As an alternative to commenting, could we just add "everyone" as read-only collaborators, or is the problem that people have to accept an invitation so it can't be automated?

Are read only collaborators able to review code and/or add reviewers?

**Comment by tobie** [comment]
Are read-only collaborators even a thing? GitHub permissions baffle me.

**Comment by zcorpan** [comment]
Read-only collaborator is a thing. Such collaborators can be assigned to issues and be requested for review. (There are read-only collaborators for w3c/webvtt.)

**Comment by tobie** [comment]
Oh wow. @jgraham, would this do?

**Comment by tobie** [comment]
@zcorpan would you have a pointer for this in GH's doc somewhere?

**Comment by annevk** [comment]
https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/

**Comment by zcorpan** [comment]
I think https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator for the API

**Comment by zcorpan** [comment]
Note also the rate limit of 50 invitations per 24h

**Comment by tobie** [comment]
@zcorpan yeah—noticed. I think that should be fine, though.

**Comment by tobie** [comment]
And here's the breakdown I was looking for: https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by tobie** [comment]
OK, so it seems we can directly add contributors with the API, no need to invite them. So… providing owners with read privilege seems just fine.

Can @jgraham and maybe @sideshowbarker approve this?

**Comment by sideshowbarker** [comment]
> Can @jgraham and maybe @sideshowbarker approve this?

100% OK by me—thanks for getting this figured out

**Comment by jgraham** [comment]
Yes, I strongly approve.

**Comment by jdm** [comment]
https://github.com/w3c/web-platform-tests/pull/5905 suggests that we only look for an OWNERS file in the current directory. We should traverse up the directory hierarchy until one is found.

**Comment by tobie** [comment]
@jdm rather it suggests there's a bug in the code I pushed last night. :(

**Comment by tobie** [comment]
@jdm should be fixed now. Forgot to return a promise-returning function. :-/
