### ISSUE TITLE
Trailing # and ? in urltestdata.json

### ISSUE THREAD

**Issue by alwinb** [w3c/web-platform-tests#5790]
In the url tests, in urltestdata.json there are a few tests with surprising hash and search field. 

Tests that have a href property with a trailing `#` symbol have their hash property set to `""`. I would expect it to be `"#"`.

Likewise for tests with empty query strings, incidentally, only the tests that have a trailing `?` in their href attribute. There's currently no test containing `?#`. 

It would be surprising for URL strings `http://example.com/` `http://example.com/#` `http://example.com/?` and `http://example.com/?#` to all parse to the same record, yet the tests indicate that this is expected. 

**Edit** I mean to say, the API will return the same search and hash attributes for all of them: the empty string.

**Comment by annevk** [comment]
The data is what the API members should return, it's not reflecting the URL record. Note that `href` still has the trailing `?` or `#` in those tests. @domenic prefers it this way over having logic in the test wrapper and I don't care strongly enough.

Would you like to add a test for `?#`?

**Comment by alwinb** [comment]
I'd like to, but let me understand this first. The hash attribute getter returns `""` for URLs with a trailing `#` symbol. I just checked and it is in fact according to the spec. So it's actually a spec issue. I would expect it to say:

> The hash attribute’s getter must run these steps:
> - If context object’s url’s fragment is <del>either</del> null <del>or the empty string</del>, return the empty string.
> - Return U+0023 (#), followed by context object’s url’s fragment.

Likewise for the search attribute's getter --- as to distinguish the example URLs I gave by their hash and search attributes only. 

Should I open an issue there? I'm willing to make a PR as well, but haven't done that before.

**Comment by annevk** [comment]
No, see https://github.com/whatwg/url/issues/221. I'm happy to consider a new feature, but we cannot change the existing API contract.

**Comment by alwinb** [comment]
Thanks, that's the thread I was looking for.

**Comment by alwinb** [comment]
Too bad. Closing the issue as there's no way to change this without breaking the contract.
