### ISSUE TITLE
WebRTC: RTCCertificate.getFingerprints() is not tested.

### ISSUE THREAD

**Issue by henbos** [w3c/web-platform-tests#5796]
The only RTCCertificate related test we have is making sure RTCPeerConnection has a generateCertificate method and that RTCPeerConnection can be constructed with certificates.

We should verify that certificates can be generated and that they have fingerprints that are semicolon-separated hashes (FF:FF:FF...).

We should also verify that when an RTCPeerConnection is constructed with certificates specified that those fingerprints show up in the SDP offer.

**Comment by foolip** [comment]
@soareschen @rwaldron FYI.

@henbos, do you have tests in Chromium that can be used as a basis for these tests? It'd be good to avoid duplicating tests and later having to reconcile.

**Comment by henbos** [comment]
Yes, I verify getFingerprints() returns a fingerprint contained in the SDP here:
https://codereview.chromium.org/2828563002/diff/160001/chrome/test/data/webrtc/peerconnection.js
And verify it has a "hashy format" here:
https://codereview.chromium.org/2828563002/diff/160001/third_party/WebKit/LayoutTests/fast/peerconnection/RTCPeerConnection-generateCertificate.html

These could be the basis for web platform tests.
