### ISSUE TITLE
Update README to point to current doc

### ISSUE THREAD

**Issue by tobie** [w3c/web-platform-tests#5840]
Additional, remove duplicate info (e.g. lint).

**Comment by morrme** [comment]
I only see one link that is "broken", to the lint-tool doc (correct one should be https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/lint-tool.md ) . 

Are there others?

**Comment by tobie** [comment]
http://testthewebforward.org/docs/ (redirects, but still worth fixing)

**Comment by morrme** [comment]
@tobie submitted a PR but it needs an "owner". Will you help?

**Comment by tobie** [comment]
@morrme seems like you already have some review comments.
