### ISSUE TITLE
Assembling an OWNERS file for Web IDL

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#5892]
Who wants in? This means you'll get pinged whenever there's a test PR for the WebIDL/ directory.

/ccing some potential people. I'll work on a PR after a day or two containing the people who chime in here. Please feel free to direct your colleagues here too.

@domenic @bzbarsky @tobie @yuki3 @jensl @nox @samweinig

**Comment by jensl** [comment]
I'd be happy to help.

**Comment by tobie** [comment]
Yes please.

**Comment by yuki3** [comment]
> This means you'll get pinged whenever there's a test PR for the WebIDL/ directory.

Do you mean that I can use this as WATCHLISTS of chromium.org?  Then, I'd like to join and follow the changes of WPT/WebIDL.
If you're expecting me to be a reviewer, like OWNERS of chromium.org, then I wouldn't be a right person.

**Comment by tobie** [comment]
@yuki3 in practice, this pings you by adding you as a reviewer (because that's the simplest way to do so without adding a comment to the thread). Doesn't mean you _actually_ have to review the pull request.

**Comment by yuki3** [comment]
Thanks for the explanation, @tobie .  Then, please let me use this chance to watch the changes on WebIDL.

**Comment by tobie** [comment]
Would be neat to handle the interfaces dir while you're at it.

**Comment by bzbarsky** [comment]
I'm just as happy to get less email, so please leave me out.
