### ISSUE TITLE
In edge cases wpt-pr-bot asks for review on reviewed PRs

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#5918]
See #5619 for an example.

**Comment by tobie** [comment]
I'm in the process of cleaning this up.

**Comment by tobie** [comment]
OK, this should be fixed now. Please reopen if it shows up again.

**Comment by annevk** [comment]
Happened again: https://github.com/w3c/web-platform-tests/pull/5955#issuecomment-302030772.

**Comment by tobie** [comment]
Oh, now I understand! Folks who review are removed from the reviewrequested API. This is so dumb. Will fix.

Thanks for helping me get to the bottom of that.
