### ISSUE TITLE
Delete imported webgl conformance tests

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#5927]
https://github.com/w3c/web-platform-tests/tree/master/webgl/conformance-1.0.3 has tests imported from https://github.com/KhronosGroup/WebGL.git

The WebGL conformance tests are imported separately into Chromium, and having a copy of them in web-platform-tests means we need to block it from being imported.

@emilio @renchenglei @jdm, are these copied tests providing value?

**Comment by jdm** [comment]
They are the only tests for Servo's WebGL implementation. They are providing very high value for us.

**Comment by foolip** [comment]
Is this because you have a policy of *only* using web-platform-tests, or just that you haven't imported https://github.com/KhronosGroup/WebGL.git separately? How about https://github.com/tc39/test262?

**Comment by jdm** [comment]
Per the explanations in https://github.com/KhronosGroup/WebGL/issues/1105, our policy is to maximize the use of existing infrastructure whenever possible.

**Comment by gsnedders** [comment]
We need somehow to deal with the fact that they're essentially a fork of the upstream tests and make sure we stay in sync (and make sure any changes here make it back upstream, ideally; https://github.com/KhronosGroup/WebGL/pull/1320 is still open years later!). As it is, the two have diverged, which helps nobody.

**Comment by foolip** [comment]
@jdm, what would it take to import https://github.com/KhronosGroup/WebGL.git into Servo instead?

Ideally, all vendors should agree on what WebGL tests matter, and contribute to and run only those. My guess is that making it https://github.com/KhronosGroup/WebGL.git is the least disruptive. As suggested in https://codereview.chromium.org/2879443002/#msg15, that would include also merging the extra tests into the main WebGL test suite.

**Comment by foolip** [comment]
@jgraham, would you happen to know if these tests are used by Gecko as well?

**Comment by jdm** [comment]
They are not used by Gecko. It sounds like Servo should set up its own separate import of the webgl tests.

**Comment by jdm** [comment]
As the the comments about using a submodule, importing the tests also requires applying patches to make the tests run under the WPT harness.

**Comment by foolip** [comment]
(FWIW, I think it'd be great if WebGL tests were part of web-platform-tests to share a lot of infrastructure, no disagreement there.)

**Comment by gsnedders** [comment]
Ideally, we get upstream to move over to `testharness.js` and then everything becomes easy if we indeed decide we want to keep a copy here.

**Comment by foolip** [comment]
@jdm, do you have a tracking bug for importing the tests separately?

**Comment by jdm** [comment]
https://github.com/servo/servo/issues/17140

**Comment by jdm** [comment]
Fixed by https://github.com/w3c/web-platform-tests/pull/8017.

**Comment by foolip** [comment]
Yay, thanks @jdm!
