### ISSUE TITLE
Consider preferring relative path to testharness.js

### ISSUE THREAD

**Issue by RByers** [w3c/web-platform-tests#5945]
It [sounds like](https://lists.webkit.org/pipermail/webkit-dev/2017-May/029133.html) the biggest pain point for the WebKit project making more active use of web-platform-tests is the hassle of continuing to support loading many tests via the file:// protocol (eg. when debugging manually).  This was a bit of a pain in chromium too (though we eventually just required wptserve for all WPTs), and I continue to hit some cases where it would be handy to run a test outside of the wptserve environment (eg. via a rawgit.com URL or some such).  Obviously that's not going to work in all cases, but it's frustrating knowing that it would work 95% of the time if we were just using relative paths.

Is there a compelling reason not to just prefer relative URLs to testharness.js and testharnessreport.js?  I think we could pretty easily build a tool to automatically rewrite the paths when moving files from one directory to another.  We could do a bulk rewrite now, either for all tests or excluding those we can easily tell actually rely on wptserve.

/cc @rniwa @foolip @jgraham @sideshowbarker

**Comment by youennf** [comment]
One reason I know is ease of authoring.
Note that to a smaller extent, the same thing happens for common and media resources as well.

**Comment by jgraham** [comment]
So the 95% figure  is just wrong. Based on some quick greping I think at least 25% of all testharness.js test files depend on serever features. I expect that number to go up over time as more features depend on e.g. https and more tests use e.g. `.any.js` to ensure that they have the correct behaviour in worker contexts without duplication.

Presumably the number that depend on either server features or absolute paths (excluding testharness.js itself) is higher, and the number that depend on one of those things and have different behaviour under `file://` is higher again.

In addition to that I think there are valid reasons to prefer what we have now. It's simple and consistent. It makes moving tests much easier (within the repo and also from vendor specific directories, which we at least run under a special `/_mozilla/` path), to the main suite. It also makes it easier to read and author tests sine you don't end up playing "count the `..`". Changing this would also break tooling e.g. the lint/manifest generator which expect the exact strings as well as vendor specific tooling e.g. Mozilla's `mach wpt-create` command which produces the boilerplate for a test.

Although I think the "run from file" thing is superficially appealing, I think in the medium term win is to make it easier to run the server. That might need some special integration with wahtever tooling exists on the WebKit side.

**Comment by othermaciej** [comment]
75% is still pretty good. We definitely want to add WebKit tooling to make it easier to run tests under the wpt server. But it will never be as universally convenient as loading a file.

**Comment by foolip** [comment]
At one point, the paths were rewritten while importing into Chromium, which solved this problem by a fashion. But, it gets in the way of easy exporting, so we ditched that and had code to translate the absolute paths while running LayoutTests even while testing with file:// paths. That worked for a lot of tests, as long as one was using run-webkit-tests. Do WebKit developers normally do that?

For the convenience of running locally modified tests in any browser, that's hard in the general case, but just importing wptserve as-is and starting that might work? I'd actually like that for Chromium, the fact that it's different from upstream wpt is a bit of a nuisance.

**Comment by bobholt** [comment]
This sounds like a will-not-fix for the foreseeable future. Please reopen and comment if this should be readdressed.
