### ISSUE TITLE
requestmediakeysystemaccess.js expects MediaKeySystemConfiguration with no MediaCapabilities to be requestable

### ISSUE THREAD

**Issue by cpearce** [w3c/web-platform-tests#5951]
Step 15 of EME's [Get Supported Configuration and Consent algorithm](https://www.w3.org/TR/encrypted-media/#get-supported-configuration-and-consent) states:
> If the videoCapabilities and audioCapabilities members in candidate configuration are both empty, return NotSupported. 

But encrypted-media/scripts/requestmediakeysystemaccess.js is expecting in 3 cases that MediaKeySystemConfigurations without MediaCapabilities should be requestable. The cases are "Empty configuration", "Two configurations, one supported", and "Two configurations, both supported".

Chrome Canary is already failing on these cases as Chrome has started to enforce this, and I'm patching Firefox at the moment to also enforce this step in the spec.

**Comment by jrummell-chromium** [comment]
This is the same as issue #4279.
