### ISSUE TITLE
Dealing with existing flaky tests

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5997]
Status:
 * We have a long, long tail of tests added before the stability bots existed which may potentially be flaky (and, in principle, so may those upstreamed from Gecko, given they don't run through the stability bot).
 * We know some of these tests are flaky cross-browser due to problems in the test.
 * We don't have any realistic plan to get them all stable.

Options:
 1. We somehow disable them so that the manifest doesn't include them.
 2. We curate some cross-browser list of flaky tests.
 3. We delete them from the repo, and let people pull them out of the history if they want them back.

On the whole, I'm against 3 unless we expect nobody to fix them any time soon (and, as far as I'm aware, this is something Bocoup are in principle working on). I have no strong preference between the first two (and indeed the second could be how the first works).

cc/ @jgraham @RByers @foolip @thejohnjansen @youennf

**Comment by foolip** [comment]
@jugglinmike was working on flaky tests he could identify by running the tests over and over, but much to my surprise the state of things wasn't terrible, and it didn't seem like a very good use of time after the first batch.

If we had any way of detecting flaky tests and if they regularly affect PR stability results, then I think resuming those efforts would make sense.

**Comment by annevk** [comment]
Can we have a list of flaky tests first before we take action?

**Comment by bobholt** [comment]
@annevk: These are the ones @jugglinmike identified back in February/March: https://github.com/bocoup/wpt-dev/wiki/Flaky-Test-Log

**Comment by annevk** [comment]
It looks like this is pretty much a non-problem then. I suggest we don't take any action unless this starts to block something. Anyone who wants to is of course welcome to reduce the flakiness of tests in that list.

**Comment by bobholt** [comment]
The list from jugglinmike seems to have been sufficient to end discussion. Closing. Please reopen if this remains an issue.
