### ISSUE TITLE
[css-flexbox-1] Negative margins floored at zero?

### ISSUE THREAD

**Issue by markbrown** [w3c/web-platform-tests#6062]
PR [#919](https://github.com/w3c/csswg-test/pull/919) added a test requiring negative margins to be floored at zero for intrinsic size calculations. This behaviour doesn't appear to be specified anywhere, however.

Is this behaviour actually specified, or is the negative-margins-001.html test case incorrect?

**Comment by gsnedders** [comment]
cc/ @cbiesinger @tabatkins @fantasai
