### ISSUE TITLE
css/css-flexbox-1/css-flexbox-height-animation-stretch.html is classified as manual test

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#6122]
Run `./manifest` and then observe this in MANIFEST.json:
```JSON
  "css/css-flexbox-1/css-flexbox-height-animation-stretch.html": [
   "920082e81b7c98f1fb8a039d3e47295f3780ef61",
   "manual"
  ],
```

As a consequence, this test isn't running correctly when imported into Chromium.

@gsnedders, can you take a look or find someone who can?

**Comment by foolip** [comment]
This is probably a result of https://github.com/w3c/web-platform-tests/pull/6093

**Comment by gsnedders** [comment]
@foolip this was deliberate; we have no automated way to check that an animation never results in any red pixels

**Comment by foolip** [comment]
Thanks, filed https://bugs.chromium.org/p/chromium/issues/detail?id=728522
