### ISSUE TITLE
Improper use of Response.redirect in fetch/api/response/response-consume-stream.html

### ISSUE THREAD

**Issue by tphamg** [w3c/web-platform-tests#6144]
fetch/api/response/response-consume-stream.html improperly uses Response.redirect in the following code:
```
promise_test(function(test) {
    assert_equals(Response.redirect(301).body, null);
}, "Getting a redirect Response stream");
```
According to the standard, a url must be passed to the function.
 [NewObject] static Response redirect(USVString url, optional unsigned short status = 302);

**Comment by domenic** [comment]
This doesn't affect test correctness, BTW. It will just create a redirect to the URL given by resolving the string `"301"` against the appropriate base URL, with the default status code of 302.
