### ISSUE TITLE
cssom/style-sheet-interfaces-001.html fails on all browsers

### ISSUE THREAD

**Issue by jyc** [w3c/web-platform-tests#6203]
`cssom/style-sheet-interfaces-001.html` fails on all browsers solely because it uses `assert_own_property(o, p)` to check if some CSSOM object `o` has property `p` rather than using `p in o`. If the calls to `assert_own_property` are changed to `assert_true(p in o)`, this test instead passes on all browsers.

Is it justified to use `assert_own_property` in some spec?

**Comment by jdm** [comment]
That sounds bogus, since all non-Nathan WebIDL interfaces place their properties on the prototype object.

**Comment by gsnedders** [comment]
We shouldn't be using `in`, we should be checking its an own property wherever it's specified (and as @jdm says, provided it follows normal WebIDL behaviour it will be on the prototype).

**Comment by jyc** [comment]
Sorry for not seeing the first reply earlier. Here is the first test:

```
    var styleElement = document.getElementById("styleElement");
    var linkElement = document.getElementById("linkElement");

    var styleSheet;
    var linkSheet;

    test(function() {
        assert_own_property(styleElement, "sheet");
        assert_readonly(styleElement, "sheet");
        styleSheet = styleElement.sheet;
        assert_true(styleSheet instanceof CSSStyleSheet);
        assert_own_property(linkElement, "sheet");
        linkSheet = linkElement.sheet;
        assert_true(linkSheet instanceof CSSStyleSheet);
    }, "sheet_property",
    { help: "http://www.w3.org/TR/cssom-1/#the-linkstyle-interface",
      assert: [ "styleElement.sheet exists", "styleElement.sheet is a CSSStyleSheet",
                "linkElement.sheet exists", "linkElement.sheet is a CSSStyleSheet"] });
```

Is `sheet` an own property of `styleElement`, which is a `HTMLStyleElement`? [`HTMLStyleElement`](https://www.w3.org/TR/2016/REC-html51-20161101/document-metadata.html#the-style-element) implements `LinkStyle` which has `sheet`, so that is where it's specified, not on `HTMLStyleElement`.

If we go to http://example.com and run

```
let el = document.querySelector("style");
console.log(el.hasOwnProperty("sheet"));
```

in Firefox, Chrome, Safari, and Edge, the output is `false`, as it seems like we should expect.

Thus the first test fails before it is able to set `styleSheet = styleElement.sheet`, and all subsequent tests fail.

> That sounds bogus, since all non-Nathan WebIDL interfaces place their properties on the prototype object.

Moreover, an own property is [defined](https://tc39.github.io/ecma262/#sec-own-property) as a "property that is directly contained by its object", as opposed to an inherited property, which is a "property of an object that is **not an own property** but is a property (either own or inherited) of the object's **prototype**"; indeed `el.__proto__.sheet`" is defined, but `el` doesn't have `sheet` as an own property. Subsequently the other tests will also fail regardless of whether `styleSheet` is correctly defined because `el.sheet`.
