### ISSUE TITLE
Add Web Share tests

### ISSUE THREAD

**Issue by mgiuca** [w3c/web-platform-tests#6234]
Web Share is currently in WICG (https://wicg.github.io/web-share) and has an implementation in Chrome. It might be worth upstreaming Chrome's layout tests into web platform tests.

Unfortunately, these would need to be manual for the time being, since it requires a user gesture and involves browser UI.

See [Chrome bug #730333](https://bugs.chromium.org/p/chromium/issues/detail?id=730333).

I'm not clear on whether WPT only accepts tests for standardized APIs or whether this is fine in principle.

**Comment by mgiuca** [comment]
I've converted Chrome's Web Share layout tests into WPT manual tests in this branch:
https://github.com/mgiuca/web-platform-tests/tree/webshare

All tests pass in Chrome with --enable-experimental-web-platform-features.

**Comment by tobie** [comment]
LGTM. I'd just submit that as a PR if I was you. Note others might disagree.

**Comment by mgiuca** [comment]
Cool, thanks. I will do that but in writing them, I found a [spec issue](https://github.com/WICG/web-share/issues/34) which I'll fix first.

**Comment by tobie** [comment]
Fixed in https://github.com/w3c/web-platform-tests/pull/6287.
