### ISSUE TITLE
/browsing-the-web/scroll-to-fragid/003.html test wrong

### ISSUE THREAD

**Issue by pyfisch** [w3c/web-platform-tests#6289]
The test at `/html/browsers/browsing-the-web/scroll-to-fragid/003.html`.

This is a standards mode document (<!doctype html>). It is scrolled to some fragments. Then document.body.scrollTop is requested. It should be nonzero if the document is scrolled. The spec states that this is only true in quirks mode, in standards mode document.documentElement is scrolled. (The test passes if one replaces document.body with document.documentElement).

So the test should either be run in quirks mode or it should be changed to use documentElement.

See also servo/servo#17385

**Comment by fred-wang** [comment]
@pyfisch I submitted #9228 , but I used document.scrollingElement so that the test works in WebKit too.

**Comment by fred-wang** [comment]
Fixed by https://github.com/w3c/web-platform-tests/pull/9228
