### ISSUE TITLE
Chrome stability checker crashes without anything actionable in the logs

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#6293]
The stability checker for Chrome failed with the following message for a couple of PRs recently:

> WebDriverException: Message: unknown error: Chrome failed to start: crashed

https://github.com/w3c/web-platform-tests/pull/6248
https://github.com/w3c/web-platform-tests/pull/6211
https://github.com/w3c/web-platform-tests/pull/6243
https://github.com/w3c/web-platform-tests/pull/6264

This happened again when restarting the build. The tests themselves work fine in Chrome locally.

cc @RByers @bobholt

**Comment by RByers** [comment]
Thanks for the report. cc @foolip

**Comment by foolip** [comment]
@JKereliuk, this may well be ChromeDriver-related.

**Comment by foolip** [comment]
I've added this to [Ecosystem Infra 2017 Q3 OKRs](https://docs.google.com/document/d/1aRpnNQ7Zz_-N9ngdcjQXNjlE1NblppN7lCQwGdxRLlc/edit?usp=sharing).

**Comment by RByers** [comment]
@JKereliuk any idea if we've seen this lately?  Since we're using dev channel there's always the risk of a Chrome bug causing a crash on startup.  Ideally the log would give us something actionable though.  IIRC Chrome outputs the crash ID (as seen in chrome://crashes) to the console when is crashes, can we get that into the logs?  Then we can use go/chromecrash to get a callstack and track/file a specific chromium bug.

**Comment by JKereliuk** [comment]
I haven't seen this lately myself. I tried briefly to reproduce this awhile ago and could not.

I will figure out how to get the crash ID into the log, I think that sounds like a good idea as the current message is less than useful :)

**Comment by RByers** [comment]
Great, thanks.  For testing you can have the browser visit some of the special crash-inducing URLs at the bottom of chrome://about/ (in renderer crashes and browser crashes will behave differently).

**Comment by bobholt** [comment]
We're crossing our fingers and waiting for a chromedriver release. Will update this issue then.

**Comment by JKereliuk** [comment]
Whoops this one fell through the cracks, I'll put it on my radar for this week.

**Comment by foolip** [comment]
@kereliuk, this is still assigned to you, is this fixed now, or not possible to reproduce?

**Comment by foolip** [comment]
With some recent fixes by @Hexclew the Chrome job is now blocking so I'm pretty sure this is resolved and if it did happen frequently we would have noticed.
