### ISSUE TITLE
How to get in touch with W3C

### ISSUE THREAD

**Issue by photopea** [w3c/web-platform-tests#6338]
Hi, 

I had an idea about a new thing, which I really miss on the web. Is there any way a person outside W3C can suggest a new feature, and some "W3C authorities" would take a look at it?

I wrote my current ideas in this text: https://github.com/photopea/AppNow . I would like to start a discussion about it. I know, that it has no relation to this repository, but I could not find any better place to get in touch with W3C.

**Comment by sideshowbarker** [comment]
Hi @photopea— https://discourse.wicg.io/ would be a great place to start a discussion about it

**Comment by photopea** [comment]
Thanks!
