### ISSUE TITLE
Where should font tests live?

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#6434]
In https://github.com/w3c/web-platform-tests/pull/6350 and https://github.com/w3c/web-platform-tests/pull/6360 some new tests by drott@ (yay!) were upstreamed under the fonts/ directory, where there previously were only font files.

I haven't looked too closely, but it looks like these are at least in part tests for CSS features. @gsnedders, can you advise on whether fonts/ is a good place for these, and close this issue if you think it's OK?

**Comment by foolip** [comment]
Oh, also @drott, could you add OWNERS files to these new directories with yourself and anyone else who would be a good reviewer? (Has to be done on GitHub because we use OWNERS files differently downstream, so they're not imported.)

**Comment by jgraham** [comment]
`fonts` was inteded for support files. Maybe we should have had some convention to distinguish such directories. Which spec do these tests cover?

**Comment by foolip** [comment]
https://drafts.csswg.org/css-fonts-4/ is part of it, anything else, @drott?

**Comment by drott** [comment]
> Oh, also @drott, could you add OWNERS files to these new directories with yourself and anyone else who would be a good reviewer?

Sure, PR #6437 

> https://drafts.csswg.org/css-fonts-4/ is part of it, anything else, @drott?

Yes, these new tests all cover OpenType variations aspects: The first set tests certain more in-depth font features such as GPOS and GSUB with variation axes. The second set tests the font matching with variable fonts and ranges for stretch, style, weight.

I'm happy to move them elsewhere if that's the recommendation. However, I read that putting them under css/ was not recommended practice anymore, and thought that fonts/ would match the spec short name, so I placed them here for now.

**Comment by foolip** [comment]
@gsnedders, for the bits that are in fact testing https://drafts.csswg.org/css-fonts-4/, I assume you'd recommend the directory name css-fonts/? What to do about the fact that https://github.com/w3c/web-platform-tests/tree/master/css/css-fonts-3 also exists?

**Comment by gsnedders** [comment]
@foolip yes, and ignore it.

**Comment by foolip** [comment]
@drott, would both of these directories make sense under css-fonts/, or should some actually be tests for the format, akin to apng/?

**Comment by drott** [comment]
Both make sense under css-fonts/, i.e. `css-fonts/variations` and `css-fonts/matching`.

**Comment by foolip** [comment]
Great, would you mind submitting a PR to do the move? Leaving a README.md in fonts/ that explains that it's only for support files would also be good, if you think it would have helped you.
