### ISSUE TITLE
removeTrack test should not rely on Transceivers

### ISSUE THREAD

**Issue by jan-ivar** [w3c/web-platform-tests#6453]
@soareschen It's great to see modern tests for `addTrack`/`removeTrack`!

Even better would be them following the [evolution](https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/) that justifies their existence.

Specifically, I don't think we should require `addTransceiver` (a stage 3 api) to test `removeTrack` (a stage 2 api), when we can use `addTrack` (a stage 2 api) which returns a sender. IMHO we should use the same abstraction level.

E.g. Firefox has supported `removeTrack` for [almost 3 years](https://hg.mozilla.org/mozilla-central/rev/79525105ef9a), yet won't pass any of the `removeTrack` tests [as written](https://github.com/w3c/web-platform-tests/pull/6251/files) because they require `addTransceiver`.

**Comment by nils-ohlmeier** [comment]
I find it also interesting that these test have landed even though not a single browser has passed them. So how do we know if there are bugs in the test?

**Comment by soareschen** [comment]
@jan-ivar got it. I will add new test cases that generate and add tracks from `getUserMedia` and `addTrack`. I think it is still good to keep the existing tests that rely on transceivers, as they eventually still need to be integrated and passed.

**Comment by soareschen** [comment]
> So how do we know if there are bugs in the test?

That is a good question which I do not have enough experience to answer. My current approach is to rely on reviewers and implementers to find out mistakes in tests, and file new issues to report them. If anyone have better ways, I am glad to hear as well.
