### ISSUE TITLE
Running tests docs should reference wptrun, not wptrunner directly

### ISSUE THREAD

**Issue by RByers** [w3c/web-platform-tests#6458]
the [running docs](http://web-platform-tests.org/running-tests/index.html) say to use `wptrunner` but on IRC jgraham said:

> So wptrunner is the generic test running tool. wptrun is a frontend on that which sets it up correctly for running from a wpt checkout
> Eventually wptrun will be spelled |wpt run| and there will be a bunch of other wpt subcommands
> Yeah, using wptrunner directly is not really recommended since it's rather generic and hard to get going

The [GitHub README](https://github.com/w3c/web-platform-tests/blob/master/README.md#running-tests-automatically) says just to use `wptrun` and that seems much simpler and easier to setup.  It's unfortunate that our two sources of docs can get out of date here.  Since the web-platform-tests.org docs don't currently add any additional information on running, perhaps they should just link to the README for that to prevent this sort of confusion in the future?

**Comment by gsnedders** [comment]
This got fixed in #6751.
