### ISSUE TITLE
CORS test incorrectly setting Content-Length

### ISSUE THREAD

**Issue by asajeffrey** [w3c/web-platform-tests#6471]
In https://github.com/w3c/web-platform-tests/blob/d6102e6097670a68abae60c6c24cc8060d9ac379/fetch/api/cors/cors-filtering.js#L59 there's a test:
```js
corsFilter(url, "Content-Length", "0" , true);
```
which asks the HTTP server to set the the `Content-Length` header to be `0`. Since the content is `top`, this causes `top` to be interpreted as the beginning of the HTTP response to the next HTTP request, so the next test to run on that connection fails. This causes nondeterministic test failure, as seen here: https://github.com/servo/servo/pull/16508#issuecomment-312979555

**Comment by annevk** [comment]
@youennf can you fix this?

**Comment by getsetbro** [comment]
Is this why IE11 is shown to FAIL when it actually followed all 5 redirects?

**Comment by annevk** [comment]
@jugglinmike hey look a similar issue to that other one.

**Comment by jugglinmike** [comment]
Well would you look at that. [This comment](https://github.com/w3c/web-platform-tests/pull/5227#issuecomment-292201147) from @ericlaw1979] may be of particular interest:

> Long ago, I conducted a related survey on this topic:
> https://blogs.msdn.microsoft.com/ieinternals/2011/03/09/content-length-in-the-real-world/.
>
> The Microsoft Edge team noted a real-world site with a compatibility issue
> related to ignoring junk: The page http://www.ntvmsnbc.com/id/25015435 sent
> back, "GET HTTP/1.1 301 Moved Permanently”, as the status line. This is
> obviously completely invalid, but since Chrome is allowing the 4 bytes of
> junk it succeeds.

**Comment by getsetbro** [comment]
When does this change get published to w3c-test.org?

**Comment by annevk** [comment]
http://w3c-test.org/fetch/api/cors/cors-filtering.js already says "3" instead of "0" here.

**Comment by getsetbro** [comment]
Sorry I've been talking about this test http://w3c-test.org/cors/redirect-preflight.htm. Should I make a separate issue?

**Comment by annevk** [comment]
@getsetbro yes, feel free to copy me.
