### ISSUE TITLE
discrete-animation tests expects oblique/italic distinction

### ISSUE THREAD

**Issue by drott** [w3c/web-platform-tests#6518]
https://github.com/w3c/web-platform-tests/blob/master/web-animations/animation-model/animation-types/discrete-animation.html#L93

expects a transition between italic and oblique, but not all UAs implement a distinction between italic and oblique. In CSS Fonts 4, UAs are allowed to treat italic and oblique as synonyms, [compare the font-style property in CSS-fonts-4](https://drafts.csswg.org/css-fonts-4/#font-style-prop).

"For the purposes of font matching, User Agents may treat italic as a synonym for oblique. For User Agents which treat these values distinctly, synthesis must not be performed for italic. All user agents may perform synthesis for oblique."

Perhaps this test can be adapted to use different discrete values or a different property?

CC @birtles

**Comment by birtles** [comment]
As I read that, the two values are only synonyms for font matching, and shouldn't affect the result of `getComputedStyle`?

If it turns out UAs are allowed to turn `italic` into `oblique` in `getComputedStyle` then I have no problem with changing that test.

**Comment by drott** [comment]
Yes, in CSS Fonts Level 4 UAs are allowed to treat them as synonyms and an `oblique` may be turned into an `italic` in `getComputedStyle`.
