### ISSUE TITLE
There are some tests for the error reporting of custom elements, but the error reporting behavior isn't clear yet

### ISSUE THREAD

**Issue by EdgarChen** [w3c/web-platform-tests#6534]
The error reporting behavior isn't clear yet, see the spec discussion: https://github.com/w3c/webcomponents/issues/635.

But there are some tests start testing it, especially https://github.com/w3c/web-platform-tests/blob/master/custom-elements/upgrading/Node-cloneNode.html.

Should we remove the error reporting test since it is still not clear?

/cc @domenic

**Comment by domenic** [comment]
I think the behavior is very clear when there are not multiple globals involved. Can we revise the tests to not involve multiple globals instead?

**Comment by EdgarChen** [comment]
Yes, I will work on the patch. Thank you.

**Comment by EdgarChen** [comment]
https://github.com/w3c/web-platform-tests/pull/6542

**Comment by EdgarChen** [comment]
#6542 has been merged, close this issue.
