### ISSUE TITLE
PR test results aren't being generated - libssl error

### ISSUE THREAD

**Issue by RByers** [w3c/web-platform-tests#6544]
Looking at recent PRs I don't see any prbuildbot results since about July 4th.  

/cc @sideshowbarker who says he upgraded the server to Debian stretch around that time and points out that https://w3c-test.org/prbuildbot.py generates the following error:

```
{
  "error": {
    "message": "libssl.so.1.0.0: cannot open shared object file: No such file or directory\nTraceback (most recent call last):\n  File \"\/u\/www.w3c-test.org\/web-platform-tests\/master\/tools\/wptserve\/wptserve\/server.py\", line 254, in handle_one_request\n    handler(request, response)\n  File \"\/u\/www.w3c-test.org\/web-platform-tests\/master\/tools\/wptserve\/wptserve\/handlers.py\", line 234, in __call__\n    execfile(path, environ, environ)\n  File \"\/u\/www.w3c-test.org\/web-platform-tests\/master\/prbuildbot.py\", line 8, in <module>\n    from webhook_handler import webhook_handler\n  File \"\/u\/www.w3c-test.org\/web-platform-tests\/master\/webhook_handler.py\", line 8, in <module>\n    from travis import Travis\n  File \"\/u\/www.w3c-test.org\/web-platform-tests\/master\/travis.py\", line 14, in <module>\n    from OpenSSL.crypto import verify, load_publickey, FILETYPE_PEM, X509\n  File \"\/usr\/local\/lib\/python2.7\/dist-packages\/OpenSSL\/__init__.py\", line 8, in <module>\n    from OpenSSL import rand, crypto, SSL\n  File \"\/usr\/local\/lib\/python2.7\/dist-packages\/OpenSSL\/rand.py\", line 12, in <module>\n    from OpenSSL._util import (\n  File \"\/usr\/local\/lib\/python2.7\/dist-packages\/OpenSSL\/_util.py\", line 6, in <module>\n    from cryptography.hazmat.bindings.openssl.binding import Binding\n  File \"\/usr\/local\/lib\/python2.7\/dist-packages\/cryptography\/hazmat\/bindings\/openssl\/binding.py\", line 14, in <module>\n    from cryptography.hazmat.bindings._openssl import ffi, lib\nImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory\n",
    "code": 500
  }
}
```

**Comment by sideshowbarker** [comment]
Sorry about this. We upgraded the server to Debian stretch a week or so ago, and had not noticed that it broke this.

Anyway as far as I can see I’ve now got it fixed (by force-reinstalling python cryptography and dependencies with pip)

**Comment by RByers** [comment]
Thanks Mike, indeed I'm [seeing results again](https://github.com/w3c/web-platform-tests/pull/6545) now.

Bob, perhaps it's worth exploring how we missed this 9-day outage to reduce the chance of it happening again?  I'm surprised nobody else reported it.  I noticed just because I was doing "chromium ecosystem infrastructure rotation" checking on the status of our export jobs.

**Comment by bobholt** [comment]
So I have a hypotheses. 

We often code-review PRs while the build is still running (so no comments. Assuming the review is good and someone has approved it we basically auto-merge the PR when it gets marked as mergeable ("when the light is green, the trap is clean"). Even if the code review happens post-build, that green light habit rules and we don't even look for the comments unless the PR is unmergeable.

As an anecdotal example, I've reviewed a couple of PRs in the last week while the build was still running. I made my comments and approval, and never looked at them again, assuming that if the build passed there was nothing to look at.

I'm a little surprised that it didn't get noticed in the rotation, but I believe that it is largely the same issue (only looking at issues if they don't merge) with the added bit of people new to the rotation maybe not recognizing what should and shouldn't be in the comments. I just checked the rotation doc, and the heuristic tells people to "stop here" if the PRs land and then only directs the person on rotation to "try to understand the failure" if they don't. I've added suggestions to the doc to indicate that there should be browser-specific comments in the GitHub issue indicating which browsers failed and which provide links back to those specific CI jobs.

That might improve that small part for one reviewer a day, but we still have the larger social issue of not noticing/caring on a day-to-day basis. @sideshowbarker proposed having some sort of technical watchdog, but it probably says a lot about the usefulness of the comments that nobody either noticed or said anything, so what can we do to address that?

**Comment by RByers** [comment]
Yeah that's a good point.  It's certainly reasonable to assume that no news is good news on the stability front, but what about for consistent test failures?  I'd hope that when most people write WPT PRs they'd want to know what browsers they're passing vs. failing in to ensure it matches their expectation.

For example, where did we ever get to with the "highlight tests that passed on some browser before the change but not after it" goal we originally had?

Anyway given the prbuildbot is about to be replaced I'm OK ignoring this for now and revisiting once we have the new system.  I can totally imagine blocking PRs until there are results and tweaking the UI to ensure it highlights the things that are likely to be interesting. Then it would actually be a good thing if people ignored the result when there's nothing highlighting, as long as they're paying attention when the system highlights an issue for their investigation :-)
