### ISSUE TITLE
The issue of test case skip-waiting-installed.https.html

### ISSUE THREAD

**Issue by xzhan96** [w3c/web-platform-tests#6548]
There is a discussion about the behavior of skipWaiting() in [ServiceWorker issues 1015](https://github.com/w3c/ServiceWorker/issues/1015) , and the final decision should be in [pull 1019](https://github.com/w3c/ServiceWorker/pull/1019):

>  **promise resolves right away after setting the skip waiting flag**

If I understand right, then there maybe a issue in the test skip-waiting-installed.https.html.
```
    var saw_message = new Promise(function(resolve) {
        onmessage = function(e) {
            resolve(e.data);
          };
        })
      .then(function(message) {
          assert_equals(
            message, 'PASS',
            'skipWaiting promise should be resolved with undefined');

          assert_equals(registration.active.scriptURL, normalizeURL(url2),
                        'skipWaiting should make worker become active');
        });
```
When the saw_message was called, **registration.active.scriptURL** should be still url1 instead of url2, because skipWaiting() will be executed just after new service worker is "installed" and before it become "activating"/"activated".

**Comment by xzhan96** [comment]
@wanderview please check if it is a issue.

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by sideshowbarker** [comment]
w3c-test:mirror

**Comment by wanderview** [comment]
I'm on PTO this week.  @asutherland, what do you think?

**Comment by xzhan96** [comment]
@asutherland could you confirm if it's an issue?

**Comment by asutherland** [comment]
Apologies for the delay; I've improved my email filters for mentions.

Yes, the test was wrong.  Your fix on https://github.com/w3c/web-platform-tests/pull/6564 is consistent with the [gecko-local patch](https://bug1318142.bmoattachments.org/attachment.cgi?id=8827764) I had on [bug 1318142](https://bugzilla.mozilla.org/show_bug.cgi?id=1318142) which was the original source of the issue I raised.

**Comment by makotoshimazu** [comment]
@xzhan96 
There is daily (weekly?) sync for layout tests in external/wpt. We don't need to cherry-pick manually.

**Comment by xzhan96** [comment]
Ok, so let's wait for asutherland's patch. Can we know when it will be merged?

**Comment by asutherland** [comment]
@xzhan96 I think it makes sense to keep and merge your #6564 fix now.  My efforts on that bug have not yet landed in Gecko and it will be at least a week (possibly longer) before they do.

**Comment by xzhan96** [comment]
Ok, thanks a lot. :-)
