### ISSUE TITLE
html/dom/interfaces.worker.js is broken

### ISSUE THREAD

**Issue by inexorabletash** [w3c/web-platform-tests#6621]
Broken c/o https://github.com/w3c/web-platform-tests/pull/5666

The test depends on html/dom/resources/*.idl files which no longer exist.

It should probably be merged in with html/dom/interfaces.html as an "any.js" test or some such.

**Comment by foolip** [comment]
Submitted https://github.com/w3c/web-platform-tests/pull/6661 to fix the immediate issue without attempting to merge the tests into an any.js test.
