### ISSUE TITLE
scrollIntoView-empty-args.html test is flaky

### ISSUE THREAD

**Issue by majido** [w3c/web-platform-tests#6811]
The test depends on window size so it is flaky. For example load [1] in Chrome and change the window size to be smaller than 500px then the test fails.

A simple fix will be to use an inner container to scroll and verify its offset instead of depending on the window.

[1] https://w3c-test.org/cssom-view/scrollIntoView-empty-args.html

**Comment by gsnedders** [comment]
> The test depends on window size so it is flaky. For example load [1] in Chrome and change the window size to be smaller than 500px then the test fails.

I think we define the viewport size to be at least 600x600px?

**Comment by majido** [comment]
I think it was failing when the window was too large too. In any case, I sent a pr which fixed it.

As a side note, I was under the impression that it should be possible to run most tests in a regular browser using `/tools/runner/index.html`. In this case that browser window size will affect the outcome.
Perhaps worth mentioning the minimum browser window size in the [documentation](http://web-platform-tests.org/running-tests/index.html).

**Comment by majido** [comment]
Here is the [PR](https://github.com/w3c/web-platform-tests/pull/6813) mentioned above.
