### ISSUE TITLE
[wptrunner] --sauce-platform argument doesn't accept platforms with spaces

### ISSUE THREAD

**Issue by jeffcarp** [w3c/web-platform-tests#6852]
For running tests on Sauce via `wptrunner` on the command line, passing a platform with spaces in it isn't currently possible. For example, I need to run tests on the platform `Windows 10`, but passing `--sauce-platform="Windows 10"` isn't possible.

**Comment by jugglinmike** [comment]
I've been trying to recreate this problem locally, but I haven't had any luck.
It's my understanding that the WPT CLI uses the built-in `argparse` module in a
pretty standard way and that the `argparse` module handles this case without
issue.

@jeffcarp and/or @jgraham: could you weigh in on this? I would like to remove
some code in the WPT dashboard project that modifies the WPT CLI.

Here's my attempt:

```py
import argparse
import subprocess
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--sauce-platform')

args = parser.parse_args()

if (args.sauce_platform):
    print '--> (in subprocess) args.sauce_platform: %s' % repr(args.sauce_platform)
    sys.exit(0)

invocations = [
  ['python', __file__, '--sauce-platform', 'windows 10'],
  ['python', __file__, '--sauce-platform=windows 10'],
  ['python', __file__, '--sauce-platform', '"windows 10"'],
  ['python', __file__, '--sauce-platform="windows 10"']
]

for args in invocations:
    print 'For arguments %s:' % args
    proc = subprocess.Popen(args)

    proc.wait()
```

And the output:

    For arguments ['python', 'experiments/argparse-spaces.py', '--sauce-platform', 'windows 10']:
    --> (in subprocess) args.sauce_platform: 'windows 10'
    For arguments ['python', 'experiments/argparse-spaces.py', '--sauce-platform=windows 10']:
    --> (in subprocess) args.sauce_platform: 'windows 10'
    For arguments ['python', 'experiments/argparse-spaces.py', '--sauce-platform', '"windows 10"']:
    --> (in subprocess) args.sauce_platform: '"windows 10"'
    For arguments ['python', 'experiments/argparse-spaces.py', '--sauce-platform="windows 10"']:
    --> (in subprocess) args.sauce_platform: '"windows 10"'

I added those last two examples because in description of this issue, Jeff
mentions attempting to quote the option's value. It's hard to say how he was
attempting to do this, but he may have been motivated by the way the Python
interpreter interacts with the shell. As demonstrated above, that pattern
produces undesired results in the absence of a shell, so this may not have been
an issue all along.

**Comment by jeffcarp** [comment]
@jugglinmike thank you for looking into this, interaction between Python & the shell (and ignorance thereof on my part) sounds like it could very well be the cause for this. One idea is that the wpt.fyi test runner uses [suprocess.call](https://github.com/w3c/wptdashboard/blob/master/run/run.py#L193), maybe the arguments are formatted incorrectly there.

Fyi closing this issue also closes part of https://github.com/w3c/wptdashboard/issues/142

**Comment by jgraham** [comment]
Try writing it as `["--sauce-platform", "windows 10"]` in the `call`. Certainly spaces are expected to work (and quoting in that case is not).

**Comment by jugglinmike** [comment]
Thanks Jeff and James! That's a good point about `subprocess.Poopn` versus `subprocess.call`, Jeff. To avoid doubt, I've modified that script to use the latter:

```python
import argparse
import subprocess
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--sauce-platform')

args = parser.parse_args()

if (args.sauce_platform):
    print '--> (in subprocess) args.sauce_platform: %s' % repr(args.sauce_platform)
    sys.exit(0)

invocations = [
  ['python', __file__, '--sauce-platform', 'windows 10'],
  ['python', __file__, '--sauce-platform=windows 10'],
  ['python', __file__, '--sauce-platform', '"windows 10"'],
  ['python', __file__, '--sauce-platform="windows 10"']
]

for args in invocations:
    print 'For arguments %s:' % args
    subprocess.call(args)
```

...and I see the same results. So I think this issue is safe to close!

**Comment by jeffcarp** [comment]
Thanks @jugglinmike, will close now and when I get the chance I'll try removing this patch from wpt.fyi. I'll reopen if I run into anything.

**Comment by jugglinmike** [comment]
Great! I've opened a pull request to remove the patching logic: https://github.com/w3c/wptdashboard/pull/457

**Comment by jeffcarp** [comment]
Fantastic, thanks so much!
