### ISSUE TITLE
abort-after-send.htm recent changes seem wrong

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#6940]
https://github.com/w3c/web-platform-tests/commit/a9f8fbcfc8aa2e301cd9693be6fbb9a739d44989 by @shuangMoz seems incorrect. In this test, there is no body, so the upload complete flag is set in step 8 of https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send. Then, when we get to https://xhr.spec.whatwg.org/#request-error-steps, we thus fire no events on the XMLHttpRequestUpload object.

Notably Firefox, Chrome, and Edge (all stable) do not match the test change. I think we should revert it.

**Comment by shuangMoz** [comment]
I'm sorry, that indeed looks wrong :(

**Comment by TimothyGu** [comment]
Fixed in 50da72aad66a06cde2367170ea1caf3885a34d0b.
