### ISSUE TITLE
PaymentRequest interfaces should be fetch()`ed

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-platform-tests#7069]
The PaymentRequest interface tests are currently copy/pasted from the spec... but this means that they risk falling out of date. Instead, we should `fetch()` them.

**Comment by marcoscaceres** [comment]
@zcorpan informs me that there is a `interfaces` directory from which these should instead be fetched.

**Comment by zcorpan** [comment]
It won't be out of date if there's a policy to update web-platform-tests for normative spec changes. ;-)

**Comment by marcoscaceres** [comment]
We have that in place for Payment Request ... struggling to get people to see the light with specs tho 😭
