### ISSUE TITLE
./wpt run doesn't support Safari

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#7124]
Safari isn't supported as a product. It should be.

**Comment by gsnedders** [comment]
Apparently we never landed actual Safari support in wptrunner, only Sauce support. See https://github.com/w3c/wptrunner/pull/225.

**Comment by mattl** [comment]
I am starting to look into this

**Comment by mattl** [comment]
@foolip I can't self assign this

**Comment by jgraham** [comment]
There shouldn't be much to do here. The previous patch worked, although these days some integration into `wpt run` will be necessary. The main problem before was the no one reviewed it, although I guess if you do the work I can review and we can sidestep that problem.

There are also problems unique to Safari as I believe it takes manual work to enable automation. Maybe that's improved  now?

**Comment by gsnedders** [comment]
@jgraham Enabling automation is fixed with High Sierra.

**Comment by gsnedders** [comment]
The PR for this is now in <https://github.com/w3c/web-platform-tests/pull/8979>.

As for enabling automation, this was fixed generally in Safari 11, not just High Sierra.

**Comment by gsnedders** [comment]
Fixed by #8979.
