### ISSUE TITLE
wptupdate is broken

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7126]
Originally posted as https://github.com/w3c/wptrunner/issues/46 by @Ms2ger on 06 Nov 2014, 16:59 UTC:

> ```
> include_types = set(manifest.item_types) ^ exclude_types
> ```
> 
> at https://github.com/w3c/wptrunner/blob/7825f82f22da3ecabb4102edb3d4548955954863/wptrunner/metadata.py#L269 no longer works, because item_types is gone.

**Comment by foolip** [comment]
Issue is 3 years old and the code doesn't look like this any longer, assuming fixed.
