### ISSUE TITLE
Servo crash detection looks like it's broken

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7130]
Originally posted as https://github.com/w3c/wptrunner/issues/105 by @jdm on 25 Apr 2015, 14:56 UTC:

> https://github.com/servo/servo/pull/5839#issuecomment-96191539
> 
> We have no more `expected: CRASH` annotations in the Servo WPT test expectations, and I'm sure we did a few days ago before the wptrunner upgrade.

**Comment by nox** [comment]
We have `CRASH` results in Servo so that probably can be closed.
