### ISSUE TITLE
dismiss_user_prompts uses nonexistent Session.alert property

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7138]
Originally posted as https://github.com/w3c/wptrunner/issues/203 by @jdm on 13 Sep 2016, 23:00 UTC:

> After fixing some remaining issues, I got webdriver tests working in Servo, but I hit the code in `dismiss_user_prompts` in `fixtures.py`. It uses `self.client.alert.dismiss()`, where `self.client` is a `wptrunner.executors.webdriver.Session` object. This object has no `alert` property defined, and neither does the `Session` defined in wdclient's client.py (which I have no idea how it's related, but there appears to be a lot of overlap?)

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptrunner/issues/203#issuecomment-246857244 by @jdm on 13 Sep 2016, 23:21 UTC:

> I have fixed this in https://github.com/servo/servo/pull/13261/commits/c73ecf7029509542ea78214b7b9c443982702b8a.

**Comment by bobholt** [comment]
Per the comments, this appears to have been resolved upstream.
