### ISSUE TITLE
Make sure screenshots are only taken after fonts have loaded for reftests

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7141]
Originally posted as https://github.com/w3c/wptrunner/issues/241 by @gsnedders on 21 Mar 2017, 21:38 UTC:

> see thread from https://lists.w3.org/Archives/Public/public-test-infra/2017JanMar/0024.html
> 
> tl;dr: we need to make sure all fonts have loaded before taking screenshots

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptrunner/issues/241#issuecomment-293010115 by @gsnedders on 10 Apr 2017, 16:51 UTC:

> https://github.com/w3c/web-platform-tests/pull/5525 shows every browser blocking the load event on fonts? uhhhh. I'm confused now.

**Comment by bobholt** [comment]
@gsnedders: Was this resolved by https://github.com/w3c/web-platform-tests/pull/6558?

**Comment by gsnedders** [comment]
Realistically part of #6329 at this point; should just close this and deal with it there.
