### ISSUE TITLE
sequential_async_test

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7157]
Originally posted as https://github.com/w3c/testharness.js/issues/96 by @mvano on 09 Dec 2014, 14:16 UTC:

> I'd like to run multiple async tests from a single page, but execute them sequentially, not in parallel. The idea would be for later tests to delay execution until the previous ones are done.
> 
> The goal would be to make tests that share state (across the tests, or in the object under test) be deterministic. Here's a contrived example:
> 
> ``` javascript
> var i = 0;
> 
> sequential_async_test(function(test) {
>     setTimeout(function() {
>         assert_equals(i, 0);
>         i++;
>         test.done();
>     }, Math.round(Math.random() * 100));
> }, 'Async test 0');
> 
> sequential_async_test(function(test) {
>     setTimeout(function() {
>         assert_equals(i, 1);
>         i++;
>         test.done();
>     }, Math.round(Math.random() * 100));
> }, 'Async test 1');
> ```
> 
> I guess the alternative is to make separate pages, each with a single `async_test`. I'll probably do that for the time being.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/96#issuecomment-66288410 by @mvano on 09 Dec 2014, 14:18 UTC:

> @mounirlamouri @beverloo because we discussed this earlier

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/96#issuecomment-154431584 by @jgraham on 06 Nov 2015, 15:02 UTC:

> You can use add_result_callback to achieve this.

**Comment by bobholt** [comment]
This appears to be resolvable with user code. Closing.
