### ISSUE TITLE
Add a user-gesture helper function

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7160]
Originally posted as https://github.com/w3c/testharness.js/issues/142 by @jyasskin on 28 Jul 2015, 22:39 UTC:

> Several web platform features [need to be called during a user gesture](https://html.spec.whatwg.org/multipage/browsers.html#allowed-to-show-a-popup), but there's no function in testharness.js to accomplish that. In Blink we have 2 ways to do this, for [pointerLock](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/http/tests/resources/pointer-lock/pointer-lock-test-harness.js&l=12) and for [Web Bluetooth](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/bluetooth/bluetooth-helpers.js&l=43), both of which rely on a Blink-specific [`eventSender`](https://code.google.com/p/chromium/codesearch#chromium/src/components/test_runner/event_sender.cc&l=495) interface to send the trusted event.
> 
> We'd [like to upstream one of these](https://crbug.com/509058). Please let us know the best way to do that.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/142#issuecomment-140189559 by @cvrebert on 14 Sep 2015, 19:57 UTC:

> X-Ref: https://github.com/w3c/web-platform-tests/issues/2161

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/142#issuecomment-140227056 by @jgraham on 14 Sep 2015, 22:48 UTC:

> There isn't currently a good way to do this, and a test-only DOM API would need vendor buy-in and standards effort. The WebDriver issue linked is the simplest way to achieve this in that it doesn't involve creating new cross-browser technology, but there is some implementation effort. Please let me know if you have someone that can work on it.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/142#issuecomment-282313315 by @gsnedders on 24 Feb 2017, 15:04 UTC:

> This is also related to #85, insofar as it's mock behaviour.

**Comment by foolip** [comment]
This has been resolved by https://github.com/w3c/web-platform-tests/pull/6897.
