### ISSUE TITLE
Add a lint for broken links in link rel=match/mismatch

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7190]
Originally posted as https://github.com/w3c/wpt-tools/issues/28 by @Ms2ger on 22 Aug 2015, 08:15 UTC:

> Not sure how hard this would be, but I submitted tests to csswg-test yesterday where I typoed the file name of the reference; it'd be useful for our lint to catch such mistakes.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wpt-tools/issues/28#issuecomment-239969622 by @gsnedders on 16 Aug 2016, 00:30 UTC:

> I think the only complicating matter here is `.sub`.

**Comment by gsnedders** [comment]
Fixed by 2e6b3eaece6 from https://github.com/w3c/wpt-tools/pull/159
