### ISSUE TITLE
Navbar Title is basically invisible (on chrome at least)

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7197]
Originally posted as https://github.com/w3c/wpt-tools/issues/80 by @halindrome on 12 Jun 2016, 16:13 UTC:

> The font / color of the text is the same as the background or something...
> 
> ![screenshot 2016-06-12 at 11 12 14](https://cloud.githubusercontent.com/assets/520688/15992277/a4cd16ee-308e-11e6-80d1-84867165f6f8.png)

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wpt-tools/issues/80#issuecomment-225445920 by @halindrome on 12 Jun 2016, 16:17 UTC:

> Actually it is just that the image is not set to float to the left.  I will put it in a patch I am putting together now.

**Comment by bobholt** [comment]
This appears to have been resolved.
