### ISSUE TITLE
bug(typo) in line 583 of client.py in webdriver

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#7212]
Originally posted as https://github.com/w3c/wpt-tools/issues/204 by @LeeiFrankJaw on 18 Apr 2017, 03:22 UTC:

> The line [583](https://github.com/w3c/wpt-tools/blob/917266150c820502f6ab6cccc53e401003f6d8d2/webdriver/webdriver/client.py#L583) of [client.py](https://github.com/w3c/wpt-tools/blob/master/webdriver/webdriver/client.py) introduced by commit [404bb38](https://github.com/w3c/wpt-tools/commit/404bb38b1558368d529aa6ba90b2f14110f70083#diff-6c1f34f5989b21db58fa05ba2e66f3f6R361) is a typo.
> 
> I think this should be `return self.session._element(elem)`, otherwise each time I call `find_element`, it will complains _'Session' object has no attribute 'element'_.

**Comment by LeeiFrankJaw** [comment]
This issue was fixed in [pull request 6743](https://github.com/w3c/web-platform-tests/pull/6743) and should be closed
