### ISSUE TITLE
https://w3c-test.org/payment-request/interfaces.https.html is broken

### ISSUE THREAD

**Issue by AmazingJaze** [w3c/web-platform-tests#7270]
seems to be some error loading JavaScript libraries that do not exist in the file path.

//CC @marcoscaceres

**Comment by marcoscaceres** [comment]
Thanks! Just waiting for the following to land and then I'll copy how that one works: 
https://github.com/w3c/web-platform-tests/pull/7037

**Comment by marcoscaceres** [comment]
@@AmazingJaze, any chance you would want to be an co owner for the Payment Request tests? Would be really helpful having another person helping review tests.

**Comment by marcoscaceres** [comment]
Closing as duplicate of https://github.com/w3c/web-platform-tests/issues/7069
