### ISSUE TITLE
[css-flex] create tests for resolution of percentages in definite flex containers

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/web-platform-tests#7271]
There was a normative change in the flexbox spec after working group resolution. Here is the [issue](https://github.com/w3c/csswg-drafts/issues/1679)

Here is the commit: https://github.com/w3c/csswg-drafts/commit/5b5db39d21f3658ae2f4d7992daaf822aca178d8

Write up a few testcases that cover this change for PR and implementations to change to.

**Comment by gsnedders** [comment]
I think we have some tests for this in `css/css-flexbox-1/percentage-heights-001.html`, FWIW.

**Comment by gsnedders** [comment]
(Though probably asserting the wrong behaviour.)

**Comment by gregwhitworth** [comment]
@gsnedders yep, was just opening this so as to write/modify the testcases since it's a normative change to a spec nearing CR and not lose track of it.

**Comment by gsnedders** [comment]
Just trying to poke people in the right direction to edit tests rather than add new contradictory ones. :)

**Comment by gregwhitworth** [comment]
So I reviewed all of the percentage tests within this and they all skirt around that line so that is how this interop issue got through. I'll add a few new tests testing specifically this change.
