### ISSUE TITLE
Failing Test in Payment-Request-Constructor

### ISSUE THREAD

**Issue by MSFTkihans** [w3c/web-platform-tests#7300]
https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-constructor.https.html#L353
Lines 353-360 cause the test to fail because they create an invalid payment request, which throws a TypeError. This is what is expected to happen, since invalid details are provided but fail the test because there is no assert_throws.
The actual test seems to be on line 361, which uses assert_throws.

**Comment by MSFTkihans** [comment]
@marcoscaceres

**Comment by marcoscaceres** [comment]
Thanks for reporting! Would you be ok to send a pull request to fix it? 

I'll try to get you write access so you can label things. 

Cc @sideshowbarker

**Comment by marcoscaceres** [comment]
@MSFTkihans looking at the test, I think it is correct as per the Constructor steps: 

> 8. If the requestShipping member of options is present and set to true, process shipping options:

**Comment by marcoscaceres** [comment]
To clarify, even if the stuff in there is invalid, the validation steps are now skipped because `requestShipping: false`.

**Comment by MSFTkihans** [comment]
The lines seem to be not very relevant, given the test's description. Chrome also fails on this test because it validates shippingOptions.

**Comment by AmazingJaze** [comment]
@marcoscaceres  If this is the intent of the test, should we expand the test description beyond [what is currently written](https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-constructor.https.html#L369)

**Comment by marcoscaceres** [comment]
@MSFTkihans, 

> Given the test's description, the lines seem to not be strictly relevant.

You are probably right. I'll revise it.  

> Checking against other browsers, Chrome also fails on this test because it validates shippingOptions.

We only changed the spec a few days ago, so Chrome is still behind. I expect them to catch up in a few days tho.

**Comment by marcoscaceres** [comment]
> @marcoscaceres If this is the intent of the test, should we expand the test description beyond what is currently written ? Alternatively, is this test going to feel overloaded with too many conflicting scenarios that it would benefit by refactoring into two separate tests?

Yeah, we should probably split it out into two or more tests.

**Comment by marcoscaceres** [comment]
@MSFTkihans or @AmazingJaze, would either of you want to have a go at splitting these up? I'm happy to review. 

If no, that's ok. Will try to do this by the end of the week (currently working on the `.updateWith()` tests). Let me know what works best.

**Comment by sideshowbarker** [comment]
@MSFTkihans how has an a write-access invite waiting

**Comment by marcoscaceres** [comment]
@MSFTkihans or @AmazingJaze ping. Let me know how you want to proceed.
