### ISSUE TITLE
All stability jobs are failing due to extra arguments in tools/wptrunner/wptrunner/environment.py

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#7306]
Since https://github.com/w3c/web-platform-tests/pull/7227 was merged all stability checker jobs are failing. https://travis-ci.org/w3c/web-platform-tests/jobs/273647276 is the earliest I could find, and it fails with:
```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/ci/check_stability.py", line 355, in run
    iterations, results, inconsistent = run(venv, wpt_logger, **wpt_kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/stability.py", line 188, in run
    wptrunner.run_tests(**kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 181, in run_tests
    env_extras) as test_environment:
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/environment.py", line 103, in __enter__
    cm.__enter__(self.options)
TypeError: __enter__() takes exactly 1 argument (2 given)
```

It looks like the problem is at https://github.com/w3c/web-platform-tests/blob/d86e192588304fb98beaf5a8435442af5e35d480/tools/wptrunner/wptrunner/environment.py#L103, a code path the was presumably not reached at all before, but now is.

It looks like the fix would be to remove the `self.options` argument, but I don't know this code. It came from https://github.com/w3c/web-platform-tests/pull/5771.

Rather than making guesses in a hurry, I will try reverting the Ahem PR and letting @bobholt take a look in due time.

**Comment by foolip** [comment]
Reopening since this is only "fixed", still needs attention.

**Comment by gsnedders** [comment]
This is the second time we've had Travis entirely broken because while a tool PR passed CI the same commit didn't pass when merged. Should we be running more Travis jobs on tools changes?

**Comment by foolip** [comment]
> https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/README.md

Maybe at the very least run the stability checker on one test? That would have caught this.

**Comment by bobholt** [comment]
Sorry about that. Yes, we should be running a stability test to verify
every infra change. I had gotten out of the habit of making an extra commit
with a stability test.

@jgraham: Does it make sense to pick and hard-code a stability test that
always runs in CI if files_changed/tests_changed comes back empty?

On Sun, Sep 10, 2017 at 9:53 PM, Philip Jägenstedt <notifications@github.com

**Comment by gsnedders** [comment]
We should probably run `assumptions/` and `infrastructure/` or something.

**Comment by foolip** [comment]
Yeah. Bikeshedding in https://github.com/w3c/web-platform-tests/pull/7305 appreciated.

**Comment by jgraham** [comment]
Think this is fixed now. Create new issues for followups if required.
