### ISSUE TITLE
Different versions of Ahem.ttf throughout the repo

### ISSUE THREAD

**Issue by Hexcles** [w3c/web-platform-tests#7352]
I notice that we have multiple copies of `[A|a]hem.ttf` in the repo:

```
find . -name "?hem.ttf"|xargs sha1sum
8cdc9e68594fbb6db8c7b4bff643ab2432b51db6  ./content-security-policy/support/Ahem.ttf
88d834aadcd7b547720992a2894b9ab3251e3e04  ./css/fonts/ahem/ahem.ttf
8cdc9e68594fbb6db8c7b4bff643ab2432b51db6  ./css/vendor-imports/mozilla/mozilla-central-reftests/ruby/support/Ahem.ttf
8cdc9e68594fbb6db8c7b4bff643ab2432b51db6  ./css/vendor-imports/mozilla/mozilla-central-reftests/text3/support/Ahem.ttf
8cdc9e68594fbb6db8c7b4bff643ab2432b51db6  ./css/vendor-imports/mozilla/mozilla-central-reftests/flexbox/support/Ahem.ttf
8cdc9e68594fbb6db8c7b4bff643ab2432b51db6  ./css/vendor-imports/mozilla/mozilla-central-reftests/variables/support/Ahem.ttf
8cdc9e68594fbb6db8c7b4bff643ab2432b51db6  ./fonts/Ahem.ttf
```

`./css/fonts/ahem/ahem.ttf` is the newest version 1.2, while everything else is version 1.1. The two versions don't exactly match (compared by using the `assumptions/ahem.html` reftest).

**Comment by Hexcles** [comment]
To put the question more directly: do we really need these many copies? If yes, shall we update the version of the older copies?

**Comment by foolip** [comment]
@Hexcles, how did you figure out the version numbers, and is 1.2 the latest? Seems like https://www.w3.org/Style/CSS/Test/Fonts/Ahem/ is the source, but that doesn't match the sha of any of the files in wpt.

@mikewest about the CSP case.

Opinion: we should keep just /fonts/Ahem.ttf, and make it the latest version. How to get there with confidence that we're not breaking things is a tricky question.

**Comment by Hexcles** [comment]
@foolip Oops, I was actually wrong in mistakenly assuming the one in `css/fonts/ahem/` was the latest version because it was committed (March 28) after the latest modified time (January 31) of `ahem.ttf` on the W3C website. I just downloaded https://www.w3.org/Style/CSS/Test/Fonts/Ahem/ahem.ttf and it is version 1.5 (`AHEM____.TTF` is the same as `ahem.ttf`).

As for where the version number is, it is in the embedded font information, which you can find using both GNOME font viewer (click on the top right "info") or fontforge.

**Comment by foolip** [comment]
@sideshowbarker, can you tell who maintains https://www.w3.org/Style/CSS/Test/Fonts/Ahem/?

**Comment by sideshowbarker** [comment]
The changelog for https://www.w3.org/Style/CSS/Test/Fonts/Ahem/ shows commits 7 months ago from @svgeesus and some much older commits 7 years ago from @fantasai

**Comment by foolip** [comment]
@svgeesus, is that the main copy of Ahem, and is it expected to keep changing?

**Comment by Hexcles** [comment]
@sideshowbarker I wonder where I can find the version history of that directory. The changelog might contain useful information on what is actually changed in the font, which may help us to evaluate the impact of the version transition. Or @svgeesus might be able to weigh in on that.

**Comment by mikewest** [comment]
The CSP tests don't rely on any particular version; they just needed a font that's loadable without error. I'm totally fine with it pointing to a more generic resource.

**Comment by jgraham** [comment]
You aren't excited about having dozens of copies of the same file scattered about the repo? :)

I agree that there should be a single copy. It should be in `/fonts/`, because that's the copy that wptrunner installs into the system. But bear in mind that fixing this will require fixing up all the tests that currently use it, and probably adding some kind of lint to stop people adding new copies.

**Comment by gsnedders** [comment]
`css/fonts/fonts/ahem.ttf` is the latest version, and should be built from https://github.com/litherum/AhemMaker (though I think it might not be given there have been changes there more recently?). The last actual changes, as opposed to moving it, were in 9904d58fa20c78aa16e948001b7d79539305f806 and c45c32ffed667bf97a91873e5818994cb8c18808 by @fantasai.

**Comment by gsnedders** [comment]
Note the copies in `./css/vendor-imports/mozilla` are synced through a one-way sync from mozilla-central and any attempt to get rid of them will get overwritten next time @dbaron runs the sync script. :(

**Comment by gsnedders** [comment]
See https://lists.w3.org/Archives/Public/public-css-testsuite/2016Jul/0014.html wrt @fantasai's changes last year to ahem.ttf.

**Comment by gsnedders** [comment]
@mikewest is the same true of Ahem2.ttf?

**Comment by mikewest** [comment]
@gsnedders: I don't know of any CSP test that cares at all about the actual rendered font.

**Comment by gsnedders** [comment]
@mikewest my concern is whether unifying Ahem2.ttf and Ahem.ttf could cause issues with whatever CSP features content-security-policy/font-src/ are testing, not the rendering?

**Comment by mikewest** [comment]
@gsnedders: Nope. Skimming through the tests, they just need a file that won't generate an error when loaded as a font. Any font will do.

**Comment by Hexcles** [comment]
@gsnedders 
> css/fonts/fonts/ahem.ttf is the latest version, and should be built from https://github.com/litherum/AhemMaker (though I think it might not be given there have been changes there more recently?).

Thanks for the pointer to the actual repo of Ahem! (It was quite a mystery to me where and how the whole stuff was built.) And the repo has version 1.5 ([see the name table definition](https://github.com/litherum/AhemMaker/blob/d06af3563537e05a7940731ed52c1fdd1bc9ec43/AhemMaker/main.swift#L489)), so we also need to update the copy in `css/fonts/fonts/ahem.ttf` (which is currently v1.2).

**Comment by gsnedders** [comment]
@Hexcles Prior to that, pretty sure it was built with a variety of tools.

**Comment by gsnedders** [comment]
See the above linked PR.

**Comment by Hexcles** [comment]
Thanks, @gsnedders  !

**Comment by gsnedders** [comment]
@sideshowbarker can you make https://www.w3.org/Style/CSS/Test/Fonts/Ahem/ redirect to https://github.com/w3c/web-platform-tests/raw/master/fonts/Ahem.ttf?

@Hexcles Now landed, FYI.

**Comment by sideshowbarker** [comment]
> @sideshowbarker can you make https://www.w3.org/Style/CSS/Test/Fonts/Ahem/ redirect to https://github.com/w3c/web-platform-tests/raw/master/fonts/Ahem.ttf?

Yup, done

**Comment by fantasai** [comment]
@gsnedders Redirecting Ahem.ttf to Ahem.ttf might have made sense, but redirecting the entire directory and all its files was pretty annoying. I've reverted that change for now; I'll set up a temporary redirect for Ahem.ttf itself instead.

Also, finding any documentation on this font--which is a frequently used and very useful resource for reftests--from the fonts/ directory requires digging through VCS logs and tracking it across to Myles's AhemMaker project. This is currently a bit annoying for those of us who know such documentation exists and will go digging, but definitely a problem for those who don't and will therefore never even go looking. Can you add the README in there alongside the TTF?
