### ISSUE TITLE
2d.missingargs.html setTransform() test is no longer valid

### ISSUE THREAD

**Issue by wisniewskit** [w3c/web-platform-tests#7357]
The spec [states](https://html.spec.whatwg.org/multipage/canvas.html#2dcontext) that the IDL for `CanvasRenderingContext2D.setTransform` is:

```void setTransform(optional DOMMatrix2DInit transform);```

As such it should not throw on a call without arguments, `setTransform()`.

**Comment by wisniewskit** [comment]
@zcorpan, could you confirm if this is alright?

**Comment by wisniewskit** [comment]
@zcorpan, gentle ping.

**Comment by zcorpan** [comment]
@wisniewskit your analysis is correct; no arguments shouldn't throw.

I left a review comment that is not yet addressed, https://github.com/w3c/web-platform-tests/pull/7358#issuecomment-329695375

I addressed the comments and created a new PR: #7447

**Comment by wisniewskit** [comment]
Ah, thanks!
