### ISSUE TITLE
User initiated keyboard input

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#7434]
We should be able to send user initiated keyboard input.

@TakayoshiKochi wants this to be able to test `tabindex` around shadow DOM.

**Comment by foolip** [comment]
Assigning to @JKereliuk as he's begun work on this.

**Comment by JKereliuk** [comment]
Are there any existing manual tests that need this?

**Comment by foolip** [comment]
@kojiishi, do you have some manual tests that need a tab key to move focus?

**Comment by TakayoshiKochi** [comment]
I guess you meant @TakayoshiKochi :)
I haven't started yet, but testing tab focus order is what I would like to
do.

2017/11/21 7:17 "Philip Jägenstedt" <notifications@github.com>:

**Comment by foolip** [comment]
Yes I did, my apologies @TakayoshiKochi!

**Comment by foolip** [comment]
@kereliuk this will be resolved by https://github.com/w3c/web-platform-tests/pull/10113, right?

**Comment by kereliuk** [comment]
Yep :)

**Comment by foolip** [comment]
https://github.com/w3c/web-platform-tests/pull/10113 has been merged \o/
