### ISSUE TITLE
Get rid of css/work-in-progress

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#7453]
This is a dumping ground for old tests and is [excluded](https://github.com/w3c/web-platform-tests/blob/master/tools/manifest/sourcefile.py#L62) from being considered as tests and hence is totally ignored. Nobody is actively moving tests out of there.

ea0d6f0bc905c122f78214ec32ee58c7949e5581 is evidence of it being actively harmful: someone wasting their time partially fixing a "test" that is never run.

Only css/work-in-progress/microsoft/css-tables has seen any activity since the testsuite was merged; @davidsgrogan @FremyCompany @gregwhitworth can we move this into css/css-tables-3? (or if you want somewhere to collaborate prior to the tests being ready, put them on a branch)

If anyone does want to get tests out of there, they're still in the history, but they aren't misleading people into thinking they actually exist.

**Comment by FremyCompany** [comment]
Feel free to move them out of the work-in-progress folder. They should all be accurate.

**Comment by foolip** [comment]
> Feel free to move them out of the work-in-progress folder. They should all be accurate.

What actually happened was that they were removed. Is that OK, @FremyCompany?

**Comment by gsnedders** [comment]
@foolip No, the table tests were moved out, which is what I'm pretty certain @FremyCompany was referring to given prior discussions. And then everything else was removed.

**Comment by FremyCompany** [comment]
@foolip @gsnedders we are all good, the tests were moved as part of https://github.com/w3c/web-platform-tests/pull/7454

**Comment by foolip** [comment]
Do the tests that we're removed still exist somewhere for future re-upstreaming, or were they really just not valuable enough to worry about that?

**Comment by gsnedders** [comment]
@foolip They'd been in the repo for years without anyone caring about them, most of them manual, and many of them nowhere near up-to-date with the spec. They still exist in the git history if anyone wants to pull them out, and I assume the ones from browser vendors exist in some form in their repos.

**Comment by foolip** [comment]
The assumed part there is what I'm wondering about. Nobody will resurrect these from git history, I'm fairly certain.
