### ISSUE TITLE
Merge labels runner and wptrun and wptrunner?

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#7486]
Seems like we have too many labels for the same thing. Keep one.

**Comment by foolip** [comment]
@gsnedders, do you know the history?

**Comment by gsnedders** [comment]
Oh, this is far from the only case.

**Comment by gsnedders** [comment]
Pretty sure `runner` is meant to be `tools/runner` and `wptrunner` is `tools/wptrunner`. So, no, they shouldn't be merged.
