### ISSUE TITLE
core-aam/exclude_element_hidden_with_css_display:none-manual.html and friend cause problems on Windows

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#7496]
- core-aam/exclude_element_hidden_with_css_display:none-manual.html
- core-aam/exclude_element_hidden_with_css_visibility:hidden-manual.html

These are not valid filenames on Windows and so they cause problems with Git. I can't really fix this from WIndows it seems. Can someone with a machine that accepts these filenames rename them to not include a colon?

**Comment by sideshowbarker** [comment]
See https://github.com/w3c/web-platform-tests/pull/7497
