### ISSUE TITLE
Consolidate CSS test suites into a single unversioned directory per spec

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#7503]
This is the outcome of the [Unifying testsuite policy and getting rid of CSS exceptions](https://lists.w3.org/Archives/Public/public-test-infra/2017JulSep/thread.html#msg29) thread on public-test-infra.

@gsnedders @astearns @jgraham @fantasai @frivoal @Hexcles

**Comment by foolip** [comment]
This should include updating the documentation, see https://github.com/w3c/web-platform-tests/issues/5264.

**Comment by foolip** [comment]
As part of fixing this, it may be necessary to handle https://github.com/w3c/web-platform-tests/issues/7652 as well. That's the only directory that seems to not correspond to any currently maintained spec.

**Comment by gsnedders** [comment]
Trying to move tests that currently are in the root into css/ leads to 133 lint errors (MISSING-LINK: 127, SUPPORT-WRONG-DIR: 4, CSS-COLLIDING-TEST-NAME: 2), given they're now subject to the css lints.

**Comment by astearns** [comment]
We agreed that we would not require links when bulk-upstreaming. Perhaps we should apply that rule here? Then you'd only have to fix 6 lint errors.

**Comment by gsnedders** [comment]
I'm more inclined to just whitelist all these lint failures, and leave it up to anyone who actually wants to use these tests through the build system to fix them.

**Comment by jgraham** [comment]
> We agreed that we would not require links when bulk-upstreaming

We don't have any code that would allow us to implement such a policy. How would you expect it to act? I can imagine turning off this lint entirely unless an extra flag is passed to the linter, but I doubt I will have time to implement anything more involved than that. In particular it's not clear how one would tell what a bulk upstreaming is.

**Comment by frivoal** [comment]
The permission to fail lints on bulk upstreaming was meant as a one time forgiveness, allowing browser vendors who were previously writing tests in isolation to switch to continuous integration, mass importing their existing stuff before switching to respecting the lints on every new thing.

With that in mind, I think that just whitelisting failing tests is fine, and we may not need anything more sofisticated. If this was something we were planning to do on a regular basis, better tooling would be justified, but this this is just a one time thing, whitelisting seems ok to me.

**Comment by foolip** [comment]
Reopening to fix the documentation at https://github.com/w3c/web-platform-tests/blob/master/css/README.md. @gsnedders, can you take care of that? Pointed out to me by @ericwilligers.

**Comment by foolip** [comment]
@gsnedders, there's also the selectors directory in the root that needs to be merged.

**Comment by foolip** [comment]
Selectors have been merged, only documentation remains.

**Comment by foolip** [comment]
The (hopefully) final directory rename is in https://chromium-review.googlesource.com/c/chromium/src/+/778884
