### ISSUE TITLE
Do not use window.testRunner for web platform tests

### ISSUE THREAD

**Issue by fred-wang** [w3c/web-platform-tests#7536]
It seems that window.testRunner is used in some places. This is specific to WebKit/Chromium and should probably not be used in the web-platform tests:

    find -type f -name '*.html' | xargs grep 'testRunner\.'
    ./service-workers/service-worker/fetch-frame-resource.https.html:  testRunner.setCanOpenWindows();
    ./css-paint-api/valid-image-before-load.html:  testRunner.waitUntilDone();
    ./css-paint-api/valid-image-after-load.html:  testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-002.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-002.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-002.html:			testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-005.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-005.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-005.html:			testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-002.html:		testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-002.html:		testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-002.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-001.html:		testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-001.html:		testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-001.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-004.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-004.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-004.html:			testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-003.html:		testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-003.html:		testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-elementFromPoint-003.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-001.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-001.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-001.html:			testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-003.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-003.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-003.html:			testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-001.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-001.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-001.html:			testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-003.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-003.html:		testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/mouse-events-003.html:		testRunner.waitUntilDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-002.html:			testRunner.notifyDone();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-002.html:			testRunner.dumpAsText();
    ./css/css-regions-1/interactivity/hit-testing/overflow-and-events-002.html:			testRunner.waitUntilDone();
    ./content-security-policy/blink-contrib/manifest-src-allowed.sub.html:        testRunner.getManifestThen(function() {
    ./content-security-policy/blink-contrib/manifest-src-blocked.sub.html:        testRunner.getManifestThen(function() {

**Comment by fred-wang** [comment]
It seems that the testRunner instances are now only used for css-regions tests: 

    find -type f -name '*.html' | xargs grep 'testRunner\.'
    ./css/css-regions/interactivity/hit-testing/mouse-events-002.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-002.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/mouse-events-002.html:			testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-005.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-005.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/mouse-events-005.html:			testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-002.html:		testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-002.html:		testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-002.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-001.html:		testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-001.html:		testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-001.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-004.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-004.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/mouse-events-004.html:			testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-003.html:		testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-003.html:		testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-elementFromPoint-003.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-001.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-001.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-001.html:			testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-003.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-003.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-003.html:			testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-001.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-001.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/mouse-events-001.html:			testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-003.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/mouse-events-003.html:		testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/mouse-events-003.html:		testRunner.waitUntilDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-002.html:			testRunner.notifyDone();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-002.html:			testRunner.dumpAsText();
    ./css/css-regions/interactivity/hit-testing/overflow-and-events-002.html:			testRunner.waitUntilDone();

cc @atanassov @astearns @Ms2ger @foolip

**Comment by fred-wang** [comment]
These tests also use eventSender and that seems to be on purpose:
https://github.com/w3c/web-platform-tests/blob/master/lint.whitelist#L961

Maybe this can be closed then?

**Comment by foolip** [comment]
Those cases should also be fixed ideally, using whatever kind of automation is required (@kerliuk) but I don't think we need to keep this issue open to track that, it's the same with most lints.
