### ISSUE TITLE
Add a lint for use of eventSender, internals, and any Gecko equivalents

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#7541]
When tests are moved from engines to wpt, these things can be accidentally left behind, and should be easy to lint for.

@jdm, can you point to some cases where this has happened?

@gsnedders @jgraham

**Comment by mrego** [comment]
Some examples:
* css-paint-api/valid-image-after-load.html
* css/css-regions-1/interactivity/hit-testing/mouse-events-002.html
* css/css-ruby-1/line-break-around-ruby-001.html

**Comment by gsnedders** [comment]
cc/ @AutomatedTester any idea what to lint for, if anything, from Gecko?

**Comment by fred-wang** [comment]
See also issue #7536

**Comment by emilio** [comment]
> cc/ @AutomatedTester any idea what to lint for, if anything, from Gecko?

In Gecko the key one is `nsIDOMWindowUtils`, I think. There's only one occurrence of it, and it's in a place that handles different browsers.

In Servo, it'd be `TestBinding`.

**Comment by foolip** [comment]
@Ms2ger pointed me to https://github.com/w3c/web-platform-tests/commit/50d72316c4ecb79492bb03c18f39612951b44dda https://github.com/w3c/web-platform-tests/pull/7341 as well.

**Comment by foolip** [comment]
Since there aren't any instances of `nsIDOMWindowUtils` or `TestBinding`, I'll close this and we can revisit if such things actually are upstreamed.
