### ISSUE TITLE
no-transfer.html loads a nonexistent worker

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#7546]
The second test in `/html/infrastructure/safe-passing-of-structured-data/shared-array-buffers/no-transfer.html` loads `resources/incrementer.js` as a worker script, but that file does not exist. Perhaps `incrementer-worker.js` was intended instead?

cc @domenic

**Comment by domenic** [comment]
Yep, sorry about that, PR incoming. I'll switch it to echo-worker too since it doesn't matter what worker it is.
