### ISSUE TITLE
Travis Sauce builds (Edge/Safari) are failing

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#7553]
See https://travis-ci.org/w3c/web-platform-tests/jobs/282693136 for an example

"404 Client Error: Not Found for url: https://saucelabs.com/downloads/sc-latest-linux.tar.gz"

**Comment by bobholt** [comment]
I haven't seen any word from them on not using that URL. If it's a hosting
error on their side, I'm reluctant to peg this to a specific SC version
which we'll have to go back in and update periodically, but I can do that
if this outage continues. I'll send a support request and give it until
noon EDT.
