### ISSUE TITLE
domxpath/interfaces.html has no spec to back it up

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-platform-tests#7562]
This file has IDL that is not backed by any actual spec; it was just checked in on someone's say-so as far as I can tell.

In addition to that, the IDL it uses is about to become invalid (assuming it's valid already, which is not clear to me) when https://github.com/heycam/webidl/pull/433 lands.

**Comment by Ms2ger** [comment]
That would be my say-so :)

The closest we have to a spec for DOM XPath is https://wiki.whatwg.org/wiki/DOM_XPath; having something better would be great, but priorities... I think it's useful to have this test as a regression test, though. If I'm not mistaken, Gecko currently uses the exact same syntax; perhaps whoever fixes Gecko could just update the test as well? I can update the wiki if you cc me on the bug.

**Comment by bzbarsky** [comment]
We could use our "tentative" or whatever it is naming convention...

I don't have a timeframe for Gecko updating to the new mixin syntax, and more importantly that timeframe may not match idlharness's.

**Comment by Ms2ger** [comment]
CC @tobie @darobin
