### ISSUE TITLE
requestidlecallback/callback-timeout-with-raf.html assumes an idle period won't start if there are pending rAF callbacks

### ISSUE THREAD

**Issue by farre** [w3c/web-platform-tests#7589]
The idea of the test is that when a rAF callback takes longer than 40 ms, which is assumed to be longer than the time until the next time that rendering will be updated, and makes a daisy chain call to requestAnimationFrame, then an idle period will never be initiated.

As far as I can tell from the spec, there is no reason for there not being an idle period in this case, given that the next update rendering step is sufficiently far away into the future. And even if the rAF callback has taken longer than the rate that the user agent wishes to run it's rendering updates, there is no requirement that the next rendering update will happen immediately.

**Comment by foolip** [comment]
@rmcilroy, is this a test you added? Can you take a look?
