### ISSUE TITLE
Potentially wrong check in entries-api/filesystemdirectoryentry-getDirectory-manual.html

### ISSUE THREAD

**Issue by cdumez** [w3c/web-platform-tests#7647]
I may have found a bad check in entries-api/filesystemdirectoryentry-getDirectory-manual.html.

The subtest "FileSystemDirectoryEntry.getDirectory() - {create:true}: //upload/subdir" expects a "SecurityError" because the 'create' flag is set.

However, as per the spec [1], we check if the path is valid *before* checking the create flag.

In my opinion, the path "//upload/subdir" is not valid, given the specification [2]. This is not a relative path since it starts with a '/'. This is not an absolute path because it is not a '/' followed by a relative path ('/upload/subdir' is not a relative path).

So based on my interpretation of the specification, we should throw a "TypeMismatchError", which is what WebKit does.

[1] https://wicg.github.io/entries-api/#dom-filesystemdirectoryentry-getdirectory
[2] https://wicg.github.io/entries-api/#valid-path

**Comment by cdumez** [comment]
@inexorabletash thoughts?

**Comment by cdumez** [comment]
Several other tests are likely impacted:

filesystemdirectoryentry-getDirectory-manual.html | FileSystemDirectoryEntry.getDirectory() - directory: //upload/subdir
filesystemdirectoryentry-getFile-manual.html | FileSystemDirectoryEntry.getFile() - {create:true}: //upload/file.txt
filesystemdirectoryentry-getFile-manual.html | FileSystemDirectoryEntry.getFile() - file: //upload/file.txt

**Comment by inexorabletash** [comment]
Chrome passes the tests with `//upload/subdir` so I'd call this a spec flaw, given the goal was to help implementations converge on Chrome's behavior without guessing. Chrome treats `//a/b` as an absolute path, my definition of absolute/relative paths in the spec prose was just not precise enough to cover this case.

I think changing the definition of absolute path as follows would address this:

> An absolute path is a string consisting of '/' (U+002F SOLIDUS) followed by one or more path segments joined by '/' (U+002F SOLIDUS).

Nothing prohibits a path segment from being empty, but then the steps to **evaluate a path** needs a case for empty string as well, or the steps to **resolve a relative path** needs to strip empty segments.

I notice WebKit passes the tests with `/upload//file.txt` so it must be doing one of those two things already?

**Comment by cdumez** [comment]
The algorithm at https://wicg.github.io/entries-api/#resolve-a-relative-path does skip empty segments, which is probably why WebKit does it.

Note that I am fine updating the spec to match Chrome. If you do so, then I'll update WebKit accordingly.

**Comment by inexorabletash** [comment]
> The algorithm at https://wicg.github.io/entries-api/#resolve-a-relative-path does skip empty segments, which is probably why WebKit does it. 

But step 1 of the algorithm early-exits if it's absolute, so `/a//b` should be passed unchanged to "evaluate" and then fail.

**Comment by inexorabletash** [comment]
Anyway, filed spec bugs, I'll fix soon. Thanks!

**Comment by cdumez** [comment]
Oh, that's right, if the path is absolute, then WebKit, WebKit calls resolveRelativeVirtualPath("/", relativeVirtualPath.substring(1)). This is to resolve absolute path like "/testFolder/../../../../hello.txt"

Closing then since the fix will be on spec-side.
