### ISSUE TITLE
testharness doesn't work with uncatchable exceptions

### ISSUE THREAD

**Issue by xiaochengh** [w3c/web-platform-tests#7657]
We are trying to add a test case of the following, asserting there is no crash. However, the `click()` will run JS with syntax error asynchronously, and there is no way to catch the error.

If the error is not caught, testharness ends up in an error state. Is it good to leave the error state as-is, or should testharness consider expected-but-uncaught exceptions?

```
<a href="javascript:">foo<img ismap style="content:'bar'; display:block;"></a>
<script>
window.onload = () => document.getElementsByTagName('img')[0].click();
</script>
```

**Comment by jdm** [comment]
Tests can use `setup({ allow_uncaught_exceptions: true })` to accommodate expected exceptions.

**Comment by xiaochengh** [comment]
Whoops. Should have read the doc more carefully...
