### ISSUE TITLE
Async add_cleanup

### ISSUE THREAD

**Issue by jakearchibald** [w3c/web-platform-tests#7744]
When `promise_test`s, I've found myself [having to create additional tests](https://github.com/w3c/web-platform-tests/pull/7674) just to do cleanup, such as unregistering service workers, or clearing storage.

Ideally, if `add_cleanup`'s callback returns a promise, it should wait for that promise to settle.

**Comment by jdm** [comment]
This sounds like a duplicate of https://github.com/w3c/web-platform-tests/issues/7188.

**Comment by jakearchibald** [comment]
It is, sorry!
