### ISSUE TITLE
Add viewport/OWNERS and viewport/README.md

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#7749]
@bokand, can add OWNERS to this directory, and a README that points to what the spec for this is? Usually it's obvious by the name, but not here.

If possible, renaming either https://wicg.github.io/ViewportAPI/spec.html or this directory so that they match would be nice.

**Comment by bokand** [comment]
Weird, I thought I had added an OWNERS file...ok I'll go ahead and do that. I'll rename to visual-viewport. 

When you say to rename https://wicg.github.io/ViewportAPI/spec.html you mean the header in the spec?
 the WICG repo? the spec.html file name?

**Comment by foolip** [comment]
The convention is that wpt for names match the "shortname", the foo in https://www.w3.org/TR/foo/.

Now /TR/ is almost never the URL used, so it's some other part of the URL. So, if you have a "shortname" that you like, using it everywhere is nice.

But it's not a big deal, in case of mismatch it's still possible to figure out what things belong together from README.

**Comment by bokand** [comment]
Do you still want me to add a README or is the fact that the name now matches the directory enough?

**Comment by foolip** [comment]
This is fine now, add a README only if you want to :)
