### ISSUE TITLE
Remove uses of SpecialPowers

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#7870]
css/css-fonts-3/test_font_feature_values_parsing.html and css/css-fonts-3/test_font_family_parsing.html contain uses of this property, which makes the tests less useful in other browsers.

**Comment by jgraham** [comment]
That shouldn't even work in Gecko…

**Comment by jgraham** [comment]
https://github.com/w3c/web-platform-tests/pull/7871
