### ISSUE TITLE
Generate and check-in the most current manifest?

### ISSUE THREAD

**Issue by tabatkins** [w3c/web-platform-tests#7908]
I'm doing some Bikeshed work that needs wpt information, particularly the stuff stored in the manifest. Currently, this means I have to pull down the entire wpt tree and run `wpt manifest`. But this file isn't based on any local information for me (I'm not adding any *new* tests to the project). Could it just be pregenerated and kept current in the repo, so that I could instead just pull down that one file?

**Comment by jgraham** [comment]
I'm planning to upload the generated manifest to GitHub releases.

**Comment by jgraham** [comment]
This now happens. `wpt manifest-download` will grab the most relevant one for the current head.
