### ISSUE TITLE
Make manifest path and expectation root independent

### ISSUE THREAD

**Issue by lukebjerring** [w3c/web-platform-tests#7959]
Currently, the MANIFEST.json is assumed to share a root with metadata (.inf) files. We should add support for passing in a different expectation root than the manifest path (--metadata-root).

This would allow us to build + utilize a root which pulls from the latest wpt.fyi results (re-using the expectation behaviour to detect regressions), for https://github.com/w3c/web-platform-tests/issues/7475

**Comment by jgraham** [comment]
Probably the right way to do this is to change `metadata_root` to `expectation_root` and `manifest_path` everywhere and for compat set `manifest_path=os.path.join(metadata_root, "MANIFEST.json")` and `expectation_root=metadata_root` if the manifest root is explicitly passed in in a command line argument (we can make the argument hidden so it's only legacy scripts that do this).

**Comment by alijuma** [comment]
This has priority:roadmap. Is there any work planned for this quarter?

**Comment by gsnedders** [comment]
fixed by #9676.
