### ISSUE TITLE
wptrunner is counting failures and errors from the same test 

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/web-platform-tests#7979]
if a test has an error AND a failure it is counted as two errors when a run has completed. this is obvious when you view https://wpt.fyi/webdriver/tests/actions.

 chrome is erroring and failing so we get twice the failure numbers

**Comment by jgraham** [comment]
I'm not sure what's going on here, but I expect it's something specific to the wdspec tests. Generally each test should give one result for the overall file, and one for the subtests (if any).

**Comment by jgraham** [comment]
I can't reproduce this with `wpt run` so I think it's maybe an error with the `wpt.fyi` data processing or an error with the way it invokes the tests. We'd need to see the logs to get a better idea.

@jeffcarp @lukebjerring

**Comment by jeffcarp** [comment]
wpt.fyi uses the `--log-wptreport` format and then generates a summary using this function:
https://github.com/w3c/wptdashboard/blob/master/run/run.py#L307

If both the test file and the only subtest returned anything other than `PASS`, it would be counted as `0/2` on the dashboard. You can see how this plays out where the denominator in a good majority of tests on wpt.fyi bottoms out at 2, not 1 - example: https://wpt.fyi/wasm

This seems like both a bug and a UI discussion around how to display test file vs. subtest passing numbers.

Also I think this bug should be re-filed against https://github.com/w3c/wptdashboard/

**Comment by RByers** [comment]
Moved to https://github.com/w3c/wptdashboard/issues/191
