### ISSUE TITLE
"wpt run firefox --install-browser --yes" fails on OSX

### ISSUE THREAD

**Issue by kereliuk** [w3c/web-platform-tests#7996]
Running on OSX, this is the stacktrace:  
```
File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/kereliuk/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/kereliuk/web-platform-tests/tools/wpt/run.py", line 373, in run
    **kwargs)
  File "/Users/kereliuk/web-platform-tests/tools/wpt/run.py", line 351, in setup_wptrunner
    kwargs["binary"] = setup_cls.install(venv)
  File "/Users/kereliuk/web-platform-tests/tools/wpt/run.py", line 147, in install
    return self.browser.install(venv.path)
  File "/Users/kereliuk/web-platform-tests/tools/wpt/browser.py", line 116, in install
    resp = self.get_from_nightly("<a[^>]*>(firefox-\d+\.\d(?:\w\d)?.en-US.%s\.tar\.bz2)" % self.platform_string())
  File "/Users/kereliuk/web-platform-tests/tools/wpt/browser.py", line 107, in get_from_nightly
    filename = re.compile(pattern).search(index.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

We are matching with the wrong regex pattern in browser.py
```
self.get_from_nightly("<a[^>]*>(firefox-\d+\.\d(?:\w\d)?.en-US.%s\.tar\.bz2)" % self.platform_string())
```
So it will search the for a nightly download with "firefox-\d+\.\d(?:\w\d)?.en-US.%s\.tar\.bz2"
This will find nothing, I think instead we need to search for "firefox-\d+\.\d(?:\w\d)?.en-US.%s.web-platform.tests\.tar\.bz2

In fact, should we be using these web.platform-test downloads from firefox nightly for every platform? @jgraham do you know?

**Comment by JKereliuk** [comment]
It looks like web-platform-test downloads exist for all platforms.

**Comment by jgraham** [comment]
Nope, we shouldn't be using those since they're test files. But it's possible that this regexp is wrong on non-linux platforms.

**Comment by JKereliuk** [comment]
Do you know what the correct download is for mac nightly? I'm not sure which one it is.

**Comment by jgraham** [comment]
It's the `dmg` file, but I don't know how to install that. You might need to do something like https://stackoverflow.com/questions/6357914/how-do-i-install-a-dmg-file-from-the-command-line

**Comment by miketaylr** [comment]
`mozdownload` and `mozinstall` would be useful, i.e.,

https://github.com/mozilla-services/fxa-testing-e2e/blob/3a58eb4067d01de480319d651f70232389a44e91/setup.sh#L19-L22

**Comment by jgraham** [comment]
Oh, look at that. Thanks!

**Comment by jgraham** [comment]
So it looks like the right solution here is to have the `wpt run` command depend on `mozdownload` and `mozinstall`. That requirement can be added in the `tools/wpt/commands.json` file. Then the `install_browser` method for Firefox should replace it's existing custom implementation with something that calls into those tools, placing the binary in the same location as we do currently (i.e. under `_venv`).
