### ISSUE TITLE
Use latest Edge and Safari versions available on Sauce

### ISSUE THREAD

**Issue by RByers** [w3c/web-platform-tests#8052]
It [looks like](https://pulls.web-platform-tests.org/build/20099) we're still running against Edge 14 and Safari 10 when Sauce [claims to have](https://saucelabs.com/platforms) support for Edge 15 and Safari 11.

Do we have these versions hard-coded?

/cc @lukebjerring @mattl

**Comment by RByers** [comment]
Luke says this is just hard-coded and it's easy to update.  Let's just update these two (might also require updating the MacOS version).

**Comment by mattl** [comment]
I’m going to look into this today.

**Comment by RByers** [comment]
Great, thanks - assigned to you.

**Comment by toddreifsteck** [comment]
@mattl ping! Saw Edge failing on tests I know we fixed in Edge 15 on a PR today.

**Comment by mattl** [comment]
Edge is actually doing pretty well today. https://wpt.fyi -- it takes a while to run, but we got a successful run of 15 last night.

**Comment by foolip** [comment]
https://github.com/w3c/web-platform-tests/pull/8882 and https://github.com/w3c/web-platform-tests/pull/9338 together have fixed this, kind of.

Safari 11.1 was just released, but I don't know how to check if it's available on Sauce. I think the issue to fix now is rather "notice when new versions become available on Sauce and update in a timely manner". @mattl, do you know how to check what the latest available versions are?

**Comment by mattl** [comment]
Safari 11.1 is available in beta. 11.2 (Release 49, Safari 11.2, WebKit 13606.1.3.3) is available as Technology Preview. Sauce doesn't have dev/beta builds of Safari at all.

**Comment by foolip** [comment]
Is there an API or status page where one can find this information? (When I upgraded Edge I had to guess the exact version string based on what I could find in BrowserStack, since I don't have a Sauce account myself.)

**Comment by mattl** [comment]
https://saucelabs.com/platforms

**Comment by mattl** [comment]
Here's a more interactive thing, https://wiki.saucelabs.com/display/DOCS/Platform+Configurator?src=sidebar#/

**Comment by gsnedders** [comment]
We've got rid of Sauce through #9903, so this is now invalid.
