### ISSUE TITLE
Support mixin syntax in idlharness

### ISSUE THREAD

**Issue by tobie** [w3c/web-platform-tests#8054]
WebIDL recently introduced [dedicated syntax for mixins][0].

This syntax replaces the `[NoInterfaceObject]` extended attribute and `implements statement` which have been deprecated (except for a few [legacy uses cases][1] explicitely mentioned in the spec).

You can read more about it [here][2].

As there are syntactical changes, we also filed an issue against WebIDL2: w3c/webidl2.js#112.

[0]: https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
[1]: https://heycam.github.io/webidl/#NoInterfaceObject
[2]: https://heycam.github.io/webidl/#idl-interface-mixins

***

*Tracked in: heycam/webidl#472* | *Original pull-request: heycam/webidl#433*

**Comment by foolip** [comment]
This was done in https://github.com/w3c/web-platform-tests/pull/8727.
