### ISSUE TITLE
Run all idlharness tests when webidl2.js changes

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#8067]
Per https://github.com/w3c/wptdashboard/issues/164#issuecomment-341899369

**Comment by jgraham** [comment]
https://github.com/w3c/web-platform-tests/pull/8069

Although it doesn't know about files other than index.js, which would probably require custom code like we have for webdriver.

**Comment by foolip** [comment]
Fixed by https://github.com/w3c/web-platform-tests/pull/8069
