### ISSUE TITLE
click-cancel.html is failing on msElementsFromPoint on Safari

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#8095]
https://wpt.fyi/uievents/order-of-events/mouse-events/click-cancel.html is now failing with "document.msElementsFromPoint is not a function. (In 'document.msElementsFromPoint(centerPoint[0], centerPoint[1])', 'document.msElementsFromPoint' is undefined)"

That seems quite wrong.

**Comment by gsnedders** [comment]
The issue here seems to be that Safari doesn't support `document.elementsFromPoint`, which is relied on by https://w3c.github.io/webdriver/webdriver-spec.html#dfn-pointer-interactable-paint-tree.

**Comment by foolip** [comment]
Maybe just add an assert with a more clear message, so it doesn't look like our setup is messed up?

**Comment by gsnedders** [comment]
@RByers just pointed out that WebKit recently added support for it: https://bugs.webkit.org/show_bug.cgi?id=153137

**Comment by RByers** [comment]
coincidentally, the chromium team (@alijuma) added it to WebKit ;-)
