### ISSUE TITLE
🐛 No `./serve` binary as instructed by documentation

### ISSUE THREAD

**Issue by snuggs** [w3c/web-platform-tests#8144]
Am attempting to get WPT setup locally and the following documentation states `./serve`.

I noticed there is a `serve.py` (which I can't seem to get working. Complains of a no nodename error in main). And a `wpt.py`. Assuming these are the two servers that need starting to run tests.

I have ran the `wpt` server fine and files are showing up. In the mean time i've created a `./serve` binary which runs both servers. Let me know if this is of any value to submit within a PR. Otherwise we can close this upon better understanding.

Please advise! 🙏 

### Documentation error
http://web-platform-tests.org/introduction.html#github

![capture d ecran 2017-11-10 a 08 59 09](https://user-images.githubusercontent.com/38223/32648302-8448b5ce-c5f5-11e7-8dac-877b92ce57a6.png)

### Current directory structure
![capture d ecran 2017-11-10 a 09 03 47](https://user-images.githubusercontent.com/38223/32648471-195983c8-c5f6-11e7-9fd9-0151b9d8359a.png)

**Comment by snuggs** [comment]
Ah I see. Should be `./wpt serve` as instructed in README.md

https://github.com/w3c/web-platform-tests#running-tests-manually

**Comment by tabatkins** [comment]
I just ran into this as well.

**Comment by snuggs** [comment]
@tabatkins good (kinda) now how do we update? That's 4 people now I know this happened to (this week). /cc @Hexcles

**Comment by zcorpan** [comment]
Seems this was fixed in https://github.com/w3c/web-platform-tests/pull/8183 , thanks @jgraham!

**Comment by snuggs** [comment]
YASSS! @jgraham what @zcorpan said... 🙏
