### ISSUE TITLE
Changing the port in config.json does not change the port in wpt run

### ISSUE THREAD

**Issue by kereliuk** [w3c/web-platform-tests#8181]
To reproduce:

Modify config.json so that the http port is set to something that isn't 8000.
```
./wpt run chrome url/urlsearchparams-append.html
```

The executor should open a browser on port 8000 and not 8001.

**Comment by foolip** [comment]
@JKereliuk, calling this backlog since it's not clear if this is blocking anything, please bump prio if needed.
