### ISSUE TITLE
Migrate remainder of w3c/wptserve

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#8292]
And once all issues are moved here we should maybe use the GitHub utility to archive that repository so it's clear it's no longer being developed.

**Comment by gsnedders** [comment]
(note that we didn't move over PRs from old repos before before that's a lot of manual work and time consuming when so many of those had sat around for years already and it seems unlikely anything will happen if I spend my time moving them over)

**Comment by gsnedders** [comment]
all the issues are now moved
