### ISSUE TITLE
Get rid of traces of css/work-in-progress/

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#8310]
There's some left in https://github.com/w3c/web-platform-tests/blob/495043fd6ed481eaea37ae3a20a43074fcf959eb/tools/manifest/sourcefile.py#L57 and also lint+tests, grep for "work-in-progress".

**Comment by gsnedders** [comment]
fixed in #8310

**Comment by foolip** [comment]
This is #8310 :)
