### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#8356]
Originally posted as https://github.com/w3c/wptserve/issues/12 by @darobin on 21 Mar 2014, 13:16 UTC:

> I can get wptserve to produce the following:
> 
> ```
> ERROR:wptserve:Traceback (most recent call last):
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/server.py", line 220, in handle_one_request
>     response.write()
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/response.py", line 200, in write
>     self.write_status_headers()
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/response.py", line 190, in write_status_headers
>     self.writer.end_headers()
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/response.py", line 401, in end_headers
>     self.write_default_headers()
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/response.py", line 386, in write_default_headers
>     self.write_header(name, f())
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/response.py", line 378, in write_header
>     self.write("%s: %s\r\n" % (name, value))
>   File "/Projects/html-ts/web-platform-tests/tools/wptserve/wptserve/response.py", line 418, in write
>     self._wfile.write(self.encode(data))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 324, in write
>     self.flush()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ```
> 
> It is difficult to reproduce reliably, but I believe it happens if wptserve tries to write a file to the socket when the browser has closed it already.
> 
> I can reproduce it only by going to a page and reloading it like a madman. It can take quite a few tries to obtain the result. (Hardware: super recent top of the line MBP with SSD — so it might reproduce differently on something slower — works in several browsers.)
> 
> Once it has happened once I get the impression that it becomes easier to produce it again if the server isn't killed (but I can't prove it, it may be an impression). That might mean that the worker in which the exception occurs survives but is in a corrupt state.

**Comment by foolip** [comment]
This was long ago and hard to reproduce then, closing as not very actionable.
