### ISSUE TITLE
Endorse as a feature the possibility to change the document root while the server is running

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#8358]
Originally posted as https://github.com/w3c/wptserve/issues/32 by @andreieftimie on 26 Jun 2014, 13:28 UTC:

> There's an interesting behaviour that allows us to change the document root _while_ the server is running.
> 
> Once the server is running if you change `httpd.router.doc_root` the next request will use the new value as document root.
> 
> I would like to propose that this becomes a supported feature.
> This is a web server created for running tests. Changing the document root without requiring a restart is a really nice feature.

**Comment by foolip** [comment]
That this worked to begin with seems kinda accidental, and to change `httpd.router.doc_root` one presumably needs to write some Python code. I'm going to close this, because it seems like complexity we should want to avoid rather than embrace. Please reopen if that's too narrow-minded of me.
