### ISSUE TITLE
missing referrer causes exception

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#8362]
Originally posted as https://github.com/w3c/wptserve/issues/67 by @hrj on 18 Sep 2015, 09:25 UTC:

> ```
> ERROR:web-platform-tests:referer
> Traceback (most recent call last):
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/server.py", line 253, in handle_one_request
>     handler(request, response)
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 142, in __call__
>     response = pipeline(request, response)
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 36, in __call__
>     response = func(request, response, *args)
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 129, in inner
>     return f(request, response, *arg_values)
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 362, in sub
>     new_content = template(request, content)
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 425, in template
>     new_content, count = template_regexp.subn(config_replacement, content)
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 413, in config_replacement
>     value = value[item[1]]
>   File "/home/ubuntu/work/web-platform-tests/tools/wptserve/wptserve/request.py", line 356, in __getitem__
>     values = dict.__getitem__(self, key.lower())
> KeyError: u'referer'
> ```

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/67#issuecomment-141405162 by @jgraham on 18 Sep 2015, 09:43 UTC:

> Loading what?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/67#issuecomment-141412712 by @hrj on 18 Sep 2015, 10:23 UTC:

> Some test under `html/`. Not sure which one. Does it matter?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/67#issuecomment-141418381 by @jgraham on 18 Sep 2015, 11:00 UTC:

> Yes, because this codepath is only taken for specific files, not for everything. It looks like that specific test depends on the presence of a referer header.

**Comment by foolip** [comment]
This was over two years ago, and not enough information was provided then about how to reproduce, so closing.
