### ISSUE TITLE
WebKit bots having too many TIME_WAIT sockets

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#8369]
Originally posted as https://github.com/w3c/wptserve/issues/108 by @youennf on 16 Nov 2016, 03:12 UTC:

> As shown in https://bugs.webkit.org/show_bug.cgi?id=159166#c21, some WebKit bots WPT servers (localhost-running) may have too many sockets in the TIME_WAIT state. This seems to prevent running the tests correctly for some runs.
> 
> Has anybody encountered the issue?
> Maybe keep-alive should be implemented in wptserve to reduce the risk?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-260989316 by @youennf on 16 Nov 2016, 16:13 UTC:

> Looking at the code, it seems keep-alive is in action.
> Not sure why we are seeing so much TIME_WAIT sockets then.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-260999668 by @youennf on 16 Nov 2016, 16:43 UTC:

> It might be that mote responses have no content-length header

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-261011143 by @gsnedders on 16 Nov 2016, 17:22 UTC:

> I spent a few hours last week trying to work out why under high load wptserve seems to sometimes hang, using `ab`—on OS X, it consistently stopped responding at c.16500, with all connections after that getting stuck in SYN_SENT. I didn't really get anywhere very useful, though! May well be related, though?
> 
> In principle, any response without Content-Length should have the connection closed by the server after the end of the response. If that's not true, we should fix that.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-261015498 by @youennf on 16 Nov 2016, 17:37 UTC:

> If more responses had content-length headers, we would enable a lot more reuse of sockets.
> I am trying to check whether https://github.com/youennf/wptserve/tree/webkit-current-wptserver would reduce the issue.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-261018428 by @gsnedders on 16 Nov 2016, 17:48 UTC:

> I have some memory of @jgraham or @Ms2ger having some reason why #86 didn't get merged.
> 
> That said, we shouldn't have them stuck in TIME_WAIT even without socket reuse.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-261018775 by @gsnedders on 16 Nov 2016, 17:49 UTC:

> We've also had issues with w3c-test.org sometimes stopping responding, so I suspect there might be some underlying issue regardless.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/108#issuecomment-276206567 by @gsnedders on 30 Jan 2017, 22:04 UTC:

> FWIW, I tried to look into why this happened and I couldn't figure out why it stopped working at the specific point it did looking at DTrace. That said, I've never tried to deal with anything at this level on OS X previously. Equally, I couldn't reproduce it on Linux artificially limiting number of sockets.

**Comment by foolip** [comment]
@youennf, is this still a problem for WebKit?

**Comment by youennf** [comment]
Not really, it can probably be closed and reopened if needed.

**Comment by foolip** [comment]
OK, I will close it. If you happen to have a list of WebKit pain points, that would be interesting to see.

**Comment by youennf** [comment]
I filed https://github.com/w3c/web-platform-tests/issues/8391 related to WPT server being slow.
