### ISSUE TITLE
Feature request: handler for invalid HTTP responses

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#8373]
Originally posted as https://github.com/w3c/wptserve/issues/116 by @jugglinmike on 14 Mar 2017, 19:16 UTC:

> In https://github.com/w3c/web-platform-tests/pull/5037, a test concerning an invalid HTTP response (specifically: a 204 response with a body) was found to be failing intermittently. I created a reduced demonstration here:
> 
> https://github.com/w3c/web-platform-tests/compare/master...bocoup:serve-bug-demo
> 
> The underlying problem stems from the fact that each response handler shares a single stream for all requests. This behavior makes writing invalid HTTP responses generally unsafe. This is by design--wptserve's handlers are derived from [Python's built-in BaseHTTPRequestHandler](https://docs.python.org/2/library/basehttpserver.html), whose documentation reads:
> 
> > BaseHTTPRequestHandler has the following instance variables:
> >
> > [...]
> >
> > **`wfile`**
> >
> > > Contains the output stream for writing a response back to the client.
> > > Proper adherence to the HTTP protocol must be used when writing to this
> > > stream.
> 
> Maintainers expressed interest in explicitly testing such conditions, but in light of the above constraint, I believe wptserve will need to be extended with a new handler type designed explicitly for this purpose.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/116#issuecomment-287007454 by @Ms2ger on 16 Mar 2017, 09:50 UTC:

> I think we discussed removing the dependency on python's built-in http handling before; not sure if an issue was filed.

**Comment by jgraham** [comment]
I don't think this is a valid issue. I'm pretty sure it's confusion resulting from the documentation of the stdlib using  "must" to mean "must (assuming you want valid output)", which we don't in a test situation.
