### ISSUE TITLE
nonexistent-origin.web-platform.test does not have a corresponding domains entry

### ISSUE THREAD

**Issue by andypaicu** [w3c/web-platform-tests#8390]
In the hosts files there is a "nonexistent-origin.web-platform.test" entry that corresponds to "0.0.0.0"
All the other domains can be used in tests using the "domains" template but from what I can tell this one does not have an entry.

For example: "{{domains[www1]}}" will expand to www1.web-platform.test.

Has this been skipped on purpose or just missed? I was just writing a test that uses the non-existent host and was surprised that I can't find an entry in the domains dictionary.

**Comment by foolip** [comment]
@jgraham, do you know if this is intentional?

**Comment by jgraham** [comment]
I think this is just an oversight.

**Comment by andypaicu** [comment]
Cool, for now I've just used the full domain name in the test.

**Comment by gsnedders** [comment]
This is arguably related to #6556.

**Comment by foolip** [comment]
@jgraham, can you point to where this could be fixed? @andypaicu, could you then try a fix?

**Comment by foolip** [comment]
@gsnedders, have you accidentally fixed this recently?

**Comment by gsnedders** [comment]
Not accidentally; deliberately. Well, accidental insofar as I didn't know this issue existed. :)

**Comment by gsnedders** [comment]
Fixed as part of #8614, seemingly.
