### ISSUE TITLE
wakelock-object-is-independent.https.html does not reflect the spec intent

### ISSUE THREAD

**Issue by andrey-logvinov** [w3c/web-platform-tests#8411]
https://github.com/w3c/web-platform-tests/blob/master/wake-lock/wakelock-object-is-independent.https.html

https://w3c.github.io/wake-lock/#extensions-to-the-navigator-interface

The spec intent is:

1. Once there is a wake lock resolution for a `Document` which is a `WakeLock` object, `Navigator.getWakeLock()` for the same Document must always return a promise resolved with the same object.

2. `WakeLock.active` reflects the global state of wake lock of this type. It is therefore an error for two `WakeLock` objects of the same wake lock type to return different values of `active`.

The test seems to expect the exact opposite.

It is `WakeLockRequest` objects that must be independent, not `WakeLock`. `WakeLock` is intended to be a singleton for this script execution context just like `Navigator`.

**Comment by foolip** [comment]
Added in https://github.com/w3c/web-platform-tests/pull/8186. @Honry, can you update the tests if needed?

**Comment by Honry** [comment]
@foolip, sure.
