### ISSUE TITLE
http headers do not support cross origin definition

### ISSUE THREAD

**Issue by loonybear** [w3c/web-platform-tests#8485]
I want to use a cross origin src in *https.sub.html.headers for feature policy, but then I realized that the origin is unrecognized:

*https.sub.html.headers:
Feature-Policy: camera https://www.example.com https://{{domains[www]}}:{{ports[https][0]}}/feature-policy/resources/feature-policy-subframe-policy.htm

Error:
ERR: CONSOLE ERROR: Error with Feature-Policy header: Unrecognized origin: 'https://{{domains[www]}}:{{ports[https][0]}}/feature-policy/resources/feature-policy-subframe-policy.html'.

**Comment by gsnedders** [comment]
You need `*https.sub.html.sub.headers`, i.e., `sub` following the filename but before the `.headers`. This, AFAICT, does work. Reopen if I'm being silly and it doesn't.
