### ISSUE TITLE
Upgrade an custom element after document.write()/writeln() call?

### ISSUE THREAD

**Issue by EdgarChen** [w3c/web-platform-tests#8528]
See the following tests in custom-elements/reactions/Document.html,
https://github.com/w3c/web-platform-tests/blob/fc70df1f7570f5aa03efd5fd3d79763498162b9c/custom-elements/reactions/Document.html#L132-L134
https://github.com/w3c/web-platform-tests/blob/fc70df1f7570f5aa03efd5fd3d79763498162b9c/custom-elements/reactions/Document.html#L147-L149

From the step 4.2 of https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#document-write-steps,
> Run the document open steps with document, "text/html", and the empty string. If the user refused to allow the document to be unloaded, then return. Otherwise, the insertion point will point at just before the end of the (empty) input stream.

The write() and writeln() calls would also run document open steps, and the custom element registry should be replaced per https://github.com/whatwg/html/issues/1698#issuecomment-298748641.
So we won't be able to get the custom element definition from the new custom element registry, and the custom element shouldn't be upgraded, right?

@domenic , @annevk

**Comment by domenic** [comment]
Hmm, yes, I think you're right, and those tests are wrong. We'll want to fix those tests, and also add some tests that use document.write() with a defined insertion point (so that step 4 isn't triggered).

**Comment by domenic** [comment]
Alternately, given the lack of passes on https://wpt.fyi/custom-elements/custom-element-registry/per-global.html, maybe we should reconsider https://github.com/whatwg/html/issues/1698#issuecomment-298748641 ?

**Comment by EdgarChen** [comment]
> Alternately, given the lack of passes on https://wpt.fyi/custom-elements/custom-element-registry/per-global.html, maybe we should reconsider whatwg/html#1698 (comment) ?

FF can pass https://wpt.fyi/custom-elements/custom-element-registry/per-global.html, we do replace the custom element registry after document.open().

**Comment by EdgarChen** [comment]
> FF can pass https://wpt.fyi/custom-elements/custom-element-registry/per-global.html

Correction: 
FF can pass the "document.open() must replace window.customElements" test in http://w3c-test.org/custom-elements/custom-element-registry/per-global.html.
