### ISSUE TITLE
Data document tests in custom-elements/parser/parser-uses-registry-of-owner-document.html doesn't match the spec

### ISSUE THREAD

**Issue by EdgarChen** [w3c/web-platform-tests#8530]
See following test in custom-elements/parser/parser-uses-registry-of-owner-document.html,
https://github.com/w3c/web-platform-tests/blob/0b5de1b8bb072bd38896cde82dff0b201904d5ed/custom-elements/parser/parser-uses-registry-of-owner-document.html#L75-L82

From the step 3 of https://html.spec.whatwg.org/#document-write-steps: 
> If document is not an active document, then return

so the `write()` call on `windowlessDocument` would do nothing. And the `instance` would be `null`.

Maybe we should use DOMParser to test data document, instead of using write()?
Something like,
```javascript
var windowlessDocument = (new DOMParser()).parseFromString('<my-custom-element></my-custom-element>', "text/html");
  
var instance = windowlessDocument.querySelector('my-custom-element'); 

assert_true(instance instanceof HTMLElement); 
assert_false(instance instanceof MyCustomElement); 
```

@domenic  @annevk

**Comment by annevk** [comment]
That sounds good. We should also have a test with a custom element appearing in an XMLHttpRequest response body.
