### ISSUE TITLE
Most css-pseudo tests are failing on all browsers

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#8551]
https://wpt.fyi/css/css-pseudo

4/7 tests are failing everywhere. first-letter-001.html fails in different ways, but marker-color.html is a red square in all browsers (manually tested) which suggests that the test is wrong.

@dbates-wk, can you take a look?

**Comment by foolip** [comment]
For future reference, these were the 4 tests:
https://wpt.fyi/css/css-pseudo/first-letter-001.html
https://wpt.fyi/css/css-pseudo/marker-and-other-pseudo-elements.html
https://wpt.fyi/css/css-pseudo/marker-color.html
https://wpt.fyi/css/css-pseudo/marker-font-properties.html

**Comment by dbates-wk** [comment]
marker-color.html is a green square in Safari Technology Preview Release 44 (Safari 11.1, WebKit 13605.1.13.2).

**Comment by dbates-wk** [comment]
From visual inspection all the tests pass in Safari Technology Preview Release 44.

**Comment by dbates-wk** [comment]
Are we able to update the bots to use Safari Technology Preview Release 44? What is the preferred way to handle tests that depend on a future browser version to pass?

**Comment by gsnedders** [comment]
@dbates-wk See the red box at the top, pointing at <https://github.com/w3c/wptdashboard/issues/112>.

**Comment by gsnedders** [comment]
Closing as not a test issue
