### ISSUE TITLE
style-attr-braces-002-quirks.htm has the wrong ref (due to quirks mode)

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#8633]
https://wpt.fyi/css/css-style-attr/style-attr-braces-002-quirks.htm is failing everywhere because of, I think, https://quirks.spec.whatwg.org/#the-body-element-fills-the-html-element-quirk or something related, which means that the actual and reference are offset a bit vertically.

@zcorpan FYI.

**Comment by zcorpan** [comment]
The quirk here is https://html.spec.whatwg.org/multipage/rendering.html#margin-collapsing-quirks I think. Ought to be fixable by explicitly setting `p { margin-top: 1em }` in the test.
