### ISSUE TITLE
css/css-color/t451-system-colors-a.xht should be updated or removed

### ISSUE THREAD

**Issue by csnardi** [w3c/web-platform-tests#8684]
[CSS Color 4](https://drafts.csswg.org/css-color/#system-colors) states that:

> Earlier versions of CSS defined several additional named color keywords, the <deprecated-system-color>s, which were meant to take their value from operating system themes. These color names have been deprecated, however, as they are insufficient for their original purpose (making website elements look like their native OS counterparts), and represent a security risk, as it makes it easier for a webpage to "spoof" a native OS dialog.
> 
> User agents must support these keywords, but should map them to "default" values, not based on the user’s OS settings (for example, mapping all the "background" colors to white and "foreground" colors to black). Authors must not use these keywords.

css/css-color/t451-system-colors-a.xht tests this behavior, so it should either be updated or removed. Since the spec doesn't specify exact mappings from system colors, it should probably be removed as this appears to be up to the implementation.

**Comment by svgeesus** [comment]
I agree that the test is now out of sync with the specification, and also that the specification is not testable on that point (it is merely guidance) and thus that the test should be removed.
