### ISSUE TITLE
Some a-element.html URL tests seem wrong

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#8707]
Scroll to the bottom of https://wpt.fyi/url/a-element.html and look at the "assert_unreached" instances that fail in all browsers. It appears the test is trying to say that parsing `test-a.html` against `a` should fail, but I believe that given how the a-element.html test runner is set up, that won't be the case; it'll just use the actual page URL as the base URL.

**Comment by annevk** [comment]
Ah yeah, because those are not valid base URLs to begin with. I'm not sure we should be having invalid base URLs in the test data.

**Comment by annevk** [comment]
It seems we should extract #6446 (and similar tests) and basically only run them for `URL`.

**Comment by annevk** [comment]
cc @GPHemsley

**Comment by annevk** [comment]
This went bad due to 90efdbecfe3c457b36c71cf3e01a72cd5301c163 by @GPHemsley (and reviewed by @domenic). I guess I can look at cleaning it up though...

**Comment by GPHemsley** [comment]
To clarify: Are we saying the tests are bad, or the test runner is bad?
