### ISSUE TITLE
Allow about:blank as a ref

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#8806]
cc/ @jgraham @Ms2ger @foolip 

At the moment, the lint disallows any absolute URL as a ref. We should probably allow `about:blank`, given plenty of Mozilla reftests use it as a ref.

This was hit by #8804, and fixed there by just using the pre-existing `flexbox_empty-ref.html` (which is no fix at all…).

**Comment by Ms2ger** [comment]
This seems fine by me.

**Comment by foolip** [comment]
@gsnedders, what would it take to actually implement this? Should we actually load and take a screenshot of about:blank once, or make some assumptions?

**Comment by gsnedders** [comment]
@foolip Literally it's just the linter that disallows it; everything else works.

**Comment by foolip** [comment]
Oh, that makes it a very easy fix, and it affected some real tests, so calling it roadmap.

**Comment by vedantc98** [comment]
I'd like to work on this issue, can I take it up?

**Comment by foolip** [comment]
@vedantc98, absolutely, just send pull requests when you have something work, and request review from someone who might know some background. Given https://github.com/w3c/web-platform-tests/issues/8806#issuecomment-354833481 maybe @gsnedders?

**Comment by vedantc98** [comment]
@gsnedders Should it be enough to test the string href for `about:blank` on this line:
[https://github.com/w3c/web-platform-tests/blob/master/tools/lint/lint.py#L433](url)?

**Comment by vedantc98** [comment]
Please review the above, thanks 😄

**Comment by foolip** [comment]
@vedantc98 that looks good to me, can you submit it as a PR against this repo?

**Comment by gsnedders** [comment]
The PR already exists as #9421.
