### ISSUE TITLE
Test values of `Request.destination`

### ISSUE THREAD

**Issue by yoavweiss** [w3c/web-platform-tests#8810]
There are multiple tests that check if `Request.destination` is exposed, but none I could find that check if the returned value is the right one (other than https://github.com/w3c/web-platform-tests/blob/master/preload/fetch-destination.https.html which tests the destination value for `<link rel=preload as=fetch>`.

We need more tests to make sure the values returned by the different engines are compatible with the spec and with each other.

**Comment by yoavweiss** [comment]
Some of the tests landed in of #8812 
As @wanderview pointed out during the review, we're still missing a good chunk of tests for:
* report
* document
   - iframe
   - navigation
* font
* sharedworker
* worker
* track
* image
   - CSS background image
   - srcset
   - `<picture>`
   - SVG `<image>`
   - favicon
   - CSS cursor
* manifest
* xslt
* ""
   - XHR
   - `sendBeacon()`
   - EventSource
   - ping
   - `Cache.add()`
* script
   - `importScripts()`
* style
   - `@import`

Also missing are tests for `<link rel=preload>` for a good chunk of the above destinations.

**Comment by wanderview** [comment]
Maybe also for modules?  Not sure the fetch table has been updated for those yet.

**Comment by yoavweiss** [comment]
A lot of the tests that are not covered by #8926 (e.g. BG images, `sendBeacon()`, ping, `@import`) are for resources which have no load event or error event, making it very hard to know if they were actually loaded or not, so hard to communicate their destination value from SW. It also hard to read any reflected values for these types of resources in a generic way.

Thoughts on how to test them would be appreciated.

**Comment by wanderview** [comment]
You can use `Client.postMessage()` to send a success or failure back to the test window.  You need to use `Clients.matchAll()` or `Clients.get(FetchEvent.clientId)` to get the Client handle.

**Comment by yoavweiss** [comment]
Not covered by #8926:
* report
* document
    - iframe
    - navigation
* sharedworker
* worker
* track
* image
  - favicon
  - CSS cursor
* manifest
* xslt
* ""
  - ping

For most of them I'm having troubling dynamically triggering a download :/ For others, testing is a bit complex (e.g. `document`, `worker` and `sharedworker`)

**Comment by wanderview** [comment]
I agree we can probably get away without initially testing things like xslt, track, etc.

I do think we should test very mainstream features like document and worker, though.  Can you describe the difficulty you are running into testing these?  Can't you use your current test approach with stuff lile:

```
let f = document.createElement('iframe');
f.src = 'foo.html?dest=document';
document.body.appendChild(f);
// wait for post message back

f.location = 'bar.html?dest=document';
// wait for post message back

let w = new Worker('inscopeworker.js?dest=script');
// wait for post message back
```
