### ISSUE TITLE
Some CSS2/lists/counter-increment-* tests are not required by spec

### ISSUE THREAD

**Issue by csnardi** [w3c/web-platform-tests#8888]
Many CSS2/lists/counter-increment-* tests check the behavior of large numbers in counters. See, e.g. [counter-increment-025.xht](https://github.com/w3c/web-platform-tests/blob/master/css/CSS2/lists/counter-increment-025.xht), which tests numbers larger than 2^31 - 1. However, neither the [CSS2 spec](https://www.w3.org/TR/CSS21/generate.html#counters) nor the [current CSS Lists spec](https://drafts.csswg.org/css-lists/#auto-numbering) specify a range of numbers that implementations must accept. The current spec even states:

> Implementations may have implementation-specific limits on the maximum or minimum value of a counter.

but does not specify what these limits should be. As a result, while these tests might be informative, I don't believe that they accurately reflect the spec, and thus might be suitable for removal.

**Comment by frivoal** [comment]
They are already flagged with "may" (at least the example you showed is, I didn't check all of them).

That indicates that passing them is optional.

I am not convinced these are terribly useful tests, but they're not wrong, and if they detect some differences in implementation, that sounds worth knowing, even if it isn't a very high priority difference.

**Comment by csnardi** [comment]
Yeah, you're correct -- all of these tests were flagged with may. I didn't realize that was signified within the tests.
