### ISSUE TITLE
Disable font-specific kerning in tests?

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9005]
https://github.com/w3c/web-platform-tests/pull/8943/commits/7aab8a5579faea3a76027a3e0c67d4025dc35b3a (by @kojiishi) disabled kerning because of differences in kerning in Blink between those tests and references.

As far as I'm aware, the fact that kerning behaviour is undefined [citation needed] means that this is probably justified far more generally (and we have loads of tests where kerning differences may occur, especially around features like `::first-letter`). Should we just disable font-specific kerning in all reftests?

Opinions?

cc/ @jgraham @dbaron @foolip @youennf @thejohnjansen

**Comment by gsnedders** [comment]
#9093 adds a load more.

**Comment by foolip** [comment]
Since it's already possible to disable using CSS isn't that good enough? Otherwise, would we invert the default just for testing?

**Comment by gsnedders** [comment]
@foolip I think the suggestion is to invert the default, yes. In principle, anywhere where it'd make a difference in a QoI issue (and something ideally browsers would fix), but it's not a requirement for conformance.

If we don't invert the default, we'll have people playing whack-a-mole changing tests where their impl fails tests because of QoI issues as a result. That said, to invert the default would probably require browser-side work to adds prefs to change the initial value?

**Comment by dbaron** [comment]
I don't think this makes sense in general.  In general reftests and their references should have a known set of differences to be able to assert that those differences produce equivalent rendering.  I think we should be able to make reasonable assumptions about things like the same text being kerned the same way multiple times, and I think given that, there might be reasons to either (a) disable kerning in tests where the same text is displayed with different inline element boundaries or (b) add appropriate inline element boundaries to the tests or references so they match.  I think (b) is likely the more appropriate fix than (a) in most cases.  (That said, I haven't looked through the examples of tests involved; I'd be interested in a description of why the kerning is actually different.)

**Comment by foolip** [comment]
@mstensho, perhaps you can comment on the necessity of disabling kerning in tests, and whether inverting the default would be an improvement?

**Comment by dbaron** [comment]
How would you detect the existing tests where making sure the kerning is equivalent is part of what the existing test was trying to test?

**Comment by foolip** [comment]
@mstensho, does the status quo also work for you,  i.e., disabling on a per-test basis as in https://github.com/w3c/web-platform-tests/pull/9093?

**Comment by mstensho** [comment]
Status quo works fine. Probably even better than fiddling with default behavior actually, when I come to think of it. @dbaron has a point, and following the principle of least surprise is a good thing.

**Comment by foolip** [comment]
@gsnedders, I think this is a WontFix, can you close it if you agree?
