### ISSUE TITLE
./wpt run broken on Windows

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9058]
From [email](https://lists.w3.org/Archives/Public/public-test-infra/2018JanMar/0001.html) from @thejohnjansen:

> I just did a brand-new clone of web-platform-tests, and now when I try to run the tests:
> 
> Python wpt run edge weddriver
> 
> I get an error:
> 
> ```
> Traceback (most recent call last):
>   File "wpt", line 5, in <module>
>     wpt.main()
>   File "C:\users\johnjan\documents\github\web-platform-tests\tools\wpt\wpt.py", line 111, in main
>     venv = setup_virtualenv(main_args.venv, props)
>   File "C:\users\johnjan\documents\github\web-platform-tests\tools\wpt\wpt.py", line 84, in setup_virtualenv
>     venv.start()
>   File "C:\users\johnjan\documents\github\web-platform-tests\tools\wpt\virtualenv.py", line 47, in start
>     self.activate()
>   File "C:\users\johnjan\documents\github\web-platform-tests\tools\wpt\virtualenv.py", line 42, in activate
>     execfile(path, {"__file__": path})
> IOError: [Errno 2] No such file or directory: 'C:\\users\\johnjan\\documents\\github\\web-platform-tests\\_venv\\Scripts\\activate_this.py'
> ```
> 
> Is there some new step I need to take to force the Scripts directory to get created?
> 
> This worked last night before I got the changes from this weekend.

@AutomatedTester suggested:

> From a quick look it could be https://github.com/w3c/web-platform-tests/commit/a1de23740cb079b71517dff563b919416198e6ca that broke it so could you update to the revision before that and see if that works.

On the whole, I agree with that quick look.

**Comment by gsnedders** [comment]
Downprioritising as seemingly not generally broken.

**Comment by thejohnjansen** [comment]
It looks to me like an issue with Windows itself. I was updated to build 17071 and this was broken, but in 17063 and 17074 this works. This should be OK to close.
