### ISSUE TITLE
css/CSS2/zorder/z-index-020.xht fails in all browsers

### ISSUE THREAD

**Issue by csnardi** [w3c/web-platform-tests#9092]
https://w3c-test.org/css/CSS2/zorder/z-index-020.xht is failing in all browsers. The test shows that two reference images could be matched, but there is only one reference with the bottom image. All browsers would match the top image.

I'm not familiar enough with `zorder` to know if both of these reference pictures would be valid per the spec.

**Comment by gsnedders** [comment]
@csnardi We support alternate references through multiple `<link rel=match>`; we just need a second `<link rel=match>` with a reference with the top image.

**Comment by csnardi** [comment]
@gsnedders Are both reference images valid though? Since all major browsers fail that test, it made me wonder if they're both still correct per the spec.

**Comment by gsnedders** [comment]
@csnardi I have no idea. :)

**Comment by gsnedders** [comment]
https://wpt.fyi/css/CSS2/zorder?sha=a9ed3553eb — Safari seems to pass this now, oddly.

**Comment by csnardi** [comment]
I think there's something wrong with that Safari run, see e.g. https://wpt.fyi/css/css-color?sha=a9ed3553eb where Safari passes tests with lab/lch that no browser has implemented yet.
