### ISSUE TITLE
font family parsing test relies on insecure behavior

### ISSUE THREAD

**Issue by svgeesus** [w3c/web-platform-tests#9103]
I noticed that the CSS test `test_font_family_parsing` used to pass (Firefox 57) and no longer does (Firefox Nightly 59.0a1). Running the test:
https://test.csswg.org/harness/test/css-fonts-3_dev/single/test_font_family_parsing/
gives failure on some subtests due to insecure operations

```
The operation is insecure.

testStyleRuleParse@https://test.csswg.org/suites/css-fonts-3_dev/nightly-unstable/html/test_font_family_parsing.htm:163:9
testFamilyNameParsing/<@https://test.csswg.org/suites/css-fonts-3_dev/nightly-unstable/html/test_font_family_parsing.htm:263:25
Test.prototype.step@https://test.csswg.org/resources/testharness.js:1489:20
test@https://test.csswg.org/resources/testharness.js:511:9
testFamilyNameParsing@https://test.csswg.org/suites/css-fonts-3_dev/nightly-unstable/html/test_font_family_parsing.htm:263:7
@https://test.csswg.org/suites/css-fonts-3_dev/nightly-unstable/html/test_font_family_parsing.htm:277:1
```
I wonder whether these insecure operations are also causing other browsers (Chrome, Safari) to fail.

**Comment by gsnedders** [comment]
@svgeesus I have no idea what's up with that; https://w3c-test.org/css/css-fonts/test_font_family_parsing.html passes fine in current Firefox nightly/ (Also, as an aside, given it isn't noted as being an HTTPS test, it should almost certainly be run over HTTP. I don't think we guarantee that all tests are valid over HTTPS.)

**Comment by gsnedders** [comment]
https://test.csswg.org/suites/css-fonts-3_dev/nightly-unstable/html/test_font_family_parsing.htm works fine for me as well.

(This is with Firefox 59.0a1 (2018-01-19) (64-bit) on Linux64)
