### ISSUE TITLE
po-navigation.html has been failing everywhere for a long time

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#9109]
See https://wpt.fyi/performance-timeline/po-navigation.html for the current state. Determined to also be failing a few years ago using [this list](https://docs.google.com/spreadsheets/u/1/d/1u6fBSy3SXJBRG57NKyu0f2M8PTitZdetbZzDiw57eFE/edit?usp=sharing).

I can't quite make sense of this test of why it should pass.

https://w3c.github.io/performance-timeline/ says that the "navigation" entryType is now defined in https://w3c.github.io/navigation-timing/, which it is, so this test should be moved if it can be fixed. But, more importantly, I can't see anything in this test that would actually cause a navigation to happen, unless just loading the test itself counts. Should PerformanceObserver be able to observe the navigation to the page it's on? Is there any raciness involved with that?

I don't know the answers, so I'm filing this issue, and pinging navigation-timing/OWNERS and performance-timeline/OWNERS:
@plehegar
@igrigorik
@toddreifsteck
@yoavweiss

Context: @rakuco and I are looking at [a long-failing test](https://docs.google.com/document/d/1kFYTqUMEbo9p87i6wAzORoicMWgHsuYwL2CgtvdhDaE/edit#heading=h.6lssu2bocbaz) every week this quarter, trying to understand why it usually is.

**Comment by igrigorik** [comment]
The navigation is the test page itself. Per spec, NT calls "queue entry" (step 28) after load event finishes execution, which should queue a PerformanceNavigationEntry into the observer. In theory, the PO registration should happen before load event fires and we'd expect the NT entry to be observed via PO. Except, it looks like that's not the case here. 

We probably need to rework the test to make sure that the async_step is executed before load event?

/cc @tdresser

**Comment by plehegar** [comment]
https://github.com/w3c/navigation-timing/commit/307faa5ac92b24e90537e7a1e15516090c8f6515 changed the returned value of PerformanceNavigationTiming.name and the test was not updated. PR is on the way.

**Comment by plehegar** [comment]
@foolip feel free to reopen this one if your report don't report proper fix.

**Comment by foolip** [comment]
https://wpt.fyi/navigation-timing/po-navigation.html is now passing in Chrome, thanks @plehegar! (So that there can be no misunderstanding, I'd be even happier if it passed in 2, 3 or 4 browsers, Chrome or not.)
