### ISSUE TITLE
Travis builds not running

### ISSUE THREAD

**Issue by csnardi** [w3c/web-platform-tests#9114]
There have been both new commits and PRs, but https://travis-ci.org/w3c/web-platform-tests/requests shows the last request for a build being https://travis-ci.org/w3c/web-platform-tests/builds/330750735. The [new commits](https://github.com/w3c/web-platform-tests/commits/master) only have GitHub pages builds and no Travis builds.

**Comment by gsnedders** [comment]
Somehow Travis CI had had the repo deactivated? o_O

Should be working now, and manually triggered a run of master.

**Comment by csnardi** [comment]
@gsnedders I think the first 5 PRs on https://github.com/w3c/web-platform-tests/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Achromium-export+-label%3A%22do+not+merge+yet%22 also need runs triggered if possible, or just manual merging.

**Comment by gsnedders** [comment]
@csnardi I've kicked them as well as I can; let's see if they get automerged after the builds run.
