### ISSUE TITLE
wpt-pr-bot is down

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#9195]
The last PR where @wpt-pr-bot did anything appears to be https://github.com/w3c/web-platform-tests/pull/9182, starting with https://github.com/w3c/web-platform-tests/pull/9183 no reviewers are added, and https://github.com/w3c/web-platform-tests/pull/9184 is a Chromium export which wasn't auto-approved and so cannot be merged.

Assigning @tobie since this is part of https://github.com/tobie/ganesh/, but if there's anything I can do, please shout!

**Comment by tobie** [comment]
Unexpected API changes: https://developer.github.com/changes/2018-01-24-end-thor-preview/

**Comment by tobie** [comment]
So this fixed it. the error logging worked as planned and allowed me to find the root cause in seconds, only problem is it wasn't alerting me. This has now been fixed, so long outages like this shouldn't ever happen again.

**Comment by tobie** [comment]
Commenting on the issues that were missed by the bot should trigger it. I don't have an automated way of doing this for now. Apologies.

**Comment by foolip** [comment]
Apology not accepted, not needed, thank you for fixing this so quickly! I guess I can close the issue, or is there something more to do?

**Comment by tobie** [comment]
No, I think we're good.
