### ISSUE TITLE
set_dirty is using unspecified behaviour in html/semantics/forms/constraints/support/validator.js

### ISSUE THREAD

**Issue by mnoorenberghe** [w3c/web-platform-tests#923]
CC @xiaojunwu
[set_dirty](https://github.com/w3c/web-platform-tests/blob/ab736442283d4fb6f0c3ce2b817fe5ed9410310e/html/semantics/forms/constraints/support/validator.js#L229) is using non-standard behaviour not supported by Gecko to make an `<input>` "dirty" via `document.execCommand("delete")`. Using execCommand on <input> without designMode/contentEditable is not specified in any current spec AFAIK. The suites setting `dirty: true` do not have accurate results because of this issue e.g.:
* form-validation-validity-tooLong.html
* form-validation-validity-tooShort.html
* form-validation-validity-valid.html

**Comment by rniwa** [comment]
No, execCommand never works inside text fields in IE and Firefox.  That `document.execCommand("Delete")` doesn't do anything regardless of whether you're in the design mode or not (it may modify random text elsewhere though).

In general, `execCommand` is an unspec'ed feature and should not be used in testing until that status changes.

**Comment by cvrebert** [comment]
For posterity: X-Ref: https://bugs.webkit.org/show_bug.cgi?id=149911
