### ISSUE TITLE
Div Tag not allowed in LI

### ISSUE THREAD

**Issue by Fu22yWu22y** [w3c/web-platform-tests#9287]
From what i get from this  
http://w3c.github.io/html/single-page.html#elementdef-dl
"The dl element represents a description list of zero or more term-description groups. Each term-description group consists of one or more terms (represented by dt elements) possibly as children of a div element child, and one or more descriptions (represented by dd elements possibly as children of a div element child), ignoring any nodes other than dt and dd element children, and dt and dd elements that are children of div element children within a single dl element."

A div tag should be allowed in a DL   
but currently  this is not passing  the W3C Validator 
https://validator.w3.org/nu/

**Comment by foolip** [comment]
This is a question about HTML document conformance. https://github.com/whatwg/html is the place to file such issues, or https://github.com/validator/validator for the validator.
