### ISSUE TITLE
Lint is failing on css/css-fonts/cascading-font-sizes.html

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#9304]
Added in https://github.com/w3c/web-platform-tests/commit/8e05b1114fe6510415a6de81ac9689e1f492e6e9 and somehow got past Travis.

**Comment by foolip** [comment]
Noticed because https://ci.chromium.org/buildbot/chromium.infra.cron/wpt-importer/ is failing. (It runs the lint before uploading the changes to Chromium code review.)

**Comment by foolip** [comment]
It looks like there is no recent PR which brought in these changes, which would explain why Travis has not run. Trying to figure out how they ended up on master...

**Comment by foolip** [comment]
Hmm, so a02f1bcf2d3c7ccc4ca9d51a5da7c508c243d69d is the topmost commit on master, and as a self-contained commit that seems to make sense. But its parent commit was a merge commit, a backwards one which would have results from `git pull`. So probably this was an attempt to push a branch to create a PR, that went wrong because of the tracking branch being origin/master, so something like that.

But why was it possible to push to master accidentally? @svgeesus, are you an admin of the repo indirectly, by any chance?

**Comment by foolip** [comment]
Anyway, a02f1bcf2d3c7ccc4ca9d51a5da7c508c243d69d and the commits merged by 63c87e573197ae817389c7dcbf765c2979570e10 together account for the changes. The merge commit appears to have been accidental, so I'll revert that while leaving a02f1bcf2d3c7ccc4ca9d51a5da7c508c243d69d alone, let's say I've reviewed it.

**Comment by Hexcles** [comment]
Thanks for fixing this!

**Comment by gsnedders** [comment]
I've asked @svgeesus not to push directly to master before, as it isn't the first time he's caused lint failures that couldn't have landed had they gone through CI. :(

**Comment by svgeesus** [comment]
Apologies for causing trouble.

> Hmm, so a02f1bc is the topmost commit on master, and as a self-contained commit that seems to make sense. 

Yes, that is the one I was trying to commit. I didn't ask for review because the substance of the tests had not changed (just the spec link was bumped from Fonts 3 to Fonts 4, as that section of the spec was deferred to level 4).

I will do PR from now on, so that Travis CI can run.
