### ISSUE TITLE
Tests with a "font" meta flag are marked as manual

### ISSUE THREAD

**Issue by jonleighton** [w3c/web-platform-tests#9374]
Per http://web-platform-tests.org/writing-tests/css-metadata.html, the "font" meta flag means this:

> Requires a specific font to be installed at the OS level. (A link to the font to be installed must be provided; this is not needed if only web fonts are used.)

Such tests are marked as manual, which was implemented in 321e622e6cdb2690292dcabef2db1e9d98710d5a.

This seems strange to me - there's no particular reason these tests cannot be run in an automated fashion, they just have a certain prerequisite for the environment. See e.g. [this test](https://github.com/w3c/web-platform-tests/blob/master/css/css-fonts/font-family-name-001.xht) which is written as a reftest, but doesn't run as one. I would propose not marking them as manual - if a certain CI environment cannot install the fonts for some reason, they can mark these tests failing via metadata.

cc @gsnedders since you're the author of the commit.

Also related to #8670.

**Comment by jonleighton** [comment]
Note: those tests which have the "font" meta flag, but that aren't written as refspecs, would need to be renamed to include the "-manual" suffix.

**Comment by gsnedders** [comment]
@jonleighton to change this, we'd need a way to declaratively state what the preconditions are (which the existing CSS test metadata didn't have), and put that in the manifest, to be able to install the fonts automatically when running them.

**Comment by gsnedders** [comment]
And, realistically, I think it's probably a better use of time and effort to move them over to use `@font-face` (where possible) than it is to add such metadata.

**Comment by jonleighton** [comment]
Why would we need that? IMO it seems reasonable to say that some tests will fail unless the necessary fonts are installed, but maybe I am missing something.

I agree that making more use of `@font-face` seems like a good direction. Presumably there will always need to be some tests that rely on system fonts though. But maybe none of those tests need to rely on the custom fonts used by WPT...

**Comment by jgraham** [comment]
Tests with requirements that could be automated but are not in practice are manual. These tests fall into that category at present, and I tend to agree that `@font-face` is the solutioin in a large fraction of cases.

**Comment by gsnedders** [comment]
> Why would we need that? IMO it seems reasonable to say that some tests will fail unless the necessary fonts are installed, but maybe I am missing something.

It makes it impossible to know whether a failure is a test execution environment issue or the test actually failing, which is annoying if you want to do any automated processing of the results.
