### ISSUE TITLE
Why are JavaScript tests inlined in <script> tags inside of HTML?

### ISSUE THREAD

**Issue by markandrus** [w3c/web-platform-tests#9510]
Hi,

It would be amazing if libraries that implement browser APIs could treat this project as a library of tests. I'm imagining, for example, a JavaScript implementation of some browser API—say URL—could import the `url/` tests and validate their implementation as part of their CI.

The problem, I see, is that most of the tests are JavaScript inlined in HTML files. Take a look at [url/urlsearchparams-append.html](https://github.com/w3c/web-platform-tests/blob/master/url/urlsearchparams-append.html), for example: there's some HTML boilerplate, two includes of `resources/testharness.js` and `resources/testharnessreport.js`, and then the actual test logic inlined in a subsequent &lt;script&gt;. So I'm wondering:

* Why doesn't the test logic doesn't live in its own JavaScript file?
* Do the maintainers of this library know of any projects using web-platform-tests in this way?
* Does this usage fit into the long-term vision of the project?

I'm kind of asking about something more general, so feel free to edit the title of my issue as necessary.

Thanks,
Mark

**Comment by jgraham** [comment]
I'm pretty sure that requiring script to be external resources in general isn't going to fly since it adds requirements on test authors that don't help most implemenations. If there are specific tests that you want to run that make sense out of the HTML file context then I suggest talking to the authors of those specific tests about your requirements.

**Comment by markandrus** [comment]
Thanks for the context and suggestion, @jgraham. I did some research on my second question, and it looks like at least one project, `jsdom`, is successfully using web-platform-tests as a library of tests.
