### ISSUE TITLE
Run infrastructure/ tests as smoketests

### ISSUE THREAD

**Issue by jgraham** [w3c/web-platform-tests#9543]
Changes to wptrunner frequently cause regressions. Running the whole testsuite isn't practical for a number of reasons, but the tests in `infrastructure/` generally have well understood expectations and should be run whenever wptrunner changes (maybe when anything in `tools` changes).

We can check in expectation data for these tests in a per-browser fashion (the format doesn't already support multiple browsers, but we could add the product to `run_info` to get that support or just have a directory per-browser).

We should be able to support all desktop browsers (including sauce) in this way. Mobile browsers may be more effort. For servo we will need to add the ability to download the servo binary.

**Comment by gsnedders** [comment]
fixed by #9676
