### ISSUE TITLE
Add the ability to download latest Servo for `wpt run`

### ISSUE THREAD

**Issue by jgraham** [w3c/web-platform-tests#9544]
Latest servo builds are available from e.g. `https://download.servo.org/nightly/linux/servo-latest.tar.gz`. We would like these to be downloaded when running e.g. `wpt run --install-browser servo dom/historical.html`.

The patch here involves updating `tools/wpt/run.py` and `tools/wpt/browser.py` to implement the `install` methods for the `Servo` classes. The `Firefox` classes in the same files provide a good template to copy.

**Comment by GloverDonovan** [comment]
I made the changes to `tools/wpt/browser.py`, but I'm not sure what I should do for `tools/wpt/run.py`. I tried looking for an `install` method to base my changes on but couldn't find one (besides `BrowserSetup`).

Also: Should the `Servo` class in `browser.py` use platform conditionals like `Firefox`?

**Comment by jgraham** [comment]
Sorry for the delayed response.

I think you are right and `run.py` might be fine as-is.

Based on [https://download.servo.org/](https://download.servo.org/) I think the servo code can use platform conditionals to get the right version for the current platform.

**Comment by kriti21** [comment]
@jgraham Please review my PR above. This is the first time I am trying to contribute to web-platform-tests. :)

**Comment by GloverDonovan** [comment]
Apologies for not making it clear that I was working on this issue. I should've replied when given the chance.

One problem I faced though was that Git commands like `git status` took several minutes to execute on my machine. I was trying to decrease this wait time before attempting to create the pull request.

Feel free to use the submitted work, although I wish I had the chance to reply to @kritisingh1 (a 2 hours' notice is not enough, it should've been at least one working day).
