### ISSUE TITLE
recent changes to browsers/*.py broke running tests on Windows

### ISSUE THREAD

**Issue by thejohnjansen** [w3c/web-platform-tests#9550]
https://github.com/w3c/web-platform-tests/commit/1b4f253cc9fd6f63c7bb74d176969a15868c6af6#diff-50efe7e042563f68301dc8f747767f99

was merged and removed the "host" value from the browser configurations. I cannot tell where that "host" is consumed, but now when I try to run the tests on Windows, they fail with an error in environment.py

  File "C:\Users\johnjan\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\environment.py", line 132, in load_config
    local_config = json.loads(data % self.options)
KeyError: 'host'

Of course, locally I fixed this by reverting the changes linked above. But I feel like that's hack and the real fix should be where the KeyError happens. I just cannot find where to fix that.

@gsnedders, can you take a look?

note: I'm calling out Windows explicitly here because I assume these ran fine on Linux before the change was merged.

**Comment by jugglinmike** [comment]
Hi John! We identified this regression earlier this week, and @gsnedders and I have been working to resolve it over at gh-9480. We're hoping to have the fix merged some time tomorrow.

**Comment by thejohnjansen** [comment]
Sweet. I'll close this issue then since we don't need to track this in two places. Just please don't forget to fix Edge as well as Chrome :-). Locally, I'm just going to add back the host value for now. Thanks @jugglinmike

**Comment by gsnedders** [comment]
@thejohnjansen can you check that it works on Edge now? it should…
