### ISSUE TITLE
GLib-GObject-CRITICAL in Firefox Travis logs makes them very verbose and harder to understand

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#9657]
https://api.travis-ci.org/v3/job/345549233/log.txt is a raw log (from https://github.com/w3c/web-platform-tests/pull/9641) and it has *lots* of this stuff:
```
PID 6210 | (firefox:6210): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed
PID 6210 | 
PID 6210 | (firefox:6210): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
```

It drowns out the rest of the content.

@jgraham, do you know where this is coming from? If it can't be fixed in Firefox, do you think we can just filter them out in the Travis runs to make these logs smaller? One has to download the raw logs normally for Firefox because they're too big to get the nice UI.

**Comment by foolip** [comment]
I think the Firefox failure in https://github.com/w3c/web-platform-tests/pull/9680 was probably caused by this:
```
Log reached capacity (3145728 bytes); output disabled.


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

Hypothesis being that the output is disabled at layer above the "output has been received" logic, so that producing too large a log will lead to this result.

@jgraham, any ideas?

**Comment by jgraham** [comment]
I don't know how to fix it in Firefox, certainly.

We could add some filtering in the logger to remove these lines from the formatted output. The hacky way to do this would be in the `on_output` method in `tools/wptrunner/wptruner/browsers/firefox.py`

**Comment by jgraham** [comment]
So let's try the simplest possible solution here. I think a regexp in `tools/wptrunner/wptruner/browsers/firefox.py::on_output` discarding input that matches the `GLib-GObject-CRITICAL` lines above would be sufficient. Ideally we would have some infrastructure to allow multiple regex to run, since I have a few other use cases that might need this in the future.

**Comment by kritisingh1** [comment]
Hi. Can I take this up? Thank you!
