### ISSUE TITLE
Updating reftest graph broken when node changes to support

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9671]
See https://github.com/w3c/web-platform-tests/pull/9598#pullrequestreview-98198304

If we have:

a.html: `<link rel=match href=b.html>`
b.html: `<link rel=match href=c.html>`
c.html: `hello world`

Then: 

a.html is a reftest (it's a test we want to run)
b.html is a reftest_node (it's in the reftest graph and can itself be run)
c.html is a support (because we can't tell anything about it statically)

If b.html changes type (e.g., to `support`), then the reftest graph isn't recomputed.

**Comment by fiennyangeln** [comment]
i want to take this issue.

**Comment by gsnedders** [comment]
@fiennyangeln: Feel free to just start working on it!
