### ISSUE TITLE
Get click-cancel.html running in Firefox

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#9694]
I can't find a run on wpt.fyi where the test was run for Firefox:
https://wpt.fyi/uievents/order-of-events/mouse-events/click-cancel.html?sha=9659a35d81
https://wpt.fyi/uievents/order-of-events/mouse-events/click-cancel.html?sha=fcf46c6ea5
https://wpt.fyi/uievents/order-of-events/mouse-events/click-cancel.html?sha=a5f6b5fa03

All are SKIP. This is bad because we can't be confident that the testdriver.js mechanism is working at all.

**Comment by foolip** [comment]
I'm assuming here that the reason is that it's really skipped by wpt run. If that's not the case, then this issue belongs on wptdashboard instead.

**Comment by jgraham** [comment]
That's https://github.com/w3c/web-platform-tests/pull/9391 which is waiting for (re)review.

**Comment by gsnedders** [comment]
#9391 has landed now
