### ISSUE TITLE
XMLHttpRequest/send-entity-body-get-head* tests should not fail if Content-Length is 0

### ISSUE THREAD

**Issue by caitp** [w3c/web-platform-tests#980]
From http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

> For response messages, whether or not a message-body is included with a message is dependent on both the request method and the response status code (section 6.1.1). All responses to the HEAD request method MUST NOT include a message-body, **even though the presence of entity- header fields might lead one to believe they do.**

So, what you really want to assert here, is that there is no request message-body, not whether there is a Content-Length header or not.

**Comment by annevk** [comment]
Specification now defines Content-Length. Sorry for the delay.

**Comment by caitp** [comment]
Cool --- so based on that, what's the plan for #981? It looks like it needs an update to specifically assert a length of 0

**Comment by annevk** [comment]
Agreed.
