### ISSUE TITLE
Allow passing in stability options via wptrunner command line

### ISSUE THREAD

**Issue by jgraham** [w3c/web-platform-tests#9877]
wptrunner (and therefore `wpt run`) has a `--verify` option. This runs the tests multiple times in various configurations in order to check that they're stable. At present this has to be configured using Python code. It would be helpful to be able to set the configuration options (i.e.   the keyword parameters in `tools/wptrunner/wptrunner/stability.py::check_stability`) via the command line. At the very least the `max_time` option should be settable, so we are able to set the maximum runtime of the command to a specified number of seconds (or other time unit; a typical value might be 50 minutes).

**Comment by marimeireles** [comment]
Hi @jgraham! 
I'd like to take this bug.

**Comment by jgraham** [comment]
Please go for it!
