### ISSUE TITLE
images not being copied correctly for background reftests in css/vendor-imports/mozilla/mozilla-central-reftests/background/

### ISSUE THREAD

**Issue by dbaron** [w3c/web-platform-tests#9912]
Gerard Talbot [reported to www-style](https://lists.w3.org/Archives/Public/www-style/2017Sep/0051.html) the following problems:

> Bad linkage of border-image.png
> ===============================
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-repeat-space-1.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-1-ref.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-repeat-space-2.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-2-ref.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-repeat-space-3.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-3-ref.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-repeat-space-4.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-4-ref-1.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-4-ref-2.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-repeat-space-5.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-5-ref-1.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-5-ref-2.htm

[...]

> Bad linkage of 2 reticule images
> ================================
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-6-ref.htm
> http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/reference/border-image-repeat-space-7-ref.htm

I think these are some sort of build problem.  The images are
present in the repository in
css/vendor-imports/mozilla/mozilla-central-reftests/background/
right next to the tests; they're just not in the built test suite.
I'm not sure what's supposed to cause them to appear in the built
test suite.

**Comment by dbaron** [comment]
Would moving them to a `support/` subdirectory fix this?

**Comment by dbaron** [comment]
Also, whatever was wrong here, it seems like a lint should have caught it.

**Comment by gsnedders** [comment]
https://github.com/w3c/web-platform-tests/blob/master/lint.whitelist#L387 seems like the lint did catch it, but was in the long tail of things already broken when we merged csswg-test into web-platform-tests.

**Comment by dbaron** [comment]
So moving them to a `support/` subdirectory would fix it?

**Comment by dbaron** [comment]
(I'll fix that in https://bugzilla.mozilla.org/show_bug.cgi?id=1444136 and then merge it over to fix this.)

**Comment by gsnedders** [comment]
When you merge it over, please remove the lines in lint.whitelist for them.

**Comment by TalbotG** [comment]
Where should images go? Into the /support subdirectory? Please answer.

**Comment by TalbotG** [comment]
Is the lint supposed to detect and report broken links? Please answer.

**Comment by dbaron** [comment]
I don't know who you're demanding answer your questions, but what I know is this:

Moving the images into a support/ subdirectory did fix the problem here, so it seems that's the answer.  The lint did detect (see above) that there were images *not* in a support directory; I don't know of a lint that would have detected the broken links since, in the web-platform-tests repository, the links weren't broken.  They were only broken post-build in the CSSWG system.

**Comment by TalbotG** [comment]
> Moving the images into a support/ subdirectory did fix the problem here, 
> so it seems that's the answer.

David, thank you for your answer and time.
I have asked in Issue 10016 that such guideline or requirement be stated in 
http://web-platform-tests.org/writing-tests/general-guidelines.html#support-files

I originally thought that tests requirements applying to web-platform-tests repository were good and sufficient for the building of CSS test suite but they are not. A correct linkage in tests in web-platform-tests repository is not necessarly good or without problems when it will be handled by the build system. I think this is inadequate otherwise imbalanced, error-prone.
