### ISSUE TITLE
web-platform-tests repository is over 200MB - how to contribute to the repository at a device having low disk space?

### ISSUE THREAD

**Issue by guest271314** [w3c/web-platform-tests#9918]
[web-platform-tests](https://github.com/w3c/web-platform-tests) repository is over 200MB. For devices with low disk space this can prevent a user from cloning the repository at the command line when attempting to contribute to this repository.

How to clone only a specific folder, for example, https://github.com/w3c/web-platform-tests/tree/master/speech-api, and create a pull request at the command line without cloning the entire repository?

**Comment by Hexcles** [comment]
If memory/storage is a constraint, perhaps try making the changes on GitHub web UI?

**Comment by guest271314** [comment]
@Hexcles How to use GitHub web UI to remove a commit from a [pull request](https://github.com/w3c/web-platform-tests/pull/9642)? Or does the existing pull request need to be cancelled and resubmitted without the erroneous commit?

**Comment by Hexcles** [comment]
Ahh, sorry, AFAIK, this can't be done on GitHub web UI... The easiest way is of course a force push, but if you can't find a device, perhaps recreating the PR is a reasonable workaround.

**Comment by guest271314** [comment]
@Hexcles How to delete the erroneous commit at fork of this repository to avoid pulling the commit again?
